### PR TITLE
13429 public user all api keys

### LINKED ISSUE #13429: "relation juanignaciosl.raster_columns does not exist" error creating an API key
```
curl -v -X POST -H "Content-Type: application/json" -d '{ "name": "power_shortage_app", "grants": [ {"type":"apis","apis":["sql","maps"]}, {"type": "database", "tables":[{ "schema": "juanignaciosl", "name": "power_shortage", "permissions": ["select","insert"] }] } ] }' "https://team.carto.com/u/juanignaciosl/api/v3/api_keys?api_key=XXXXXXXXXXX"
```

That returned this error:

```
{"errors":"relation \"juanignaciosl.raster_columns\" does not exist","errors_cause":null}%
```

cc @amartinj

### PR DESCRIPTION
**Pull request by javitonino**
Closes #13429

### CODE REVIEW

File: app/models/carto/api_key.rb [hunk 1]
```diff
@@ -56,7 +56,6 @@ class ApiKey < ActiveRecord::Base
     after_create :setup_db_role
     after_save { remove_from_redis(redis_key(token_was)) if token_changed? }
     after_save :add_to_redis
-    after_save :update_role_permissions
```
Comment (amartinj) [inline app/models/carto/api_key.rb]: We agreed that, since apikeys would not be updateable this makes no sense, but you did not remove `update_role_permissions` and `revoke_privileges`

File: app/models/carto/api_key.rb [hunk 2]
```diff
@@ -136,14 +135,27 @@ def create_db_config
...
+      end
+
+      table_permissions.each do |tp|
+        unless tp.permissions.empty?
+          db_run("GRANT #{tp.permissions.join(', ')} ON TABLE \"#{tp.schema}\".\"#{tp.name}\" TO \"#{db_role}\"")
+        end
+      end
+
+      read_schemas, write_schemas = affected_schemas(table_permissions)
+      (read_schemas + write_schemas).each { |s| grant_aux_write_privileges_for_schema(s) }
```
Comment (amartinj) [inline app/models/carto/api_key.rb]: Now you are grating `user.service.organization_member_group_role_member_name` to the newly created role so it should not be necessary to grant extra usages on schemas and sequences

Comment (javitonino) [reply app/models/carto/api_key.rb]: Yes, it is:
- The schema usage is needed to access schemas from other users. 
- The sequences are needed as well, same reason.

The organization role just gives access to cartodb specific things (functions, triggers, etc) but it doesn't give access to schemes or sequences for other users in the org.

If https://github.com/CartoDB/cartodb-postgresql/issues/321 is resolved, we could change this for `CDB_Organization_Add_Table_Read_Write_Permission` (which contains the table and schema permission, but is currently missing the sequences) and share the same code as normal table sharing. But for now, I prefer to keep this working, we can take a look

File: app/models/carto/api_key.rb (hunk 1 above)
Comment (javitonino) [reply app/models/carto/api_key.rb]: Oh, nevermind, psql requires you to manually revoke objects. I'll keep `revoke_privileges` then, but remove `update_role_permissions`.
