### PR TITLE
Use plain sql queries to workaround ORM #3541

### LINKED ISSUE #3541: feature flags migration fails when re-creating the full db schema
```
bundle exec rake --trace db:migrate
#...
method name= doesn't exist
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1780:in `block in set_restricted'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1767:in `each'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1767:in `set_restricted'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1278:in `set'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1736:in `initialize_set'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:920:in `initialize'
db/migrate/20150505103504_new_dashboard_for_everybody.rb:16:in `new'
```

The problem is that Sequel is not smart enough to parse and load the generated schema.rb in one big run. The solution is not to depend on the model to execute non-schema migrations. This affects on-premise image generation as well as any other fresh instance.

### PR DESCRIPTION
**Pull request by rafatower**
It also adds a sequence, which shall be safer.

Fixes #3541

@juanignaciosl can you please review?

@santisaez this should solve the generation issue

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3523/))

File: db/migrate/20150505103504_new_dashboard_for_everybody.rb [hunk 1]
```diff
@@ -3,26 +3,47 @@
...
+    # It starts in negative numbers and goes downward in order to be able to identify quickly flags added automatically
+    Rails::Sequel.connection.run(%Q{
+      CREATE SEQUENCE machine_added_feature_flags_id_seq INCREMENT BY -1
+        START WITH #{START_SEQ_NUMBER}
+        OWNED BY feature_flags.id;
+    })
+
+    # Update the flags if they exist to make them unrestricted
+    Rails::Sequel.connection.run(%Q{
+      UPDATE feature_flags SET restricted = FALSE WHERE name IN (#{sql_flag_list}) AND restricted = TRUE;
```
Comment (juanignaciosl) [inline db/migrate/20150505103504_new_dashboard_for_everybody.rb]: Could you double check this works, please? I think `%Q` won't add single quotes so the names inside the `IN` would be interpreted as columns instead of literals.

File: db/migrate/20150505103504_new_dashboard_for_everybody.rb [hunk 2]
```diff
@@ -3,26 +3,47 @@
...
+    })
+
+    # Create the flags if they don't exist
+    Rails::Sequel.connection.run(%Q{
+      INSERT INTO feature_flags (id, name, restricted)
+        WITH flags_to_add as (
+          SELECT * FROM (SELECT unnest(array[#{sql_flag_list}]) as name) as flag EXCEPT (SELECT name from feature_flags)
```
Comment (juanignaciosl) [inline db/migrate/20150505103504_new_dashboard_for_everybody.rb]: Hadn't used `unnest`, it goes inside my toolbox right now!! :heart_eyes:

**Comment by juanignaciosl** [comment]
:+1: Maybe it'd be interesting involving someone else in the CR, since the negative id might feel hacky (no need to say I really like it and has never given problems to me).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3533/))

**Comment by rafatower** [comment]
I modified it because it still had some problems, namely:
  - Deprecate a buggy migration (but not add anything to it nor delete
    the file).
  - Move the sequence to its own migration.
  - Specific migration for the addition of dashboard feature flags.

@lbosque: please review

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3534/))

**Comment by lbosque** [comment]
:+1:
