### PR TITLE
3815 error generating vizjson if affected table does not exist

### LINKED ISSUE #3815: Error generating vizjson if affected table does not exist
https://rollbar.com/vizzuality/CartoDB/items/7042/occurrences/5583986264/

```
ActiveRecord::StatementInvalid: PG::Error: ERROR: relation "<table name>" does not exist
: SELECT CDB_QueryTables(
<omitted>
)
... 6 non-project frames
7
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/layer.rb", line 66 in affected_table_names
8
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/layer.rb", line 59 in tables_from_query_option
9
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/layer.rb", line 27 in affected_tables
10
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/visualization.rb", line 285 in block in get_related_tables
... 3 non-project frames
14
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/visualization.rb", line 285 in get_related_tables
15
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/visualization.rb", line 63 in related_tables
16
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/visualization.rb", line 272 in has_private_tables?
17
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/carto/visualization.rb", line 135 in retrieve_named_map?
18
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/visualization/vizjson.rb", line 95 in layers_for
19
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/models/visualization/vizjson.rb", line 42 in to_poro
20
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/carto/api/vizjson_presenter.rb", line 33 in calculate_vizjson
21
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/carto/api/vizjson_presenter.rb", line 17 in block in to_vizjson
22
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/helpers/redis_vizjson_cache.rb", line 21 in cached
23
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/carto/api/vizjson_presenter.rb", line 16 in to_vizjson
24
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/carto/admin/visualization_public_map_adapter.rb", line 31 in to_vizjson
25
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/admin/visualizations_controller.rb", line 128 in public_table
... 6 non-project frames
32
File "/home/ubuntu/www/production.cartodb.com/releases/20150527154133/app/controllers/application_controller.rb", line 54 in wrap_in_profiler
```

Reported to @iriberri . cc @rafatower @Kartones

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #3815 by restoring old behaviour. A layer with invalid SQL can now be opened in the editor. @Kartones can you CR this, please?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3973/))

File: app/models/carto/layer.rb [hunk 1]
```diff
@@ -57,6 +57,10 @@ def tooltip_template_path
 
     def tables_from_query_option
       ::Table.get_all_user_tables_by_names(affected_table_names, user)
+    rescue => exception
+      # INFO: this covers changes that CartoDB can't track. For example, if layer SQL contains wrong SQL (uses a table that doesn't exist, or uses an invalid operator).
+      CartoDB.notify_debug('Could not retrieve tables fro query', { user: user, layer: self })
```
Comment (Kartones) [inline app/models/carto/layer.rb]: typo "fro query"

**Comment by Kartones** [comment]
:+1:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3979/))
