### PR TITLE
403 redirections (formerly "Redirect to change password page when session is expired")

### LINKED ISSUE #14435: Enable MFA from the UI should redirect to MFA setup to logged users.
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

0. Login in an incognito window with a org user
1. Login in other browser as org admin
2. Go to your organization
3. Go to organization settings -> users -> click on user
4. Enable MFA and save
5. Go to the org user browser and click on View datasets.

### Current Result

There's a 404 in the Network tab

### Expected result

It should be redirected to `/multifactor_authentication` and block any other URL

### Additional info

The redirection takes place in Rails [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/application_controller.rb#L206-L207) but we should also check [this](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/dashboard/statics/static.js#L104-L106)

See [this comment](https://github.com/CartoDB/cartodb/pull/14396#issuecomment-438390496) to reproduce the `static.js` redirection locally

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR adds the ability to redirect users (belonging to an organization or not) to the password change page when their session has expired.

The PR implements a general approach to the problem using a network request interceptor, that allows the developer to add any behaviours on top of the request-defined ones. It defines success and error interceptors for all the filtered requests.

Related to #13794 
Closes #14435

### CODE REVIEW

**Comment by jesusbotella** [comment]
retest this please

**Comment by alrocar** [comment]
I'm starting to work on this PR to add what it's required to solve [this issue](https://github.com/CartoDB/cartodb/issues/14435).

I'll let you know when it's ready for CR/Acceptance.

**Comment by alrocar** [comment]
@jesusbotella This should be ready for review. I'd like to have this merged this week if possible 🙏 

I'm adding it to the backend kanban as well, to get a quick CR for the backend part.

Regarding acceptance I guess it can be done by someone at backend (since it involves enabling MFA, password expiration, etc.)

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -288,7 +299,7 @@ def redirect_or_not_found(path)
   end
 
   def render_multifactor_authentication
-    redirect_or_not_found('multifactor_authentication_session')
+    redirect_or_forbidden('multifactor_authentication_session', 'mfa_required')
   end
 
   def render_locked_user
```
Comment (javitonino) [inline app/controllers/application_controller.rb]: Maybe change this method (lockout) as well to use the new system?

Comment (alrocar) [reply app/controllers/application_controller.rb]: 👍 

At some point we could add interceptors for 404 and 401 as well...

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js [hunk 2]
```diff
@@ -0,0 +1,97 @@
+var $ = require('jquery');
```
Comment (jesusbotella) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Can we use const/let (depending on the case) for all these variables that use `var` keyword in this file? I think that when I coded this we were not allowed to use ES6 in Builder.

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
+/**
+ * 403 Forbidden Network Error Interceptor
+ *
+ * This interceptor redirects 403 errors
+ * to their corresponding routes
+ */
+
+var DEFAULT_ROUTE = '/login';
```
Comment (jesusbotella) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js]: Same here please 😂

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+var LOGIN_ROUTE = '/login?error=session_expired';
+var SESSION_EXPIRED = 'session_expired';
+var MFA_REQUIRED = 'mfa_required';
+var MFA_ROUTE = '/multifactor_authentication';
+var LOCKOUT = 'lockout';
+var LOCKOUT_ROUTE = '/lockout';
+
+var subdomainMatch = /https?:\/\/([^.]+)/;
+
+var redirectRoutes = {};
```
Comment (jesusbotella) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js]: There's one neat thing in ES6 that allows you to put dynamic object keys in object declaration, like:
```js
const redirectRoutes = {
  [SESSION_EXPIRED]: LOGIN_ROUTE,
  [MFA_REQUIRED]: MFA_ROUTE,
  [LOCKOUT]: LOCKOUT_ROUTE
};
```

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+  getRedirectURL: function getRedirectURL (currentURLOrigin, route, username) {
+    if (!username) {
+      return currentURLOrigin + route;
+    }
+
+    var newURL = currentURLOrigin.replace(subdomainMatch, function () {
+      return username;
+    });
+
+    return window.location.protocol + '//' + newURL + route;
```
Comment (jesusbotella) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js]: Just to make it look newer, let's use string templates here:
```js
return `${window.location.protocol}//${newURL}${route}`;
```

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js (hunk 4 above)
Comment (alrocar) [reply lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptors/forbidden-403.js]: Didn't know about this. Thanks!

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+
+function NetworkResponseInterceptor () {
+  this._originalAjax = $.ajax;
+  this._successInterceptors = [];
+  this._errorInterceptors = [];
+  this._urlPatterns = [];
+}
+
+NetworkResponseInterceptor.prototype.start = function () {
+  let onRequestStart = this._onRequestStart.bind(this);
```
Comment (ivanmalagon) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Why this indirection and not `$.ajax = this._onRequestStart.bind(this)`?

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+
+/**
+ * Network Interceptors
+ *
+ * Tool to easily intercept network responses in order
+ * to override or add behaviours on top of the usual ones
+ */
+
+function NetworkResponseInterceptor () {
+  this._originalAjax = $.ajax;
```
Comment (ivanmalagon) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Does `$.ajax` points to `XmlHttpRequest` object or is it a wrapper on jQuery?

I ask this because in the new dashboard we don't use jQuery so we must take it into account to not cause a regression on the new dashboard.

Comment (jesusbotella) [reply lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: It is [jQuery ajax](http://api.jquery.com/jquery.ajax/), which I suppose that is a wrapper over `XmlHttpRequest` using jQuery promises.

Yes, I was planning on opening a new issue to implement this in the New Dashboard.

Comment (jesusbotella) [reply lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: https://github.com/CartoDB/cartodb/issues/14489
