### PR TITLE
Fix layer counter

### LINKED ISSUE #12236: Faulty Layer Counter
@arredond commented on [Tue May 30 2017](https://github.com/CartoDB/support/issues/738)

### Context

```NOTE: This only happened opening a new map once. Haven't been able to reproduce; the counter is working fine in other maps.```

The recently added layer counter in BUILDER starts on 0, even though there always has to be at least one layer to create a dashboard. That means that, when you reach the limit of 8 layers, the counter is showing one less (in most cases, 7/8).

layer_count_0
layer_count

### PR DESCRIPTION
**Pull request by rubenmoya**
Fixes #12236

screen shot 2017-05-31 at 10 50 19

### Acceptance
- [ ] Counter increase/decrease when creating `CartoDB` layers
- [ ] Counter increase/decrease when creating `torque` layers

### CODE REVIEW

File: lib/assets/core/javascripts/cartodb3/editor/editor-pane.js [hunk 1]
```diff
@@ -302,12 +302,8 @@ module.exports = CoreView.extend({
     window.location = this._userModel.get('base_url');
   },
 
-  _getCartoLayerCount: function () {
-    return this._layerDefinitionsCollection.models.filter(
-      function (model) {
-        return model.get('type') === 'CartoDB';
-      }
-    ).length;
+  _getDataLayerCount: function () {
```
Comment (xavijam) [inline lib/assets/core/javascripts/cartodb3/editor/editor-pane.js]: Do we need this helper function? I feel this._layerDefinitionsCollection.getNumberOfDataLayers() is quite straight forward.

**Comment by matallo** [comment]
🚀
