### PR TITLE
Copy visualizations using export/import

### LINKED ISSUE #7657: duplicate map of a map with analyses fails
**str**

- import a map with analyses (classic paradas de metro)
- open map
- duplicate map
- open duplicate map in builder

**expected behaviour**

- panels and map load

**actual behaviour**

- panels and map fail, find attached the developer tools trace

```
editor3.js:21147 Uncaught Error: layerAnalysisDefinitionNodeModel is required
common_editor3.js:62620 Uncaught TypeError: Cannot read property 'toJSON' of undefined
```

### PR DESCRIPTION
**Pull request by javitonino**
Fix #7657 #6889

Uses the export/import flow to duplicate maps, in order to support the latest features. Note that creating a map from a canonical visualization still uses `TableBlender` and `Map::Copier` which do not support analyses, etc. This should not be a problem as canonical visualizations can't have those.

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @gfiorav

File: Makefile [hunk 1]
```diff
@@ -46,7 +46,6 @@ WORKING_SPECS_1 = \
 	spec/models/map_spec.rb \
 	spec/models/map/copier_spec.rb \
 	spec/models/visualization/collection_spec.rb \
-	spec/models/visualization/copier_spec.rb \
```
Comment (gfiorav) [inline Makefile]: There are no new specs for this?

Comment (javitonino) [inline Makefile]: I rely on the import/export tests, which include exporting and reimporting maps, so that should be covered. I also kept the controller level tests.

File: lib/carto/named_maps/api.rb [hunk 2]
```diff
@@ -1,7 +1,7 @@
 # encoding: utf-8
 
 require_relative '../http/client.rb'
-require_relative 'template.rb'
```
Comment (gfiorav) [inline lib/carto/named_maps/api.rb]: Thanks man

File: Makefile (hunk 1 above)
Comment (gfiorav) [inline Makefile]: 🌴

**Comment by gfiorav** [comment]
📦 ready for me if you tested it in staging!
