### PR TITLE
Embed privacy fix

### LINKED ISSUE #9643: Having problems with sharing maps the first time you publish them
Lately we are having problems when sharing maps. After publishing them for the first time (if you change the privacy before) It gives an instantiation error on the public view. You have to move the map on the builder, click on update and then it works.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixed #9643

This basically does two things:

- Always generates the named map template based on non-mapcapped visualisation
- Updates named map template even if the visualisation is mapcapped provided the privacy has changed

And has a bonus:

- Removes duplicate mapcap regeneration in embed

Please CR @juanignaciosl

### CODE REVIEW

File: app/controllers/carto/builder/public/embeds_controller.rb [hunk 1]
```diff
@@ -45,11 +50,11 @@ def load_auth_tokens
         end
 
         def load_vizjson
-          @vizjson = generate_named_map_vizjson3(@visualization.for_presentation, params)
+          @vizjson = generate_named_map_vizjson3(@visualization_for_presentation, params)
```
Comment (juanignaciosl) [inline app/controllers/carto/builder/public/embeds_controller.rb]: Maybe we're pushing this "load_X" pattern a little too far here. `load_visualization` currently loads not only `visualization` but also `visualization_for_presentation`. Maybe creating a `visualization_for_presentation` private method in the controller that returns `@visualization.for_presentation` memoized. Minor, though, up to you.

File: app/models/carto/visualization.rb [hunk 2]
```diff
@@ -420,6 +420,10 @@ def for_presentation
     mapcapped? ? latest_mapcap.regenerate_visualization : self
   end
 
+  def non_mapcapped
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Could you please explain to me what does this method do? Just to be clear, this is not a complain, just a question :_). Needing a "non mapcapped" instead of just using the visualization instead feels weird.

**Comment by juanignaciosl** [comment]
I've done a couple of minor comments, I'll resume the CR after your answers.

**Comment by gfiorav** [comment]
So from offline discussion: It seems clear that visualisation methods should be mapcap aware at this point. I'm going to propose we chicken out though, and leave it as is (this is sensible). I'll open an issue for it if you agree.

File: app/models/visualization/member.rb [hunk 3]
```diff
@@ -648,7 +648,6 @@ def invalidate_redis_cache
 
       def save_named_map
         return if type == TYPE_REMOTE
-        return true if mapcapped?
```
Comment (juanignaciosl) [inline app/models/visualization/member.rb]: About this deletion: is saving named map for "mapcapped" members no longer needed, or is saving naming maps for "mapcapped" members safe?

**Comment by juanignaciosl** [comment]
Ok, chickening out on this is fine. Instead of opening an issue, I'd add a comment at `non_mapcapped` method. At the offline discussion we agreed that leaking mapcaps out _can_ be dangerous but we're not 100% confident about that, so I'd add a warning explaining that if that method is needed again because of auth reasons, that auth check should probably me moved inside the visualization itself.

File: app/models/visualization/member.rb (hunk 3 above)
Comment (gfiorav) [inline app/models/visualization/member.rb]: The decision is taken in `update_named_map` now. I can replicate that check here and save the transaction. Good point.

**Comment by gfiorav** [comment]
Took your comments into consideration and made some adjustments. Have a (hopefully) final look!

File: app/models/visualization/member.rb [hunk 4]
```diff
@@ -648,7 +648,7 @@ def invalidate_redis_cache
...
+        return true if mapcapped? && !privacy_changed
```
Comment (juanignaciosl) [inline app/models/visualization/member.rb]: `if mapcapped? && !privacy_changed` seems to be duplicated, consider extract method refactor.

**Comment by juanignaciosl** [comment]
I've just made a minor comment. 👍

**Comment by juanignaciosl** [comment]
I would've chosen the positive expression, `named_map_updates_enabled?`, but up to you 😅 👍
