### PR TITLE
User pages fixes

### LINKED ISSUE #2651: Changing avatar does not refresh it when selecting the file
## STR
 1. Go to "*Account settings*"
 1. Go to "*Profile*"
 1. "*Chose avatar*"
 1. Select a file

## Current result
There is no preview of the new avatar

## Expected result
The new avatar should have a preview (specially when you don't have an avatar yet)

screen shot 2015-03-06 at 12 50 43

### LINKED ISSUE #2652: It's not possible select a different avatar after selecting a first one
## STR
 1. Go to "*Account settings*"
 1. Go to "*Profile*"
 1. "*Chose avatar*"
 1. Select a file

## Current result
It's no longer possible to select again another avatar

## Expected result
It should be possible to select another avatar before saving the change

screen shot 2015-03-06 at 12 50 43

### LINKED ISSUE #3066: Error message not showed correctly if you try to delete an user from org with shared entities
*How to reproduce:*
1. Using your org user owner. (example: ded01testorg)
2. Go to * organization -> manage your seats *
3. Click on an user that *has shared entities.* (example: ded01orguser2)
4. Click on `Delete this user` and `Yes, delete ded01orguser2`
5. Then, nothing happens in that modal window. (Although a POST request is done , checked with Network-Developer Tools)
6. Click on `Cancel` or `X`. 
7. Reload the page.
8. Now, the error message is showed: `User was not deleted. Can't delete user. Has shared entities` .

I guess that the error should be displayed in the modal infowindow, or another interaction. But the user would not know what's happening if he/she doesn't reload the page.

Gif:
delete_user_org_error

### PR DESCRIPTION
**Pull request by xavijam**
Several fixes for user and organization pages.

- [x] It's not possible select a different avatar after selecting a first one (fixes #2652).
- [x] Changing avatar does not refresh it when selecting the file (fixes #2651).
- [x] Error message not showed correctly if you try to delete an user from org with shared entities (fixes #3066).
- [x] Admin of the organisation cannot assign quota to its sub-users (Fixes cartodb/cartodb-central#583).

avatar_selector

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2900/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2901/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2906/))

**Comment by xavijam** [comment]
@kartones and @javierarce, could you review it please?
Now avatar/logo upload takes place in the frontend and not in the backend, so backend only receives an url, and that's it.

File: app/controllers/admin/organization_users_controller.rb [hunk 1]
```diff
@@ -147,7 +147,11 @@ def destroy
     else
       set_flash_flags(nil, true)
       flash[:error] = "User was not deleted. #{e.user_message}"
-      head :no_content
+      if new_dashboard
+        redirect_to CartoDB.url(self, 'organization', {}, current_user)
+      else
+        head :no_content
+      end
     end
```
Comment (xavijam) [inline app/controllers/admin/organization_users_controller.rb]: Fixes #3066.

File: app/controllers/admin/organizations_controller.rb [hunk 2]
```diff
@@ -31,14 +31,7 @@ def settings_update
...
-      asset = Asset.new
-      asset.raise_on_save_failure = true
-      asset.user_id = current_user.id
-      asset.asset_file = attributes[:avatar_url]
-      asset.kind = Asset::KIND_ORG_AVATAR
-      if asset.save
-        @organization.avatar_url = asset.public_url
-      end
+      @organization.avatar_url = attributes[:avatar_url]
     end
```
Comment (xavijam) [inline app/controllers/admin/organizations_controller.rb]: No more asset upload

File: app/views/admin/organization_users/_new_form.html.erb [hunk 3]
```diff
@@ -164,8 +164,10 @@
   <% end %>
   <%
     assigned_quota_in_bytes = 0
-    current_user.organization.users.map { |u| 
-      assigned_quota_in_bytes = assigned_quota_in_bytes + u.quota_in_bytes 
+    current_user.organization.users.map { |u|
+      if (u.username != @user.username) 
+        assigned_quota_in_bytes = assigned_quota_in_bytes + u.quota_in_bytes 
+      end
     }
```
Comment (xavijam) [inline app/views/admin/organization_users/_new_form.html.erb]: Fixing https://github.com/CartoDB/cartodb-central/issues/583. Total assigned_quota_in_bytes shouldn't include the current user assigned quota. It caused problems with the "quota slider" setting more quota than the org had.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2908/))

File: app/views/admin/organizations/new_settings.html.erb [hunk 4]
```diff
@@ -60,12 +60,14 @@
...
-        <div class="Form-row">
+        <div class="Form-row js-avatarSelector">
           <div class="Form-rowLabel">
-            <label class="Form-label">Logo</label>
+            <label class="Form-label">Avatar</label>
           </div>
           <div class="Form-rowData Form-avatar">
-            <img src="<%= @organization.avatar_url %>" title="" alt="" class="Form-avatarPreview" />
+            <div class="Form-avatarPreview">
+              <img src="<%= @organization.avatar_url %>" title="" alt="" class="Form-avatarPreviewImage" />
```
Comment (javierarce) [inline app/views/admin/organizations/new_settings.html.erb]: I would fill the empty quotes of `title` and `alt`, otherwise I'de remove them.

File: lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+    avatarUpload.save({
+      kind: 'orgavatar',
+      filename: file
+    }, {
+      success: this._onSuccess,
+      error: this._onError
+    });
+  },
+
+  _onSuccess: function(m, d) {
```
Comment (javierarce) [inline lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js]: I'd remove the comments here, the method names really explain what's going on :)

Comment (xavijam) [inline lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js]: Don't worry, it is overridden by avatar_selector_view template. Where it has alt and title values.
 https://github.com/CartoDB/cartodb/blob/user-pages-fixes/lib/assets/javascripts/cartodb/new_common/views/avatar_selector_view.jst.ejs#L7

File: app/views/admin/organizations/new_settings.html.erb (hunk 4 above)
Comment (xavijam) [inline app/views/admin/organizations/new_settings.html.erb]: Don't worry, it is overridden by avatar_selector_view template. Where it has alt and title values.
 https://github.com/CartoDB/cartodb/blob/user-pages-fixes/lib/assets/javascripts/cartodb/new_common/views/avatar_selector_view.jst.ejs#L7

File: lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js (hunk 5 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js]: Those ones -> https://github.com/CartoDB/cartodb/pull/3088#discussion-diff-28060076R45?

File: app/views/admin/organizations/new_settings.html.erb (hunk 4 above)
Comment (javierarce) [inline app/views/admin/organizations/new_settings.html.erb]: :ok_hand:

**Comment by javierarce** [comment]
:dancers: frontend code looks and smells good.

File: lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js (hunk 5 above)
Comment (javierarce) [inline lib/assets/javascripts/cartodb/new_common/avatar_selector_view.js]: :ok_hand:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2910/))

**Comment by xavijam** [comment]
:dancer:

File: app/controllers/admin/organization_users_controller.rb (hunk 1 above)
Comment (Kartones) [inline app/controllers/admin/organization_users_controller.rb]: weren't we going to remove the ifs distinguishing the new/old dashboard? :trollface:

Comment (xavijam) [inline app/controllers/admin/organization_users_controller.rb]: Yep, boss said next sprint. Fasten your seat belts :D

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2913/))

**Comment by Kartones** [comment]
ok!
