### PR TITLE
Regression for broken google organization login

### LINKED ISSUE #11224: Regression for Broken Google organization login
Test covering #11223 regression. It was a quick fix that will probably be deployed without test.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #11224

### CODE REVIEW

File: spec/requests/sessions_controller_spec.rb [hunk 1]
```diff
@@ -4,6 +4,66 @@
...
+
+  def stub_subdomainless
+    CartoDB.stubs(:session_domain).returns('localhost.lan')
+    CartoDB.stubs(:subdomainless_urls?).returns(true)
+    host! "localhost.lan"
+  end
+
+  shared_examples_for 'Google' do
+    before(:all) do
+      google_plus_config_mock = mock
```
Comment (javitonino) [inline spec/requests/sessions_controller_spec.rb]: Can you not use a real object here? Something like
`GooglePlusConfig.new(CartoDB, { domain: user_domain }, '', 'atfi')`
instead of the mock. (Of course, you still need to mock `instance`).

File: spec/requests/sessions_controller_spec.rb [hunk 2]
```diff
@@ -4,6 +4,66 @@
...
+    CartoDB.stubs(:session_domain).returns('.localhost.lan')
+    CartoDB.stubs(:subdomainless_urls?).returns(false)
+    host! "#{subdomain}.localhost.lan"
+  end
+
+  def stub_subdomainless
+    CartoDB.stubs(:session_domain).returns('localhost.lan')
+    CartoDB.stubs(:subdomainless_urls?).returns(true)
+    host! "localhost.lan"
+  end
```
Comment (javitonino) [inline spec/requests/sessions_controller_spec.rb]: Nice helpers!

We could consider extracting them to a global spec helper as there are more tests that do something like this. Something to keep in mind while working on tests in the future.

Comment (juanignaciosl) [inline spec/requests/sessions_controller_spec.rb]: Moved to `spec/spec_helper.rb`.

File: spec/requests/sessions_controller_spec.rb (hunk 1 above)
Comment (juanignaciosl) [inline spec/requests/sessions_controller_spec.rb]: True, better, although `domain` will still be a mock in order to lazy load it.

File: spec/requests/sessions_controller_spec.rb [hunk 3]
```diff
@@ -4,6 +4,56 @@
...
 describe SessionsController do
+  shared_examples_for 'Google' do
+    before(:all) do
+      google_plus_config = {
+        access_token_field_id: 'atfi',
+        iframe_src: '',
+        signup_action: '',
+        unauthenticated_valid_access_token: ''
+      }
+      # mocking `:domain` allows lazy loading `user_domain`
```
Comment (javitonino) [inline spec/requests/sessions_controller_spec.rb]: Nice comment 🤗
