### PR TITLE
Fixes custom ramp selection

### LINKED ISSUE #10089: Fill component doesn't allow to edit the custom ramps
It seems that a previous enhancement of the Fill component (the removal of the "Custom color set" link) broke the possibility of editing the custom ramps. 

The solution would be this: after a ramp is selected, a new click will send users to the editing form.

### PR DESCRIPTION
**Pull request by javierarce**
From the issue description: 

> It seems that a previous enhancement of the Fill component (the removal of the "Custom color set" link) broke the possibility of editing the custom ramps.

> The solution would be this: after a ramp is selected, a new click will send users to the editing form.

See solution in action: 

gradient

Closes #10089

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam 
CC: @arianaescobar

File: lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-item-view.js [hunk 1]
```diff
@@ -56,7 +56,12 @@ module.exports = CoreView.extend({
 
   _onClick: function (ev) {
     this.killEvent(ev);
-    this.model.set('selected', true);
+
+    if (this.model.get('selected')) {
+      this.trigger('customEvent', 'customize', this.model.get('val'), this);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-item-view.js]: Why not send parameters as an object instead of sending multiple vars?

Comment (javierarce) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-item-view.js]: Well, I'm just using the implemented solution right now. It's being used in another place, but I could do the improvement in this ticket.

**Comment by xavijam** [comment]
:+1:

File: lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-item-view.js (hunk 1 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-item-view.js]: Dale neno!
