### PR TITLE
11722 user table refactor 5

### LINKED ISSUE #11722: [Model refactor] Switching UserTable model [DEPLOY SOON*]
Now that all `table_spec.rb` tests pass, it's time to approach other tests. We did a test run changing `model_class` in `::Table` to point to the AR model, and the following tests failed, which can be used as a guide for further refactors:

```
services/user-mover/spec/user_mover_spec.rb:117 # CartoDB::DataMover::ExportJob should move a whole organization
services/user-mover/spec/user_mover_spec.rb:163 # CartoDB::DataMover::ExportJob should move a whole organization without splitting user schemas
spec/connectors/importer_spec.rb:323 # CartoDB::Connector::Importer imported visualization should have registered table dependencies
spec/connectors/importer_spec.rb:381 # CartoDB::Connector::Importer should be able to import a multi file zip as a multilayer map
spec/connectors/importer_spec.rb:403 # CartoDB::Connector::Importer should be able to handle a zip with more files max_layers
spec/models/layer_shared_examples.rb:235 # Carto::Layer behaves like Layer model #uses_private_tables? returns true if any of the affected tables is private
spec/models/carto/user_migration_spec.rb:18 # UserMigration exports and reimports a user
spec/models/carto/user_migration_spec.rb:58 # UserMigration with organization exports and reimports an organization
spec/models/carto/user_table_spec.rb:52 # Carto::UserTable#readable_by? returns true for shared tables
spec/models/layer_shared_examples.rb:235 # Layer behaves like Layer model #uses_private_tables? returns true if any of the affected tables is private
spec/models/map_spec.rb:211 # Map#tables updates associated tables/vis upon change
spec/models/map_spec.rb:275 # Map#after_save invalidates varnish cache
spec/models/map_spec.rb:283 # Map#after_save recalculates bounds
spec/models/map_spec.rb:302 # Map#after_save recenters map using bounds
spec/models/map_spec.rb:425 # Map#admits? when linked to a table visualization returns false when passed a data layer and it is already linked to a base layer
spec/models/map_spec.rb:454 # Map#before_destroy invalidates varnish cache
spec/models/map_spec.rb:462 # Map#process_privacy_in sets related visualization private if layer uses private tables
spec/models/table/relator_spec.rb:82 # CartoDB::TableRelator.serialize_fully_dependent_visualizations given there are at least one dependent visualization should return a list with dependent visualizations
spec/models/table/relator_spec.rb:86 # CartoDB::TableRelator.serialize_fully_dependent_visualizations given there are at least one dependent visualization should contain expected datapoints required for dashboard
spec/models/table/relator_spec.rb:141 # CartoDB::TableRelator.serialize_partially_dependent_visualizations given there are at least one non_dependent visualization should return a list with dependent visualizations
spec/models/table/relator_spec.rb:145 # CartoDB::TableRelator.serialize_partially_dependent_visualizations given there are at least one non_dependent visualization should contain expected datapoints required for dashboard
spec/models/table_spec.rb:700 # Table with ::UserTable model behaves like table service when removing the table should remove the automatic_geocoding
spec/models/table_spec.rb:704 # Table with ::UserTable model behaves like table service when removing the table should remove the table from the user database
spec/models/table_spec.rb:710 # Table with ::UserTable model behaves like table service when removing the table should not remove the table from the user database if specified
spec/models/table_spec.rb:717 # Table with ::UserTable model behaves like table service when removing the table should update denormalized counters
spec/models/table_spec.rb:723 # Table with ::UserTable model behaves like table service when removing the table should remove the metadata table even when the physical table does not exist
spec/models/table_spec.rb:700 # Table with Carto::UserTable model behaves like table service when removing the table should remove the automatic_geocoding
spec/models/table_spec.rb:704 # Table with Carto::UserTable model behaves like table service when removing the table should remove the table from the user database
spec/models/table_spec.rb:710 # Table with Carto::UserTable model behaves like table service when removing the table should not remove the table from the user database if specified
spec/models/table_spec.rb:717 # Table with Carto::UserTable model behaves like table service when removing the table should update denormalized counters
spec/models/table_spec.rb:723 # Table with Carto::UserTable model behaves like table service when removing the table should remove the metadata table even when the physical table does not exist
spec/models/visualization/collection_spec.rb:188 # CartoDB::Visualization::Collection#fetch Checks all supported sorting methods work
spec/models/visualization/collection_spec.rb:300 # CartoDB::Visualization::Collection#fetch counts total liked
spec/models/visualization/collection_spec.rb:402 # CartoDB::Visualization::Collection#fetch checks filtering by 'liked' 
spec/models/visualization/member_spec.rb:1295 # CartoDB::Visualization::Member licenses should store correctly a visualization with its license
spec/models/visualization/member_spec.rb:1305 # CartoDB::Visualization::Member licenses should return nil if the license is nil, empty or unkown
spec/models/visualization/member_spec.rb:1321 # CartoDB::Visualization::Member licenses should raise exception when try to store a unknown license, empty or nil
spec/models/visualization/organization_visualization_spec.rb:70 # CartoDB::Visualization::Member sharing tables and visualizations should give read permission to table aka canonical visualization
spec/models/visualization/organization_visualization_spec.rb:82 # CartoDB::Visualization::Member sharing tables and visualizations other user should not have permission until given
spec/models/visualization/organization_visualization_spec.rb:93 # CartoDB::Visualization::Member sharing tables and visualizations other user will not get permission in private table when the table owners adds it to the visualization
spec/models/visualization/organization_visualization_spec.rb:106 # CartoDB::Visualization::Member sharing tables and visualizations should not remove access to visualization if table privacy is changed to private
spec/models/visualization/relator_spec.rb:60 # CartoDB::Visualization::Relator#related_canonical_visualizations should return the canonical visualizations associated to a derived visualization
spec/models/visualization/table_blender_spec.rb:35 # CartoDB::Visualization::TableBlender#blend multiple tables sets increasing order for data layers and keep tiled first and last
spec/queries/carto/visualization_query_builder_spec.rb:71 # Carto::VisualizationQueryBuilder can prefetch table
spec/queries/carto/visualization_query_builder_spec.rb:99 # Carto::VisualizationQueryBuilder orders using different criteria
spec/requests/admin/visualizations_spec.rb:665 # Admin::VisualizationsController find visualizations by name does not find visualizations outside org
spec/requests/admin/visualizations_spec.rb:687 # Admin::VisualizationsController find visualizations by name does not find visualizations outside user with public schema
spec/requests/api/json/visualizations_controller_spec.rb:159 # Api::Json::VisualizationsController#create #creates map from datasets correctly creates a visualization from two dataset of different users
spec/requests/api/json/visualizations_controller_spec.rb:214 # Api::Json::VisualizationsController#create #creates map from datasets doen't add style properites for editor users
spec/requests/api/json/visualizations_controller_spec.rb:249 # Api::Json::VisualizationsController#create #creates map from datasets rewrites queries for other user datasets
spec/requests/api/json/visualizations_controller_spec.rb:269 # Api::Json::VisualizationsController#create #creates map from datasets does not rewrite queries for same user datasets
spec/requests/api/json/visualizations_controller_spec.rb:360 # Api::Json::VisualizationsController#likes when a map is liked should send an email to the owner
spec/requests/api/json/visualizations_controller_spec.rb:373 # Api::Json::VisualizationsController#likes when a map is liked by the owner, the email should not be sent
spec/requests/api/visualizations_spec.rb:74 # Api::Json::VisualizationsController POST /api/v1/viz creates a visualization from a source_visualization_id
spec/requests/api/visualizations_spec.rb:88 # Api::Json::VisualizationsController POST /api/v1/viz creates a private visualization from a private table
spec/requests/api/visualizations_spec.rb:100 # Api::Json::VisualizationsController POST /api/v1/viz creates a private visualization if any table in the list is private
spec/requests/api/visualizations_spec.rb:115 # Api::Json::VisualizationsController POST /api/v1/viz creates a private visualization if any table in the list is private
spec/requests/api/visualizations_spec.rb:137 # Api::Json::VisualizationsController POST /api/v1/viz assigns a generated name if name taken
spec/requests/carto/api/layers_controller_spec.rb:560 # Carto::Api::LayersController attribution changes attribution changes in a visualization propagate to associated layers
spec/requests/carto/api/layers_controller_spec.rb:626 # Carto::Api::LayersController index fetches layers from shared visualizations
spec/requests/carto/api/layers_controller_spec.rb:762 # Carto::Api::LayersController#show legacy tests Gets layers by map id
spec/requests/carto/api/templates_controller_spec.rb:85 # Carto::Api::TemplatesController tests index action
spec/requests/carto/api/templates_controller_spec.rb:112 # Carto::Api::TemplatesController tests show action
spec/requests/carto/api/templates_controller_spec.rb:127 # Carto::Api::TemplatesController tests create action
spec/requests/carto/api/templates_controller_spec.rb:155 # Carto::Api::TemplatesController tests update action
spec/requests/carto/api/templates_controller_spec.rb:207 # Carto::Api::TemplatesController tests destroy action
spec/requests/carto/api/templates_controller_spec.rb:227 # Carto::Api::TemplatesController tests related_tables_by_xxx actions
spec/requests/carto/api/vizjson_shared_examples.rb:182 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility Sanitizes vizjson callback
spec/requests/carto/api/vizjson_shared_examples.rb:223 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility get vizjson renders vizjson vx
spec/requests/carto/api/vizjson_shared_examples.rb:231 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility get vizjson returns 200 if subdomain is empty
spec/requests/carto/api/vizjson_shared_examples.rb:276 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility get vizjson joins the attributions of the layers in a layergroup in the viz.json
spec/requests/carto/api/vizjson_shared_examples.rb:316 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility get vizjson joins the attributions of the layers in a namedmap in the viz.json
spec/requests/carto/api/vizjson_shared_examples.rb:358 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator vizjson2 compatibility get vizjson Updates viz.json's layergroup when attributions in a related layer change
spec/requests/carto/api/vizjson_shared_examples.rb:425 # Carto::Api::VisualizationsController vizjson2 generator behaves like vizjson generator attributes contain type, not kind, for basemaps
spec/requests/carto/api/vizjson_shared_examples.rb:182 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility Sanitizes vizjson callback
spec/requests/carto/api/vizjson_shared_examples.rb:223 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility get vizjson renders vizjson vx
spec/requests/carto/api/vizjson_shared_examples.rb:231 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility get vizjson returns 200 if subdomain is empty
spec/requests/carto/api/vizjson_shared_examples.rb:276 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility get vizjson joins the attributions of the layers in a layergroup in the viz.json
spec/requests/carto/api/vizjson_shared_examples.rb:316 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility get vizjson joins the attributions of the layers in a namedmap in the viz.json
spec/requests/carto/api/vizjson_shared_examples.rb:358 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator vizjson2 compatibility get vizjson Updates viz.json's layergroup when attributions in a related layer change
spec/requests/carto/api/vizjson_shared_examples.rb:425 # Carto::Api::VisualizationsController vizjson3 generator behaves like vizjson generator attributes contain type, not kind, for basemaps
spec/requests/carto/api/visualizations_controller_spec.rb:317 # Carto::Api::VisualizationsController index returns valid information for a user with one table
spec/requests/carto/api/visualizations_controller_spec.rb:987 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz retrieves a collection of visualizations
spec/requests/carto/api/visualizations_controller_spec.rb:1000 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz is updated after creating a visualization
spec/requests/carto/api/visualizations_controller_spec.rb:1023 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz is updated after deleting a visualization
spec/requests/carto/api/visualizations_controller_spec.rb:1046 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz paginates results
spec/requests/carto/api/visualizations_controller_spec.rb:1065 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz returns filtered results
spec/requests/carto/api/visualizations_controller_spec.rb:1089 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz creates a visualization from a list of tables
spec/requests/carto/api/visualizations_controller_spec.rb:1138 # Carto::Api::VisualizationsController main behaviour GET /api/v1/viz/:id returns a visualization
spec/requests/carto/api/visualizations_controller_spec.rb:1473 # Carto::Api::VisualizationsController main behaviour tests visualization listing filters uses locked filter
spec/requests/carto/api/visualizations_controller_spec.rb:1502 # Carto::Api::VisualizationsController main behaviour tests visualization listing filters searches by tag
spec/requests/carto/api/visualizations_controller_spec.rb:1518 # Carto::Api::VisualizationsController main behaviour non existent visualization returns 404
spec/requests/carto/api/visualizations_controller_spec.rb:1546 # Carto::Api::VisualizationsController main behaviour /api/v1/viz/:id/watching returns an empty array if no other user is watching
spec/requests/carto/api/visualizations_controller_spec.rb:1580 # Carto::Api::VisualizationsController index orders remotes by size with external sources size
spec/requests/carto/api/visualizations_controller_spec.rb:1617 # Carto::Api::VisualizationsController index mixed types search should filter only remote without display name
spec/requests/carto/api/visualizations_controller_spec.rb:1830 # Carto::Api::VisualizationsController error with wrong visualization url normal user urls returns 200 if user at url is empty
spec/requests/carto/api/visualizations_controller_spec.rb:1899 # Carto::Api::VisualizationsController error with wrong visualization url organization urls returns 200 with valid shared user (current_user) user_domain, with current_viewer being the owner
spec/requests/carto/api/visualizations_controller_spec.rb:1927 # Carto::Api::VisualizationsController error with wrong visualization url organization urls returns 404 if user at url is empty
spec/requests/carto/api/visualizations_controller_spec.rb:1936 # Carto::Api::VisualizationsController error with wrong visualization url organization urls returns 404 if user at url is empty, current_user is the owner and current_viewer has permission
spec/requests/carto/api/visualizations_controller_spec.rb:1946 # Carto::Api::VisualizationsController error with wrong visualization url organization urls returns 404 if user at url does not match visualization owner
spec/requests/carto/api/visualizations_controller_spec.rb:1959 # Carto::Api::VisualizationsController error with wrong visualization url organization urls returns 404 if user at url does not match visualization owner with current_user being the owner and current_viewer the shared to
spec/requests/superadmin/organizations_spec.rb:95 # Superadmin's organization API organization delete success destroys organizations (even with shared entities)
spec/requests/superadmin/organizations_spec.rb:185 # Superadmin's organization API users with shares destruction logic cleans sharing information when recipient user is deleted
spec/services/carto/visualizations_export_service_2_spec.rb:922 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables replaces owner name with new user name on import for user_name and query
spec/services/carto/visualizations_export_service_2_spec.rb:930 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables replaces owner name (with dash) with new user name on import for user_name and query
spec/services/carto/visualizations_export_service_2_spec.rb:938 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables replaces owner name (without dash) with new user name (with dash) on import for user_name and query
spec/services/carto/visualizations_export_service_2_spec.rb:947 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables removes owner name from user_name and query importing into a non-organization account
spec/services/carto/visualizations_export_service_2_spec.rb:955 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables removes owner name from user_name and query importing into a non-org. even if username matches
spec/services/carto/visualizations_export_service_2_spec.rb:993 # Carto::VisualizationsExportService2 exporting exporting + importing visualizations with shared tables does not replace owner name with new user name on import when new query fails
spec/services/carto/visualizations_export_service_spec.rb:91 # Carto::VisualizationsExportService Imports data from DB
```

### PR DESCRIPTION
**Pull request by javitonino**
Closes #11722

This is the big one, it switch `::Table` to use the AR model instead of the Sequel one. It includes minor changes to production code, and several fixes for specs.

**The 🐔 section**
I feel like we might be losing some test coverage in the map model specs in this. We still have pretty good coverage via controller tests, but some of the tests in `map_spec` were somehow tied to the table model and I fell like there is a mix of testing `::Map` and `Carto::Map` in there now.

**Acceptance**
I would consider exhaustive smoke-like checks for this one 🐔 : [mandatory acceptance smoke tests](https://docs.google.com/spreadsheets/d/1Kdl-2iCoDg6X3_M4P5vl1y9rs3i2ugaH14gGB4tLNCE/edit?ts=58c687bd#gid=1195336423).

Some specific tests that we need to perform, in addition:
- Bounding boxes automatically calculated on map creation.
- Privacy
- Cache invalidation
Let's take it slow and add tests where we feel we lack them.

**Before merging**
Remove debug traces added in previous PRs. We are sure to hit those places a lot now. 

**Next steps**
Remove `::UserModel`. It is used directly in a few places still, nothing too major.

### CODE REVIEW

File: app/models/common/map_common.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ def set_default_boundaries!
 
   def get_map_bounds
     # (lon,lat) as comes out from postgis
-    BoundingBoxHelper.get_table_bounds(user.in_database, table_name)
+    BoundingBoxHelper.get_table_bounds(::User[user.id].in_database, table_name)
```
Comment (juanignaciosl) [inline app/models/common/map_common.rb]: How come is this needed? Maybe a comment about it is convenient.

File: app/models/layer.rb [hunk 2]
```diff
@@ -227,7 +227,7 @@ def insert_table_dependencies
   end
 
   def tables_from_names(table_names, user)
-    ::Table.get_all_by_names(table_names, user)
+    ::Table.get_all_by_names(table_names, user).compact.map { |t| ::UserTable[t.id] }
```
Comment (juanignaciosl) [inline app/models/layer.rb]: Another strange change:
- type changes but calls don't.
- Shouldn't `Carto::Layer` implementation change as well?

File: app/models/carto/layer.rb [hunk 3]
```diff
@@ -111,7 +111,7 @@ def set_default_order(parent)
     # Sequel model compatibility (for TableBlender)
     def add_map(map)
       CartoDB::Logger.debug(message: 'Adding map to Carto::Layer with legacy method')
-      maps << map
+      map.layers << self
```
Comment (javitonino) [inline app/models/carto/layer.rb]: I know 😞 

I kept the `add_map` because right now `MapCopier` is compatible with both models. I am not sure if it is still called with the old models anywhere from the production code (I think not) but is still being used with old models from a bunch of tests. So instead of inlining and breaking compatibility, I did this.

About the change itself, it's needed so the `Carto::Map` instance can keep track of layers for ordering purposes. Since `inverse_of` is not supported with `has_many through:` associations, we need to do this or a reload, and this seemed nicer than to reload the map a bunch of times.

File: app/models/common/map_common.rb (hunk 1 above)
Comment (javitonino) [inline app/models/common/map_common.rb]: `BoundingBoxHelper.get_table_bounds` runs some SQL queries and assumes a Sequel DB connection is returned from `User.in_database`.

I was lazy and did a quick fix to try this, but I'll try to create `Carto::BoundingBoxHelper` that works with an AR connection instead, and we can clean this.

File: app/models/layer.rb (hunk 2 above)
Comment (javitonino) [inline app/models/layer.rb]: This is just an instance of the confusion in old code between `::Table` and `::UserTable`.

- `table_from_names` is only called from the layer dependencies code, common to both layer models. It is expected that it returns an ORM model (`::UserTable` or `Carto::UserTable`) as this is used to create the association between layer and user table models.
- `Carto::Layer` does this by calling `::Table.get_all_user_tables_by_names` which returns `Carto::UserTables`. It has a giant TODO on top of it, related to #3664
- `::Layer` calls `::Table.get_all_by_names` which returns `::Table` objects, which are not compatible for use in associations.

Wait, I just saw that `get_all_by_names` should be returning `::UserTable` models. Now I am very confused. Taking a look. Thanks!

File: app/models/carto/layer.rb (hunk 3 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: Ok, np. What about a comment to make this explicit? Inlining can be put off until `::UserTable` deletion (:psycho:).

File: app/models/common/map_common.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/common/map_common.rb]: Great!

File: app/models/layer.rb (hunk 2 above)
Comment (javitonino) [inline app/models/layer.rb]: Ok, so the problem was that I was returning a `Carto::UserTable` for `::Table.get_all_by_names ` as well, because a search and replace went too far.

Fixed without model casting.

File: app/models/common/map_common.rb (hunk 1 above)
Comment (javitonino) [inline app/models/common/map_common.rb]: Duplicated the helper (outside the  view helpers directory) to work with AR db connection. We should be able to remove the old one after refactoring Map.

File: app/models/table.rb [hunk 4]
```diff
@@ -210,7 +210,7 @@ def self.get_all_by_names(names, viewer_user)
           user_id = owner.id
         end
       end
-      UserTable.where(user_id: user_id, name: table_name).first
+      ::UserTable.where(user_id: user_id, name: table_name).first
```
Comment (juanignaciosl) [inline app/models/table.rb]: Don't we want to switch `::Table` from `::UserTable` to `Carto::UserTable`?

Comment (javitonino) [inline app/models/table.rb]: Related to https://github.com/CartoDB/cartodb/pull/11737#discussion_r105639894

This function is only used for calculating layer dependencies from the Sequel layer models. I think it's okay to keep for now.

**Comment by juanignaciosl** [comment]
To acceptance, then.

**Comment by juanignaciosl** [comment]
@javitonino 7416b5d6561d3b236eff3519ff595ec9faa4811d is a quick fix for this issue: if you click "New map" from the dashboard, using a Data Library dataset, it fails because `TableRegistrar` needs that method. I first inlined it, but it's also declared in `::UserTable::INTERFACE`, so it's leaked to other places (and harder to trace).

Nevertheless, my main concern is that I tried to cover that usage in `table_registrar_spec` and then I realized that it's using `TableMockHelper`, which mocks a `::Table` using `::UserTable`. I think that we should completely remove that mock. Have you already struggled with this?

**Comment by juanignaciosl** [comment]
af1ee82b53ca578886d94d9dd1a47e234387c3cf removes the mock and introduces a test covering the found issue.

**Comment by juanignaciosl** [comment]
I'm getting this error when a new visualization is created: [Missing or empty layers array from layergroup config](https://rollbar.com/vizzuality/CartoDB/items/18849).

**Comment by javitonino** [comment]
About the comments.
- I've run into the ::Table and ::UserTable mocking situation before. And yes, I basically ended unmocking it. I first tried to add the needed stuff to the mock, but that only compounded the problem, and there is no good reason for this to be a mock anyway. I see you followed the same approach, 👍 
- "Missing or empty layers array from layergroup config" is most likely due to the thing I did for saving the layers after saving the map (in the last PR). So I think it might be saving the named map for a first time before adding the layers. Obvious solution is to add an `unless layers.empty?` to the hook, but maybe there is a better way.

**Comment by juanignaciosl** [comment]
Added _do not merge yet_ because of "Before merging" comments at the description.

**Comment by juanignaciosl** [comment]
Fix for [this](https://rollbar.com/vizzuality/CartoDB/items/22027/) in progress:

```ruby
NoMethodError: undefined method `save!' for #<UserTable:0x000000055516f8>
1
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/app/models/table.rb", line 94 in save
2
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 226 in create_user_table
3
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 76 in each
4
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 76 in sync
5
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 59 in block in sync_user_tables_with_db
6
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/bolt.rb", line 20 in run_locked
7
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 59 in sync_user_tables_with_db
8
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/carto/ghost_tables_manager.rb", line 30 in link_ghost_tables_synchronously
9
File "/home/ubuntu/www/production.cartodb.com/releases/20170321120157/lib/resque/user_db_jobs.rb", line 14 in perform
```

**Comment by juanignaciosl** [comment]
@javitonino 🍏  on latest changes; take a look. I'll resume acceptance.

File: app/models/table.rb [hunk 5]
```diff
@@ -91,7 +91,7 @@ def layers
   end
 
   def save
-    @user_table.save!
+    @user_table.save
```
Comment (javitonino) [inline app/models/table.rb]: I introduced this change because Sequel raises on error and AR only does that with `save!` (not with `save`). I'd keep it if possible to maintain compatibility with callers.

Comment (juanignaciosl) [inline app/models/table.rb]: Changing this back. I think that I was misled by an error, keeping `save!` is certainly better 👍

**Comment by javitonino** [comment]
CR :+1: and tests 🍏

**Comment by juanignaciosl** [comment]
@javitonino I've passed every acceptance test that felt relevant to me. Maybe you could drop the debug traces and do a final, minor test: check the sheet, and do any other test, there or not, that you consider important. If you can't find anything wrong, let's deploy this on Monday.

**Comment by javitonino** [comment]
We detected that deleting a dataset is still using the old models and codepaths. Changing that should probably be the focus of the following PRs. I removed all Rollbar traces except for the ones related to this.

Otherwise, still doing some last acceptance checks.

**Comment by javitonino** [comment]
Did some more of the privacy tests (mixed privacy maps) and some deletion checks. Everything 👍
