### PR TITLE
Copy visualizations using export/import

### LINKED ISSUE #7657: duplicate map of a map with analyses fails
**str**

- import a map with analyses (classic paradas de metro)
- open map
- duplicate map
- open duplicate map in builder

**expected behaviour**

- panels and map load

**actual behaviour**

- panels and map fail, find attached the developer tools trace

```
editor3.js:21147 Uncaught Error: layerAnalysisDefinitionNodeModel is required
common_editor3.js:62620 Uncaught TypeError: Cannot read property 'toJSON' of undefined
```

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #7657

Now more :bomb:-proof than ever.

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @gfiorav

File: app/controllers/api/json/visualizations_controller.rb [hunk 1]
```diff
@@ -40,53 +40,30 @@ def create
...
-                additional_fields = {
-                  type:       params.fetch(:type, Visualization::Member::TYPE_DERIVED),
-                  parent_id:  params.fetch(:parent_id, nil)
-                }
-
-                @stats_aggregator.timing('copy') do
-                  Visualization::Copier.new(current_user, source, name_candidate)
-                                       .copy(copy_overlays, copy_layers, additional_fields)
+        source_id = params[:source_visualization_id]
+        vis = if source_id
```
Comment (gfiorav) [inline app/controllers/api/json/visualizations_controller.rb]: This seems really prone to corner cases but I guess it's the easiest path. Let's make a mental note to create a duplicate api or something like that.

**Comment by gfiorav** [comment]
If you tested it and it works, 📦 it!
