### PR TITLE
SAML service should return emails in DB format

### LINKED ISSUE #12365: SAML authentication fails if claim contains an uppercase email
### Steps to Reproduce
1. Set up a SAML server (this has been reproduced with ADFS, others should work too)
2. Create a user with an uppercase email on the SAML IdP. e.g: Juan.Perez@example.com
3. Try to log in

### Current Result
You get redirected from login -> saml -> finalize -> dashboard -> login

The `login_required` filter fails to correctly identify the user as logged in. The warden session contains `{"juan-perez" => nil}`, which seems wrong.

### Expected result
You log in

### PR DESCRIPTION
**Pull request by javitonino**
The reason that this is required is that the email in the authentication methods is used to [query the database](https://github.com/CartoDB/cartodb/blob/master/app/controllers/sessions_controller.rb#L209) for the corresponding username, in order to set the correct warden scope. The returned email should match [validation rules](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L231)

Without this, the scope was being set to :default on login when the SAML IdP server sent an uppercase email, causing login to fail to set the correct cookies (and redirect from login to dashboard to login)

Fixes #12365

### CODE REVIEW

File: config/initializers/warden.rb [hunk 1]
```diff
@@ -262,7 +262,7 @@ def authenticate!
     saml_service = Carto::SamlService.new(organization)
 
     email = saml_service.get_user_email(params[:SAMLResponse])
-    user = organization.users.where(email: email.strip.downcase).first
+    user = organization.users.where(email: email).first
```
Comment (juanignaciosl) [inline config/initializers/warden.rb]: As downcasing is a "feature" of our authentication assumptions, I'd keep it. In fact, I'd stop the madness of the downcasing duplication everywhere and I'd do a `prepare_for_authentication` method or something similar used for downcase usernames and/or emails.

File: lib/carto/saml_service.rb [hunk 2]
```diff
@@ -18,7 +18,7 @@ def authentication_request
 
     def get_user_email(saml_response_param)
       response = get_saml_response(saml_response_param)
-      response.is_valid? && email_from_saml_response(response)
+      response.is_valid? && email_from_saml_response(response).try(:strip).try(:downcase)
```
Comment (juanignaciosl) [inline lib/carto/saml_service.rb]: Reverse comment: `SamlService` should return the email as is, there's no reason for it to know that we need it for authentication.

File: lib/carto/saml_service.rb [hunk 3]
```diff
@@ -86,7 +87,8 @@ def debug_response(message, response)
         message: message,
         response_settings: response.settings.to_json,
         response_options: response.options,
-        response_errors: response.errors
+        response_errors: response.errors,
+        response_body: response.response
```
Comment (juanignaciosl) [inline lib/carto/saml_service.rb]: ❤️

File: lib/carto/saml_service.rb [hunk 4]
```diff
@@ -76,6 +76,7 @@ def saml_metadata
     private
 
     def email_from_saml_response(saml_response)
+      CartoDB::Logger.info(message: 'SAML attributes', attributes: saml_response.attributes.to_h)
```
Comment (juanignaciosl) [inline lib/carto/saml_service.rb]: Minor: `debug` level?

Comment (javitonino) [inline lib/carto/saml_service.rb]: I was not aware I committed this. We did this for testing, but it's quite noisy (although useful). 🤔 I think the best solution is to move it to the "else" branch of `email.present?`, so we only log this when we are not getting the attributes we expect (which is when you need this log).

File: config/initializers/warden.rb (hunk 1 above)
Comment (javitonino) [inline config/initializers/warden.rb]: Uhm, I am taking a look at how LDAP does this, and it does not seem to do it at all. I just assumed other login providers would do the downcasing, but it seems it's not the case.

I'll take a look at moving the code back to the authentication methods themselves, which also implies changes to the sessions controller, and I think another palce in warden configuration. But this way, it should work for all authentication provides ✨

Comment (juanignaciosl) [inline config/initializers/warden.rb]: Maybe LDAP will need it as well in the future. I think that in the past we solved it by fixing the email in the DB, but I can't remember.

It would be ideal if we could keep the downcasing within `warden.rb`, but we probably have some direct DB searches.

**Comment by javitonino** [comment]
🍏 Back to CR with a different approach

File: lib/carto/email_cleaner.rb [hunk 5]
```diff
@@ -0,0 +1,5 @@
+module Carto::EmailCleaner
+  def clean_email(email)
+    email.strip.downcase
```
Comment (juanignaciosl) [inline lib/carto/email_cleaner.rb]: Minor: previous code had `.to_s`, making `strip` nil-safe. I'm ok with removing it, because it might not make sense at all in the past and, worst-case scenario, it should fail, but I wanted to mention it to have it in mind.

Comment (javitonino) [inline lib/carto/email_cleaner.rb]: Good catch! I actually had it completely removed and it failed the tests. I [added it back to the model](https://github.com/CartoDB/cartodb/pull/12367/commits/d42d6d3d07f20f3d386a872c35751a20fd83d2b2) as this was there before and lot of tests rely on that.

For the rest of calls, they should never be nil, so I prefer to get a proper error there.
