### PR TITLE
toString JS error when a link without href is clicked within header breadcrumb dropdown

### LINKED ISSUE #4593: Dashboard dataset list gets blocked in Data Library
There are not specific steps to reproduce this issue, but it seems that under certain circumstances (probably cache issues) although the user has datasets in his/her account, the dashboard is always going to "Data Library" and there's no way to change the tab. This is not something attached to an specific account, as testing the same scenario in an incognito window doesn't raise the issue.

When clicking on the "Datasets" tab, the following error is appearing:

`Uncaught Typerror: Cannot read property 'toString' of undefined router.js:152`

### PR DESCRIPTION
**Pull request by xavijam**
Checking [this error](https://my.trackjs.com/details/58cb06f9332b4d4bbc2af4e1ffc78bad) I've seen that if a link in the "breadcrumb" element doesn't have a href attribute, dashboard router fails and can't redirect to any location.
If you check the stack trace you will check that it comes from there.

cc @iriberri 

REVIEWER: @viddo 

Fixes #4593

### CODE REVIEW

**Comment by iriberri** [comment]
:)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5200/))

File: lib/assets/javascripts/cartodb/common/view_helpers/navigate_through_router.js [hunk 1]
```diff
@@ -62,6 +62,10 @@ module.exports = function(ev) {
   this.killEvent(ev);
   var url = $(ev.target).attr('href');
 
+  if (!url) {
+    return false;
+  }
+
```
Comment (viddo) [inline lib/assets/javascripts/cartodb/common/view_helpers/navigate_through_router.js]: I'm not convinced that this is the right solution to the issue. If this mixin is used for a click event the target _must have_ a href, if it doesn't then what's the point of having the event go though it? 

Assuming there actually is a a `href` attr set, I've seen that in some cases links have nested DOM elements (e.g. `<a href="…" class="Button"><span>EX</span></a>`), so the `ev.target` is not actually a `<a>` but a `<span>` in the callback (depending on browser). In those cases this fix would actually fail the user.

So, instead of just returning false, why not do a `$(ev.target).closest('a').attr('href')` to get correct target and attribute value? Only if that fails I think it makes sense to abort.

Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/view_helpers/navigate_through_router.js]: Sounds good!

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5204/))
