### PR TITLE
Fix problems with raster overview factors

### LINKED ISSUE #7082: Numeric calculation issues when importing a small raster
See RB/17210:
```
FloatDomainError: -Infinity

services/importer/lib/importer/raster2pgsql.rb, line 154 in ceil
services/importer/lib/importer/raster2pgsql.rb, line 154 in calculate_raster_overviews
services/importer/lib/importer/raster2pgsql.rb, line 37 in run
services/importer/lib/importer/tiff_loader.rb, line 23 in run
services/importer/lib/importer/runner.rb, line 236 in file_based_loader_run
services/importer/lib/importer/runner.rb, line 182 in import
services/importer/lib/importer/runner.rb, line 344 in execute_import
services/importer/lib/importer/runner.rb, line 273 in block (3 levels) in single_resource_import
services/importer/lib/importer/runner.rb, line 267 in each
services/importer/lib/importer/runner.rb, line 267 in each_with_index
services/importer/lib/importer/runner.rb, line 267 in block (2 levels) in single_resource_import
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 262 in block in single_resource_import
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 240 in single_resource_import
services/importer/lib/importer/runner.rb, line 97 in run_import
services/importer/lib/importer/runner.rb, line 90 in block in run
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 89 in run
app/connectors/importer.rb, line 43 in run
app/models/data_import.rb, line 663 in new_importer
app/models/data_import.rb, line 389 in dispatch
app/models/data_import.rb, line 176 in run_import!
lib/resque/importer_jobs.rb, line 9 in block in perform
lib/resque/base_job.rb, line 21 in call
lib/resque/base_job.rb, line 21 in run_action
lib/resque/importer_jobs.rb, line 9 in perform
```

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #7082

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rafatower please review this

File: services/importer/lib/importer/raster2pgsql.rb [hunk 1]
```diff
@@ -187,12 +188,16 @@ def calculate_raster_scale(pixel_size)
       def calculate_raster_overviews(raster_size)
         bigger_size = raster_size.max
 
-        max_power = (Math::log(bigger_size / 256, 2)).ceil.to_i
+        max_power =
+          if bigger_size > MAX_REDUCTED_SIZE
+            Math::log(bigger_size.to_f / MAX_REDUCTED_SIZE, 2).ceil
+          else
+            0
```
Comment (rafatower) [inline services/importer/lib/importer/raster2pgsql.rb]: I'd rather set it to `-1` so that no overview is generated, with a comment. I haven't tested it though. What do you think?

Comment (jgoizueta) [inline services/importer/lib/importer/raster2pgsql.rb]: With 0 the range will be `(1..1)`, so there will be a single overview with no size reduction. I had in mind that we  must always generate at least an overview (because original raster table may not have webmercator projection) but maybe I was wrong.

You probably know better about this... can be avoid all overviews?

Comment (rafatower) [inline services/importer/lib/importer/raster2pgsql.rb]: not exact:

```ruby
irb(main):001:0> max_power = -1
=> -1
irb(main):002:0> range = (1..max_power + 1)
=> 1..0
irb(main):003:0> overviews = range.map { |x| 2**x }.select { |x| x <= 1000 }
=> []
irb(main):004:0> additional_tables = overviews
=> []
irb(main):005:0> overviews.join(',')
=> ""
```

but chances are it will break later on.

Comment (rafatower) [inline services/importer/lib/importer/raster2pgsql.rb]: I mean, what you said is 100% correct, sorry I was too fast :joy: 

A different thing is whether it will crash later on or not. The renderer should work fine and in this very case it makes little sense to generate overviews at all.

If it requires many more changes, then we're better off with the proposed patch.

**Comment by rafatower** [comment]
:+1: go for it, thanks for the fix
