### PR TITLE
Fix this._tooltipTitle is not a function

### LINKED ISSUE #12279: this._tooltipTitle is not a function
Since merging https://github.com/CartoDB/cartodb/commit/0bdf4a6f7b20d347d96aee93d229205092172f44 we are getting every now and then the error `this._tooltipTitle is not a function` related to `editor-pane.js' line 206.

More info on 
https://my.trackjs.com/messages/filtered?hash=8bf772edd23f337d&sort=serverTimestamp%7casc

I think it just prevent the tooltip from appearing so no critical. But it's happened a thousand times since it was deployed one week ago so it'd be nice to fix it.

### PR DESCRIPTION
**Pull request by rjimenezda**
Fix #12279 

Minor oversight when it was developed, did not take widgets into account 🙇 

I fixed tooltip showing on widget tab & guarded in case it's not set.

### CODE REVIEW

File: lib/assets/core/javascripts/cartodb3/editor/editor-pane.js [hunk 1]
```diff
@@ -338,6 +342,7 @@ module.exports = CoreView.extend({
 
     switch (this._mapTabPaneView.getSelectedTabPaneName()) {
       case 'widgets':
+        this._tooltipTitle = String;
```
Comment (rubenmoya) [inline lib/assets/core/javascripts/cartodb3/editor/editor-pane.js]: What about setting `_tooltipTitle` to empty string instead of `String` in both cases, and then here `this._tooltipTitle = this._getMaxLayerTitle;` call the function instead of passing it? This way we only use strings and we don't need the `if`.

Comment (rjimenezda) [inline lib/assets/core/javascripts/cartodb3/editor/editor-pane.js]: At some point we needed it to be a function call because we were reading the number of layers for the _t call.

Now we don't, so we could refactor to just use strings.

Comment (rubenmoya) [inline lib/assets/core/javascripts/cartodb3/editor/editor-pane.js]: Oh, I remember now!

**Comment by rubenmoya** [comment]
Moving to deploy!

**Comment by rubenmoya** [comment]
In production 🚀
