### PR TITLE
Private shared map email link is wrong

### LINKED ISSUE #6066: Private shared map email link is wrong
When you share a private map with anybody within your organization the link doesn't work, it displays the "Looks like this map no longer exists or is set as private" error page.

Not working email link: https://OWNER.cartodb.com/viz/ID/public_map

Working link (from dashboard):
https://ORG.cartodb.com/u/USER/viz/OWNER.ID/public_map?redirected=true

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #6066

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

File: app/mailers/user_mailer.rb [hunk 1]
```diff
@@ -26,18 +26,26 @@ def share_table(table, user)
...
-  
+
   def share_visualization(visualization, user)
     @visualization = visualization
     @user = user
     organization = @visualization.user.organization
-    @link = "#{CartoDB.base_url(organization.name, @visualization.user.username)}#{CartoDB.path(self, 'public_visualizations_show_map', {id: @visualization.id})}"
+    if @visualization.privacy == CartoDB::Visualization::Member::PRIVACY_PRIVATE
+      base_url = CartoDB.base_url(organization.name, user.username)
+      vis_id = "#{@visualization.user.username}.#{@visualization.id}"
```
Comment (juanignaciosl) [inline app/mailers/user_mailer.rb]: Maybe we could extract this logic so this "username.id" requirement is not hidden in the mailer. I've also found it at [visualizations controller](https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L201).

Comment (juanignaciosl) [inline app/mailers/user_mailer.rb]: PS: I'm not sure about the best place for url generation logic, there's some at [VisualizationPresenter](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualization_presenter.rb#L96).

Comment (Kartones) [inline app/mailers/user_mailer.rb]: About the Presenter, is it compatible with old Visualization models? If so perfect to use it.

And yes, I wasn't too sure about this either, but as in the mailer there are no controllers... I'll try plugging the vis to the VisualizationPresenter and if works, we're done :)

Comment (juanignaciosl) [inline app/mailers/user_mailer.rb]: I think the only not compatible method call is `.canonical?`, you could add it to the old one (to avoid ugly constant checks everywhere).

Presenters were not meant to be used by old models, but I think we need a central file with URL generation logic. If you come up with a better location please use it :)

Comment (Kartones) [inline app/mailers/user_mailer.rb]: I know they are not meant to be reused, but also we should have got rid of the old models and they still live there... I'm checking and if I only use the url generation call it can work with old models adding jus that method to the old one, indeed.

For me in the new schema this belongs to the VisualizationPresenter, in the old in the Presenter, so maybe I'll just duplicate the code there so both Presenters are equivalent.

Comment (juanignaciosl) [inline app/mailers/user_mailer.rb]: Ok. If they are compatible we can begin not duplicating among both, IMHO.

**Comment by Kartones** [comment]
@juanignaciosl Can you re-check?

- Admin Vis. controller doesn't makes use of the VisualizationPresenter and is not relying on a Visualization object either, so I made a static method to cope with that.
- The other uses ae more straightforward, but the private `url` method uses `canonical` instead of `privacy` so I just reused the "qualified visualization id"

File: app/controllers/admin/visualizations_controller.rb [hunk 2]
```diff
@@ -196,13 +196,14 @@ def public_map
...
-                                'public_visualizations_public_map',
-                                {
-                                  id: "#{@visualization.user.username}.#{params[:id]}",
-                                  redirected:true
-                                },
-                                @visualization.user
-                              ) and return
+                              'public_visualizations_public_map',
+                              {
+                                id: Carto::Api::VisualizationsPresenter.qualified_visualization_id(
```
Comment (juanignaciosl) [inline app/controllers/admin/visualizations_controller.rb]: _(comment moved from the commit)_

Why not Carto::Api::VisualizationsPresenter.new(@visualization, current_viewer, self), both to avoid class method and using params[:id] (which can be extracted from @visualization.id)? This controller didn't use it, but it can create a new instance here.

**Comment by Kartones** [comment]
@juanignaciosl Sorry, now it is ready

File: app/controllers/admin/visualizations_controller.rb [hunk 3]
```diff
@@ -195,14 +195,16 @@ def public_map
     end
     # Legacy redirect, now all public pages also with org. name
     if eligible_for_redirect?(@visualization.user)
+      visualization_presenter = Carto::Api::VisualizationsPresenter.new(@visualization, @visualization.user, self)
```
Comment (juanignaciosl) [inline app/controllers/admin/visualizations_controller.rb]: Just to be sure: `@visualization.user` is not `current_viewer` because it might be `nil` (public map) and it's safe because `eligible_for_redirect?` check, isn't it?

File: app/controllers/carto/api/visualization_presenter.rb [hunk 4]
```diff
@@ -71,15 +71,38 @@ def to_public_poro
...
 
+      # Ideally this should go at a lower level, as relates to url generation, but at least centralize logic here
+      # INFO: For now, no support for non-org users, as intended use is for sharing urls
+      def privacy_aware_map_url
+        organization = @visualization.user.organization
+
+        return unless organization
+
+        if @visualization.is_privacy_private?
+          base_url_username = @current_viewer.username
```
Comment (juanignaciosl) [inline app/controllers/carto/api/visualization_presenter.rb]: This gets `@current_viewer.username` because Presenter assumes that the visualization has been shared with `current_viewer`, isn't it?

**Comment by juanignaciosl** [comment]
:+1: URL logic generation is hard to understand :-\

File: app/controllers/admin/visualizations_controller.rb (hunk 3 above)
Comment (Kartones) [inline app/controllers/admin/visualizations_controller.rb]: yep, but that is in part a "side effect".

Here we're just using the url generation part, so instead of having a separate vis owner/user and "viewer", it will generate the same url just "namespacing" the ID. Check [the existing code](https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L201). But maybe is worth a note here explaining the "trick", will add it.

Comment (juanignaciosl) [inline app/controllers/admin/visualizations_controller.rb]: Ok, thanks! URL generation is tricky, comments are gold.
