### PR TITLE
Revert "Revert "11722 user table refactor 5""

### LINKED ISSUE #11889: Fix syncs at UserTable refactor
Fix for the regression caused by CartoDB/cartodb/pull/11884 

- [x] Test for syncs (there isn't any).
- [x] Fix syncs.

### PR DESCRIPTION
**Pull request by javitonino**
This reverts commit 27eb4389a1707000f456fdbcf1b6bd6c961d72ca.

Closes #11889.

**Acceptance** (keeping an eye on Rollbar)
- [x] Check that nothing from the refactor PR broke. Quick test: import from URL, file and data library. Deleting a dataset with dependencies.
- [x] Syncs, smoke tests
- [x] Sync, sync a dataset, truncate it, force a resync. Make sure it syncs correctly (data is filled again).
- [x] Ghost tables:
  - [x] `create table`, create map, `rename table`, map is updated and working, `drop table`, map dissapears.
  - [x] `create table`, create map, `drop table`, `create table`, map keeps working and ghost table link the new physical table.

### CODE REVIEW

File: spec/factories/assets.rb [hunk 1]
```diff
@@ -1,6 +1,8 @@
 FactoryGirl.define do
   factory :asset do
-    asset_file { (Rails.root + 'db/fake_data/simple.json').to_s }
+    to_create(&:save)
+
+    public_url 'https://manolo.es/es/co/bar.png'
```
Comment (javitonino) [inline spec/factories/assets.rb]: What's the reason for changing this factory (removing `asset_file`, adding `public_url`)?

File: spec/models/synchronization/member_spec.rb [hunk 2]
```diff
@@ -51,34 +52,66 @@
...
+        @user1.sync_tables_enabled = false
+        @user2.sync_tables_enabled = false
+
+        member.authorize?(@user1).should eq true
+      end
+    end
+
+    describe "synchronization" do
+      it 'syncs' do
+        # TODO: this is the minimum test valid to reproduce #11889, it's not a complete sync test
```
Comment (javitonino) [inline spec/models/synchronization/member_spec.rb]: Should we create a ticket for a more complete coverage of syncs?

File: spec/models/user_spec.rb [hunk 3]
```diff
@@ -2327,7 +2327,7 @@ def create_org(org_name, org_quota, org_seats)
     organization.name = unique_name(org_name)
     organization.quota_in_bytes = org_quota
     organization.seats = org_seats
-    organization.save!
+    organization.save
```
Comment (javitonino) [inline spec/models/user_spec.rb]: 🤦‍

File: spec/requests/carto/api/geocodings_controller_spec.rb [hunk 4]
```diff
@@ -249,14 +249,14 @@ def remove_dates(geocoding_hash)
 
     it 'returns started geocodings but not finished' do
       geocoding1 = FactoryGirl.create(:geocoding, user: @user1, kind: 'high-resolution', created_at: Time.now,
-                                      processed_rows: 1, state: 'started')
+                                      processed_rows: 1, state: 'started', formatter: 'foo')
```
Comment (javitonino) [inline spec/requests/carto/api/geocodings_controller_spec.rb]: I think the `formatter` parameter is not needed anymore (after adding it to the geocodings factory). But not worth another commit just for this.

File: spec/support/factory_girl.rb [hunk 5]
```diff
@@ -1,6 +1 @@
 # This makes factory_girl compatible with Sequel
-class Sequel::Model
-  def save!
-    save(:validate=>false)
-  end
-end
```
Comment (javitonino) [inline spec/support/factory_girl.rb]: As the guy who usually fixes the randomly-failing tests, it's great to see this go. Thanks for taking the time to do it ❤️

File: spec/factories/assets.rb (hunk 1 above)
Comment (juanignaciosl) [inline spec/factories/assets.rb]: I didn't find `asset_file` to be needed. In fact, it's likely to be incorrect (json is not a valid asset type).

`public_url` is needed because validation checks the type. I think that validation before silently failed.

File: spec/models/synchronization/member_spec.rb (hunk 2 above)
Comment (juanignaciosl) [inline spec/models/synchronization/member_spec.rb]: Meh. I don't think so. This test is minimum, but tests the basics. Creating a full test suite would require reverse engineering the full class. I see more value on pushing the refactor. We can defer more testing to `Carto::Synchronization` improvements.

File: spec/models/user_spec.rb (hunk 3 above)
Comment (juanignaciosl) [inline spec/models/user_spec.rb]: I'm not sure what you mean with that 😅

File: spec/support/factory_girl.rb (hunk 5 above)
Comment (juanignaciosl) [inline spec/support/factory_girl.rb]: _I don't know why I can't answer your comment about `formatter`, so I'll do it here_: it might not be needed for geocoding, but validation fails without it. Removing it is certainly out of scope.

I can't remember seeing this code in months, I didn't remember it :dori: . This is the kind of shortcuts that bites you hard and silently (like today!).

File: spec/models/user_spec.rb (hunk 3 above)
Comment (javitonino) [inline spec/models/user_spec.rb]: Just that the factory was incorrect before, but the monkey patch hide it. It's better now 👍

**Comment by javitonino** [comment]
Looking good. Only thing is, we are triggering this Rollbar trace on sync. I think it's innocuous, but please take a look:

https://rollbar.com/vizzuality/CartoDB/items/22184/

**Comment by juanignaciosl** [comment]
@javitonino it's documented (even the trace matches) --> https://github.com/CartoDB/cartodb/pull/11886/files#diff-58ad7505224c2c16ac009d75fae1e3b3R182 . I'm pretty sure that we're safe. I don't know if it will be too spammy, though. It was added [here](https://github.com/CartoDB/cartodb/commit/1970db407e1b38d4f4de18aa3511d43c5c9aca53), as a trace safety. Looks ok.
