### PR TITLE
Fix Oauth redirection for subdomainless

### LINKED ISSUE #14498: OAuth should redirect to org login if using org endpoint
If visiting `carto.lan/user/orgname/oauth2/authorize` and you are not logged in, yo are redirected to the global login `carto.lan/login` but you should be redirected to `carto.lan/user/orgname/login`. This currently works OK in domainful mode. We should fix it so it works with both.

The problem is here:
https://github.com/CartoDB/cartodb/blob/master/app/controllers/application_controller.rb#L313

Using `CartoDB.path` works for subdomainful
Using `CartoDB.url` works for subdomainless

We need a way that works for both, maybe with some helper method that builds the URL differently depending on the mode. We have some similar ugly code in https://github.com/CartoDB/cartodb/blob/master/app/controllers/signup_controller.rb#L159-L170 but we can probably do better than that.

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes #14498 

I've also changed `CartoDB.url` to use keyword arguments, so I had to update it in many places (sorry for the big PR).

### CODE REVIEW

File: config/initializers/carto_db.rb [hunk 1]
```diff
@@ -27,11 +27,16 @@ module CartoDB
   # Helper method to encapsulate Rails full URL generation compatible with our subdomainless mode
   # @param context ActionController::Base or a View or something that holds a request
   # @param path String Rails route name
-  # @param params Hash Parameters to send to the url (Optional)
+  # @param params Hash (Optional) Parameters to send to the url
   # @param user ::User (Optional) If not sent will use subdomain or /user/xxx from controller request
-  def self.url(context, path, params = {}, user = nil)
+  # @param keep_base_url Boolean (Optional) Keeps the base url from the request in case of subdomainful
+  def self.url(context, path, params: {}, user: nil, keep_base_url: false)
```
Comment (juanignaciosl) [inline config/initializers/carto_db.rb]: I've searched through the code to be sure that there's no use of this function without the named parameters but I found nothing (rb, erb and rake files), it looks like you did a great job with this refactor :clap:

**Comment by alrocar** [comment]
Acceptance 🍏
