### PR TITLE
data-library: fix viewed_user check

### LINKED ISSUE #6469: NoMethodError: undefined method `username' for nil:NilClass
@matallo assigning to you because I think it's related to your latest changes, feel free to assign it to me if you can't.

https://rollbar.com/vizzuality/CartoDB/items/13747/

```
NoMethodError: undefined method `username' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20160120175207/app/controllers/admin/visualizations_controller.rb", line 690 in data_library_user?
2
File "/home/ubuntu/www/production.cartodb.com/releases/20160120175207/app/controllers/admin/visualizations_controller.rb", line 149 in public_table
... 6 non-project frames
9
File "/home/ubuntu/www/production.cartodb.com/releases/20160120175207/app/controllers/application_controller.rb", line 95 in wrap_in_profiler
... 69 non-project frames

```

### PR DESCRIPTION
**Pull request by matallo**
close #6469

finally I could take a look at this, it a weird case because at the moment of the compare, I'm checking the username in the config (if it exists) against @viewed_user, which occurs in the `get_viewed_user` before_filter.

Also, if that helps for debugging, the request is done by googlebot crawler

In any case, I added `@viewed_user &&` check

CR @juanignaciosl

### CODE REVIEW

File: app/controllers/admin/visualizations_controller.rb [hunk 1]
```diff
@@ -671,7 +671,7 @@ def get_viewed_user
   end
 
   def data_library_user?
-    Cartodb.get_config(:data_library, 'username') && (Cartodb.config[:data_library]['username'] == @viewed_user.username)
+    @viewed_user && Cartodb.get_config(:data_library, 'username') && (@viewed_user.username == Cartodb.config[:data_library]['username'])
```
Comment (juanignaciosl) [inline app/controllers/admin/visualizations_controller.rb]: `Cartodb.get_config(:data_library, 'username')` returns `nil` if configuration is not present, and nil comparisons are safe, so the line can be simplified to:

```ruby
@viewed_user && Cartodb.get_config(:data_library, 'username') == @viewed_user.username
```

**Comment by juanignaciosl** [comment]
I suggested a simplification of the comparison, but :+1: anyway
