### PR TITLE
11123 org login restrictions

### LINKED ISSUE #11123: Organization login not for not org users
### Steps to Reproduce

1. Go to an organization login page.
2. Login with a user outside the organization.
3. You'll be logged in.

### Expected result

It should fail.

### Additional info

It's not a concern: you login as usual, without any relation to the org. Anyway, it might look strange.

### PR DESCRIPTION
**Pull request by javitonino**
**We need to double check that Google signup into an organization from the login page still works.**

Closes #11123 

screenshot_20170103_163046

Acceptance:
 - Staging:
   - Test that login works from Central (carto.com/login), using an org user and a free user
   - Test that org login (org.carto.com/login) doesn't allow to log in as a non-member. Also that it works for org members.
   - Test that the user login from the box (user.carto.com/login) redirects to Central.
 - Onpremise (local without Central)
    - Test that org (org.carto.com/login) login accepts logging in as a non-org member (and as a member as well)
    - Test that user login (user.carto.com/login) works (no redirects)
 - Onpremise (local without Central) + subdomainless
    - Test that org (carto.com/user/:org/login) login accepts logging in as a non-org member (and as a member as well)
    - Test that user login (carto.com/user/:user/login) works (no redirects)
    - Test that plain login (carto.com/login) works (no redirects)

### CODE REVIEW

File: app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -32,23 +32,33 @@ class SessionsController < ApplicationController
...
+      return redirect_to(CartoDB.path(self, 'dashboard', trailing_slash: true))
     end
 
     # Automatically trigger SAML request on login view load -- could easily trigger this elsewhere
     if saml_authentication? && !user
-      redirect_to saml_service.authentication_request
+      return redirect_to(saml_service.authentication_request)
+    end
+
+    if central_enabled? && (!@organization || !@organization.auth_enabled?)
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: A bit of a brain twister there. How about

```ruby
if central_enabled? && !@organization.try(:auth_enabled?)
```

File: app/controllers/sessions_controller.rb [hunk 2]
```diff
@@ -32,23 +32,33 @@ class SessionsController < ApplicationController
...
+      return redirect_to(Cartodb::Central.new.login_url)
     end
   end
 
   def create
+    if central_enabled? && @organization && !@organization.users.exists?(username: extract_username(request, params))
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: Too extreme, but consider:
```ruby
if central_enabled? && !@organization.try(:users).try(:exists, username: extract_username(request, params))
```

File: app/views/sessions/new.html.erb [hunk 3]
```diff
@@ -89,6 +90,16 @@
                 <% if @github_config.present? %>
                   <%= render partial: 'github/github_button',  locals: { config: @github_config } %>
                 <% end %>
+
+                <% if @user_login_url %>
+                  <p class="CDB-Text CDB-Size-medium u-altTextColor u-tSpace--m u-justifyCenter Sessions-description">
+                    Not a member of the <%= @organization.name %> organization? Try the <a href="<%= @user_login_url %>"> general login</a> instead.
+                  </p>
+                <% elsif @organization && @organization.auth_username_password_enabled %>
```
Comment (gfiorav) [inline app/views/sessions/new.html.erb]: compacty, compacty

```ruby
elsif @organization.try(:auth_username_password_enabled)
```

File: lib/cartodb/central.rb [hunk 4]
```diff
@@ -28,6 +28,10 @@ def google_signup_url
       "#{host}/google/signup"
     end
 
+    def login_url
+      "#{host}/login"
```
Comment (gfiorav) [inline lib/cartodb/central.rb]: I feel it's safer to use:

```ruby
URI.join(host, 'login')
```

since it will handle extra `/` correctly.

**Comment by javitonino** [comment]
❤️ those suggestions, will apply, thanks! Maybe I'll skip the extreme try case, but maybe there is another way to rewrite it, I'll give it a 🤔

File: lib/cartodb/central.rb (hunk 4 above)
Comment (javitonino) [inline lib/cartodb/central.rb]: You are missing a `.to_s`, but otherwise it works nicely :)

File: app/controllers/sessions_controller.rb (hunk 2 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: Your suggestion doesn't work because it returns true when the org is nil (which it shouldn't). What you want to do can be achieved replacing `exists?` with `none?` but for some weird reason, `@organization.users` (dataset object) is not the same as `@organization.try(:users)` (array). Weird...

Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: Ah, sorry!

File: lib/cartodb/central.rb (hunk 4 above)
Comment (gfiorav) [inline lib/cartodb/central.rb]: Yup! Missed that!

**Comment by javierarce** [comment]
I'm doing the acceptance for this feature and the testing done in staging using the provided list is ok, but I've seen some issues with the implementation of the design:

screen shot 2017-01-05 at 12 34 41
screen shot 2017-01-05 at 12 38 10

As you can see, the Google button doesn't fill the whole space and the help text appears in the empty right area.

**Comment by javitonino** [comment]
Thanks, that's a good one. Let's go back to development to fix the styling, and next time it goes to acceptance we can skip the login tests and just focus on design.

**Comment by javitonino** [comment]
Fixed it for the one button case:

screenshot_20170105_134253

Asking for CR for the .erb's

File: app/controllers/sessions_controller.rb [hunk 5]
```diff
@@ -46,16 +46,18 @@ def new
   end
 
   def create
-    if central_enabled? && @organization && !@organization.users.exists?(username: extract_username(request, params))
+    strategy, username = ldap_user || saml_user || google_user || credentials_user
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: I see the convenience of returning two things since they're tightly nit together and it's not worth it to use a meta structure. 

I'd change the method names, though. If you wan't to be straightforward about it, I'd suggest: `xxx_strategy_and_username`.

File: app/controllers/sessions_controller.rb [hunk 6]
```diff
@@ -46,16 +46,18 @@ def new
...
+    return render(action: 'new') unless strategy.present?
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: I think it's best to never allow for an empty string `strategy` to happen. Only nil. In that case, you'd just `unless strategy`. No need for `.present?`!

File: app/controllers/sessions_controller.rb [hunk 7]
```diff
@@ -32,23 +32,35 @@ class SessionsController < ApplicationController
...
 
     # Automatically trigger SAML request on login view load -- could easily trigger this elsewhere
     if saml_authentication? && !user
-      redirect_to saml_service.authentication_request
+      return redirect_to(saml_service.authentication_request)
+    end
+
+    if central_enabled? && !@organization.try(:auth_enabled?)
+      return redirect_to(Cartodb::Central.new.login_url)
     end
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: suggestion:
```ruby
after_login_location = if logged_in?(CartoDB.extract_subdomain(request))
                         CartoDB.path(self, 'dashboard', trailing_slash: true)
                       elsif saml_authentication? && !user
                         saml_service.authentication_request
                       elsif central_enabled? && !@organization.try(:auth_enabled?)
                         Cartodb::Central.new.login_url
                       end

redirect_to(after_login_location)
```

Also, we  may need an `else` clause with a controlled error.

File: app/controllers/sessions_controller.rb [hunk 8]
```diff
@@ -32,23 +32,35 @@ class SessionsController < ApplicationController
...
   end
 
   def create
-    user = ldap_user || saml_user || credentials_or_google_user
+    strategy, username = ldap_user || saml_user || google_user || credentials_user
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: I see the convenience of returning two things since they're tightly nit together and it's not worth it to use a meta structure. 

I'd change the method names, though. If you wan't to be straightforward about it, I'd suggest: `xxx_strategy_and_username`.

File: app/controllers/sessions_controller.rb [hunk 9]
```diff
@@ -171,6 +183,10 @@ def initialize_github_config
 
   private
 
+  def central_enabled?
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: Do you think it would be useful to memmonize this?

File: app/controllers/sessions_controller.rb [hunk 10]
```diff
@@ -187,63 +203,54 @@ def username_from_user_by_email(email)
...
-      # Convenient because it's disabled on SAML
-      verify_authenticity_token
+    if saml_authentication?
+      email = saml_service.get_user_email(params[:SAMLResponse])
+      if email
+        username = username_from_user_by_email(email)
+        [:saml, username]
+      else
+        verify_authenticity_token
+        nil
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: best to return `[nil, nil]` I think. least likely to generate errors like `"no method '[]' for NilClass"`.

File: app/controllers/sessions_controller.rb [hunk 11]
```diff
@@ -187,63 +203,54 @@ def username_from_user_by_email(email)
...
       else
-        username = extract_username(request, params)
-        user = authenticate!(:password, scope: username)
+        # token valid, unknown user
+        @google_plus_config.unauthenticated_valid_access_token = params[:google_access_token]
+        nil
       end
+    end
+  end
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: same comment of `nil` vs `[nil, nil]` for this method.

File: spec/requests/sessions_controller_spec.rb [hunk 12]
```diff
@@ -235,22 +235,6 @@ def stub_saml_service(user)
       post create_session_url(user_domain: user_domain, SAMLResponse: 'xx')
     end
 
-    # If SAML returns authentication error we should fallback to login
-    it 'fallbacks to login if SAMLResponse is present and SAML is enabled but subdomain is nil' do
```
Comment (gfiorav) [inline spec/requests/sessions_controller_spec.rb]: Why did you drop it?

File: app/controllers/sessions_controller.rb [hunk 13]
```diff
@@ -32,23 +32,35 @@ class SessionsController < ApplicationController
...
+
+    if central_enabled? && !@organization.try(:auth_enabled?)
+      return redirect_to(Cartodb::Central.new.login_url)
     end
   end
 
   def create
-    user = ldap_user || saml_user || credentials_or_google_user
+    strategy, username = ldap_user || saml_user || google_user || credentials_user
+    return render(action: 'new') unless strategy.present?
```
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: If `strategy` can be `''`, let's avoid it. No need for `.present?` and you can do `unless strategy` directly.

File: app/controllers/sessions_controller.rb (hunk 7 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: Actually, `else` is not an error, but the default render :)

👍 I'll take a look at cleaning this up.

File: app/controllers/sessions_controller.rb (hunk 9 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: It's just a lookup into a dictionary, so I think it's fast enough already. Also, I do not think it can be used more than once per request (this is just a convenience function).

File: app/controllers/sessions_controller.rb (hunk 10 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: It's not a problem in the current use of this method, as `a,b,c = nil` assigns `nil` to all three variables.

File: spec/requests/sessions_controller_spec.rb (hunk 12 above)
Comment (javitonino) [inline spec/requests/sessions_controller_spec.rb]: It doesn't make much sense, `authenticate!` cannot return `nil` in normal usage, it raises instead. So the stub is incorrect. The old behaviour (and new as well) is that after raising an exception it displays the errored out form.

Also, I don't think it makes sense for a request to contain login information for both SAML and login via password, I don't think this is even possible (as the request comes from the SAML IdP).

All of this makes me think this is a bad test. We should take a deeper look in https://github.com/CartoDB/cartodb/issues/11156, which should address this.

File: app/controllers/sessions_controller.rb [hunk 14]
```diff
@@ -186,64 +201,55 @@ def username_from_user_by_email(email)
...
-    authenticate_with_ldap if ldap_authentication?
-  end
-
-  def saml_user
-    user = authenticate_with_saml if saml_authentication?
-    if !user && saml_authentication?
-      # Convenient because it's disabled on SAML
-      verify_authenticity_token
+  def ldap_strategy_username
+    if ldap_authentication?
```
Comment (juanignaciosl) [inline app/controllers/sessions_controller.rb]: ~~I _think_ that this might break current expectations for LDAP authentication (more info in progress). At least, I'll check that it's coherent with previous behaviour, which might be different than the documented one.~~

After talking to @danicarrion , we agreed that LDAP should fallback to "normal" (local) user + password, which is interesting not only as a fallback if LDAP server is not available but also for administrator users and so on.

File: app/controllers/sessions_controller.rb [hunk 15]
```diff
@@ -32,23 +32,34 @@ class SessionsController < ApplicationController
...
+    strategy, username = ldap_strategy_username || saml_strategy_username ||
+                         google_strategy_username || credentials_strategy_username
+    return render(action: 'new') unless strategy
 
-    return render(action: 'new') unless user.present?
+    candidate_user = Carto::User.where(username: username).first
 
+    if central_enabled? && @organization && candidate_user && !candidate_user.belongs_to_organization?(@organization)
+      @login_error = 'The user is not part of the organization'
+      @user_login_url = "#{Cartodb::Central.new.host}/login"
```
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: Yup, didn't catch this one after extracting the method. Changing 👍

File: app/controllers/sessions_controller.rb (hunk 14 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: I think this currently fails. I'll add a test and take a look at implementing fallback. I will try to use warden's built-in fallback if possible.

Comment (juanignaciosl) [inline app/controllers/sessions_controller.rb]: Could you try with a previous version? If that's true and it currently fails this might be reconsidered.

Comment (javitonino) [inline app/controllers/sessions_controller.rb]: I wrote a test (just pushed so you can see it). It fails in this PR, but passes in master. So yes, this used to work but was broken in this PR.

**Comment by javitonino** [comment]
Merging master into this, now that the GME test has been fixed.

File: app/controllers/sessions_controller.rb (hunk 11 above)
Comment (juanignaciosl) [inline app/controllers/sessions_controller.rb]: I agree with gfiorav. These methods return a "strategy, username" tuple, and `[nil, nil]` is more accurate. Although it's not the main reason, there's a practical one: `strategy_and_username = the_method` is a legit assignment, but `strategy_and_username[0]` would fail if `nil` is returned.

Anyway, as they're private methods, this is minor. Up to you.

File: spec/requests/sessions_controller_spec.rb [hunk 16]
```diff
@@ -358,6 +392,74 @@ def create_admin_user(organization)
...
+        create
+      end
+
+      after(:all) do
+        cleanup
+      end
+    end
+  end
+
+  describe '#login' do
```
Comment (juanignaciosl) [inline spec/requests/sessions_controller_spec.rb]: Nice test suite <3

**Comment by javitonino** [comment]
I cannot reply inline to the `[nil, nil]` comment 😕 

The issue with changing it to the array is that the `ldap_user || saml_user ...` line stops working (as an array of `nil` is true-ish. I agree with what you said about breaking the case when the return is assigned to an array variable, but maybe it's worth to keep it like it is now, as it makes the user code much shorter.

**Comment by javitonino** [comment]
Fixed the typo and added a test for SAML login failure,  that would have caught it.

**Comment by juanignaciosl** [comment]
It looks like autocreation with Google from organization login is broken.

I'll also like to check LDAP and SAML.

**Comment by juanignaciosl** [comment]
Google autocreation from login is broken in master.
