### PR TITLE
insert or update on table external sources violates foreign key constraint

### LINKED ISSUE #12488: [Model refactor] insert or update on table "external_sources" violates foreign key constraint
### Context

This will remove the usage of ExternalSource from CommonDataService.

[Trace](https://rollbar.com/carto/CartoDB/items/24077/)

```
PG::Error: ERROR: insert or update on table "external_sources" violates foreign key constraint "external_sources_visualization_id_fkey"
DETAIL: Key (visualization_id)=(bdbea4a0-003c-4559-addc-154568103228) is not present in table "visualizations".

+ 45 non-project frames
46
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 85 in block in load_common_data_for_user
47
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 58 in each
48
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 58 in load_common_data_for_user
49
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/models/user.rb", line 329 in load_common_data
50
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/models/carto/user_creation.rb", line 289 in load_common_data
+ 51 non-project frames
102
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/lib/resque/user_jobs.rb", line 54 in perform
+ 26 non-project frames
Sequel::DatabaseError: PG::Error: ERROR: insert or update on table "external_sources" violates foreign key constraint "external_sources_visualization_id_fkey"
DETAIL: Key (visualization_id)=(bdbea4a0-003c-4559-addc-154568103228) is not present in table "visualizations".

+ 45 non-project frames
46
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 85 in block in load_common_data_for_user
47
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 58 in each
48
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/services/visualization/common_data_service.rb", line 58 in load_common_data_for_user
49
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/models/user.rb", line 329 in load_common_data
50
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/app/models/carto/user_creation.rb", line 289 in load_common_data
+ 51 non-project frames
102
File "/home/ubuntu/www/production.cartodb.com/releases/20170719082510/lib/resque/user_jobs.rb", line 54 in perform
```

### Steps to Reproduce

Organization user signup.

This is likely to be related with this change: #12460

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #12488.

### CODE REVIEW

File: app/models/visualization/external_source.rb [hunk 1]
```diff
@@ -22,16 +22,7 @@ def initialize(visualization_id, import_url, geometry_types, rows_counted, size,
...
-        self.import_url = import_url
-        self.geometry_types = geometry_types
-        self.rows_counted = rows_counted
-        self.size = size
-        self.username = username
-        self
-      end
-
-      def importable_by(user)
+      def importable_by?(user)
```
Comment (mayoral) [inline app/models/visualization/external_source.rb]: 😍

File: app/services/visualization/common_data_service.rb [hunk 2]
```diff
@@ -78,11 +78,28 @@ def load_common_data_for_user(user, visualizations_api_url)
...
-              ExternalSource.new(visualization.id, dataset['url'], dataset['geometry_types'], dataset['rows'], dataset['size'], 'common-data').save
+              external_source = Carto::ExternalSource.create(
+                visualization_id: visualization.id,
+                import_url: dataset['url'],
+                rows_counted: dataset['rows'],
+                size: dataset['size'],
+                username: 'common-data'
+              )
+              # ActiveRecord array issue
+              external_source.update_attribute(:geometry_types, dataset['geometry_types'])
```
Comment (mayoral) [inline app/services/visualization/common_data_service.rb]: What error did you get from ActiveRecord if you try to set the field on the create method? Just curiosity.

File: spec/services/visualization/common_data_service_spec.rb [hunk 3]
```diff
@@ -50,6 +50,14 @@ def dataset(name, description: 'A very creative description')
     expect(remote_visualizations(@user).first.name).to eq 'ds1'
   end
 
+  it 'should import common data datasets within an ActiveRecord transaction (see #12488)' do
```
Comment (mayoral) [inline spec/services/visualization/common_data_service_spec.rb]: What's the expectation of this test? Not to raise an exception?

File: app/services/visualization/common_data_service.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/services/visualization/common_data_service.rb]: Generated SQL is wrong. It doesn't add single quotes around arrays. We searched for workarounds, but there's no one perfect for the gems versions that we use. This will be forgotten when we upgrade to Rails 4.

File: spec/services/visualization/common_data_service_spec.rb (hunk 3 above)
Comment (juanignaciosl) [inline spec/services/visualization/common_data_service_spec.rb]: Yes, that's what I explain in the next line: "# This would trigger an exception because of data integrity". It fails because of a FK (the one linked at the issue, indeed).

Comment (mayoral) [inline spec/services/visualization/common_data_service_spec.rb]: In that case we can do something like:

``` ruby
expect { service.load_common_data_for_user(@user, 'some_url') }.not_to raise_error CartoDB::Datasources::AuthError
```

Comment (juanignaciosl) [inline spec/services/visualization/common_data_service_spec.rb]: 👍

File: spec/services/visualization/common_data_service_spec.rb [hunk 4]
```diff
@@ -50,6 +50,16 @@ def dataset(name, description: 'A very creative description')
...
+    # This would trigger an exception because of data integrity
+    expect {
+      ActiveRecord::Base.transaction do
+        service.stubs(:get_datasets).returns([dataset('ds1')])
+        service.load_common_data_for_user(@user, 'some_url')
+      end
+    }.not_to raise_error
```
Comment (mayoral) [inline spec/services/visualization/common_data_service_spec.rb]: Nice! I usually prefer to tell here what error should not be raised instead of use the catch-all, but it works here.

Comment (juanignaciosl) [inline spec/services/visualization/common_data_service_spec.rb]: Yep, as the problem is quite indirect I prefer a broad spectrum check.

**Comment by juanignaciosl** [comment]
Ey, I'm moving this backwards because after a last look I think that there's a redundant `.save!`.

**Comment by juanignaciosl** [comment]
@mayoral sorry, I realized about a redundant `.save!`, and then I also realized that I could wrap the iteration through the data sources in a transaction, making it much faster. In addition, I've added a workaround that makes `change?` detection better, so we don't trigger unnecessary `UPDATE` requests. Could you do a second CR + Acceptance, please?

This involves user creation (normal signup, organization signup, organization creation, superadmin creation), and data library refresh (you can force it setting `last_common_data_update_date` to null and then opening the dashboard again).

Take a look at the queries in first insert, no metadata change, and changed metadata, I think they're close to optimal now. Let me know if you have trouble reproducing.

File: app/models/carto/external_source.rb [hunk 5]
```diff
@@ -22,4 +23,14 @@ def update_data(import_url, geometry_types, rows_counted, size, username = nil)
...
   end
+
+  private
+
+  # True if array (`['ST_MultiPolygon']`) contains the same elements than string, in PG notation (`{ST_MultiPolygon}`)
+  def equal_pg_array?(array, string)
+    array = [] if array.nil?
+    string = '{}' if string.nil?
+
+    "{#{array.join(',')}}" == string
```
Comment (mayoral) [inline app/models/carto/external_source.rb]: Looks good, but I think this method (and maybe others) have more sense to be part of a generic Carto ActiveRecord base class that our models can use as a base class instead of `ActiveRecord::Base`.

I know, it's out of the scope of this issue. I'm just mentioning it to open the debate and consider to do it in the future.

Comment (juanignaciosl) [inline app/models/carto/external_source.rb]: I wouldn't encourage inheritance for code reuse. Maybe a mixin. Anyway, agreed on refactor when we need this again. Maybe we'll upgrade versions before that and we can throw away this ugly hack.

Comment (mayoral) [inline app/models/carto/external_source.rb]: 👍
