### PR TITLE
Torque enhancementes

### LINKED ISSUE #9419: Blending mode doesn't work in time aggregated styled maps

### PR DESCRIPTION
**Pull request by xavijam**
- Removed unnecessary properties for static and animated heatmap.
- Make use of blending for animated layers.

CR: @nobuti 
Fixes #9419.

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js [hunk 1]
```diff
@@ -344,14 +355,14 @@ function generateCartoCSS (style, geometryType) {
 
 function trails (def) {
   var baseWidth = def.fill.size && parseInt(def.fill.size.fixed, 10);
-  var baseOpacity = def.fill.color.opacity;
+  var baseOpacity = def.fill.color.opacity != null ? def.fill.color.opacity : 1;
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: does `def.fill.color` (or even `def.fill`) it suppose to existe under any circumstance?

**Comment by nobuti** [comment]
👍
