### PR TITLE
Fixed image preview for subdomainless (without CDN) applications

### LINKED ISSUE #6274: Image preview is not working for standard users with subdomainless and no CDN
cc @javisantana

### PR DESCRIPTION
**Pull request by xavijam**
Basically we tried to parse maps_api_template incorrectly. So, right now we replace username from that string and it works perfectly in any situation, w/o subdomain.

Fixes #6274.

REVIEWER: @javierarce, you was my mate changing this stuff some time ago :D.

### CODE REVIEW

File: lib/assets/javascripts/cartodb/common/views/mapcard_preview.js [hunk 1]
```diff
@@ -10,17 +15,17 @@ module.exports = cdb.core.View.extend({
...
     username: '',
     visId: '',
-    mapsApiHost: '',
+    mapsApiResource: '',
     className: ''
   },
 
   _TEMPLATES: {
-    regular: '<%- protocol %>://<%- username %>.<%- mapsApiHost %>/api/v1/map/static/named/<%- tpl %>/<%- width %>/<%- height %>.png',
+    regular: '<%- protocol %>://<%= mapsApiResource %>/api/v1/map/static/named/<%- tpl %>/<%- width %>/<%- height %>.png',
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/views/mapcard_preview.js]: Using ```<%= %>``` because if not the other way (```<%- %>```) escaped ```/``` characters.

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
Deploying in ded02.

File: lib/assets/javascripts/cartodb/common/views/mapcard_preview.js (hunk 1 above)
Comment (javierarce) [inline lib/assets/javascripts/cartodb/common/views/mapcard_preview.js]: Shouldn't we maybe comment this, since it'd be possible that we change this inadvertently in the future?

Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/views/mapcard_preview.js]: :+1:

**Comment by javierarce** [comment]
:+1: code looks fine
