### PR TITLE
Torque categories

### LINKED ISSUE #9389: Torque category is not working
As @javisantana mentioned [here](https://github.com/CartoDB/cartodb/issues/9010):

When style is set as animated some things needs to happen:

- if the style applied does not use any variable it should work like it's working with now
- if we have one style using "by value" 
    - if it's a category attribute: torque style should use `cdb_mode([attribute])` as aggregation and use the turbocarto for the category
    - if it's a ramp attribute: torque style should use `avg([attribute])` as aggregation and use the turbocarto for ramps

- if we have more than one style attribute using "by value" -> we can't do anything with torque here since we don't have multivariable torque <- cc @saleiva. One solution would be to disable animated when this happen but not sure how hard is to explain that limitation to the user.

### PR DESCRIPTION
**Pull request by xavijam**
Fixes in this PR:

- [x] Categorize all type of columns, not only string ones: add a new option to categorize any selected column, no matter the its column type (cc @javierarce).
- [x] Check problems with `Others` value (exposed max number of categories cc @javierarce).
- [x] Instantiate map when a new ramp value is selected (CartoDB/cartodb.js#1409), dependencies updated (cc @alonsogarciapablo).
- [x] Added tests for style-form-components-dictionary.
- [x] Updated several repos dependencies (it will happen thanks to @rochoa).
- [x] Add tests for new things touched in style-generator (cc @javisantana).
- [x] Problem in public embed (it is likely related with sql_wrap not included) (cc @gfiorav).

Fixes #9389.

### CODE REVIEW

**Comment by xavijam** [comment]
CR: @nobuti  (y a volar!)

File: app/controllers/carto/api/vizjson3_presenter.rb [hunk 1]
```diff
@@ -349,6 +349,9 @@ def as_torque
 
         torque[:source] = @layer.options['source'] if @layer.options['source'].present?
 
+        sql_wrap = @layer.options['sql_wrap'] || @layer.options['query_wrapper']
+        torque[:sql_wrap] = sql_wrap if sql_wrap
```
Comment (gfiorav) [inline app/controllers/carto/api/vizjson3_presenter.rb]: Why are you putting this here? 😄

File: lib/carto/named_maps/template.rb [hunk 2]
```diff
@@ -127,19 +127,7 @@ def options_for_http_basemap_layers(layer_options)
...
-        layer_options_sql_wrap = layer_options[:sql_wrap]
-        layer_options_query_wrapper = layer_options[:query_wrapper]
-
-        options[:sql_wrap] = layer_options_sql_wrap || layer_options_query_wrapper
-
-        options
-      end
-
-      def common_options_for_carto_and_torque_layers(layer, index)
+      def options_for_carto_and_torque_layers(layer, index)
```
Comment (gfiorav) [inline lib/carto/named_maps/template.rb]: Rename this to `options_for_data_layers` since data is carto or torque ❤️

File: spec/lib/carto/named_maps/template_spec.rb [hunk 3]
```diff
@@ -343,8 +343,8 @@ module NamedMaps
               @template_hash = nil
             end
 
-            it 'should not contain sql wrap' do
-              @template_hash[:layergroup][:layers].second[:options][:sql_wrap].should be_nil
+            it 'should contain sql wrap' do
+              @template_hash[:layergroup][:layers].second[:options][:sql_wrap].should =~ /SELECT manolo FROM (<%= sql %>)/
```
Comment (xavijam) [inline spec/lib/carto/named_maps/template_spec.rb]: :kiss: hound.

File: lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js [hunk 4]
```diff
@@ -31,14 +45,26 @@ function getOptionsByStyleType (querySchemaModel, filterFunction, styleType) {
...
+    case 'animation':
+      if (params.animationType === 'heatmap') {
+        optionsArray = [{
+          val: 'cartodb_id',
+          label: 'cartodb_id',
+          type: 'number'
+        }];
+      }
+      break;
     default:
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js]: I guess we can get rid of this, but I like the explicit of the construction.

File: lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js [hunk 5]
```diff
@@ -133,104 +177,87 @@ function generateLineStroke (querySchemaModel, styleType, configModel) {
...
-        label: _t('editor.style.components.blending.options.src-over')
-      }
-    ];
-
-    var filterFunction = function (option) {
-      return _.contains(styleType === 'animation' ? animationOptions : simpleOptions, option.val);
+    var labelTranslate = 'editor.style.components.blending.options';
+
+    var generateBlendingOptions = function (options) {
+      return _.reduce(options, function (memo, option) {
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js]: why not _.map? performance or something? Just a question.

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js [hunk 6]
```diff
@@ -20,8 +21,9 @@ function makeCartoCSS (obj, prefix) {
   return css;
 }
 
-function makeColorRamp (props) {
-  var c = ['ramp([' + props.attribute + ']'];
+function makeColorRamp (props, isTorqueCategory) {
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: Out of scope but how difficult would be make this template based?

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js [hunk 7]
```diff
@@ -83,28 +96,31 @@ function blending (b, geometryType, animatedType) {
 }
 
 // fill
-function pointFill (props, animatedType) {
+function pointFill (props, animationType) {
   var css = {};
+  var isTorqueCategory = animationType && !props.color.fixed;
+  var markerFillOpacity = props.color && props.color.opacity;
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: should not we check for `props.color` in the line above as well?

File: lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js (hunk 5 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/style/style-form/style-form-components-dictionary.js]: I like reduce, nothing else :).

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js (hunk 7 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: Yeah, feedback applied :kiss:

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js (hunk 6 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: uhm... it would be possible, but I would not like to include more improvements, enough hard PR.

**Comment by xavijam** [comment]
Passing frontend and backend tests (not waiting for on premises ones).

**Comment by xavijam** [comment]
🚀
