### PR TITLE
Fix lockout redirection

### LINKED ISSUE #14607: Lockout screen not showing for locked users
### Context
It's happening for organizational users in a domainful server.

### Steps to Reproduce
1. Set the state of a user to "locked"
2. Go to a private URL (/dashboard)

### Current Result
ERR_TOO_MANY_REDIRECTS

### Expected result
Lockout screen

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes #14607 

The problem was that, for organizational users in domainful, the redirection was to `myorg.carto.com/lockout` instead of `myorg.carto.com/user/myuser/lockout`. It was trying to the check the user from the request (not found), causing a loop redirection between `login => dashboard => lockout`.

The solution was to fix the redirection URL.

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -196,7 +196,8 @@ def check_cors_headers_for_whitelisted_origin
   end
 
   def check_user_state
-    return unless (request.path =~ %r{^\/(lockout|login|logout|unauthenticated|multifactor_authentication)}).nil?
+    ignore_paths = %w(lockout login logout unauthenticated multifactor_authentication)
```
Comment (juanignaciosl) [inline app/controllers/application_controller.rb]: Minor: this could be a constant outside the method.

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -196,7 +196,8 @@ def check_cors_headers_for_whitelisted_origin
...
+    return if ignore_paths.any? { |path| request.path.include?(path) }
```
Comment (juanignaciosl) [inline app/controllers/application_controller.rb]: For this to be equivalent to the previous code, it needs `"/#{path}"` instead of `path` as `include?` parameter, I think that it'd be safer.

File: spec/requests/user_state_spec.rb [hunk 3]
```diff
@@ -256,11 +320,12 @@ def follow_redirects(limit = 10)
       end
       @public_api_endpoints.each do |endpoint|
         get endpoint, {}, @api_headers
-        request.path == endpoint
+        request.path.should == endpoint
```
Comment (juanignaciosl) [inline spec/requests/user_state_spec.rb]: :man_facepalming:

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (gonzaloriestra) [reply app/controllers/application_controller.rb]: Even with the slash, it wouldn't be equivalent, because it was required to start with it. I mean, only `/lockout` or `/login`.

But now we can receive something like `/user/fulano/lockout`, that's why I changed it to `include?`. What we could do is to use `end_with?` instead. What do you think?

Comment (juanignaciosl) [reply app/controllers/application_controller.rb]: Yep, I realized about the `^`, I shouldn't have said "equivalent" but "closer" :_)

A `end_with?` with `"/#{path}"` on _path_ (without parameters) should be safe. Please check that a trailing `/` in the URL wouldn't affect this, but yes, I'd give it a try.

Comment (gonzaloriestra) [reply app/controllers/application_controller.rb]: Ready! The trailing slash doesn't affect.

**Comment by juanignaciosl** [comment]
In acceptance a missing piece was detected: in staging and production there are redirections outside Rails that must also be fixed.

**Comment by gonzaloriestra** [comment]
The pending piece It's being fixed in another PR (https://github.com/CartoDB/cartodb/pull/14617), but when it's ready maybe we can merge it here and do the acceptance for both together.

**Comment by juanignaciosl** [comment]
In fact I'd suggest doing the acceptance both in staging _and_ in local so we're sure that both Rails and the full deployment are right.

**Comment by gonzaloriestra** [comment]
I've merged here the front changes to test both together.

**Comment by gonzaloriestra** [comment]
Ready for acceptance again! It should be tested in local and staging.

**Comment by juanignaciosl** [comment]
:+1: to acceptance. Wait for the tests to finish before merging (I rerun them because backend tests didn't end).
