### PR TITLE
Fixing translation for infowindow none template

### LINKED ISSUE #9199: Infowindow hint template rendered wrongly
STR
- Create a new map for a point dataset
- Enable pop-up (which style doesn't matter)
- Click a point

Actual result: 
- screen shot 2016-08-01 at 16 14 29

Expected result:
- A popup with some hint text

### PR DESCRIPTION
**Pull request by xavijam**
Mustache templates don't know anything about `_t` functionality, and also interpolation was not correct. Do you think @alonsogarciapablo we could pass variables to the fields array? Any better idea?

CR: @alonsogarciapablo
cc @matallo

Fixes #9199.

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/deep-insights-integration/link-layer-infowindow.js [hunk 1]
```diff
@@ -10,17 +10,19 @@ module.exports = function linkLayerInfowindow (layerDef, visMap) {
...
 
-      if (cartdb_id) {
+      if (cartodb_id) {
         attrs.fields = [{
           name: 'cartodb_id',
           title: true,
           position: 0
         }];
-        attrs.template = INFOWINDOW_NONE;
+        attrs.template = INFOWINDOW_NONE
```
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/deep-insights-integration/link-layer-infowindow.js]: Here's another idea... we could change the template as:
```
  ...
     <h5 class="CDB-infowindow-subtitle">{{ subtitle }}</h5>
     <h4 class="CDB-infowindow-title">{{ title }}</h4>
  ...
```
And then render the template using mustache templating (it's a mustache template after all!):

```
Mustache.render(INFOWINDOW_NONE, {
  subtitle: _t('editor.layers.infowindow.select-fields'),
  title: _t('editor.layers.infowindow.no-fields')
}  
```

Comment (matallo) [inline lib/assets/javascripts/cartodb3/deep-insights-integration/link-layer-infowindow.js]: +1

**Comment by xavijam** [comment]
Using .tpl (underscore template) instead of mustache, makes sense, idea by @alonsogarciapablo. What do you think?

**Comment by alonsogarciapablo** [comment]
👍

**Comment by xavijam** [comment]
Merging, frontend tests ready 💋
