### PR TITLE
12286 dropbox connect error handling

### LINKED ISSUE #12286: 500 when rejecting Dropbox oauth modal
### Steps to Reproduce
1. Disconnect from Dropbox (if your account is connected)
2. Go to import a new dataset
3. Select connect to dropbox
4. In the oauth popup, choose "cancel"

### Current Result
A 500 error page in the popup and https://rollbar.com/carto/CartoDB/items/23479/?item_page=0&item_count=100&#instances

### Expected result
A cleaner failure.

cc @juanignaciosl

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #12286 

Tests
1. Disconnect from Dropbox (if your account is connected)
2. Go to import a new dataset
3. Select connect to dropbox
4. In the oauth popup, choose "cancel"

-> Popup closes, shows error in main window, Rollbar trace (Error in oauth callback)

1. Connect to dropbox
2. Disconnect dropbox from dropbox side
3. Go to import a new dataset

-> Ask to connect again

### CODE REVIEW

File: services/datasources/lib/datasources/url/dropbox.rb [hunk 1]
```diff
@@ -207,9 +207,11 @@ def data_import_item=(value)
         # @return bool
         # @throws AuthError
         def token_valid?
-        # Any call would do, we just want to see if communicates or refuses the token
-          raise "Current account not found" unless @client.get_current_account
+          # Any call would do, we just want to see if communicates or refuses the token
+          @client.get_current_account
```
Comment (juanignaciosl) [inline services/datasources/lib/datasources/url/dropbox.rb]: Ok, I guess that this can't return `nil`, can it? This change is not needed but cleanup, isn't it?

File: services/datasources/lib/datasources/url/dropbox.rb [hunk 2]
```diff
@@ -207,9 +207,11 @@ def data_import_item=(value)
...
           true
+        rescue DropboxApi::Errors::HttpError
+          false
```
Comment (juanignaciosl) [inline services/datasources/lib/datasources/url/dropbox.rb]: What about adding a warning trace? This shouldn't happen, should it?

File: services/datasources/lib/datasources/url/dropbox.rb (hunk 1 above)
Comment (javitonino) [reply services/datasources/lib/datasources/url/dropbox.rb]: The problem was actually the negative case. It should return `false` instead of raising. This is not related to the issue in the ticket, but rather to the second one in this PR (disconnecting from dropbox).

File: services/datasources/lib/datasources/url/dropbox.rb (hunk 2 above)
Comment (javitonino) [reply services/datasources/lib/datasources/url/dropbox.rb]: This happens when the account is disconnected from the dropbox side, or if the token expires. According to the docs, the tokens do not have a defined expiry, but it has happened to me in my account. I'll add a warning, it could be useful to debug in the future.

**Comment by juanignaciosl** [comment]
To acceptance after warning added, then. Thanks!
