### PR TITLE
Fix missing geometry type exceptions

### LINKED ISSUE #7728: Error when trying to add an analysis
**STR:**

1. Create a new map from an existing dataset (I tried with points).
2. Click "Add analysis", select "Buffer" / "Trade areas" and click "Add analysis".

**Expected result:**

- Analysis is added, modal is closed.

**Actual result:**

- JS error in the console:
`Uncaught Error: TrackJS Caught: simpleGeometryTypeInput is required`
- Modal is not closed and analysis is not created.

NOTE: I observed that it's possible to add Buffer / Trade Areas analyses after having added a Point in Polygon analysis first.

cc: @viddo

### PR DESCRIPTION
**Pull request by viddo**
Fixes #7728 

It had two origins:
1. Race-condition when the query-schema-model was updated while the
modal was closing, the model listeners weren’t removed until the modal
animation finished. Changed to be removed straight away.
2. Option view required geometry type, even though it might not be
available (yet, or due to failing node results), so relaxed the check

@alonsogarciapablo could you try this branch locally and confirm that it solves your problem, please?

### CODE REVIEW

**Comment by javisantana** [comment]
\o/

**Comment by alonsogarciapablo** [comment]
Checking!

File: lib/assets/javascripts/cartodb3/components/modals/modal-view.js [hunk 1]
```diff
@@ -59,6 +60,7 @@ module.exports = CoreView.extend({
 
   _onDestroy: function () {
     this.hide();
+    _.invoke(this._subviews, 'allOff');
```
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/components/modals/modal-view.js]: First time I see `_.invoke` 👍  and `allOff`. Where's `allOff` defined? I'm sure that there's a reason for doing it this way, but just in case, why are not we just using `this.clean` here (without the delay)? Thanks!

**Comment by alonsogarciapablo** [comment]
👍  👍  👍  Code looks 👍  and it works 👍  locally.

File: lib/assets/test/spec/cartodb3/components/modals/add-analysis/analysis-option-view.spec.js [hunk 2]
```diff
@@ -12,52 +12,69 @@ describe('components/modals/add-analysis/analysis-option-view', function () {
...
+        spyOn(this.model, 'acceptsGeometryTypeAsInput').and.returnValue(false);
+        this.view.render();
+      });
+
+      it('should disable the view', function () {
+        expect(this.view.el.className).toContain('is-disabled');
+      });
+
+      it('should show alternative desc', function () {
+        expect(this.view.$el.html()).toContain('disabled-option-desc');
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/modals/add-analysis/analysis-option-view.spec.js]: I guess we could assert that text is "Your layer geometry is something and this analysis needs wadus"... Here and when the geometry is unknown.

File: lib/assets/javascripts/cartodb3/components/modals/modal-view.js (hunk 1 above)
Comment (viddo) [inline lib/assets/javascripts/cartodb3/components/modals/modal-view.js]: http://underscorejs.org/#invoke - _Calls the method named by methodName on each value in the list._

> …, why are not we just using this.clean here (without the delay)?

Because clean removes the view (and sub-views, and [more stuff](https://github.com/CartoDB/cartodb/blob/master/lib/assets/node_modules/backbone/core-view.js#L48-L69)) right away which removes the animation. So, I extracted the model unbinding code to a separate method to be able to use only that.

Comment (viddo) [inline lib/assets/javascripts/cartodb3/components/modals/modal-view.js]: > Where's allOff defined? 

It's in core-view, for some reason the changes are surpressed by default when viewed on Github though so you need to click to see it. ¯\_(ツ)_/¯

Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/components/modals/modal-view.js]: Perfect. Thanks for the clarification! :shipit:

File: lib/assets/test/spec/cartodb3/components/modals/add-analysis/analysis-option-view.spec.js (hunk 2 above)
Comment (viddo) [inline lib/assets/test/spec/cartodb3/components/modals/add-analysis/analysis-option-view.spec.js]: In test environment we don't load the actual strings (so output is the token itself), and just like visual things they need to be reviewed manually, so IMHO it's not worth testing in such detail.
