### PR TITLE
Stop fetching geocodings when first request fails

### LINKED ISSUE #4834: Check current problems when a geocoding is non authorized
https://my.trackjs.com/messages/filtered?message=401+Unauthorized%3a+GET+https%3a%2f%2fquanzhou41.cartodb.com%2fapi%2fv1_1%2fgeocodings

### PR DESCRIPTION
**Pull request by xavijam**
We didn't check if geocodings request failed, so basically we have this amount of errors because polling kept requesting the endpoint.

https://my.trackjs.com/messages/filtered?message=401+Unauthorized%3a+GET+https%3a%2f%2fbdavidson.cartodb.com%2fapi%2fv1_1%2fgeocodings
https://my.trackjs.com/messages/filtered?message=401+Unauthorized%3a+GET+https%3a%2f%2fcarloscrhz.cartodb.com%2fapi%2fv1_1%2fgeocodings
https://my.trackjs.com/messages/filtered?message=401+Unauthorized%3a+GET+https%3a%2f%2fmancha.cartodb.com%2fapi%2fv1_1%2fgeocodings

REVIEWER: @javierarce 
Fixes #4834.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5536/))

File: lib/assets/javascripts/cartodb/common/background_polling/models/geocodings_collection.js [hunk 1]
```diff
@@ -74,16 +74,25 @@ module.exports = Backbone.Collection.extend({
     });
   },
 
+  fetchGeocodings: function() {
+    var self = this;
+    // Start doing a fetch
```
Comment (javierarce) [inline lib/assets/javascripts/cartodb/common/background_polling/models/geocodings_collection.js]: This comment is not really necessary :)

**Comment by javierarce** [comment]
:+1: Looks good to me.

File: lib/assets/javascripts/cartodb/common/background_polling/models/geocodings_collection.js (hunk 1 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/background_polling/models/geocodings_collection.js]: Agree, copy-paste hell :(.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5539/))
