### PR TITLE
Autostyle legends embed

### LINKED ISSUE #11098: Autostyle does not hide/update legends in embed
### Context
Testing autostyle. In the embed, legends are not disabled when applying autostyle. And in the case of bubbles, the color is not updated.
Split from #10420
 
### Steps to Reproduce
1. Create a map
2. Style by value, so a legend is created
3. Add a widget to the same column
4. Publish the map
5. Go to the embed
6. Click autostyle in the widget

### Current Result
The legend is shown 

### Expected result
The legend disappears

### Additional info
https://github.com/CartoDB/cartodb/pull/10420#issuecomment-267952816
https://github.com/CartoDB/cartodb/pull/10420#issuecomment-267519787

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #11098, it adds the connection between legends, widgets and autostyle. 
- It exposes the same `layersData` object we are already exposing for Builder. We need it to handle layer's styles if no autstyle is applied.
- It includes some kind of deep-insights integration file, in order to bind widgets autostyle changes.
- The proper legend manager takes care of hiding/showing the affected legends, coloring the bubble legend as well from the styles of autostyle.

### Todo
- [ ] Tests.

### How to test it
- [ ] Create a map of points, add a layer and some widgets. Style some column in order to generate some legends. Apply auto style from a widget. Color legend should hide and bubble color should follow the ramp applied.
- [ ] Apply autostyle from another widget. All should work properly, inheriting from the new styles.
- [ ] Unapply autostyle from the selected widget. The original style should be recovered.
- [ ] Try the same adding more than one layer.
- [ ] Test the embed without the auto-style feature flag enabled.
- [ ] Try with different geometries.

### CODE REVIEW

**Comment by matallo** [comment]
trying select/unselect autostyle for lines (to prepare for the spec) fount it's failing for lines, on it

screen shot 2016-12-27 at 15 30 58

**Comment by matallo** [comment]
- tried different geometries and found "lines" failing, made further changes (explained below)
- completed dashboard tests
- added public tests
- removed the bubble color inherit when autostyle, for legends in both in public and dashboard views

File: lib/assets/core/javascripts/cartodb3/embed/legend-manager.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
+var _ = require('underscore');
+
+var legends;
+
+var LEGENDS_METADATA = ['bubble', 'category', 'choropleth', 'custom', 'custom_choropleth'];
+var LEGENDS_COLOR = ['category', 'choropleth'];
+
```
Comment (ivanmalagon) [inline lib/assets/core/javascripts/cartodb3/embed/legend-manager.js]: We're using this magical strings `bubble - category - custom_choropleth` in more than 10 different files. Should we create a common place for them to avoid typos and possible bugs?

File: app/views/carto/builder/public/embeds/show.html.erb [hunk 2]
```diff
@@ -27,6 +27,7 @@
 <%= content_for(:js) do %>
   <script>
     var vizJSON = <%= safe_js_object @vizjson.to_hash.to_json %>;
+    var layersData = <%= safe_js_object @layers_data.to_json %>;
```
Comment (ivanmalagon) [inline app/views/carto/builder/public/embeds/show.html.erb]: This exposes too much information in the embed view about the layers information.
In case we need some information from the layers we should expose only that.

After checking this with @xavijam this issue should go back to development. Check if we really need this info or we can get from another place.

File: app/controllers/carto/builder/public/embeds_controller.rb [hunk 3]
```diff
@@ -21,6 +21,9 @@ class EmbedsController < BuilderController
         layout false
 
         def show
+          @layers_data = @visualization.layers.map do |l|
+            Carto::Api::LayerPresenter.new(l, with_style_properties: true).to_poro(migrate_builder_infowindows: true)
+          end
           render 'show', layout: 'application_public_visualization_layout'
```
Comment (ivanmalagon) [inline app/controllers/carto/builder/public/embeds_controller.rb]: Same comment as in [https://github.com/CartoDB/cartodb/pull/11121/files#diff-6cb2ca8a977e537854e3b540e80bf5f6](embed/show.hmtl.erb) applies here.

File: app/views/carto/builder/public/embeds/show.html.erb (hunk 2 above)
Comment (matallo) [inline app/views/carto/builder/public/embeds/show.html.erb]: investigated as much as we could but we'd need @juanignaciosl @gfiorav @javitonino to take a closer look at this and only expose `style_properties` we need

Comment (juanignaciosl) [inline app/views/carto/builder/public/embeds/show.html.erb]: Yup, we could restrict that easily. Maybe something like this?

```ruby
 var layersStyle = <%= safe_js_object @layers_style.to_json %>;
```

We'd need to know what you actually need. Could you open an issue with the needed properties and desired output so we can branch this and do it, please?

Comment (matallo) [inline app/views/carto/builder/public/embeds/show.html.erb]: there! https://github.com/CartoDB/cartodb/issues/11160

File: app/controllers/carto/builder/public/embeds_controller.rb [hunk 4]
```diff
@@ -21,6 +21,9 @@ class EmbedsController < BuilderController
         layout false
 
         def show
+          @layers_data = @visualization.layers.map do |l|
```
Comment (xavijam) [inline app/controllers/carto/builder/public/embeds_controller.rb]: I feel we don't need this exposed variable anymore :).

File: lib/assets/core/javascripts/cartodb3/data/legends/legend-bubble-definition-model.js [hunk 5]
```diff
@@ -38,7 +38,9 @@ module.exports = LegendBaseDefModel.extend({
   },
 
   _onChangeStyle: function () {
-    this.set('fillColor', this._inheritStyleColor(this.layerDefinitionModel.styleModel));
+    if (!this.layerDefinitionModel.get('autoStyle')) {
```
Comment (xavijam) [inline lib/assets/core/javascripts/cartodb3/data/legends/legend-bubble-definition-model.js]: Thanks @matallo 👍

File: lib/assets/core/javascripts/cartodb3/embed/style-collection.js [hunk 6]
```diff
@@ -0,0 +1,24 @@
+var Backbone = require('backbone');
```
Comment (xavijam) [inline lib/assets/core/javascripts/cartodb3/embed/style-collection.js]: We don't need this file anymore, don't we?

**Comment by xavijam** [comment]
We have found a problem related with autostyle in production. I encourage you to try this feature without the auto-style feature flag enabled before the acceptance. 💋  and review my comments ❤️ .

**Comment by matallo** [comment]
totally, changes done, the only issue I could find, after enabling and checking autostyle, then disabling feature is the url will make some error appear, but I think it's kind of unavoidable

**Comment by xavijam** [comment]
It is almost impossible someone with autostyle wants to go back and disable it, so :+1:. Also we are pretty close to enable for everybody so, we are ok with that man, thanks.

**Comment by matallo** [comment]
BOOM

**Comment by xavijam** [comment]
Deployed in ded03.

**Comment by xavijam** [comment]
Har... One thing we (mainly @nobuti) have noticed. If we select the auto-style of one widget, then select the auto-style of other widget (from the same column), and then we deselect the auto-style, the layer style is not correct. I feel @nobuti wanted the layer style also for that :(. Seems like we will need to get back that code @matallo, sorry a lot.

**Comment by matallo** [comment]
ok, taking a look

**Comment by matallo** [comment]
indeed after much testing we use

```layer && layer.set({cartocss: layerStyle.get('cartocss')});```

from https://github.com/CartoDB/cartodb/pull/11121/commits/61f4f7fc34f54b63485b6edd2d5a055b5e2e8b83#diff-d3b4bb54a183449471a27c2dd0396578R59 so we'd definitely need the `layerStyleCollection`

despite the `initialStyle` of the layer is set in the widget-model we can't use the cartocss from there as it appears already generated

```
"#layer {
  marker-width: 7;
  marker-fill: #666666;
  [ crimedescr = "10851(A)VC TAKE VEH W/O OWNER" ] {
    marker-fill: #ff0000;
  }
  [ crimedescr = "TOWED/STORED VEH-14602.6" ] {
    marker-fill: #0000ff;
  }
  [ crimedescr = "459 PC  BURGLARY VEHICLE" ] {
    marker-fill: #00ff55;
  }
  [ crimedescr = "TOWED/STORED VEHICLE" ] {
    marker-fill: #0F8554;
  }
  [ crimedescr = "459 PC  BURGLARY RESIDENCE" ] {
    marker-fill: #73AF48;
  }
  [ crimedescr = "MISSING PERSON" ] {
    marker-fill: #EDAD08;
  }
  [ crimedescr = "10851 VC AUTO THEFT LOCATE" ] {
    marker-fill: #E17C05;
  }
  [ crimedescr = "594(B)(2)(A) VANDALISM/ -$400" ] {
    marker-fill: #CC503E;
  }
  [ crimedescr = "TRAFFIC-ACCIDENT INJURY" ] {
    marker-fill: #94346E;
  }
  [ crimedescr = "TRAFFIC-ACCIDENT-NON INJURY" ] {
    marker-fill: #6F4070;
  }
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}"
```

instead of the

```
"#layer {
  marker-width: 7;
  marker-fill: ramp([crimedescr], (#ff0000, #0000ff, #00ff55, #0F8554, #73AF48, #EDAD08, #E17C05, #CC503E, #94346E, #6F4070, #666666), ("10851(A)VC TAKE VEH W/O OWNER", "TOWED/STORED VEH-14602.6", "459 PC  BURGLARY VEHICLE", "TOWED/STORED VEHICLE", "459 PC  BURGLARY RESIDENCE", "MISSING PERSON", "10851 VC AUTO THEFT LOCATE", "594(B)(2)(A) VANDALISM/ -$400", "TRAFFIC-ACCIDENT INJURY", "TRAFFIC-ACCIDENT-NON INJURY"), "=");
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}"
```

we obtain with the `layerStyle`

I'm restoring the layerdata stuff, and reopening https://github.com/CartoDB/cartodb/issues/11160 so we at least don't expose more data than necessary

in any case I'm removing the update bubble part

thanks @nobuti for pointing that out, I should have spotted it, please @xavijam prioritize for backend changes 🙏

File: app/controllers/carto/builder/public/embeds_controller.rb (hunk 4 above)
Comment (xavijam) [inline app/controllers/carto/builder/public/embeds_controller.rb]: Finally yes, we need it :S.

**Comment by xavijam** [comment]
VAMOS NIÑOS! Que ganas...

**Comment by javierarce** [comment]
This seems to be getting stuck again and again in the build check :/

**Comment by xavijam** [comment]
Thing is backend tests are not passing either, that worries me.

**Comment by xavijam** [comment]
cc @CartoDB/builder-backend

**Comment by xavijam** [comment]
In fact: 

```ruby
Failures:
10:45:12 
10:45:12   1) Imports API raises an error if the user attempts to import tables when being over quota
10:45:12      Failure/Error: last_import.error_code.should be == 8002
10:45:12        expected: == 8002
10:45:12             got:    1006
10:45:12      # ./spec/requests/api/imports_spec.rb:156:in `block (2 levels) in <top (required)>'
10:45:12 
10:45:12 Finished in 5 minutes 41.27 seconds
10:45:12 55 examples, 1 failure, 1 pending
10:45:12 
10:45:12 Failed examples:
```

**Comment by javitonino** [comment]
Looks like a fluke, they passed in onpremise and they work locally. Making a dummy commit to make sure.

**Comment by javitonino** [comment]
Backend passing, it was just a random error, it seems. Moving back to acceptance (I think it was there, right?)

**Comment by xavijam** [comment]
It was in deploy, hur, now failing on-premises tests :(. Just restarting once more, this is crazy.

**Comment by javierarce** [comment]
Thanks!

**Comment by xavijam** [comment]
Failed onpremises frontend tests, due to PhantomJS timed out, not waiting anymore because those tests belong to old onpremises.

**Comment by nobuti** [comment]
\o/
