### PR TITLE
11262 keep mimetype in organization assets

### LINKED ISSUE #11262: Preserve original file extension in asset import
### Context

Discovered by @ivanmalagon when working with org assets front. The problem is that neither s3 headers can be prepared nor can RAILS serve adequate MIME type headers without the original extension. (i.e: upload hey.svg, produce an import file imported_assets_blabla.svg).

 

### Steps to Reproduce

1. Upload an asset 
2. Access asset through provided URL

### Current Result

The headers are wrong. 

### Expected result

The headers are correct since the extension is present in the filename and s3 or RAILS can better infer the file type.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #11262 
Keep extensions when saving tempfiles, which makes the mimetypes be correct upon download.

**Acceptance**
Upload a file using the organization assets API. Check that the download link contains the extension and the correct mimetype (check response headers). Check at least with `.svg` as it is the more problematic allowed format.

Example API call:
```
curl -X POST <orgname>.localhost.lan:3000/u/<username>/api/v1/organization/<organization_uuid>/assets?api_key=<api_key_of_user_in_org> -F resource=@path/to/file/you/want/to/upload.svg
```

### CODE REVIEW

File: lib/carto/assets_service.rb [hunk 1]
```diff
@@ -50,5 +51,17 @@ def location
...
       1_048_576 # 1 MB
     end
+
+    def resource_extension(resource)
+      # Resource can be a ActionDispatch::Http::UploadedFile or a URI string
+      filename = resource.respond_to?(:original_filename) ? resource.original_filename : resource
+      extension = File.extname(filename).downcase
+
+      # Filename might include a postfix hash -- Rack::Test::UploadedFile adds it
+      extension.gsub!(/\d+-\w+-\w+\z/, '') if Rails.env.test?
```
Comment (juanignaciosl) [inline lib/carto/assets_service.rb]: Does this `if Rails.env.test?` should be kept?

**Comment by javitonino** [comment]
There is a failing test (due to the new validation), so moving back to development.

File: lib/carto/assets_service.rb (hunk 1 above)
Comment (javitonino) [inline lib/carto/assets_service.rb]: I am not sure this line is needed at all. I copied it from old code, but it seems it is not needed for the new tests, so I think we can remove it altogether.

In case we keep it, yes, the environment check is needed, as this weakens the validation.

Comment (juanignaciosl) [inline lib/carto/assets_service.rb]: I'd give the deletion a try. If both local and CI work without that, the line is no longer needed.

**Comment by gfiorav** [comment]
Acceptance 🍏
