### PR TITLE
Legend fixes

### LINKED ISSUE #4608: make default legend title the column name instead of empty
when a choropleth or bubble or ... map is made, put the legend title to default as the column name used to visualize the data

### LINKED ISSUE #10135: Bubble legend fails to generate for line layer
### STR

- Load a line dataset and style size by cartodb_id.
- The legend show `No data available`.

#### Expected

- The map shows a shiny bubble legend

### LINKED ISSUE #10138: Choropleth legend fails to generate after trying to style by null values
### STR

I can't reproduce it consistently, but when I can this are the steps:

- Style a map points by a column full of null values. 
- The category legend won't show because of validation. The fill component shows a ramp with only one color.
- Next change the value to style to a numeric one, in order to get a choropleth.
- 💥  The fill component shows the one color ramp selected, and the seems falling apart. But as soon I change the ramp, all goes well again.

#### Expected 

- A choropleth legend

I've recorded a screengif to illustrate the issue:

legend-fill-bug

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes a few more legend bugs.

Fixes #10135, including the shrinkwrap to update cartodb.js version.
Fixes #4608.
Fixes #10138.

https://www.dropbox.com/s/5xx9aqat745s4zx/legends.gif?dl=0

CR @xavijam 

Also @javierarce if you could take a look at https://github.com/CartoDB/cartodb/commit/792b7e2196518b81e1ea7e886ff24fc3d41d9cb1 would be great. I think it's ok, but not completely sure about the implications. Basically it introduces a validation for ramps. Maps api cries if a ramp length is less than two, and I feel it makes sense to have ramps of at least two colors.

https://www.dropbox.com/s/bu878ota3wpnx3s/Screen%20Shot%202016-10-11%20at%2016.49.06.png?dl=0

(Sorry for the links, file uploading seems to be broken right now).

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-color-ramps.js [hunk 1]
```diff
@@ -45,18 +45,25 @@ module.exports = CoreView.extend({
...
 
-    if (!this.model.get('range')) {
+    if (!range || !this._isValidRange(range)) {
       this.model.set('range', this._getDefaultRamp());
     }
   },
 
+  // range minimun size should be 2
+  _isValidRange: function (range) {
+    return range.length >= 2;
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-color-ramps.js]: We checked if range exists couple lines above, but it's good to be explicit 👍
