### PR TITLE
Test maps controller

### LINKED ISSUE #6808: Cover map edition endpoint with tests
Map endpoint api doesn't have enough validation. For example, using a wrong ok version (`gem 'oj',                    '~> 2.12.14'`) breaks parsing. Tests should check that input format is valid.

### PR DESCRIPTION
**Pull request by javitonino**
Closes #6808 

This adds tests to both maps API endpoints, moving the existing tests to use the new spec_helper_min. A couple of bugs where discovered by this and are fixed in the same PR.

CR @gfiorav @juanignaciosl

### CODE REVIEW

File: app/controllers/api/json/maps_controller.rb [hunk 1]
```diff
@@ -42,6 +43,8 @@ def update
   protected
 
   def load_map
+    raise RecordNotFound unless is_uuid?(params[:id])
```
Comment (juanignaciosl) [inline app/controllers/api/json/maps_controller.rb]: I guess this will trigger a 404 error, but it should actually be a 400, since request is not valid.

Comment (javitonino) [inline app/controllers/api/json/maps_controller.rb]: Yes, it is a 404 for consistence with the other controller. Probably could change this to 400, and unauthorized requests to 403 (from 401 and 404). Don't know how this could affect API callers.

Comment (juanignaciosl) [inline app/controllers/api/json/maps_controller.rb]: :ok_hand: then

**Comment by juanignaciosl** [comment]
:+1:

**Comment by gfiorav** [comment]
:package: for me!

**Comment by javitonino** [comment]
Retest this, please
