### PR TITLE
10250 migrate custom label bubble legends

### LINKED ISSUE #10250: Error migrating bubble legend with custom labels
If labels are custom, they are not numeric, so calculating the intermediate steps fail.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10250

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @juanignaciosl

File: lib/carto/legend_migrator.rb [hunk 1]
```diff
@@ -129,9 +129,13 @@ def build_html_definition_from_bubble(steps: 6)
...
-      step = (max - min) / (steps - 1)
-      values = Array.new(steps) do |index|
-        formatted_string_number(min + (index * step))
+      if min.is_a?(Numeric) && max.is_a?(Numeric)
+        step = (max - min) / (steps - 1)
+        values = Array.new(steps) do |index|
+          formatted_string_number(min + (index * step))
+        end
+      else
+        values = [min] + [""] * (steps-2) + [max]
```
Comment (juanignaciosl) [inline lib/carto/legend_migrator.rb]: If `steps` can be 1 or 0 this will fail.
