### PR TITLE
fix popups on layer creation, close #7556

### LINKED ISSUE #7556: After adding a new layer, popup panel is not working
### STR

1. Create a map (with one layer) and go to editor 3.
2. Add a new layer.
3. Go to popup block.
4. Nothing is rendered, check chrome dev console.

cc @alonsogarciapablo

### PR DESCRIPTION
**Pull request by matallo**
CR @xavijam

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js [hunk 1]
```diff
@@ -125,7 +125,9 @@ module.exports = Backbone.Collection.extend({
         tooltip: {},
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js]: Why don't we remove the options ones?
Also, could we add a tests please?

**Comment by xavijam** [comment]
Checking what I've commented, adding a spec, and ready to go.

File: lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js (hunk 1 above)
Comment (matallo) [inline lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js]: totally true! they were misplaced since the beginning :/

tests added, merging as it goes 💚

File: lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js [hunk 2]
```diff
@@ -28,6 +28,25 @@ describe('data/layer-definitions-collection', function () {
   });
 
   describe('.createLayerForTable', function () {
+    it('should create layer with infowindows and tooltips', function () {
+      var TiledLayer = new Backbone.Model({
```
Comment (xavijam) [inline lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js]: I feel we don't need those TiledLayer or CartoDBlayer, right?
With only the collection and using the function is enough.

Comment (matallo) [inline lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js]: it gave me a hard time on the layer creation because of an invalid sourceId, that being related to the letters, that being related to the order

https://github.com/CartoDB/cartodb/blob/7556-popups/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L42-L50

this is the best solution I found to workaround that

Comment (xavijam) [inline lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js]: Hey, if we need that, let's add it within `beforeEach` + a comment, and 🎉 .

Comment (matallo) [inline lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js]: roger

Comment (xavijam) [inline lib/assets/test/spec/cartodb3/data/layer-definitions-collection.spec.js]: Ok, already checked with @matallo that rest of specs within that describe do other things in a different way. So 🍏 man!

**Comment by matallo** [comment]
🚀
