### PR TITLE
8964 add connection events

### LINKED ISSUE #8964: [Metrics] Add new segment event 'Failed connection'
Track a new event 'Failed connection' into Segment.com every time a new dataset import fails.

The event will be identified by user id (box id) and include the following attributes
 - username: (user.username)
 - email: (user.email)
 - plan: (user.account_type)
 - organization: (user.organization_user? ? user.organization.name : nil)
 - event_origin: 'Editor'
 - creation_time: (Time.now.utc)
 - ~~import_size: (size of dataset to be imported)~~
 - ~~import_type: (type of file (csv, shp, geojson, ...) or connection (twitter, common data))~~

@gfiorav Is it possible to get the 'import_size' attribute?

### LINKED ISSUE #9329: [Metrics] Add new segment event 'Completed connection'
We'll track the import process to see when a user completes an import into carto and which types of files he imports. 
Importing several files in a zip file or similar should generate an event per file if possible (some errors like corrupted zip files won't allow for this, no problem)

The event will be identified by user id (box id) and include the following attributes
- normal user properties (id, username, email, plan, ...)
- data_from: origin of imported data (value of data_type in data_imports)
  -  Possible values: [table, file, query, url, external_table, datasource, null]
- imported_from: (if data_from = 'datasource' the service name that provides the file: dropbox, gmail, ...)
- file_type: (file extension)

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #8964
Fixes #9329

### CODE REVIEW

**Comment by gfiorav** [comment]
Please CR, @javitonino

File: lib/carto/tracking/events.rb [hunk 1]
```diff
@@ -88,6 +88,34 @@ def initialize(user, visualization)
...
+      end
+
+      class CompletedConnection < ConnectionEvent
+        def initialize(user, result: nil, data_from: '', imported_from: '', sync: false)
+          super(user, 'Completed connection', result, data_from, imported_from, sync)
+        end
+      end
+
+      class FailedConnection < ConnectionEvent
+        def initialize(user, result: nil, data_from: '', imported_from: '', sync: false)
```
Comment (javitonino) [inline lib/carto/tracking/events.rb]: Hound is wrong!

**Comment by javitonino** [comment]
A bit hacky, but such is the nature of the imported. Ready to :gift:
