### PR TITLE
13333 update api keys on table change

### LINKED ISSUE #13333: Delete API Key entries when tables get deleted
An API Key contains references to tables. When a table is deleted, we should clean that. Otherwise, we must take that case into account whenever that metadata is used.

- [ ] ~Delete API key entries when tables get deleted.~
- [ ] ~Ensure that API key deletion is clean. If you run~ `spec/requests/carto/api/api_keys_controller_spec.rb`, you see this message ([context](https://github.com/CartoDB/cartodb/pull/13359#discussion_r160512387)):~

```
An error occurred in an after(:all) hook.
  Sequel::DatabaseError: PG::Error: ERROR:  role "test_cartodb_user_75c9f2ee-b568-11e7-ab5a-784f436d1355" cannot be dropped because some objects depend on it
DETAIL:  privileges for database cartodb_test_user_75c9f2ee-b568-11e7-ab5a-784f436d1355_db
3 objects in database cartodb_test_user_75c9f2ee-b568-11e7-ab5a-784f436d1355_db
```

### PR DESCRIPTION
**Pull request by amartinj**
Closes #13333

### CODE REVIEW

File: app/models/carto/api_key_grants.rb [hunk 1]
```diff
@@ -26,6 +26,13 @@ def merge!(permissions)
       @permissions += permissions.reject { |p| @permissions.include?(p) }
     end
 
+    def <<(permission)
```
Comment (juanignaciosl) [inline app/models/carto/api_key_grants.rb]: An `add!` method makes it more readable. Symbols are often constrained to primitive types.

File: app/models/carto/api_key_grants.rb [hunk 2]
```diff
@@ -26,6 +26,13 @@ def merge!(permissions)
...
+      down_permission = permission.downcase
+      if !@permissions.include?(down_permission) && ALLOWED_PERMISSIONS.include?(down_permission)
```
Comment (juanignaciosl) [inline app/models/carto/api_key_grants.rb]: This method should fail if the permission is not allowed.

File: app/models/carto/api_key_grants.rb [hunk 3]
```diff
@@ -72,5 +85,31 @@ def process_table_permissions(grants_json)
...
+        permission_key = "#{line[:schema]}.#{line[:table_name]}"
+        unless permissions[permission_key]
+          permissions[permission_key] = TablePermissions.new(schema: line[:schema], name: line[:table_name])
+        end
+        permissions[permission_key] << line[:permission]
+      end
+      permissions.values
+    end
+
+    def roles_from_db
```
Comment (juanignaciosl) [inline app/models/carto/api_key_grants.rb]: Minor: as `roles_from_db` imposes an structure (it will return a collection of elements with three columns: `schema`, `table_name` and `privilege_type` (renamed to `permission`), it'd be better if this method parsed the result instead of `table_permissions_from_db`.

Given that suggestion you might thing "well, ok, but the parsing is not trivial, so the method is too long". That's right for this query, but you could make it simpler:

```sql
select table_schema, table_name, string_agg(privilege_type,',') privilege_types from information_schema.role_table_grants where grantee = '#{@db_role}' group by table_schema, table_name;
```

That makes parsing trivial.

File: app/models/carto/api_key_grants.rb [hunk 4]
```diff
@@ -36,14 +43,20 @@ class ApiKeyGrants
 
     attr_reader :granted_apis
 
-    def initialize(grants_json = [])
+    def initialize(db_connection:, db_role:, grants_json: [])
```
[the remark this answers is not in the document]
Comment (amartinj) [reply app/models/carto/api_key_grants.rb]: Yes but `ApiKeyGrants` is the only one managing the grants of the ApiKey. I also thought about splitting this behaviour, but I decided not to because the design would be more complicated. It's just one method, but the class still holds behaviour to handle the grants of the ApiKey

[the remark this answers is not in the document]
Comment (juanignaciosl) [reply app/models/carto/api_key_grants.rb]: Disagree and commit.

File: app/models/carto/api_key_grants.rb [hunk 5]
```diff
@@ -36,14 +43,20 @@ class ApiKeyGrants
...
-      @table_permissions.values
+    def table_permissions(from_db: false)
+      if from_db
+        table_permissions_from_db
+      else
+        @table_permissions.values
+      end
     end
 
     def to_json
```
Comment (juanignaciosl) [inline app/models/carto/api_key_grants.rb]: We said that we must remove the *reads* from the metadata and replace them with the DB ones.

File: app/models/carto/api_key_grants.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (juanignaciosl) [reply app/models/carto/api_key_grants.rb]: For future reference: we had a talk and this is going to _change_.

File: app/models/carto/api_key_grants.rb (hunk 2 above)
Comment (amartinj) [reply app/models/carto/api_key_grants.rb]: Permissions were validated after saving the JSON, so it's safe to skip this validation

File: spec/models/carto/api_key_spec.rb [hunk 6]
```diff
@@ -194,4 +198,49 @@ def with_connection_from_api_key(api_key)
       api_key.errors.full_messages.should include 'Grants only one apis section is allowed'
     end
   end
+
+  describe '#table_permission_from_db' do
+    it 'loads newly created grants for role' do
+      api_key = Carto::ApiKey.new(user_id: @user1.id,
```
Comment (juanignaciosl) [inline spec/models/carto/api_key_spec.rb]: Minor: you can use `create!` instead of `create` + `save!`

File: spec/models/carto/api_key_spec.rb [hunk 7]
```diff
@@ -194,4 +198,49 @@ def with_connection_from_api_key(api_key)
       api_key.errors.full_messages.should include 'Grants only one apis section is allowed'
     end
   end
+
+  describe '#table_permission_from_db' do
+    it 'loads newly created grants for role' do
```
Comment (juanignaciosl) [inline spec/models/carto/api_key_spec.rb]: Nice test!

File: spec/models/carto/api_key_spec.rb [hunk 8]
```diff
@@ -194,4 +198,49 @@ def with_connection_from_api_key(api_key)
...
+                                    database_grant('public', @table1.name),
+                                    apis_grant(['maps', 'sql'])
+                                  ])
+      api_key.save!
+
+      sql = "drop table #{@table1.name}"
+      @user1.in_database(as: :superuser).run(sql)
+
+      table_permission = api_key.table_permissions_from_db.find do |tp|
+        tp.schema == @table2.database_schema && tp.name == @table2.name
```
Comment (juanignaciosl) [inline spec/models/carto/api_key_spec.rb]: This test is really nice but I think that this is wrong. Shouldn't this be `tp.schema == @table1.database_schema && tp.name == @table1.name`? The test drops `@table1`.

Suggestion: in order to avoid this kind of errors, I usually add the positive check before the effect. In this case, I'd check that it shows the permission before the drop, then drop, and then check that it's not shown.

File: app/models/carto/api_key.rb [hunk 9]
```diff
@@ -8,163 +8,237 @@ def validate_each(record, attribute, value)
...
+    def drop_db_role
+      revoke_privileges(*affected_schemas(table_permissions))
+      db_run("drop role \"#{db_role}\"")
+    end
 
-  def remove_from_redis(key = redis_key)
-    redis_client.del(key)
-  end
+    def update_role_permissions
+      revoke_privileges(*affected_schemas(table_permissions_from_db)) if grants_was.present?
```
Comment (juanignaciosl) [inline app/models/carto/api_key.rb]: I _think_ (I'm not 100% sure) that `if grants_was.present?` shouldn't be there now. `table_permissions_from_db` will always return the current state, which is valid (by definition), so checking `grants_was.present?` is not needed.

In fact, it _might be useful to compare `table_permissions_from_db` with `table_permissions`, and don't do anything if they're equal. But this is an optimization that can wait.

Comment (amartinj) [reply app/models/carto/api_key.rb]: `grants_was` means there already was a permission definition, in which case we need to get the actual permissions for the tables to revoke them. Not sure if it exists but this could be replaced with something like `was_persisted?`

Comment (juanignaciosl) [reply app/models/carto/api_key.rb]: Can't we just run `revoke_privileges(*affected_schemas(table_permissions_from_db))` always? `table_permissions_from_db` will just be empty in the first case.

Comment (amartinj) [reply app/models/carto/api_key.rb]: You're right

File: app/models/carto/api_key.rb [hunk 10]
```diff
@@ -8,163 +8,237 @@ def validate_each(record, attribute, value)
...
-  VALID_TYPES = [TYPE_REGULAR, TYPE_MASTER, TYPE_DEFAULT_PUBLIC].freeze
+    def initialize(schema:, name:, permissions: [])
+      @schema = schema
+      @name = name
+      @permissions = permissions
+    end
 
-  self.inheritance_column = :_type
+    def merge!(permissions)
+      @permissions += permissions.select { |p| p.downcase unless @permissions.include?(p) }
```
Comment (juanignaciosl) [inline app/models/carto/api_key.rb]: I'll change this one. Although this works, it's not the natural way to use `select`. This should've been written like this:

```
@permissions += permissions.select { |p| !@permissions.include?(p.downcase) }
```

And then, replacing `select` + `!` with `reject`:

```ruby
@permissions += permissions.reject { |p| @permissions.include?(p.downcase) }
```

Comment (juanignaciosl) [reply app/models/carto/api_key.rb]: PD: in addition, you probably wanted to check against the downcased `p`.

File: app/models/carto/api_key.rb [hunk 11]
```diff
@@ -8,163 +8,237 @@ def validate_each(record, attribute, value)
...
+      @permissions = permissions
+    end
 
-  self.inheritance_column = :_type
+    def merge!(permissions)
+      @permissions += permissions.reject { |p| @permissions.include?(p.downcase) }
+    end
 
-  belongs_to :user
+    def add!(permission)
```
Comment (juanignaciosl) [inline app/models/carto/api_key.rb]: `add!` can be rewritten in terms of `merge!`.

Comment (juanignaciosl) [reply app/models/carto/api_key.rb]: PD: `add!`, in fact, is not used. Deleting.

File: app/models/carto/api_key.rb [hunk 12]
```diff
@@ -8,163 +8,231 @@ def validate_each(record, attribute, value)
...
-  VALID_TYPES = [TYPE_REGULAR, TYPE_MASTER, TYPE_DEFAULT_PUBLIC].freeze
+    def initialize(schema:, name:, permissions: [])
+      @schema = schema
+      @name = name
+      @permissions = permissions
+    end
 
-  self.inheritance_column = :_type
+    def merge!(permissions)
+      down_permissions = permissions.map(&:downcase)
```
Comment (amartinj) [inline app/models/carto/api_key.rb]: @juanignaciosl I've added this line to make all permissions downcase to compare against.

Comment (juanignaciosl) [reply app/models/carto/api_key.rb]: Ok. The _comparison_ was already downcased (`@permissions += permissions.reject { |p| @permissions.include?(p.downcase) }`). But it's true that it would add upcased values. I would've inlined it, though. To acceptance, then.
