### PR TITLE
Fix pagination on new public pages

### LINKED ISSUE #2623: Pagination doesn't work on new public profile

### PR DESCRIPTION
**Pull request by viddo**
Fixes #2623 

The problem is not really on the public pages but in how the pagination view was changed to work for the create-map dialog, so refactored the code to allow the click-behaviour to work as default. Instead, only block stop event it if a url resolver (`url_to`) is not provided (which is the desired behavior for the create map dialog).

### CODE REVIEW

**Comment by viddo** [comment]
@xavijam tested locally and works as expected now, but code review 
cc @saleiva for reporting the issue

File: lib/assets/javascripts/cartodb/new_common/views/pagination/view.js [hunk 1]
```diff
@@ -50,15 +54,13 @@ module.exports = cdb.core.View.extend({
...
-    if (this.router !== undefined) {
+    if (this.router) {
       navigateThroughRouter.apply(this, arguments);
+    } else if (!this.model.hasUrl()) {
+      this.killEvent(ev);
     }
-    if (ev) {
-      ev.preventDefault();
-    }
+
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb/new_common/views/pagination/view.js]: :+1:  ojete :)

**Comment by xavijam** [comment]
:+1:

File: lib/assets/javascripts/cartodb/new_common/views/pagination/view.js (hunk 1 above)
Comment (viddo) [inline lib/assets/javascripts/cartodb/new_common/views/pagination/view.js]: ojete?

Comment (xavijam) [inline lib/assets/javascripts/cartodb/new_common/views/pagination/view.js]: ojete in @cartodb team === good
cc @kartones.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2219/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2220/))
