### PR TITLE
Skip layer after_added_to_map callback for in-memory operations

### LINKED ISSUE #12459: [Model refactor] Remove Visualization::Member usage from CommonDataService
### Steps to Reproduce

1. Create a new user.

### Current Result

There are `SELECT * FROM "maps" WHERE ("id" IS NULL) LIMIT 1` queries in the trace. Those queries are harmful from a performance perspective.

### Expected result

That query is not run (as it's not needed).

### Additional notes

This is caused by methods at `Visualization::Member`, such as `validate?` or `do_store`.

### LINKED ISSUE #12473: Vizjson regeneration touches user DB
### Context

CartoDB/oncall/issues/45

Is this trace really needed? Shouldn't an existing visualization be regenerable without the need of reaching user DB?

```
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/config/initializers/zz_patch_reconnect.rb:32:in `execute'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:333:in `affected_table_names'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:37:in `tables_from_query'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:18:in `block in affected_tables'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:17:in `map'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:17:in `affected_tables'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:241:in `register_table_dependencies'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/layer.rb:294:in `after_added_to_map'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_association.rb:507:in `block in callback'



….



  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/visualization.rb:500:in `block in populate_ids'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb:91:in `each'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb:91:in `each_with_index'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/visualization.rb:495:in `populate_ids'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/mapcap.rb:31:in `regenerate_visualization'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/models/carto/visualization.rb:510:in `for_presentation'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/controllers/carto/builder/public/embeds_controller.rb:105:in `visualization_for_presentation'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/controllers/carto/builder/public/embeds_controller.rb:71:in `load_vizjson'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:562:in `block in _run__2580254839828980911__process_action__4380531090709114371__callbacks'
  /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_2251'
  /home/ubuntu/www/production.cartodb.com/releases/20170713150350/app/controllers/application_controller.rb:101:in `wrap_in_profiler'
```

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #12473 and #12471.

Notes for acceptance: this might affect layer ordering and the detection of table <-> layer dependency (so, deletion of a table might not be detected as a conflict on a map).

### CODE REVIEW

**Comment by juanignaciosl** [comment]
In addition to the normal CR, I'd like @gfiorav wise 👀  on this, as he's the MaMa (Mapcap Master).

File: app/models/carto/layer.rb [hunk 1]
```diff
@@ -290,6 +292,9 @@ def uses_private_tables?
     end
 
     def after_added_to_map(map)
+      # This avoids unnecessary operations for in-memory logic. Example: Mapcap recreation. See #12473.
+      return unless map.persisted?
+
       set_default_order(map)
```
Comment (gfiorav) [inline app/models/carto/layer.rb]: I understand that `register_table_dependencies` is persistence oriented, but what about `set_default_order(map)`?

Could you explain what this method does and if it alters the layer's order? I'm asking because that might be nice to have in the mapcap as well.

File: spec/models/carto/mapcap_spec.rb [hunk 2]
```diff
@@ -104,29 +104,53 @@
   describe '#regenerate_visualization' do
     before(:all) do
       @mapcap = Carto::Mapcap.create!(visualization_id: @visualization.id)
```
Comment (gfiorav) [inline spec/models/carto/mapcap_spec.rb]: I'm curious as to why you removed the before all regeneration? The tests in this suite only need one mapcap. Is it a new "caution" principle? I agree with it, I just want to make sure there's nothing more (if it failed with a single mapcap creation something is off).

File: spec/models/carto/mapcap_spec.rb [hunk 3]
```diff
@@ -104,29 +104,53 @@
...
+      after(:all) do
+        @user_nodb.update_attribute(:database_name, @actual_db_name)
+        destroy_full_visualization(@map_nodb, @table_nodb, @table_visualization_nodb, @visualization_nodb)
+        @user_nodb.destroy
+      end
+
+      it 'should work' do
+        CartoDB::Logger.expects(:warning).never
+        @mapcap_nodb.regenerate_visualization
+      end
```
Comment (gfiorav) [inline spec/models/carto/mapcap_spec.rb]: It'd suggest that you set an expectation on the user db object to verify it is never used, rather than on the logger.

It feels weird to expect on the logger!

File: spec/models/carto/mapcap_spec.rb [hunk 4]
```diff
@@ -135,20 +159,24 @@
...
         @carto_layer.destroy
         @visualization.reload
-        @regenerated_visualization = nil
       end
 
       it 'should contain same layers in same order' do
-        @regenerated_visualization.layers.each_with_index do |layer, index|
-          layer.id == @regenerated_visualization.layers[index].id
+        CartoDB::Logger.expects(:warning).never
+        User.any_instance.stubs(:in_database).raises("Mapcap regeneration shouldn't touch user database")
```
Comment (gfiorav) [inline spec/models/carto/mapcap_spec.rb]: My previous comment was towards using something like this instead!

File: spec/models/carto/mapcap_spec.rb [hunk 5]
```diff
@@ -135,20 +159,24 @@
...
+        Carto::User.any_instance.stubs(:in_database).raises("Mapcap regeneration shouldn't touch user database")
+        regenerated_visualization = @mapcap.regenerate_visualization
+        regenerated_visualization.layers.each_with_index do |layer, index|
+          layer.id == regenerated_visualization.layers[index].id
         end
+        Carto::User.any_instance.unstub(:in_database)
+        User.any_instance.unstub(:in_database)
```
Comment (gfiorav) [inline spec/models/carto/mapcap_spec.rb]: Now that I think about it and since it's a global requirement with mapcaps:

Why not do a global before each expectation of user db not being touched? That way you test that any of the actions performed on this suite (which ideally englobe all the possible actions with mapcaps) are user db safe.

File: spec/models/carto/mapcap_spec.rb [hunk 6]
```diff
@@ -135,20 +159,24 @@
...
 
       it 'should contain same layers in same order' do
-        @regenerated_visualization.layers.each_with_index do |layer, index|
-          layer.id == @regenerated_visualization.layers[index].id
+        CartoDB::Logger.expects(:warning).never
+        User.any_instance.stubs(:in_database).raises("Mapcap regeneration shouldn't touch user database")
+        Carto::User.any_instance.stubs(:in_database).raises("Mapcap regeneration shouldn't touch user database")
+        regenerated_visualization = @mapcap.regenerate_visualization
+        regenerated_visualization.layers.each_with_index do |layer, index|
+          layer.id == regenerated_visualization.layers[index].id
```
Comment (mayoral) [inline spec/models/carto/mapcap_spec.rb]: Can we convert this to `expect(layer.id).to eq(regenerated_visualization.layers[index].id)`?

**Comment by juanignaciosl** [comment]
@mayoral don't do acceptance until we get @gfiorav 's 👍

File: app/models/carto/layer.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: It sets `layer.order`. For persisted maps it will be set, as usual. If map is not persisted, so we're working in memory, we must be working with previously persisted data, so order must be already ok. In some way, you only want to set the order when you first add a layer, or when you change it. There's no point on constantly recalculating it, I think.

I also had mixed feelings about it, but there are tests covering this and my manual tests also worked, so I chose to go :psycho: on this. As the whole callback seems thought for "first addition" scenario, it makes sense.

File: spec/models/carto/mapcap_spec.rb (hunk 2 above)
Comment (juanignaciosl) [inline spec/models/carto/mapcap_spec.rb]: The system under test should always be at the test itself, not at the preparation, mostly for readability reasons. As we're checking regeneration, it should be run in the test. I realized it when adding a new test that was slightly different was harder to me.

As the overhead of regenerating a visualization is low, keeping it at the test is clearer.

File: spec/models/carto/mapcap_spec.rb (hunk 3 above)
Comment (juanignaciosl) [inline spec/models/carto/mapcap_spec.rb]: You're right. I'll add `User.any_instance.expects(:in_database).never`. 👍 

I'll keep the warning level as well, to be safer (there's a legit rescue swallowing errors, I prefer having a double check on this, if you don't mind).

File: spec/models/carto/mapcap_spec.rb (hunk 5 above)
Comment (juanignaciosl) [inline spec/models/carto/mapcap_spec.rb]: Because other test code, such as table creation or data cleanup, need it, so I prefer making tests only fail because of one reason this time.

File: spec/models/carto/mapcap_spec.rb (hunk 6 above)
Comment (juanignaciosl) [inline spec/models/carto/mapcap_spec.rb]: Good catch! I think that this wasn't testing anything!

File: app/models/carto/layer.rb (hunk 1 above)
Comment (gfiorav) [inline app/models/carto/layer.rb]: Interesting!

One last thought:

Why don't you just avoid calling the method?

```ruby
after_added_to_map(map) unless map.persisted?
```

Seems like the right place to do this. Furthermore, I'd rename this method to reflect it's enacting strictly on persisted maps. That might help making the intent of this flow more glanceable

Comment (juanignaciosl) [inline app/models/carto/layer.rb]: You can't add the check outside because it's called from several places, some of them outside `Layer`, and clients shouldn't be aware of this.

I wouldn't rename it, though, because that's an implementation detail that is not a concern of the callers. This happens to be "maintenance on a layer that has just been added to a map". In fact, maybe the order, as you suggested, might make sense on both cases. Or maybe in the future some additional maintenance is needed here for in-memory models.

**Comment by gfiorav** [comment]
Thanks for the comments. Definitely :+1:
