### PR TITLE
Quantification migration #8036

### LINKED ISSUE #8036: Migration of bubble maps is broken when using "quantile" agg method
in the builder it is quantiles

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #8036.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino CR this, please.

File: spec/requests/carto/api/layer_presenter_spec.rb [hunk 1]
```diff
@@ -301,7 +301,8 @@ def build_layer_with_wizard_properties(properties)
 
       describe 'bubble' do
         let(:property) { "actor_foll" }
-        let(:qfunction) { "Quantile" }
+        let(:quantile_function) { "Quantile" }
+        let(:qfunction) { quantile_function }
```
Comment (javitonino) [inline spec/requests/carto/api/layer_presenter_spec.rb]: Why this split? `quantile_function` is not used anywhere than I can see.

**Comment by javitonino** [comment]
:+1: Left a minor comment about specs.

File: spec/requests/carto/api/layer_presenter_spec.rb (hunk 1 above)
Comment (juanignaciosl) [inline spec/requests/carto/api/layer_presenter_spec.rb]: I extracted it because it's a value with an specific check within the tests, but in the end I didn't see the need for using it. I can keep it or undo it if you think it's confusing, as you wish.
