### PR TITLE
PG::Error: ERROR: column visualizations.mapviews does not exist

### LINKED ISSUE #3608: PG::Error: ERROR: column visualizations.mapviews does not exist
Steps to reproduce:

1. Go to dashboard
1. Order by "visits"

Expected results: List ordered by map views
Actual results: 500 server-side error (see title)

E.g. https://rollbar.com/vizzuality/CartoDB/items/5816/ for more info etc.

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #3608

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3691/))

File: app/models/carto/visualization.rb [hunk 1]
```diff
@@ -42,6 +42,10 @@ class Carto::Visualization < ActiveRecord::Base
   PRIVACY_LINK = 'link'
   PRIVACY_PROTECTED = 'password'
 
+  def size
+    table.size
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: I don't know whether you've already talked about this, but I'd want @rafatower to know that we've agreed banning [train wrecks](http://c2.com/cgi/wiki?TrainWreck).

File: app/queries/carto/offdatabase_query_adapter.rb [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    def results
+      @results ||= get_results
+    end
+
+    def get_results
+      all = @query.all
+      @order_by_asc_or_desc_by_attribute.each { |attribute, asc_or_desc|
+        # Cache attribute type
+        unless all.count == 0
+          @is_array = all.first.send(attribute).is_a?(Array)
```
Comment (juanignaciosl) [inline app/queries/carto/offdatabase_query_adapter.rb]: `is_array` is only used in this method, it shouldn't be an instance variable.

File: app/models/carto/visualization.rb (hunk 1 above)
Comment (Kartones) [inline app/models/carto/visualization.rb]: Well, I wouldn't directly ban them, but here the benefit is clear, as helps easing the ordering, etc.).

I can add a comment explaining the specific usage, though

File: app/queries/carto/offdatabase_query_adapter.rb [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+        end
+        all = all.sort { |x, y|
+          x_attribute = x.send(attribute)
```
Comment (juanignaciosl) [inline app/queries/carto/offdatabase_query_adapter.rb]: I'd prefer ternary here (array attributes will always do a useless assignment), but it's a matter of taste.

Comment (juanignaciosl) [inline app/queries/carto/offdatabase_query_adapter.rb]: Just to be sure: this means that if you tell the wrapper to sort by an association it'll sort by the size of the association collection, isn't it?

File: app/queries/carto/offdatabase_query_adapter.rb (hunk 2 above)
Comment (Kartones) [inline app/queries/carto/offdatabase_query_adapter.rb]: true, as I undid some changes I forgot to set it as a normal variable

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3694/))

File: app/queries/carto/offdatabase_query_adapter.rb (hunk 3 above)
Comment (Kartones) [inline app/queries/carto/offdatabase_query_adapter.rb]: yes, I'll add a note there too

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3696/))

File: app/models/carto/visualization.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Nonono, no need for a comment. I'd ban it and write it in the styleguide, with a punishment for offenders :smiling_imp:

File: app/queries/carto/offdatabase_query_adapter.rb (hunk 3 above)
Comment (juanignaciosl) [inline app/queries/carto/offdatabase_query_adapter.rb]: I hadn't seen that convention (ordering by association == ordering by association_size), but it might be useful and I see no conflict with other conventions :+1:

**Comment by juanignaciosl** [comment]
:+1:
