### PR TITLE
fix oauth migrations

### LINKED ISSUE #14600: [OAuth] User migration after OAuth create tables
Check if user migration still works (it should) or fix it.

- On the other hand, since we are creating a new role for ownership tracking, we should manually fix the current `oauth_app_users` so that they have this new role. See [this piece of code](https://github.com/CartoDB/cartodb/blob/master/services/user-mover/import_user.rb#L506-L528)
- ~Also update the `cdb_conf_info` with the ownership_role for every oauth api_key~ <- not needed since no one is using the `schemas:c` grant on their api keys.

### PR DESCRIPTION
**Pull request by alrocar**
Closes #14600

**NOTE**: After this is merged we need to execute the `create_ownership_role` in the `oauth.rake`

### CODE REVIEW

File: app/models/carto/api_key.rb [hunk 1]
```diff
@@ -581,6 +581,7 @@ def db_run(query, connection = db_connection)
       connection.execute(query)
     rescue ActiveRecord::StatementInvalid => e
       CartoDB::Logger.warning(message: 'Error running SQL command', exception: e)
+      return if e.message =~ /OWNED BY/ # role might not exist becuase it has been already dropped
```
Comment (ethervoid) [inline app/models/carto/api_key.rb]: Why are we silencing the owned by errors?

File: app/models/carto/user_db_service.rb [hunk 2]
```diff
@@ -150,6 +150,17 @@ def all_schemas_granted_hashed(role = nil)
...
 
+    def exists_role?(rolname)
+      query = %{
+        SELECT 1
+        FROM   pg_catalog.pg_roles
+        WHERE  rolname = '#{rolname}'
+      }
+
+      result = @user.in_database(as: :superuser).execute(query)
+      result&.count > 0
```
Comment (ethervoid) [inline app/models/carto/user_db_service.rb]: Shouldn't be just result.count without &?

File: services/user-mover/export_user.rb [hunk 3]
```diff
@@ -211,7 +211,7 @@ def dump_user_metadata
       end
 
       def dump_role_grants(role)
-        roles = user_pg_conn.exec("SELECT oid, rolname FROM pg_roles WHERE pg_has_role( '#{role}', oid, 'member') AND rolname not like 'carto_role_%';")
+        roles = user_pg_conn.exec("SELECT oid, rolname FROM pg_roles WHERE pg_has_role( '#{role}', oid, 'member') AND rolname not like 'carto_role_%' AND rolname not like 'carto_oauth_app_%';")
```
Comment (ethervoid) [inline services/user-mover/export_user.rb]: This query could be replaced by `SELECT oid, rolname FROM pg_roles WHERE pg_has_role( '#{role}', oid, 'member') AND rolname not similar to '(carto_role|carto_oauth_app_)_%'`

File: spec/requests/carto/api/public/oauth_apps_controller_spec.rb [hunk 4]
```diff
@@ -695,15 +695,28 @@
       end
     end
 
-    it 'returns 500 if there is an error reassigning owners' do
+    it 'returns 204 if role does not exist when reassigning' do
```
Comment (ethervoid) [inline spec/requests/carto/api/public/oauth_apps_controller_spec.rb]: Why are we returning 204 instead of 500?

File: app/models/carto/user_db_service.rb (hunk 2 above)
Comment (alrocar) [reply app/models/carto/user_db_service.rb]: Yes... I think we can remove the `&`

File: app/models/carto/api_key.rb (hunk 1 above)
Comment (alrocar) [reply app/models/carto/api_key.rb]: It was happening to me (at least in specs) that the code passed here twice. Second time, since the role didn't exist it was raising an error.

We do `DROP ROLE IF EXISTS` and catch errors for `role already exists` in other places, so I guess it could be fine ignoring these errors as well.

What do you think?

File: spec/requests/carto/api/public/oauth_apps_controller_spec.rb (hunk 4 above)
Comment (alrocar) [reply spec/requests/carto/api/public/oauth_apps_controller_spec.rb]: Because of ignoring the `REASSIGN OWNED BY` errors.

File: app/models/carto/api_key.rb (hunk 1 above)
Comment (ethervoid) [reply app/models/carto/api_key.rb]: Maybe we could add a debug trace to follow up this in case we're missing something (you know, I'm a bit :chicken: )

Comment (alrocar) [reply app/models/carto/api_key.rb]: You mean besides the `warning` just above? (not sure I'm following you).

Comment (ethervoid) [reply app/models/carto/api_key.rb]: I'm a bit blind yes :rofl:

Comment (alrocar) [reply app/models/carto/api_key.rb]: 😅

**Comment by gonzaloriestra** [comment]
:heavy_check_mark: Acceptance OK

Succesfully migrated a user with OAuth app, granted app and OAuth api key.

**Comment by gonzaloriestra** [comment]
retest this please
