### PR TITLE
[popups] custom, fix change select

### LINKED ISSUE #8228: [popups] when select none template it launches custom
/cc @nobuti

### PR DESCRIPTION
**Pull request by matallo**
close #8228 

better use methods in the definition model than string checks (I should have spotted this in the review), the empty template name wasn't quite right as that can perfectly be a select option; the custom template is empty template name and template not empty

also, I removed that _wrong_ code as with the last mirgation we're not exposing that `table/views/infowindow_light` anymore (copying @juanignaciosl to confirm)

CR @nobuti /cc @juanignaciosl

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/data/infowindow-definition-model.js [hunk 1]
```diff
@@ -178,8 +178,8 @@ module.exports = Backbone.Model.extend({
     return this.get('template_name') && this.TEMPLATES[this.get('template_name')];
   },
 
-  wrongTemplate: function () {
-    return this.get('template_name') && !this.TEMPLATES[this.get('template_name')];
+  isCustomTemplate: function () {
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/data/infowindow-definition-model.js]: ❤️

**Comment by nobuti** [comment]
👍

**Comment by juanignaciosl** [comment]
@matallo [migration replaces `table/views/infowindow_light` with `infowindow_light`](https://github.com/CartoDB/cartodb/blob/33750dd4e6e3c1f72f04994f16c22fd338f02154/app/controllers/carto/api/infowindow_migrator.rb#L56). If this only affects the builder it _should_ be true, but please try it, as I've seen some unexpected behaviour around infowindows (for example, editor only displayed that path in the first assignment).
