### PR TITLE
Reduce visualization endpoint queries

### LINKED ISSUE #12058: Query for listing datasets and layers within an analysis node (for example) becomes slow when having +100 datasets (yours or shared with you)
### Context
As we keep expanding our accounts in big organizations we need to improve performance under some specific circumstances.

### Steps to Reproduce

1. Enter in an account with +100 datasets
2. Apply an analysis which requires a target node
3. Wait...

### Current Result
Query takes several seconds to load

### Expected result
The query should be fasta as a charm

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #12058

This also needs @CartoDB/frontend 👀  Please, could you take a look at the impact of the JS change? I'm not sure if this could break something.

Note: you can add test data to an account with this rake:

`$ RAILS_ENV=staging bundle exec rake cartodb:import['j-ded06','/home/ubuntu/www/production.cartodb.com/current/./spec/support/data/guess_country.csv',350]`

**Acceptance**

- Create an analysis including target node in a account with >300 datasets. Table listing shouldn't take longer than ~2s.
- Whatever frontend-savvy folks add to check that this doesn't break anything 😅 

^ I'd stress the importance of the 2nd point, as I'm not sure of the impact of the JS change.

### CODE REVIEW

File: lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js [hunk 1]
```diff
@@ -93,7 +93,18 @@ module.exports = Backbone.Model.extend({
 
   _fetchTables: function (queue) {
     queue.defer(function (cb) {
-      this._tablesCollection.fetch();
+      this._tablesCollection.fetch({
+        data: {
```
Comment (xavijam) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js]: Totally acceptable! 💃

Comment (xavijam) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js]: Maybe it sounds a bit "wtf", but could we add a test checking those params are added when it is fetched?

Comment (juanignaciosl) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js]: Uhm. IMHO, thats bounding test to implementation, so it doesn't adds too much value. Nevertheless, I must admit that I don't know how to properly test this without a proper integration test.

Comment (juanignaciosl) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js]: Uhm. IMHO, that's bounding test to implementation, so it doesn't add too much value. Nevertheless, I must admit that I don't know how to properly test this without a proper integration test.

File: app/controllers/carto/api/visualization_presenter.rb [hunk 2]
```diff
@@ -9,6 +9,9 @@ class VisualizationPresenter
       # options
       # - related: load related tables. Default: true.
       # - show_stats: load stats (daily mapview counts). Default: true.
+      # - show_likes: load likes info. Default: true.
+      # - show_liked: load liked info. Default: true.
+      # - show_table: load table info. Default: true.
```
Comment (javitonino) [inline app/controllers/carto/api/visualization_presenter.rb]: Maybe a good chance to get rid of this `options` hash and convert to proper keyword arguments. It's not too bad right now as it is documented, but still, it would be better to have it with keyword arguments. What do you think? Are you up for it?

File: spec/requests/carto/api/visualizations_controller_spec.rb [hunk 3]
```diff
@@ -368,6 +368,60 @@ def attributions_from_vizjson(visualization)
...
+        show_liked: false,
+        show_stats: false,
+        show_table: false,
+        show_permission: false,
+        show_synchronization: false,
+        show_uses_builder_features: false,
+        load_totals: false
+      }.freeze
+
+      it 'should improve with reduced fetching (see #12058)' do
```
Comment (javitonino) [inline spec/requests/carto/api/visualizations_controller_spec.rb]: Nice!

File: lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js (hunk 1 above)
Comment (juanignaciosl) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-source-options-model.js]: Done: https://github.com/CartoDB/cartodb/pull/12067/commits/fc8cd8abe801cc16925eeb27fbbb9e7c5136bec7

File: lib/assets/core/test/spec/cartodb3/editor/layers/layer-content-view/analyses/analysis-source-options-model.spec.js [hunk 4]
```diff
@@ -87,6 +87,23 @@ describe('cartodb3/editor/layers/layer-content-views/analyses/analysis-source-op
       this.model.fetch();
     });
 
+    it('should fetch tables reducing the data to be retrieved', function () {
```
Comment (xavijam) [inline lib/assets/core/test/spec/cartodb3/editor/layers/layer-content-view/analyses/analysis-source-options-model.spec.js]: MU RICO! Thanks!

**Comment by javitonino** [comment]
🤔 Found a weird thing. In production, this requests pages of 1000 visualizations. With this PR (in staging), it requests pages of 20 visualizations:

screenshot_20170505_183820

It is indeed faster (but it is cheating a lot, so how could it not, haha), and checked the dashboard and add layer dialogs for regressions, they seem to work ok.

Not giving the green light until the first point get clarified, not sure if it is on purpose or not (it doesn't look like it).

**Comment by javitonino** [comment]
Did a quick try in staging before CR. Times in staging for 341 datasets:
Before this PR 9s
After this PR 2.5s

**Comment by juanignaciosl** [comment]
Yup. Previously it was ~1 order of magnitude faster, but a JS error appeared if table is not loaded.

**Comment by javitonino** [comment]
Ok then. I think this is ready to go then. Maybe take a look at the last commit (even though it's trivial), but we should be good.

**Comment by juanignaciosl** [comment]
As this changes JS and I'm not aware of the scope of this kind of modification, I'd gentle ask for acceptance to any @CartoDB/frontend folk, as I mentioned earlier 🤗  .

**Comment by nobuti** [comment]
This works pretty well. I found what I thought it was an issue but in fact is the real behaviour: in the connect with line to target analysis, only the point datasets are shown. So when I tried with the find nearest analysis, the numbers didn't match. But like I said, this is the behaviour. So far, so good.
