### PR TITLE
Show title & error on analysis workflow tooltip

### LINKED ISSUE #12250: Problem with analysis tooltip and error
@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798)

Checking some behaviors with analyses, I've found this problem:

screen shot 2017-05-31 at 15 05 32

Should we remove the analysis-name tooltip when there is an error in the analysis node?

Assigning @arianaescobar because she opened the ticket in CartoDB repository 😬 
cc @rjimenezda @rubenmoya 

---

@arianaescobar commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305192214)

I'd say that's the fastest solution, yeah. 

But, just wondering, is it possible to "merge" both tooltips in a single one in those cases? Like "Centroid analysis failed"? 

---

@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305193780)

Sure!

---

@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305194033)

But take into account that the error could change and provide more info. It could be like:

`Centroid (A2): column whatever is not longer available`

What do you think?

---

@arianaescobar commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305196064)

Love it.

### PR DESCRIPTION
**Pull request by rubenmoya**
Fix #12250 

If there's an error, it shows the tooltip in red and combines the Analysis name & the error message.

tooltip_2

### CODE REVIEW

File: lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js [hunk 1]
```diff
@@ -41,6 +33,14 @@ module.exports = CoreView.extend({
     var isSelected = this._analysisNode.id === this._viewModel.get('selectedNodeId');
     var letter = nodeIds.letter(this._analysisNode.id);
     var bgColor = layerColors.getColorForLetter(letter);
+    var analysisTitle = Analyses.title(this._analysisNode.get('type') || '');
+    var tooltipTitle = analysisTitle;
+    var hasFailed = status === 'failed';
+
+    if (hasFailed) {
+      var message = NotificationErrorMessageHandler.extractErrorFromAnalysisNode(this.analysisNode);
```
Comment (nobuti) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: This is my monthly quota of "I don't like to define vars inside if block".  Also, as far I can see, `extractErrorFromAnalysisNode` already returns a string with `:` as part of the message key, so be careful with that.

File: lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js [hunk 2]
```diff
@@ -41,6 +33,16 @@ module.exports = CoreView.extend({
     var isSelected = this._analysisNode.id === this._viewModel.get('selectedNodeId');
     var letter = nodeIds.letter(this._analysisNode.id);
     var bgColor = layerColors.getColorForLetter(letter);
+    var analysisTitle = Analyses.title(this._analysisNode.get('type') || '');
+    var tooltipTitle = analysisTitle;
+    var hasFailed = status === 'failed';
+
+    if (hasFailed) {
+      var message = NotificationErrorMessageHandler.extractErrorFromAnalysisNode(this.analysisNode).message;
```
Comment (nobuti) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: `extractErrorFromAnalysisNode` method uses the locale `notifications.analysis.failed`, that is `Analysis %{nodeId} failed`. Then it concatenates this with the error message. I think we are only interested in the message, so I guess we should use the `extractError` method instead. Also, according to the issue's description, the message should be something like `Centroid (A2): column whatever is not longer available`. I miss the id here.

Comment (rubenmoya) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: We talked about the id, and decided not to put it in the message. About the error message you're right. Do you know any way to produce an error in an analysis to test this?

**Comment by rubenmoya** [comment]
Improved error message format, see updated gif in OP

File: lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js [hunk 3]
```diff
@@ -36,14 +36,14 @@ module.exports = CoreView.extend({
     var analysisTitle = Analyses.title(this._analysisNode.get('type') || '');
     var tooltipTitle = analysisTitle;
     var hasFailed = status === 'failed';
-
-    if (hasFailed) {
-      var message = NotificationErrorMessageHandler.extractErrorFromAnalysisNode(this.analysisNode).message;
-      if (message) {
-        tooltipTitle = analysisTitle + ': ' + message;
-      }
+    var error = this._analysisNode.get('error');
```
Comment (nobuti) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: We only need `errorMessage` if `hasFailed`, so I'd avoid the `extractError` call check by default:
```
var error;
var errorMessage;

if (hasFailed) {
    error = this._analysisNode.get('error');
    errorMessage = error && error.message && NotificationErrorMessageHandler.extractError(error.message);
    tooltipTitle = analysisTitle + ': ' + errorMessage.message;
}
```
what do you think?

Comment (rubenmoya) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: You're right, but what happens if `errorMessage.message` is an empty string or undefined? we'll end up with something like: `Georeference: ` or `Georeference: undefined`

Comment (nobuti) [inline lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js]: Right, we should check that case too.

**Comment by nobuti** [comment]
Picking this up to make the changes.

**Comment by nobuti** [comment]
What do you think about last changes @rubenmoya?

**Comment by rubenmoya** [comment]
I like that approach, pretty interesting!

**Comment by rubenmoya** [comment]
It works like a charm! ✨
