### PR TITLE
No request made to enable MFA

### LINKED ISSUE #14505: [MFA] no request made
### Context
Trying to enable MFA functionality.

### Steps to Reproduce

1. Go to /account view
2. Try and enable MFA
3. Click "Save"
4. Introduce your password

### Current Result
No requests get made. MFA does not get enabled.

screenshot from 2018-11-29 14-59-57

### Expected result
MFA gets enabled.

### Browser and version
Chromium Version 70.0.3538.77 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Additional info
If it is of any help, the feature was working in tag `4.23.0` https://github.com/CartoDB/cartodb/blob/master/NEWS.md#4230-2018-11-19

/cc @ivanmalagon @CartoDB/rt-managers

### PR DESCRIPTION
**Pull request by ivanmalagon**
Fixes #14505

### CODE REVIEW

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js [hunk 1]
```diff
@@ -47,32 +47,42 @@ NetworkResponseInterceptor.prototype._shouldListenToRequest = function (url) {
 };
 
 NetworkResponseInterceptor.prototype._onRequestStart = function (url, options) {
+  let requestUrl = null;
```
Comment (rjimenezda) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Do we have ES6 on builder now?

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js [hunk 2]
```diff
@@ -47,32 +47,42 @@ NetworkResponseInterceptor.prototype._shouldListenToRequest = function (url) {
...
+    requestOptions = url;
+  }
 
   if (!this._shouldListenToRequest(requestUrl)) {
     return this._originalAjax.apply(this, arguments);
   }
 
-  const errorCallback = requestOptions.error;
-  const successCallback = requestOptions.success;
+  if (requestOptions && requestOptions.error && requestOptions.success) {
```
Comment (rjimenezda) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Does it make sense to split this?

Otherwise if you have success, but no error, this doesn't happen.

Comment (jesusbotella) [inline lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: My only concern is that requests have to have both callbacks. I've reviewed Backbone ones and they do, but just in case 🤷‍♂️

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js (hunk 1 above)
Comment (jesusbotella) [reply lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: Yes, we do 😂

File: lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js (hunk 2 above)
Comment (ivanmalagon) [reply lib/assets/javascripts/builder/data/backbone/network-interceptors/interceptor.js]: I removed the conditional.

It was for the calls that don't have those properties but that ìf` prevented then from triggering the interception.

I'm going to test it in acceptance.
