### PR TITLE
Fixed problem related with operator component + tests

### LINKED ISSUE #9599: Aggregation selection component doesn't let apply changes until changing the selected column
STR

- Aggregate by square for example
- Click on SUM(cartodb_id)
- Click on AVG(cartodb_id) - You cannot as cartodb_id is already selected.

### PR DESCRIPTION
**Pull request by xavijam**
Fixed problems identified with custom operator component.

operator

Fixes #9599.

CR: @nobuti

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js [hunk 1]
```diff
@@ -22,50 +23,49 @@ Backbone.Form.editors.Operators = Backbone.Form.editors.Base.extend({
...
   _initViews: function () {
     var value = this.model.get(this.options.keyAttr);
-    this.$el.html(
-      template({
-        name: this._getOperatorsTextValue(),
-        disabled: this.options.disabled,
-        keyAttr: this.options.keyAttr
-      })
+
+    this.$el.append(
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: Should not be this in the template somehow?

Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: No, because the template changes the "input"/button. So, if there is any change over the values, we only need to run `_setOperatorTemplate` method and 💫 .

File: lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js [hunk 2]
```diff
@@ -22,50 +23,49 @@ Backbone.Form.editors.Operators = Backbone.Form.editors.Base.extend({
...
-      }
-    );
-
-    var optionsCollection = opts.schema && opts.schema.options || opts.options || [];
-    this.collection = new OperatorListCollection(optionsCollection);
-    this.setValue(this.model.get(this.options.keyAttr));
     Backbone.Form.editors.Base.prototype.initialize.call(this, opts);
+    this._setOptions(opts);
+
+    this.collection = new OperatorListCollection(this.options.options);
```
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: `this.options.options` it's weird, could be `opts.options` better?

File: lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js (hunk 1 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: Basically, if we include that in the template, we would need to overwritten template each time the vulues change, and that would destroy the list view.

File: lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js (hunk 2 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: Uhm... not really, if not an alone field will not work (using it in a form yes). We use that for the select view and it is inherited from the base.js view.

Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/form-components/editors/operators/operators-view.js]: And yes, it is weird, I should fix it for any component that needs a list :(.

**Comment by nobuti** [comment]
👏  🇪🇸
