### PR TITLE
11217 visualization listing slow

### LINKED ISSUE #11217: Visualization listing endpoint is slow
### Context
When adding an analysis like merge layers, a request is made to retrieve all datasets from the user. That request is slow (~10s) in accounts with many datasets. This request is made pretty often from frontend, in some case unnecessarily (see #11218).

### Steps to Reproduce
1. Create a map
2. Add an intersect second layer analysis

### Current Result
Slow request: `api/v1/viz?type=table&order=updated_at&page=1&per_page=1000&exclude_shared=false&exclude_raster=true&tags=&q=`

### Expected result
Make it fly! (if possible)

### PR DESCRIPTION
**Pull request by javitonino**
Closes #11217 

This improves the performance in visualization controller index by almost 50%. A summary of the changes:
- Prefetch synchronizations
- Do not check for builder features (costly as it loads widgets, analyses and mapcaps) if the visualization version is 3 (see `uses_builder_features?`)
- Adds `inverse_of` to the relations between Visualizations, Maps and UserTables

A quick explanation of `inverse_of`. This association attribute tells Rails that it can go back through the association without fetching again. For example: `visualization.map.visualization` would run a query for the visualization without `inverse_of`, but after adding it, it is not loaded (instead, the parent object is referenced).

To achieve this, I converted the Visualization<->Map and Map<->UserTable to `has_one` associations. Although the DB modelling allows for 1:N relations, that is not actually the way we use it. Also, the Visualization<->UserTable used to be a direct association, using Map as a `through` table. I changed that for helper methods in order to be able to use AR cache and `inverse_of` effectively.

All of this, reduces the number of queries needed to present a visualization from 11 to 3 (1 for table size and two for likes) for builder visualizations. Three extra queries are needed for non-builder visualizations (to check if it uses builder features nonetheless).

-----

**Acceptance**
Check the speed loading the dashboard and loading the list of tables in the builder (e.g: filter by layer analysis). We also need to do some quick smokes for common dashboard operations: creation/deleting/renaming visualizations and so on.

Additional acceptance note (@juanignaciosl): double check that deleting a dataset removes associated visualizations and vice versa. This kind of ORM mapping tuning might cause deletion propagation issues, as the order of the queries is likely to change. Check it at database level.

Synchronizations (creation, update at re-sync, un-sync, deletion)... might also be affected.

I'd encourage to base the acceptance on smoke test script. A lot of fine-grained Builder tests can be dropped, but many operations should be tested.

### CODE REVIEW

File: app/controllers/carto/api/visualization_presenter.rb [hunk 1]
```diff
@@ -60,18 +59,18 @@ def to_poro
           prev_id: @visualization.prev_id,
           next_id: @visualization.next_id,
           transition_options: @visualization.transition_options,
-          active_child: @visualization.active_child,
+          active_child: nil,
```
Comment (juanignaciosl) [inline app/controllers/carto/api/visualization_presenter.rb]: Isn't `active_child` used at all? :-\ It isn't a performance penalty as long as it's `null`, though.

File: app/controllers/carto/api/visualization_presenter.rb [hunk 2]
```diff
@@ -60,18 +59,18 @@ def to_poro
...
           table: user_table_presentation,
           external_source: Carto::Api::ExternalSourcePresenter.new(@visualization.external_source).to_poro,
           synchronization: Carto::Api::SynchronizationPresenter.new(@visualization.synchronization).to_poro,
-          children: @visualization.children.map { |v| children_poro(v) },
+          children: [],
```
Comment (juanignaciosl) [inline app/controllers/carto/api/visualization_presenter.rb]: Same here: I'm not sure about removing this. If it's not a performance penalty, I'd keep it. If we want to remove the deprecated functionality, let's remove the whole property, just setting it to null is confusing.

File: app/models/carto/visualization.rb [hunk 3]
```diff
@@ -106,6 +102,11 @@ def tags=(tags)
     super(tags)
   end
 
+  def user_table
+    map.user_table if map
+  end
+  alias :table :user_table
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: This is a safety measure and to make this consistent with `Visualization::Member`, isn't it?

File: app/models/carto/map.rb [hunk 4]
```diff
@@ -105,7 +106,7 @@ def view_bounds_data
   end
 
   def writable_by_user?(user)
-    visualizations.select { |v| v.writable_by?(user) }.any?
+    visualization.writable_by?(user)
```
Comment (juanignaciosl) [inline app/models/carto/map.rb]: _I know that you spoke about the n-arity change in the PR, I just want to stress and comment it_.

This is a nice decision. It enables optimizations at ORM level, which is a application-wide performance boost, and the relational model underneath is "wrong", in the sense that the cardinality is broader, more flexible than actually needed and used. I'm a little worried about the change, as it might lead to unexpected errors. I'd write down a reduced smoke script for this. Specially, taking into account that this involves permission checks, with are used in many places (sharing, public pages, shared dashboard loads...).

In addition, `inverse_of` is not only convenient but needed: ORMs need them to be able to propagate actions successfully. If `inverse_of` are missing, some operations won't work ok.

Despite the risk and the need for thorough testing, I think that this is a great, non-trivial, non-obvious decision 💪 👏  The repeated usage of `.first` was a clear smell and reinforces this change.

Pinging @gfiorav about this CR, just in case he wants to add something. Anyway, he should be aware of this change if he's not.

File: app/models/carto/visualization.rb [hunk 5]
```diff
@@ -404,7 +405,7 @@ def latest_mapcap
   end
 
   def uses_builder_features?
-    analyses.any? || widgets.any? || mapcapped?
+    builder? || analyses.any? || widgets.any? || mapcapped?
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: This is used by the frontend to display a warning about opening it "backwards" (in the editor). This is likely to be even better than before, probably coded back when `builder?` couldn't be explicitly checked.

File: app/services/carto/visualizations_export_persistence_service.rb [hunk 6]
```diff
@@ -27,9 +27,6 @@ def save_import(user, visualization, renamed_tables: {})
 
         map = visualization.map
         map.user = user
-        unless map.save
```
Comment (juanignaciosl) [inline app/services/carto/visualizations_export_persistence_service.rb]: How come isn't this needed anymore?

File: spec/queries/carto/visualization_query_builder_spec.rb [hunk 7]
```diff
@@ -66,12 +66,15 @@
   it 'can prefetch table' do
     table1 = create_random_table(@user1)
 
+    # To preload AR table metadata
```
Comment (juanignaciosl) [inline spec/queries/carto/visualization_query_builder_spec.rb]: _Minor_: instead of adding a comment, a method called `preload_activerecord_table_metadata` would be informative, reusable and even hides implementation details.

File: app/controllers/carto/api/visualization_presenter.rb (hunk 1 above)
Comment (javitonino) [inline app/controllers/carto/api/visualization_presenter.rb]: Nope. This is part of odyssey, which we could remove https://github.com/CartoDB/cartodb/issues/7677. This change is actually not needed (as it is a plain field), but I added it to avoid inconsistency with the next one (more in that comment).

File: app/controllers/carto/api/visualization_presenter.rb (hunk 2 above)
Comment (javitonino) [inline app/controllers/carto/api/visualization_presenter.rb]: This is a performance penalty. It adds a `SELECT * FROM visualizations WHERE parent_id = <id>` to each visualization presentation. It's no longer used (part of odyssey) so I just removed it. I left it in the presenter just in case, for compatibility with JS although I'm pretty sure it doesn't matter, but I didn't want to complicate this.

File: app/models/carto/visualization.rb (hunk 3 above)
Comment (javitonino) [inline app/models/carto/visualization.rb]: Exactly. I tried removing it at first and changed the references in the code. But it is still used in some templates that can receive either Visualization model, so I had to add it back for compatibility.

File: app/models/carto/visualization.rb (hunk 5 above)
Comment (javitonino) [inline app/models/carto/visualization.rb]: Yes. It should be a bit better to add the builder check (aside from a performance gain). We almost can remove the rest of the check, but there could still be some visualizations that are version 2 but have builder features from the transition period, so I kept this for safety, and to keep things simple.

File: app/services/carto/visualizations_export_persistence_service.rb (hunk 6 above)
Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: It's due to the addition of the map.visualization relation. `has_one` relations have autosave by default, so saving the map saves everything (autosave on inserts but not on updates, to be more exact. See http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html)
> Note that autosave: false is not same as not declaring :autosave. When the :autosave option is not present then new association records are saved but the updated association records are not saved.

This was causing issues as this save is happening before setting up everything (in this case, the analysis.user was nil) and it breaks. I tried moving it down, but it turns out that this is not needed, since the visualization.save will take care of everything.

File: app/controllers/carto/api/visualization_presenter.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/visualization_presenter.rb]: Ok, both agreed. What do you think about adding a comment making this clear?

File: app/services/carto/visualizations_export_persistence_service.rb (hunk 6 above)
Comment (juanignaciosl) [inline app/services/carto/visualizations_export_persistence_service.rb]: Uhm. As you say, it's not saved on update. In addition, later on this method there's a 

```ruby
visualization_member = CartoDB::Visualization::Member.new(id: visualization.id).fetch
visualization_member.store
```

Doesn't it make the `map.user = user` assignment to be dismissed?

Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: When this method is run, nothing is saved, so the visualization save triggers creation of all sub-entities, saving them. I double-checked, and indeed `map.user` is correctly set and saved.

Regarding the trick using visualization member, that is only there to trigger invalidations/named maps update. It is executed after the visualization is saved. This is probably not needed anymore, since more and more of the new models trigger those invalidations, but I think it's better left for another occasion.

**Comment by juanignaciosl** [comment]
Let's move this to acceptance when tests are 🍏

**Comment by javitonino** [comment]
🍏 Moving to acceptance

**Comment by MariaCheca** [comment]
Acceptance passing 👍
