### PR TITLE
SQL query error message

### LINKED ISSUE #9497: Data panel doesn't change its state when sql query fails
I've checked that problem before, but I don't remember how to make it fail so, I've decided to reproduce it like:

## STR
1. Create a map with any layer, and go to the builder.
2. Once there, go to your dev environment and stop the SQL API (fast and easy instead of looking for a new way of making it fail).
3. Go back to the builder UI.
4. Click over one layer, and check that panel doesn't change its state. It should show an error message and the loading should be hidden.

screen shot 2016-08-22 at 11 41 30

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #9497 and #9475.

I added a direct link to the message, so the user can easily access to the sql editor to fix the query. Please @urbanphes @saleiva confirm this is ok.

Also, in order to reduce the noise about notifications, we make the error notification fixed (not closable), so when the user changes the active tab, the notification remains with the error to add some context.

sql-error

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
If we do so (perfect for me), let's disable CartoCSS buttons in style panel.

**Comment by nobuti** [comment]
sql-error-disable

**Comment by nobuti** [comment]
btw in ded06

File: lib/assets/javascripts/cartodb3/editor/style/style-content-view.js [hunk 1]
```diff
@@ -1,12 +1,23 @@
...
 var StyleFormView = require('./style-form/style-form-view');
 var StylesFactory = require('./styles-factory');
 var CarouselFormView = require('../../components/carousel-form-view');
 var CarouselCollection = require('../../components/custom-carousel/custom-carousel-collection');
 var styleFormNotReadyTemplate = require('./style-form-not-ready.tpl');
+var styleSQLErrorTemplate = require('./style-content-sql-error.tpl');
 var OverlayView = require('../components/overlay/overlay-view');
 var Notifier = require('../../components/notifier/notifier');
+var QuerySanity = require('../layers/query-sanity-check');
+var ACTION_ERROR_TEMPLATE = _.template("<button class='CDB-Text u-actionTextColor js-fix-sql'><%- label %></button>");
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/style/style-content-view.js]: Why not using a .tpl?

File: lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/data/data-view.js [hunk 2]
```diff
@@ -393,6 +404,10 @@ module.exports = CoreView.extend({
 
     this.$el.append(panelWithOptionsView.render().el);
     this.addView(panelWithOptionsView);
+
+    // If there are errors in the SQL, open the sql editor by default
+    // we defer it to not interfere with the high order tabpane item selection
+    setTimeout(this._redirectIfErrors.bind(this), 0);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/data/data-view.js]: 😱  but 👌

**Comment by xavijam** [comment]
Not much to say, perfect! 💋

File: lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/data/data-view.js (hunk 2 above)
Comment (nobuti) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/data/data-view.js]: Agree, I need to investigate a better way of doing this kind of things because it's really ugly. Bu at the time, I don't know how to solve it. Even with that, I think the final result is not totally good.
