### PR TITLE
11142 saml username collision

### LINKED ISSUE #11142: SAML username collision workaround
### Context

Organization with SAML authentication.

_Edit by gfiorav: You must have an existing user, whose username is the result of `CartoDB::UserAccountCreator.email_to_username(email)` with the new user's email. This will provoke the collision._

### Steps to Reproduce

1. Attempt your first login with a SAML user.
2. CARTO will try to autocreate the user within the organization (see #11073).

### Current Result

"Signup issues: username is already taken" error.

### Expected result

Allow picking a different username.

### Additional info

Current solution (crashing) is good enough for onpremise (both LDAP and SAML) environments. Nevertheless it's not for SaaS (#11108).

This is somehow related to #11087, although a workaround for collisions is a must.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #11142

## Context

When a SAML user creates an account in CARTO, her CARTO username is inferred from her SAML email. This gives way to the following scenario:

A SAML user's email, when converted to a username, corresponds another already existent user in CARTO. We call this a username collision. 

This PR introduces a patch that checks if the inferred username is available and if not looks for a variation that is available.

## Acceptance

You should have a SAML server running in your machine and a user with a known email in it. Say this user's SAML email is `patata@carto.com`. You know have to create a user in your CARTO instance with username `patata`, so a collision is bound to happen. You also need to configure an organisation with SAML enabled.

Once this is set up, check that signing up with the SAML user yields in a CARTO account with name `patata-1`, hence the collision is avoided.

For SAML configuration, you can follow @javitonino 's nice GIST: https://gist.github.com/javitonino/416f2ac8b5ab4f978478d2475e48fb0d

### CODE REVIEW

**Comment by jorgesancha** [comment]
Nicely written PR @gfiorav. Useful context and acceptance specs :clap: :metal:

**Comment by javitonino** [comment]
Merging master into this after the GME test was fixed.

File: app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -95,16 +96,20 @@ def ldap_user_not_at_cartodb
...
 
-  # Meant to be called always from warden SAML authentication
-  def saml_user_not_at_cartodb
-    render action: 'new' and return unless verify_warden_failure
+  def saml_user_not_in_carto
+    # ensure to be called only from warden SAML authentication
+    unless verify_warden_failure
+      render action: 'new'
+      return
+    end
```
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: What about `return render(action: 'new') unless verify_warden_failure` instead? Or even extracting this to a filter, as it is shared with ldap.

File: app/controllers/sessions_controller.rb [hunk 2]
```diff
@@ -95,16 +96,20 @@ def ldap_user_not_at_cartodb
     create_user(username, organization_id, email, created_via)
   end
 
-  # Meant to be called always from warden SAML authentication
-  def saml_user_not_at_cartodb
-    render action: 'new' and return unless verify_warden_failure
+  def saml_user_not_in_carto
```
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: Nice name change ✨

File: app/controllers/sessions_controller.rb [hunk 3]
```diff
@@ -95,16 +96,20 @@ def ldap_user_not_at_cartodb
...
+    unless verify_warden_failure
+      render action: 'new'
+      return
+    end
 
-    email = warden.env['warden.options'][:saml_email]
-    username = CartoDB::UserAccountCreator.email_to_username(email)
+    saml_email = warden.env['warden.options'][:saml_email]
+    username = CartoDB::UserAccountCreator.email_to_username(saml_email)
+    unique_username = Carto::UsernameFinder.find_unique(username)
```
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: This can be problematic in multi-cloud systems, but we already have a comment telling us to review this in the SAML for SaaS issue, so 👍

File: config/initializers/warden.rb [hunk 4]
```diff
@@ -230,7 +230,10 @@ def authenticate!
         fail!
       end
     else
-      throw(:warden, action: 'saml_user_not_at_cartodb', organization_id: organization.id, saml_email: email)
+      throw(:warden,
+            action: 'saml_user_not_in_carto',
+            organization_id: organization.id,
+            saml_email: email)
```
Comment (javitonino) [inline config/initializers/warden.rb]: I don't like this split too much, as it is not too long in a single line, and if we split each parameter into a single line it takes 4 lines.

Anyway, old discussion, keep it this way if you prefer it.

File: spec/models/carto/username_finder_spec.rb [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+  describe UsernameFinder do
+    describe '#find_unique' do
+      before(:all) do
+        @users = Array.new
+        @users << FactoryGirl.create(:carto_user, username: 'manolo')
+        @users << FactoryGirl.create(:carto_user, username: 'manolo-1')
+      end
+
+      after(:all) do
+        @users.map(&:destroy)
```
Comment (javitonino) [inline spec/models/carto/username_finder_spec.rb]: `.each` if you don't care about the return. I am having a déjà vu about this one; IIRC we tested `.each` and it worked.

File: lib/carto/username_finder.rb [hunk 6]
```diff
@@ -0,0 +1,16 @@
+# encoding: utf-8
+
+module Carto
+  class UsernameFinder
```
Comment (javitonino) [inline lib/carto/username_finder.rb]: Maybe `UsernameProposer` so it's more similar to `TableNameProposer`?

File: app/controllers/sessions_controller.rb (hunk 1 above)
Comment (gfiorav) [inline app/controllers/sessions_controller.rb]: The thing is the `return`. I've assumed there's a good reason for it to be there.

**Comment by gfiorav** [comment]
Thanks @javitonino.

Answering to your question: In the case that 99 tries later, there's still no available name (i.e.; `patata`-> `patata-99` are taken) it would fail due to collision. We have to stop somewhere, I just chose 99.

**Comment by javitonino** [comment]
Question is, how does it fail? It is a clean failure, or a random 500?

File: config/initializers/warden.rb (hunk 4 above)
Comment (gfiorav) [inline config/initializers/warden.rb]: +100, so I hadda 

I will buy you beer whenever you decide to start drinking 🤗

File: app/controllers/sessions_controller.rb (hunk 1 above)
Comment (javitonino) [inline app/controllers/sessions_controller.rb]: The return is indeed needed, but is still in my alternative. The difference is that it returns whatever `render` returns, (the HTML), but it shouldn't matter, as all evidence points to Rails ignoring the return value from controllers.

**Comment by gfiorav** [comment]
It just returns a username, and that username will collide. The signup will fail with the standard validation issue.
