### PR TITLE
Validate widget form when widget type changes

### LINKED ISSUE #11536: Changing widget type to histogram doesn't show up the error field on column selector even if it's empty
### Steps to Reproduce

1. Add a formula widget 
2. Change type to histogram

### Current Result
Widget don't show anything because column input is not specified.

screen shot 2017-02-14 at 18 37 09

### Expected result
We should show an error status on that input, to show the user that if column is not selected, widget will not work. Another option is to select another _numeric_ column by default.

### PR DESCRIPTION
**Pull request by rubenmoya**
Fixes #11536

When we change the widget type, we're now validating the column type, if the column is not numeric, we show an error. It will prevent us from saving widgets with wrong data, for example, an histogram widget with a string column (it was happening before).

Thank you for the help! @ivanmalagon @rjimenezda

histogram_widget

I'm not sure about the copy for error message, right now it's `Column type must be %{type}`, what do you think @brittanymicek?

### CODE REVIEW

**Comment by rubenmoya** [comment]
Tests failing, back to develop

File: lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js [hunk 1]
```diff
@@ -37,7 +40,8 @@ module.exports = WidgetsFormBaseSchema.extend({
         dialogMode: 'float',
         editorAttrs: {
           disabled: this._columnOptionsFactory.areColumnsUnavailable()
-        }
+        },
+        validators: [this.validateColumnType]
```
Comment (ivanmalagon) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js]: We can set here `this.validateColumnType.bind(this)`, right? So we avoid binding the context in initialize.

File: lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js [hunk 2]
```diff
@@ -53,12 +57,20 @@ module.exports = WidgetsFormBaseSchema.extend({
...
 
+  validateColumnType: function (value, formValues) {
+    if (!this._columnOptionsFactory.isColumnOfType(value, NUMBER_TYPE)) {
+      return {
+        type: 'column',
+        message: _t('validations.only-numeric-column')
+      };
+    }
+  },
+
```
Comment (ivanmalagon) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js]: Can we make this in a helper function for reusability? It'd be great if we have this more visible as another validator for forms. It's likely that we can use it in more places in the future.

File: lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/widgets-form-column-options-factory.js [hunk 3]
```diff
@@ -41,4 +41,11 @@ F.prototype.create = function (currentVal, columnFilter) {
   }
 };
 
+F.prototype.isColumnOfType = function (columnName, type) {
+  var column = this._querySchemaModel.columnsCollection.findWhere({
+    name: columnName
+  });
+  return column && column.get('type') === type;
+};
+
```
Comment (ivanmalagon) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/widgets-form-column-options-factory.js]: I see here that the new validator above relies on this one, who is only for widgets.

Perhaps we can use another object than `_querySchemaModel` and pass to the validator a simple array with options. I don't know but if we can improve reusability of the validator I'd be happier.

File: lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/widgets-form-fields-view.js [hunk 4]
```diff
@@ -82,6 +82,10 @@ module.exports = CoreView.extend({
     return this;
   },
 
+  validateForm: function () {
+    return this._widgetFormView.validate();
+  },
+
```
Comment (ivanmalagon) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/widgets-form-fields-view.js]: :+1:

File: lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js (hunk 1 above)
Comment (rjimenezda) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js]: I would avoid binding on updateSchema, it's called a lot, and each bind creates a new function

Comment (rubenmoya) [inline lib/assets/core/javascripts/cartodb3/editor/widgets/widgets-form/schema/widgets-form-histogram-schema-model.js]: Probably it won't be needed, since I'm creating a new backbone-forms validator for column-type, but I'm not sure if you'll like it

**Comment by nobuti** [comment]
We should check the validate method before fetch in order to save a request. Right now, if you change the type, even with a wrong column, the request is made. Back to development.

**Comment by nobuti** [comment]
Also, not sure if we should tackle it here, but once you fix the column, the widget is not rendered, even if you change the form with new data. This happens with pretty much all widgets but categories, and in production as well. @xavijam your call.

**Comment by brittanymicek** [comment]
Hey! @rubenmoya sorry just seeing this now! I would change the error message to (a couple options):

1. "Column type must be a %{type}."
2. "Column type must contain a %{type} value."

I suggest the first option if the column type must exclusively be of one data type (EX: Column type must be a number/string/boolean).

I suggest the second option if the column type only needs to contain that value but doesn't necessarily need to be of a specific data type. (EX: Column type can be a number but contain a boolean value).

Sorry if that is confusing! Please let me know if that helps or if you need anything else. :)

**Comment by ivanmalagon** [comment]
Answering @nobuti comments.

First one, saving a request. After checking all the actors involved, I think that the devil you know, it's better than the devil you don't. The request is not sent by the object responsible for validation and we should modify the way it's triggered for all models. The user is not bothered by that failed request so it's not worth it.

The second one has been fixed. Nevertheless, it's been two birds, one stone, because we've fixed another histogram bug. When changing the widget `column`, the widget URL changes but we were updating only the dataviewmodel URL, not the datamodel one. The datamodel URL was set on stone the first time it was instantiated and column changes were not notifying the datamodel.

This has been fixed in `cartodb.js` in this [PR](https://github.com/CartoDB/cartodb.js/pull/1672)

Moving to acceptance.
