### PR TITLE
Explicitly close file

### LINKED ISSUE #13630: Ensure user mover temp logs are cleaned
User mover dumps logs to a file temporarily, and then copies them into the database.
https://github.com/CartoDB/cartodb/pull/13069/files#diff-0bf443506bccffbd76093b1fdc80d201R63

There seem to be a problem where these files are not cleaned. Although we use the [block syntax](https://ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#method-c-new-label-Exceptions) that seems to only close the file, but does not guarantees it being unlinked.

We should explicitly unlink it and check if that solves our problem.

### PR DESCRIPTION
**Pull request by amartinj**
Closes #13630

### CODE REVIEW

File: services/user-mover/utils.rb [hunk 1]
```diff
@@ -60,7 +60,10 @@ def remove_user_mover_banner(user_id)
 
       def run_command(cmd)
         logger.debug "Running command: \"#{cmd}\""
-        Tempfile.open('datamover') { |f| run_command_with_log(cmd, f) }
+        Tempfile.open('datamover') do |f|
+          run_command_with_log(cmd, f)
+          f.close(true)
```
Comment (javitonino) [inline services/user-mover/utils.rb]: What about putting this in an `ensure` (maybe inside `run_command_with_log`?). I was thinking what would happen if an exception is raised (maybe that's the issue).

Comment (amartinj) [reply services/user-mover/utils.rb]: You are right

**Comment by javitonino** [comment]
Working fine!
