### PR TITLE
Geocoder initialization does not fail if Cartodb.config is not loaded, fixes #2318

### LINKED ISSUE #2318: geocoder_test broken
https://github.com/CartoDB/cartodb/blob/master/script/geocoder_test is broken at 
https://github.com/CartoDB/cartodb/blob/master/script/geocoder_test#L23

Since CartoDB/cartodb@6ebb8bb

### PR DESCRIPTION
**Pull request by azamorano**
@rafatower please :eyes:

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1736/))

File: services/geocoder/lib/geocoder.rb [hunk 1]
```diff
@@ -47,7 +47,11 @@ def initialize(arguments)
       @mailto             = arguments.fetch(:mailto)
       @force_batch        = arguments[:force_batch] || false
       @dir                = arguments[:dir] || Dir.mktmpdir
-      @batch_api_disabled = Cartodb.config[:geocoder]['batch_api_disabled'] == true
+      begin
+        @batch_api_disabled = Cartodb.config[:geocoder]['batch_api_disabled'] == true
+      rescue
+        @batch_api_disabled = false
+      end
```
Comment (rafatower) [inline services/geocoder/lib/geocoder.rb]: A rubyist shortcut would be something like:
```Ruby
@batch_api_disabled = Cartodb.config[:geocoder]['batch_api_disabled'] == true rescue false
```
but I'm ok with that
