### PR TITLE
10127 custom baselayer

### LINKED ISSUE #10127: custom baselayer not added to user custom baselayer collection when importing .carto
**steps to reproduce**

- export .carto from a map with a custom basemap (i.e. mapbox)
- import .carto into another account which doesn't have such custom basemap
- enter in basemap panel in layer list

**expected behaviour**

- the custom basemap should be added in the respective custom basemap category

**actual behaviour**

as custom basemaps are currently three different geared parts working together:
- user custom baselayer collection (where the basemap isn't yet)
- custom baselayers collection for panel (which consists in default baselayers from config and custom baselayers from ^^^)
- baselayer in layer collection of map

the baselayer in the map is set indeed (thus we can properly see the map), but the custom baselayer isn't added to the user custom baselayers, and we can't deselect and select it again (see attached)

screen shot 2016-10-11 at 11 15 17

we should, at the moment of map import, create a custom baselayer for the user

/cc @xavijam

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #10127.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino , @matallo , could you CR this, please? It's currently deployed at ded06 in case that you want to take a look (specially @matallo , the Lord of the Basemaps :-) ).

**Comment by matallo** [comment]
👏 I'm not the proper guy to review the code, but tested several scenarios and looks awesome

File: app/models/carto/layer.rb [hunk 1]
```diff
@@ -231,8 +231,26 @@ def force_notify_change
...
+    def custom?
+      CUSTOM_CATEGORIES.include?(category)
+    end
+
+    def category
+      options && options['category']
+    end
+
+    def copy(override_attributes = {})
+      Carto::Layer.new(public_values.select { |k, _| k != 'id' }.merge(override_attributes))
```
Comment (javitonino) [inline app/models/carto/layer.rb]: I think this is equivalent to [`dup`](http://apidock.com/rails/ActiveRecord/Core/dup) which is built-in into ActiveRecord.

Uhm, I actually just seen the `public_values` thing, but I still think it's the same (all attributes are public except for creation_date, I believe).

File: app/services/carto/visualizations_export_persistence_service.rb [hunk 2]
```diff
@@ -70,6 +73,14 @@ def save_import(user, visualization, renamed_tables: {})
 
     private
 
+    def contains_equivalent_base_layer?(layers, layer)
+      layers.any? { |l| equivalent_base_layer?(l, layer) }
+    end
+
+    def equivalent_base_layer?(layer_a, layer_b)
```
Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: Maybe this is better as a model method. Not sure though, as it is quite specific to the importer.

File: app/services/carto/visualizations_export_persistence_service.rb [hunk 3]
```diff
@@ -59,6 +59,9 @@ def save_import(user, visualization, renamed_tables: {})
         end
 
         map.data_layers.each(&:register_table_dependencies)
+
+        new_user_layers = map.base_layers.select(&:custom?).select { |l| !contains_equivalent_base_layer?(user.layers, l) }
+        new_user_layers.map(&:copy).map { |l| user.layers << l }
```
Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: Curious: Where is the user saved? Or does AR automatically saves this to the `layers_users` relationship some how?

File: app/models/carto/layer.rb (hunk 1 above)
Comment (javitonino) [inline app/models/carto/layer.rb]: Well, this would not copy FK's if we add them, as long as they are not in public values. But I don't like that something called `public_values` and smells of presenter is used for the copy. I think `dup` is alright here because it copies all attributes except id and the relations, which is what we want now, and I feel it's what makes more sense in most situations.

File: app/services/carto/visualizations_export_persistence_service.rb (hunk 3 above)
Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: I didn't know it saved inmediately upon adding. Good to know :sparkles:

File: app/models/carto/layer.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: I would 100% agree if `dup` doesn't copy the relationships, but it does:

```ruby
irb(main):002:0> Carto::User.where('organization_id is not null').first.dup.organization_id
  Carto::User Load (1.6ms)  SELECT "users".* FROM "users" WHERE (organization_id is not null) LIMIT 1
=> "bb5c969c-3fd6-43dd-9606-47654ea9c0cd"
```

It doesn't create a shallow copy, but it _does_ copy the FK, so the duplicated object is linked.

Certainly it's not a current issue, as `layers` is a leaf in the relational model, but if a FK is eventually added this won't be noticed and thus be duplicated as well. Proposal:
a) Use `dup` as you suggest, since `layers` table hasn't FKs and it's not likely to have or to turn into a problem.
b) Rename `public_values` method at `Carto::Layer` to `cloneable_attributes`.
c) Other?

**Comment by javitonino** [comment]
Oh, forgot to mention. LGTM. Left a couple of comments, but nothing blocking.

File: app/models/carto/layer.rb (hunk 1 above)
Comment (javitonino) [inline app/models/carto/layer.rb]: Oh, didn't understood it worked that way. I tested it with layers and it worked (didn't copy relationships), but that is most likely because I tested the ternary ones (layers <-> maps).

That said, I prefer `dup` here as I feel it is more likely we add an attribute (and we forget to add it to cloneable attributes) than it is that we add a new fk. But no strong feelings either way, 1 or 2 both work for me. Go for the one you like better.

**Comment by juanignaciosl** [comment]
@javitonino let's discuss the layer duplication design, as I also had some doubts, before merging.

**Comment by juanignaciosl** [comment]
@javitonino quick CR for latest changes before merging, please.

File: app/services/carto/visualizations_export_persistence_service.rb [hunk 4]
```diff
@@ -59,6 +59,9 @@ def save_import(user, visualization, renamed_tables: {})
         end
 
         map.data_layers.each(&:register_table_dependencies)
+
+        new_user_layers = map.base_layers.select(&:custom?).select { |l| !contains_equivalent_base_layer?(user.layers, l) }
+        new_user_layers.map(&:dup).map { |l| user.layers << l }
```
Comment (javitonino) [inline app/services/carto/visualizations_export_persistence_service.rb]: You can do `user.layers << new_user_layers.map(&:dup)` although it is poorly documented :(

**Comment by javitonino** [comment]
Last change seems clean. I added another comment just to be a little nitpicky, comply or ignore. Ship when :green_apple:

**Comment by matallo** [comment]
BOOM, thanks mates
