### PR TITLE
Let exceptions bubble up to base_job and delete temp stale tables

### LINKED ISSUE #6628: Notify errors at base_job

### PR DESCRIPTION
**Pull request by iriberri**
Fixes #6628 
Fixes https://github.com/CartoDB/cartodb/issues/2917

While checking the importer flow, I've seen that there are multiple exceptions which get rescued and never get notified.

This PR adds several `raise` for those exceptions that were getting hidden and notifies them with our error notifier.

When those exceptions happened, we weren't cleaning the stale tables in the `cdb_importer` schema, which was also treated at #2917, so this new iteration tries to get rid of the tables that get stuck when an exception occurs.

### CODE REVIEW

**Comment by iriberri** [comment]
In my initial commit I added a raise exception in [this resque](https://github.com/CartoDB/cartodb/blob/6af94f5c44a9cbd5dbbf9572770626cbdd37e003/app/connectors/importer.rb#L201), but according to the tests this part is not expected to raise an import error, so I'm getting rid of it.

**Comment by iriberri** [comment]
I added a change in tests, [here](https://github.com/CartoDB/cartodb/blob/6628-notify_errors_base_job/spec/connectors/importer_spec.rb#L249-L250) so that they pass with the new exception raising additions.

````
    # It raises #<RuntimeError: Error: User doesn't have private tables enabled>
    expect{data_import.run_import!}.to raise_error(RuntimeError)
````

It comes from [here](https://github.com/CartoDB/cartodb/blob/9a4d3d696629720752f223a749a33ab313b36de6/app/models/table.rb#L424), where it is not treated as a specific CartoDB exception but simply `raised`.

**Comment by iriberri** [comment]
Please, @ethervoid, could you take a look? :)

File: app/connectors/importer.rb [hunk 1]
```diff
@@ -76,6 +76,7 @@ def register(result)
         runner.log.append("Table '#{name}' registered")
       rescue => exception
         if exception.message =~ /canceling statement due to statement timeout/i
+          drop("#{ORIGIN_SCHEMA}.#{current_name}")
```
Comment (ethervoid) [inline app/connectors/importer.rb]: There is no `current_name` variable in the method

File: app/models/data_import.rb [hunk 2]
```diff
@@ -208,6 +208,7 @@ def run_import!
     stacktrace = exception.to_s + exception.backtrace.join
     Rollbar.report_message('Import error', 'error', error_info: stacktrace)
```
Comment (ethervoid) [inline app/models/data_import.rb]: Change this to use `CartoDB.report_exception(e, message = nil, additional_data = {})` . We have to remove all the Rollbar direct calls

File: app/models/table_registrar.rb [hunk 3]
```diff
@@ -52,6 +52,7 @@ def set_metadata_from_data_import_id(table, data_import_id)
       end
     rescue => e
       Rollbar.report_exception(e)
```
Comment (ethervoid) [inline app/models/table_registrar.rb]: Same here

File: lib/resque/base_job.rb [hunk 4]
```diff
@@ -32,10 +32,12 @@ def self.run_action(options, queue_name, action)
             retry
           else
             raise e
-          end  
+          end
         else
           raise e
         end
+      rescue => e
+        CartoDB.notify_exception(e)
```
Comment (ethervoid) [inline lib/resque/base_job.rb]: Here is well done

**Comment by ethervoid** [comment]
Take a look to the comments

**Comment by iriberri** [comment]
I'll do asap. I just saw your issue about the Rollbar change in the list, so I'll change whatever mentions to it that still appear in these files.

**Comment by iriberri** [comment]
I made a new commit for Hound's recommendations, only style fixes in a test.

I guess that this is good to go next week then. :-)

**Comment by iriberri** [comment]
I found another one [here](https://github.com/CartoDB/cartodb/blob/ce8834ffac1d738aad08d1b12710d7eb3da9694b/app/models/data_import.rb#L598), although unrelated with the cdb_import stale tables. This is affecting: https://github.com/CartoDB/cartodb/issues/6707

File: app/connectors/importer.rb [hunk 5]
```diff
@@ -198,7 +205,7 @@ def rename_the_geom_index_if_exists(current_name, new_name)
           RENAME TO "the_geom_#{UUIDTools::UUID.timestamp_create.to_s.gsub('-', '_')}"
         })
       rescue => exception
-        runner.log.append("Silently failed rename_the_geom_index_if_exists from #{current_name} to #{new_name} with exception #{exception}. Backtrace: #{exception.backtrace.to_s}. ")
+        runner.log.append("Silently failed rename_the_geom_index_if_exists from #{current_name} to #{new_name} with exception #{exception}. Backtrace: #{exception.backtrace}. ")
```
Comment (rafatower) [inline app/connectors/importer.rb]: are you sure logging directly `backtrace` instead of `backtrace.to_s` is not gonna cause trouble? I remeber some issues logging exceptions because of not being able to serialize when sending to rollbar (breaking when trying to log something)

cc/ @ethervoid

Comment (iriberri) [inline app/connectors/importer.rb]: Oh, good catch. I removed the `to_s` because of Hound complaints, but it would make sense in this case.

File: lib/resque/base_job.rb (hunk 4 above)
Comment (rafatower) [inline lib/resque/base_job.rb]: Please raise the exception again.

By quickly looking into the code, this class has two purposes: retrying when there's a connection error and reporting resque stats properly. It was done by systems. In case of doubt ask systems.

By catching the exception and not re-throwing you're modifying the behavior

**Comment by luisbosque** [comment]
retest this please
