### PR TITLE
Be more forgiving when retrieving likes/shares count

### LINKED ISSUE #1638: Be more forgiving when retrieving likes/shares count
Instead of failing by default with an exception, return 0 and allow to toggle on the exception scenario.

```KeyError: Can't retrieve likes count without specifying visualization type```

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #1638

### CODE REVIEW

**Comment by Kartones** [comment]
@lbosque CR please

File: app/models/visualization/collection.rb [hunk 1]
```diff
@@ -119,60 +119,87 @@ def to_poro
...
-                                                          :visualizations__id.cast(:uuid) => :entity_id,
-                                                          :type => @type)
-                                                   .count
-          user = User.where(id: @user_id).first
-          if user.nil? || user.organization.nil?
-            org_shared_count = 0
+      def total_shared_entries(raise_on_error = false)
+        user_shared_count = org_shared_count = 0
+
+        unless @unauthenticated_flag
```
Comment (lbosque) [inline app/models/visualization/collection.rb]: What will it return if @unauthenticated_flag?

Comment (Kartones) [inline app/models/visualization/collection.rb]: `user_shared_count = org_shared_count = 0`

So in case of @unauthenticated_flag it will return `0 + 0` for shared entities

Comment (lbosque) [inline app/models/visualization/collection.rb]: You are right.

**Comment by lbosque** [comment]
+1
