### PR TITLE
If you try to import from data-library and fails, disappear from the list

### LINKED ISSUE #5132: If you try to import from data-library and fails, disappear from the list
**Problem**

I've trying to import a dataset from data-library without connection and failed. After that I don't have the datasets imported and has disappear from the data-library list

**Solution**

If there is an import error we should not add to `external_data_import` so we could re-import the dataset

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #5132

### CODE REVIEW

**Comment by Kartones** [comment]
@ethervoid CR please

File: app/models/data_import.rb [hunk 1]
```diff
@@ -638,11 +638,11 @@ def store_results(importer=nil, runner=nil, datasource_provider=nil, manual_fiel
       self.table_name = importer.table.name if importer.success? && importer.table
       self.table_id   = importer.table.id if importer.success? && importer.table
 
-      if importer.success? && importer.data_import.create_visualization
-        self.visualization_id = importer.data_import.visualization_id
+      if importer.success?
+        self.visualization_id = importer.data_import.visualization_id if importer.data_import.create_visualization
```
Comment (ethervoid) [inline app/models/data_import.rb]: I'd put the if condition above with &&

**Comment by ethervoid** [comment]
Ok despite a minor comment

**Comment by ethervoid** [comment]
retest this please

File: app/models/data_import.rb (hunk 1 above)
Comment (Kartones) [inline app/models/data_import.rb]: Careful, check the diff at the left, setting the vis. id is only to be done if the second condition is true, but updating the sync is to be done always that importer is a success

Comment (ethervoid) [inline app/models/data_import.rb]: Hum you're right! . Anyway I don't like the inline ifs, maybe `importer.data_import.visualization_id if importer.data_import.create_visualization` should be extract away as a method. There are too much logic implicit that could lead to error

Comment (Kartones) [inline app/models/data_import.rb]: I don't think is too complex or bad to have two ifs but ok, I'll extract to a method because if you already got confused others might too :+1:
