### PR TITLE
Fix tests

### LINKED ISSUE #10327: Some test use a bad method for get|delete|put
```ruby
post url do |response|
  response.code.should eq 200
end
```

is OK

```ruby
(get|put|patch|delete) url do |response|
  response.code.should eq 'banana bananita'
end
```

does not execute the block and the tests always passes.

For those other verbs, the right way is:

```ruby
(get|put|patch|delete)_json do |response|
  (...)
end
```

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #10327

```ruby
post url do |response|
  response.code.should eq 200
end
```

is OK

```ruby
(get|put|patch|delete) url do |response|
  response.code.should eq 'banana bananita'
end
```

does not execute the block and the tests always passes.

For those other verbs, the right way is:

```ruby
(get|put|patch|delete)_json do |response|
  (...)
end
```

### CODE REVIEW

**Comment by xavijam** [comment]
ping when you are back 😛

**Comment by gfiorav** [comment]
Retest this, please.

**Comment by gfiorav** [comment]
Please review @juanignaciosl 

cc/ @javitonino

File: spec/requests/carto/admin/bi_visualizations_controller_spec.rb [hunk 1]
```diff
@@ -1,50 +0,0 @@
-# encoding: utf-8
```
Comment (juanignaciosl) [inline spec/requests/carto/admin/bi_visualizations_controller_spec.rb]: How come you delete this file? As long as `BiVisualizationsController` is not gone, their tests should stay.

Comment (gfiorav) [inline spec/requests/carto/admin/bi_visualizations_controller_spec.rb]: The code is deprecated and it's tests never worked. It might make more sense to remove them as the code is frozen and won't change. I'll add it back and fix them if you think it's necessary, but no one should be using this code anymore :)

Comment (juanignaciosl) [inline spec/requests/carto/admin/bi_visualizations_controller_spec.rb]: I did those tests and I know that they once worked, for sure, at least in local, because I saw them failing.

Anyway, if you confirm that those controllers are not used maybe we can get rid of them now. But I wouldn't delete the tests without deleting the controllers.

Comment (gfiorav) [inline spec/requests/carto/admin/bi_visualizations_controller_spec.rb]: I just checked in master again to make sure. The tests are 100% not working. The code block is not executed. It's easy to miss it unless you add an impossible condition or a breakpoint and watch it pass. 

I'm thinking that RSpec would be wise to show a an obvious message for asserted expectations (not only failed ones) so this doesn't happen. ¯\_(ツ)_/¯

I'll put them back and fix them, but there isn't much point. I'll make a ticket to remove the bi controllers as well.

Comment (gfiorav) [inline spec/requests/carto/admin/bi_visualizations_controller_spec.rb]: Update: I'm fixing them:
+ one variable was missing a `@` in `bi_visualization` in the REGEXP), take a look when I push in case I'm missing something here.
+ another one is correct but it returns the wrong code. It's `returns 401 for non-authenticated requests`

Any input on the wrong code one? Which is the right behaviour?

**Comment by gfiorav** [comment]
Could you have a final look @juanignaciosl ?

File: Makefile [hunk 2]
```diff
@@ -27,7 +27,6 @@ WORKING_SPECS_1 = \
 	spec/requests/application_controller_spec.rb \
 	spec/requests/sessions_spec.rb \
 	spec/requests/api/json/layer_presenter_spec.rb \
-	spec/requests/carto/admin/bi_visualizations_controller_spec.rb \
```
Comment (juanignaciosl) [inline Makefile]: Bring this line back now that it's not deleted :-)

Comment (gfiorav) [inline Makefile]: oh! thanks

**Comment by gfiorav** [comment]
Hey @juanignaciosl could you have a look at the test error and maybe suggest something?

**Comment by juanignaciosl** [comment]
@gfiorav take a look at the commit I pushed. This was obviously urgent for this PR but checking login page might be nice in further tests. It's not a redirection but a display, so a helper that checks the presence of a field is the best that I've come up with.
