### PR TITLE
11153 simplify fix saml configuration rake

### LINKED ISSUE #11153: Simplify SAML configuration
- As assertion_consumer_service_url is known when you configure the SAML service, you shouldn't need to explicitly set it.
- name_identifier_format could provide a common default, such as `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
- validate parameters at model?
- https://github.com/CartoDB/cartodb/issues/11199
- Implement SAML metadata files (XML) both ways (parse IdP, generate SP)

This should also make `cartodb:saml:create_saml_configuration` simpler.

### LINKED ISSUE #11199: Issuer is not properly defined in saml.rake
In https://github.com/CartoDB/cartodb/blob/master/lib/tasks/saml.rake#L17 `saml_issuer` should be named `issuer`

cc @javitonino

### PR DESCRIPTION
**Pull request by javitonino**
Closes #11153
Fixes #11199 

Auto-configuration made easy.

Acceptance: test the rake and the new endpoint. Some suggestions (but feel free to experiment, the documentation is in a comment in the rake source):
- Run the rake as `ORGANIZATION_NAME=org SAML_EMAIL_ATTRIBUTE=username SAML_IDP_METADATA_FILE='http://localhost:5000/saml2/idp/metadata.php' bundle exec rake cartodb:saml:create_saml_configuration`
- Paste the generated XML file (from org.localhost.lan/saml/metadata) into http://localhost:5000/admin/metadata-converter.php and use it to configure the saml IdP (put the results of that PHP into the metadata config file, it is not automatic in simplesaml)
- Try to break the metadata endpoint (invalid organization)
- Try the rake the old way (specifying all parameters manually). Check for errors for required fields

### CODE REVIEW

File: app/controllers/carto/saml_controller.rb [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+module Carto
+  class SamlController < ApplicationController
+    include Carto::ControllerHelper
+
+    ssl_required  :metadata
+    before_filter :load_organization, :ensure_saml_enabled
+
+    rescue_from LoadError, UnauthorizedError, with: :rescue_from_carto_error
+
+    # Callback from Github Oauth
```
Comment (juanignaciosl) [inline app/controllers/carto/saml_controller.rb]: This comment is not true ;-)

File: lib/tasks/saml.rake [hunk 2]
```diff
@@ -2,31 +2,54 @@ namespace :cartodb do
   namespace :saml do
     # Sets (inserts or overrides) SAML configuration for an organization. The following environments variables are needed:
     # ORGANIZATION_NAME: name of the organization. Example: 'orgname'.
-    # SAML_ISSUER: Name of the service provider in the SAML server. Example: 'CARTO_SAML_Test'.
+    # SAML_ISSUER: [OPTIONAL] Name of the service provider in the SAML server. Example: 'CARTO_SAML_Test'. Defaults are based on organization name and domain.
```
Comment (juanignaciosl) [inline lib/tasks/saml.rake]: "based on" sounds too general. An specific example saying what issuer is set "based on" an organization would be more clear (if it's the same, maybe changing "based on" to "is the organization name" is accurate enough).

**Comment by gfiorav** [comment]
regarding acceptance:

I've verified that the generated config works, but I can't come up with any way to make it break. I've tried logging and creating users.
