### PR TITLE
Redirect to waiting page on ongoing http header authentication

### LINKED ISSUE #9362: Wrong redirection on user autocreation
STR

1. [Enable HTTP Header Authentication with autocreation](http://cartodb.readthedocs.io/en/latest/operations/http_headers_authentication.html).
2. Go to login with a header. Redirection is wrong, it will retry and displays a 500 error. User creation is ok though (going to login again will work).

cc @gfiorav @javitonino @xavijam

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #9362 and #9369 .

As depending on timing there might be redundant requests from frontend, instead of failing with a 409 user will be redirected to waiting screen.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@javitonino CR this, please. cc @MariaCheca

File: app/controllers/signup_controller.rb [hunk 1]
```diff
@@ -97,6 +98,12 @@ def create_http_authentication
     render_500
   end
 
+  def create_http_authentication_in_progress
+    authenticator = Carto::HttpHeaderAuthentication.new
+    render_500 unless authenticator.autocreation_enabled? && authenticator.creation_in_progress?(request)
```
Comment (javitonino) [inline app/controllers/signup_controller.rb]: I think this might just move the race condition. Can the creation be in progress (in `http_header_authentication`) but finish just while the user gets redirected here?

Comment (juanignaciosl) [inline app/controllers/signup_controller.rb]: Yes, it can happen, but it's not a problem. User will be redirected to `signup_confirmation`, which will check the state of the creation. As it will be finished he will be redirected to the dashboard. The problem is that 409 page was a dead end.

Comment (javitonino) [inline app/controllers/signup_controller.rb]: How come they aren't they 500'ed before the redirection happens? As I read it, `authenticator.creation_in_progress?(request)` is `false` and that renders a 500. By the way, shouldn't that call include a `return` to avoid double render?

Comment (juanignaciosl) [inline app/controllers/signup_controller.rb]: Oh, I hadn't realized about that both, great catch! What about this?

```ruby
if !authenticator.creation_in_progress?(request)
  _redirect to login_
else
  render 'shared/signup_confirmation'
end
```

This way the race condition is still avoided, and redirecting to login is safe.

Comment (javitonino) [inline app/controllers/signup_controller.rb]: That should work fine. I think this will be very rare (it's difficult for a user creation to finish faster than a redirection) but still better safe than sorry :sparkles:

**Comment by juanignaciosl** [comment]
@javitonino suggestions applied, second CR, please.

File: app/controllers/signup_controller.rb [hunk 2]
```diff
@@ -7,12 +7,13 @@ class SignupController < ApplicationController
...
+  ssl_required :signup, :create, :create_http_authentication, :create_http_authentication_in_progress
 
-  skip_before_filter :http_header_authentication, only: [:create_http_authentication]
+  skip_before_filter :http_header_authentication,
+                     only: [:create_http_authentication, :create_http_authentication_in_progress]
 
-  before_filter :load_organization, only: [:create_http_authentication]
-  before_filter :check_organization_quotas, only: [:create_http_authentication]
+  before_filter :load_organization, only: [:create_http_authentication, :create_http_authentication_in_progress]
+  before_filter :check_organization_quotas, only: [:create_http_authentication, :create_http_authentication_in_progress]
```
Comment (javitonino) [inline app/controllers/signup_controller.rb]: I think you may want to remove this filter. Once the creation is started it doesn't make much sense to check if there is enough space in the org. In fact, it may have been taken precisely by this creation. If you do this, I think you can also remove `load_organization` but not sure about that.

File: app/controllers/application_controller.rb [hunk 3]
```diff
@@ -74,7 +74,8 @@ def http_header_authentication
       authenticator = Carto::HttpHeaderAuthentication.new
       if authenticator.autocreation_enabled?
         if authenticator.creation_in_progress?(request)
-          render_http_code(409, 500, 'Creation already in progress')
+          # render_http_code(409, 500, 'Creation already in progress')
```
Comment (javitonino) [inline app/controllers/application_controller.rb]: Better to remove this altogether but not important.

**Comment by javitonino** [comment]
Check out the filters comment, which may make some sense or not. After that, this looks production-ready to me. :+1:

File: app/controllers/signup_controller.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/controllers/signup_controller.rb]: Uhm, you're right about `check_organization_quotas`. I prefer keeping `load_organization`, because the page might want to render something (it _could_ use user's, but it might not, I prefer keeping it).

File: app/controllers/application_controller.rb (hunk 3 above)
Comment (juanignaciosl) [inline app/controllers/application_controller.rb]: True. 100% Diogenes Syndrome.

**Comment by javitonino** [comment]
:ship: when :green_book:

**Comment by juanignaciosl** [comment]
@javitonino I've taken into account both. I'll merge after 🍏  unless you say something.

**Comment by juanignaciosl** [comment]
Merged and removed the yielding that fixed #9369 because @MariaCheca merged the WIP into master, fixing it.
