### PR TITLE
Layers should be loaded from visualization_for_presentation at embed

### LINKED ISSUE #11554: Incorrect style restored when disabling autostyle in mapcapped embed
### Context
Discovered by looking at code: https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/builder/public/embeds_controller.rb#L25
That should be visualization for presentation.
 
### Steps to Reproduce
Reverse engineered from code.

1. Create a map
2. Apply a simple style (the default one works)
3. Add a histogram widget
4. Apply autostyle on the widget
5. Publish the map
6. Disable autostyle
7. Change the simple style (for example, change the color)
8. Do NOT publish the map
9. Go to the embed
10. Disable autostyle

### Current Result
The style in step 7 

### Expected result
The style in step 2

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #11554

Acceptance:
- [x] Issue STR.
- [x] Afterwards, change layer style. Reload the embed. Style shouldn't change.
- [x] Publish. Reload the embed. Style should change.

### CODE REVIEW

File: spec/requests/carto/builder/public/embeds_controller_spec.rb [hunk 1]
```diff
@@ -56,6 +57,26 @@ def stub_passwords(password)
       unpublished_visualization.destroy
     end
 
+    it 'displays published layers, not ("live") visualization layers' do
+      @map, @table, @table_visualization, @visualization = create_full_builder_vis(@carto_user)
```
Comment (javitonino) [inline spec/requests/carto/builder/public/embeds_controller_spec.rb]: Don't this instance variable conflict with the ones at before/after :all ? I don't get how test below this one pass if `@visualization` is being overwritten, it makes me think that `destroy_full_visualization` is not fully working or the test below do so much stubbing that it doesn't matter (but it doesn't seem to be the case) 😕

Do you know? If not, I can take a look.

Comment (juanignaciosl) [inline spec/requests/carto/builder/public/embeds_controller_spec.rb]: In fact, I ran into trouble when I set `destroy_full_visualization` in a `after(:all)`, so I blindly moved it inside the test and forget, as it worked. But you're right, it deserves a closer look.

This works because within rspec tests, declaring instance variables is hierarchical. Before line 61 is run, `@visualization` resolves to the one defined in the `before(:all)` block. Within the line 60 test, after line 61 is run, it resolves to the instance returned by `create_full_builder_vis`, so that's the one which is deleted. Outside line 60 test, `@visualization` is still the outer one.

Comment (javitonino) [inline spec/requests/carto/builder/public/embeds_controller_spec.rb]: So many layers of magic, it's amazing 😮 

:+1: Thanks for the great explanation!

Comment (juanignaciosl) [inline spec/requests/carto/builder/public/embeds_controller_spec.rb]: https://media.giphy.com/media/VHngktboAlxHW/giphy.gif

**Comment by javitonino** [comment]
Like a 🚀
