### PR TITLE
12568 nil processing named map template

### LINKED ISSUE #12568: NoMethodError: undefined method `[]' for nil:NilClass on named map template processing
### Context

[trace](https://rollbar.com/carto/CartoDB/items/24269/?item_page=0&item_count=100&#instances)

```
NoMethodError: undefined method `[]' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/template.rb", line 263 in view
2
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/template.rb", line 44 in block in to_hash
3
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/cartodb/stats/aggregator.rb", line 97 in method_missing
4
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/template.rb", line 31 in to_hash
5
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/template.rb", line 50 in to_json
6
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/api.rb", line 70 in block in update
7
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/cartodb/stats/aggregator.rb", line 97 in method_missing
8
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/api.rb", line 68 in update
9
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/lib/carto/named_maps/api.rb", line 102 in upsert
10
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/app/models/carto/mapcap.rb", line 55 in update_named_map
+ 25 non-project frames
36
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/app/models/carto/visualization.rb", line 453 in create_mapcap!
37
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/app/controllers/carto/api/mapcaps_controller.rb", line 31 in create
+ 6 non-project frames
44
File "/home/ubuntu/www/production.cartodb.com/releases/20170807121743/app/controllers/application_controller.rb", line 101 in wrap_in_profiler
```

[Culprit](https://github.com/CartoDB/cartodb/blob/3c0afefc4365e67ccd3124436771f0f6e9f00847/lib/carto/named_maps/template.rb#L263):

```
          bounds_data = {
            west: state[:map][:sw][0],
            south: state[:map][:sw][1],
            east: state[:map][:ne][0],
            north: state[:map][:ne][1]
          }
```

Similar to #12453

Please review all parameter fetching at that class, because there are more than one failure points due to an unexpected storage of the properties.

I don't have STR. It comes from an non validated JSON, so we can't make any assumption of it.

### PR DESCRIPTION
**Pull request by amartinj**
When a named map template is used, if there is some data corruption in the state field, it was throwing an exception.

More conditions have been aded to the [condition](https://github.com/CartoDB/cartodb/compare/12568NilProcessingNamedMapTemplate?diff=unified&expand=1&name=12568NilProcessingNamedMapTemplate#diff-37de14bd6f97d298cf49816cf53dbf67L240) so it takes this into account.

Code refactor to make it more readable and easy to follow

A test has also been added

Fixes #12568

### CODE REVIEW

File: lib/carto/named_maps/template.rb [hunk 1]
```diff
@@ -237,52 +237,71 @@ def auth
 
       def view
         state = @visualization.state.json
-        if state.blank? || state[:map].blank? || state[:map][:center].blank?
-          # Use map info when there's no state info
-          map = @visualization.map
-          center_data = map.center_data
-          data = {
+        if invalid_state? state # Use map info when there's no state info
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: From [our style guide](https://github.com/Vizzuality/ruby-style-guide):

> Omit parentheses around parameters for methods that are part of an internal DSL (e.g. Rake, Rails, RSpec), methods that have "keyword" status in Ruby (e.g. attr_reader, puts) and attribute access methods. Use parentheses around the arguments of all other method invocations.

As this is not any of previous exceptions, we write `invalid_state?(state)`

Comment (juanignaciosl) [reply lib/carto/named_maps/template.rb]: Next: instead of `invalid_state?`, having a positive expression (`valid_state?`) makes more sense.

Comment (juanignaciosl) [reply lib/carto/named_maps/template.rb]: Last, your nice refactor leads to a one liner `view` with a ternary expression:

`valid_state?(@visualization.state.json) ? view_from_state  : view_from_map`

File: lib/carto/named_maps/template.rb [hunk 2]
```diff
@@ -237,52 +237,71 @@ def auth
...
+          view_from_map
+        else # Use state information when present
+          view_from_state
+        end
+      end
+
+      def preview_layers
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: Why is this method now public? I can't find any change needing it.

File: lib/carto/named_maps/template.rb [hunk 3]
```diff
@@ -237,52 +237,70 @@ def auth
...
+
+      def view_from_map
+        map = @visualization.map
+        center_data = map.center_data
+        data = {
             zoom: map.zoom,
             center: {
-              lng: center_data[1].to_f,
-              lat: center_data[0].to_f
+                lng: center_data[1].to_f,
```
[the remark this answers is not in the document]
Comment (juanignaciosl) [reply lib/carto/named_maps/template.rb]: ^ honor this, please.

File: lib/carto/named_maps/template.rb [hunk 4]
```diff
@@ -237,52 +237,71 @@ def auth
...
         state = @visualization.state.json
-        if state.blank? || state[:map].blank? || state[:map][:center].blank?
-          # Use map info when there's no state info
-          map = @visualization.map
-          center_data = map.center_data
-          data = {
+        if invalid_state? state # Use map info when there's no state info
+          view_from_map
+        else # Use state information when present
+          view_from_state
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: `view` method (and the class, after the refactor) uses two different approaches to object orientation and method declaration:

- `(in)valid_state?` requires an argument (although it could take it from object state.
- `view_from_*` don't require an argument.

Having both styles at the same method is confusing. Personally, I prefer using the least object state possible and pass arguments.

File: lib/carto/named_maps/template.rb [hunk 5]
```diff
@@ -237,52 +237,71 @@ def auth
...
             }
-          }
-          bounds_data = map.view_bounds_data
-        else
-          # Use state information when present
-          center_data = state[:map][:center]
-          data = {
+        }
+        bounds_data = map.view_bounds_data
+        filter_and_merge_view(bounds_data, data)
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: `filter_and_merge_view ` method is called at both `view_from_*` methods. That might be a smell of having a wrong abstraction.

What do you think about changing `view_from_*` to `bounds_and_data_from_*`, then `return bounds_data, center_and_zoom` at both, and using `filter_and_merge_view` outside? Even though having methods with "and" is also an smell, in this case it's a data extraction, it might be a better solution.

File: lib/carto/named_maps/template.rb (hunk 1 above)
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: I'm not a big fan of ternaries, but okay. Agree on the rest :)

File: lib/carto/named_maps/template.rb (hunk 4 above)
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: absolutely agree

File: lib/carto/named_maps/template.rb (hunk 2 above)
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: It's not 😖 . Just checked :/

File: lib/carto/named_maps/template.rb (hunk 5 above)
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: I've decided to do it this way in order to keep `view` method more readable and move the "dark" code deeper. I also considered splitting `filter_and_merge_view` to make it only responsible for one thing and then, inside `view_from_state` and `view_from_map` call both methods, but this would result into duplicated code in both methods. The solution is not the most philosophically correct, but I see it as the most readable option :)

**Comment by amartinj** [comment]
retest this please

File: lib/carto/named_maps/template.rb [hunk 6]
```diff
@@ -236,53 +236,66 @@ def auth
...
+
+      def valid_state?
         state = @visualization.state.json
-        if state.blank? || state[:map].blank? || state[:map][:center].blank?
-          # Use map info when there's no state info
-          map = @visualization.map
-          center_data = map.center_data
-          data = {
+        map = state[:map]
+        not(state.blank? || map.blank? || map[:center].blank? || map[:sw].blank? || map[:ne].blank? ||
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: Instead of `not ... blank? ... ||` you can use `... present? .... &&`, isn`t it? That way you can skip the negation.

File: lib/carto/named_maps/template.rb [hunk 7]
```diff
@@ -236,53 +236,66 @@ def auth
       end
 
       def view
+        valid_state? ? view_from_state : view_from_map
+      end
+
+      def preview_layers
```
[the remark this answers is not in the document]
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: Diff issues :S

File: lib/carto/named_maps/template.rb (hunk 6 above)
Comment (amartinj) [reply lib/carto/named_maps/template.rb]: 👍

File: lib/carto/named_maps/template.rb [hunk 8]
```diff
@@ -236,53 +236,66 @@ def auth
       end
 
       def view
+        valid_state? ? view_from_state : view_from_map
```
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: What about `view_from_state || view_from_map`, inlining `valid_state?` inside `view_from_state`? It's readable and might avoid `state = @visualization.state.json` duplication`.

Minor, though.

Comment (amartinj) [reply lib/carto/named_maps/template.rb]: that would make `view_from_state` return both a boolean and a data structure 😖

Comment (juanignaciosl) [reply lib/carto/named_maps/template.rb]: You can return `nil` instead of a boolean.

Comment (amartinj) [reply lib/carto/named_maps/template.rb]: I'd rather not return unexpected types and leave as it is :/

**Comment by juanignaciosl** [comment]
To acceptance, then!

**Comment by javitonino** [comment]
Acceptance 👍 

Could not make it break. As a bonus, if you put garbage in the state, it gets automatically fixed next time you open builder.
