### PR TITLE
Group points into polygons fixes

### LINKED ISSUE #9538: The target_percent input of the concave hull analysis should have a different scale
As reported by @saleiva: from 0 o 100 or from 0 to 1, not from 0 to 10 like it's right now.

### LINKED ISSUE #9542: Changing the method on the group points in polygons analysis shouldn't change the group by option

### LINKED ISSUE #9544: Make Convex hull the default option on Groups points in polygons analysis
After testing for a while I've discovered that it makes sense to have the list like...
- Convex Hull
- Concave Hull
- Bounding Circle
- Bounding Box

### PR DESCRIPTION
**Pull request by javierarce**
Several fixes for the Group points into polygons analysis.

Closes #9544 --> reorder list of analyses
Closes #9538 --> changes the `target_percent` scale to 0 to 100
Closes #9542 --> persists the `category_column` when switching between methods

### CODE REVIEW

**Comment by javierarce** [comment]
CR: @xavijam

File: lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-models/group-points/concave-hull.js [hunk 1]
```diff
@@ -12,18 +12,25 @@ module.exports = {
...
     }
+
     var aggregate = {
       operator: nodeAttrs.aggregation,
       attribute: nodeAttrs.aggregation === 'count' ? '' : nodeAttrs.aggregation_column
     };
+
     return {
       type: 'concave-hull',
+      target_percentage: nodeAttrs.target_percent ? nodeAttrs.target_percent * 100 : 70,
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-models/group-points/concave-hull.js]: If target_percent is 0, it will return 70. Is it ok?

**Comment by xavijam** [comment]
Apart from my comment, :es:.

**Comment by javierarce** [comment]
Thanks! I'll fix what you mention.
