### PR TITLE
First part of the layers content view

### LINKED ISSUE #6722: Clicking the back button from the widget editing form should go to the widgets view
We should modify the stack layout navigation to allow going to a specific view.

### LINKED ISSUE #6833: map URL not working on the new editor
https://team.cartodb.com/u/saleiva/viz/56f0a9a6-f93a-11e2-8a7e-3085a9a9563c/map it gives a js error

### PR DESCRIPTION
**Pull request by xavijam**
screen shot 2016-03-15 at 11 24 16

Instead of creating a super huge PR, I've decided to start with this and then keep going with the proper analysis form. In short:

- [x] Show the content of the selected layer (screenshot above ^^^).
- [x] Updated CartoAssets to the last version (cc @piensaenpixel).
- [x] Keep the state of the first stack layout view (fixes #6722).
- [x] Fixes a problem related with vizJSON overlays (fixes #6833).

CR: @viddo 
cc @javierarce

### CODE REVIEW

**Comment by xavijam** [comment]
I have pending to add first tests for `layer-view` and `layers-view` classes.

File: lib/assets/javascripts/cartodb3/editor/layers/layer-header-view.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  initialize: function (opts) {
+    this.layerDefinitionModel = opts.layerDefinitionModel;
+    this.layerTableModel = this.layerDefinitionModel.layerTableModel;
+  },
+
+  render: function () {
+    this.$el.html(
+      template({
+        title: this.layerTableModel.get('table_name'),
+        alias: this.layerTableModel.get('alias') || this.layerTableModel.get('table_name').replace(/_/gi, ' ')
```
Comment (viddo) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-header-view.js]: Why not use `layerDefinitionModel.getName()` here? Internally that is using the name, table alias, or table name. I'd prefer that we're not relying more on layer table model as it will be removed eventually.

File: lib/assets/locale/en.json [hunk 2]
```diff
@@ -37,6 +37,23 @@
...
+      "style": {
+        "title-label": "Style"
+      },
+      "popup": {
+        "title-label": "Pop-up"
+      },
+      "legends": {
+        "title-label": "Legend"
+      }
+    },
```
Comment (viddo) [inline lib/assets/locale/en.json]: I repeat what [I wrote in another PR](https://github.com/CartoDB/cartodb/pull/6838#issuecomment-194801697), translations should be grouped not by _type_, but indicating _how_/_where_ they're used, so a translator can know how to translate things consistently. In this case I'd suggest:

```js
layers: {
  menu-tab-pane-labels: {
    data: 'Data',
    analyses: 'Analyses',
    …
  }
}
``

File: lib/assets/javascripts/cartodb3/editor/map/map-view.js [hunk 3]
```diff
@@ -24,23 +25,43 @@ module.exports = cdb.core.View.extend({
 
     var stackViewCollection = new Backbone.Collection([{
       createStackView: function (stackLayoutModel, opts) {
+        var lastStep = opts[0] || 'layers';
```
Comment (viddo) [inline lib/assets/javascripts/cartodb3/editor/map/map-view.js]: Just a minor detail, but why not name this to something that indicate what it actually _does_ instead, e.g. `selectTabItem` or `selectedTabItem`?

File: lib/assets/javascripts/cartodb3/editor/layers/layer-header-view.js (hunk 1 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-header-view.js]: Absolutely agree with you, thanks @viddo.

File: lib/assets/javascripts/cartodb3/editor/map/map-view.js (hunk 3 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/map/map-view.js]: :+1:

File: lib/assets/locale/en.json (hunk 2 above)
Comment (xavijam) [inline lib/assets/locale/en.json]: Ahh, ok, I followed what I've seen in the en.json, but I don't have any strong opinion on that, so :+1:.

**Comment by xavijam** [comment]
Created a ticket for layers-view and layer-view tests (https://github.com/CartoDB/cartodb/issues/6891).

How do you like it?

**Comment by viddo** [comment]
:shipit:
