### PR TITLE
Use presenter for compatibility with both permission models

### LINKED ISSUE #11800: Warn about layer/map deletion on dataset deletion
### Steps to Reproduce

1. Import a file dragging it to Maps section.
2. Delete the dataset from the dataset list (select + delete dataset...).

### Current Result

You aren't  warned about map deletion.

 

### Expected result

You should be warned about map deletion.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #11800 

This was introduced in https://github.com/CartoDB/cartodb/pull/11600/files (user table refactor, part 3). In this one, we changed how `::Table.user_table` works, so it could return `Carto::UserTable`. This was judged to be OK, as is only used for presenters.

However, this broke `TableRelator.preview_for` when called like `Carto::UserTable.service.public_values` since this uses the new models and that method is not compatible. Moreover:
- This method was only tested on `table_relator_spec` which makes heavy use of stubs.
- There is a `rescue all` that hides the issue: https://github.com/CartoDB/cartodb/blob/4a5715ad25f88dc15fedc85cd1f8b2649d52f5d0/app/models/table.rb#L121

### CODE REVIEW

File: app/models/table.rb [hunk 1]
```diff
@@ -117,9 +117,7 @@ def public_values(options = {}, viewer_user=nil)
     selected_attrs = options[:except].present? ?
       PUBLIC_ATTRIBUTES.select { |k, v| !options[:except].include?(k.to_sym) } : PUBLIC_ATTRIBUTES
 
-    attrs = Hash[selected_attrs.map{ |k, v|
-      [k, (self.send(v) rescue self[v].to_s)]
-    }]
+    attrs = Hash[selected_attrs.map { |k, v| [k, send(v)] }]
```
Comment (juanignaciosl) [inline app/models/table.rb]: Although this is a nice move, I'm worried about issues with old/broken data. Have you done some research or tests about the impact of this? 🐔

Comment (javitonino) [inline app/models/table.rb]: Uhm, I checked that all methods existed, which is the original intent of the code. I reviewed the entire list, and I'm fairly confident on all counts, but `rows_estimated` may be an issue. Failures in that can be quite common (DB connection fail, table without stats), the old code would return 0, and the new one raises an exception.

I though that `::Table[:rows_estimated]` wouldn't work, but it actually does, because `[]` is delegated to the model. It doesn't do anything that makes much sense (it returns a field in the database which is always 0, it is not updated), but...

I am not sure where I land on the 🐔  <-> :psycho: scale today. I think I am leaning towards removing this part of the PR (revert last commit), as we are already making big changes to the model soon™.

Comment (juanignaciosl) [inline app/models/table.rb]: 👍  to that. Let's keep this PR safe.
