### PR TITLE
basemaps: fix change custom layer

### LINKED ISSUE #9194: Basemaps are not loading correctly (tiles and labels) or disabling the zoom in control beyond level 10
OS: mac OS El Capitán 10.11.5
Browser: Chrome Version 51.0.2704.106 (64-bit)
CARTO Account used when this happened: arianaescobar 

## Issue

On the Basemaps picker, the basemaps are sometimes taking a lot of time to load, are loading incorrectly (not loading tiles or labels, or loading another basemaps label styles instead), or not loading at all. Also sometimes the basemaps are only letting me zoom in until zoom level 10. 

Tiles didn't load: 
screen shot 2016-08-01 at 13 23 13

Positron label styles on a Dark Matter basemap:
screen shot 2016-08-01 at 13 26 47

Take a look on how the + icon on the zoom controls is disabled: 
screen shot 2016-08-01 at 13 27 26
screen shot 2016-08-01 at 13 29 36

## Steps taken when it happened 

1. I logged in into the my account
2. I opened one of my maps
3. I clicked on the Basemap layer and the basemaps picker appeared.
5. Then I clicked on differents basemaps and the errors began to occur. 

## Expected behaviour 

When I click on different basemaps than the one picked, it should load it and change to that one faster and correctly (tiles and labels). 

## Console errors

**tracker.js:26 Uncaught Error: TrackJS Caught: Cannot read property 'getName' of undefined**

## Reproduction 

I can reproduce it on every map in that account. I tried to reproduce it creating a new map but then I got this old bug #8879 when I opened the basemaps picker. 

If there's any other information or context I can give to help reproduce the issue, just let me know, I'll be happy to :)

### LINKED ISSUE #9202: on change custom basemaps, they are saved wrong

### LINKED ISSUE #9210: Builder - Empty UI Basemap Error
## Context
When user "stuartlynn" of the CARTO team organization account uploads a CSV, an error occurs and he is unable to select a basemap for his map. The UI shows empty when he clicks on the Positron basemap layer.
screen shot 2016-08-01 at 4 36 33 pm

I was unable to replicate in my account using the same CSV.
Dataset stored here in a Gist for testing: https://gist.github.com/michellechandra/de2005a6e6d4208d03453adaa09b1e04

## Rollbar Error
screen shot 2016-08-01 at 13 13 33
https://rollbar.com/vizzuality/CartoDB/items/19650/occurrences/14933316071/

Maybe related Rollbar Errors:
screen shot 2016-08-01 at 13 15 10

## Tracker.js Error
**tracker.js:4 Uncaught Error: TrackJS Caught: Cannot read property 'replace' of undefined**

Maybe related to https://github.com/CartoDB/cartodb/issues/9194 ?

### PR DESCRIPTION
**Pull request by matallo**
Fixes #9202.
Fixes #9210.
Fixes #9194.

also, this comes with the fix for selected categories (Carousel)

CR @xavijam

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/data/custom-baselayer-model.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ module.exports = Backbone.Model.extend({
   },
 
   toJSON: function () {
-    var layerOptions = _.clone(_.reject(this.attributes, 'order'));
+    var layerOptions = _.clone(_.omit(this.attributes, ['order', 'id']));
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/data/custom-baselayer-model.js]: Why order and id are omitted?

File: lib/assets/javascripts/cartodb3/editor/layers/basemap-content-view.js [hunk 2]
```diff
@@ -191,16 +191,8 @@ module.exports = CoreView.extend({
...
-    oldCategory && oldCategory.set({ selected: false });
-
     var newCategory = this._categoriesCollection.findWhere({ val: cat });
-
-    if (newCategory) {
-      if (oldCategory && oldCategory.getName() === newCategory.getName()) return;
-
-      newCategory.set({ selected: true });
-    }
+    newCategory && newCategory.set({ selected: true });
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/basemap-content-view.js]: great!

File: lib/assets/javascripts/cartodb3/data/custom-baselayer-model.js (hunk 1 above)
Comment (matallo) [inline lib/assets/javascripts/cartodb3/data/custom-baselayer-model.js]: because they already live as first class citizens

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/custom-baselayer-model.js#L38

**Comment by xavijam** [comment]
Added all tickets related to this problem, we will need to "recover" all broken custom maps, not a big problem though.

**Comment by xavijam** [comment]
Hey, be careful, we are updating CDB submodule (¿?) without a cartodb.uncompressed.js change.

**Comment by matallo** [comment]
yeah, realised that, I'm restoring those :(

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Looks great!
