### PR TITLE
Make all test independent of Internet access

### LINKED ISSUE #7240: Remove the need of Internet connection for tests
```
10:48:54 rspec ./services/datasources/spec/acceptance/datasources_factory_spec.rb:18 # CartoDB::Datasources::DatasourcesFactory#provider_instantiations tests all available provider instantiations
10:48:54 rspec ./services/datasources/spec/acceptance/gdrive_spec.rb:16 # CartoDB::Datasources::Url::GDrive#manual_test with user interaction, tests the full oauth flow and lists files of an account
10:48:54 rspec ./services/datasources/spec/acceptance/public_url_spec.rb:10 # CartoDB::Datasources::Url::PublicUrl#basic_tests Some basic download flows of this file provider, including error handling
10:48:54 rspec ./services/datasources/spec/unit/gdrive_spec.rb:20 # CartoDB::Datasources::Url::GDrive#filters test that filter options work correctly
10:48:54 rspec ./services/importer/spec/acceptance/csv_spec.rb:104 # csv regression tests imports files from Google Fusion Tables
10:48:54 rspec ./services/importer/spec/acceptance/kml_spec.rb:43 # KML regression tests imports KML files from url
10:48:54 rspec ./services/importer/spec/unit/downloader_spec.rb:244 # CartoDB::Importer2::Downloader#source_file returns a source_file name
10:48:54 rspec ./services/importer/spec/unit/downloader_spec.rb:250 # CartoDB::Importer2::Downloader#source_file returns a local filepath
10:48:54 rspec ./spec/requests/api/imports_spec.rb:122 # Imports API imports all the sample data
10:48:54 rspec ./spec/requests/api/imports_spec.rb:148 # Imports API raises an error if the user attempts to import tables when being over quota
```

Maybe some _must_ have access if they _actually_ check the connection. If they don't, we should mock it.

Reported by @jvillarf . More details in CartoDB/cartodb-platform#1851

cc @xavijam @javitonino @gfiorav

### PR DESCRIPTION
**Pull request by javitonino**
Closes #7240

Moves test to use the internal file server so when testing URL connection we don't depend on external online resources.

For Google Drive, stubbing the internal client (from google gem) is enough.

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by javitonino** [comment]
retest this please

**Comment by javitonino** [comment]
CR please @juanignaciosl

File: services/importer/spec/acceptance/csv_spec.rb [hunk 1]
```diff
@@ -102,21 +102,20 @@
...
-          "?query=select+*+from+1dimNIKKwROG1yTvJ6JlMm4-B4LxMs2YbncM4p9g"
-    downloader  = Downloader.new(url)
-    runner      = Runner.new({
-                               pg: @user.db_service.db_configuration_for,
-                               downloader: downloader,
-                               log: CartoDB::Importer2::Doubles::Log.new(@user),
-                               user: @user
-                             })
-    runner.run
+    serve_file 'spec/support/data/dec_2012_modis_forest_change_fusion_tables.csv' do |url|
```
Comment (juanignaciosl) [inline services/importer/spec/acceptance/csv_spec.rb]: Although mocking it is certainly the way to go, I'd keep the old url as documentation of the source of the file, since that csv might be confused with a "normal" one instead of a GFT one. Not important though.

File: spec/helpers/file_server_helper.rb [hunk 2]
```diff
@@ -0,0 +1,45 @@
+module FileServerHelper
```
Comment (juanignaciosl) [inline spec/helpers/file_server_helper.rb]: Nice <3

**Comment by juanignaciosl** [comment]
👍
