### PR TITLE
Include only the tokens for the entities in permissions in the named map

### LINKED ISSUE #9175: Too many auth tokens sent to named maps api
When creating a named map for a privately shared map, the list of available auth tokens is incorrect. The code responsible for generating them is this:
```
 auth_tokens = @visualization.all_users_with_read_permission
                             .map(&:get_auth_tokens)
                             .flatten
                             .uniq
```
- ~~If shared with an organization (and nothing else), this includes no tokens.~~
  - There is a hack that always includes the owner user, so the organization token is always included (see next item).
- If shared with an user, it includes the user token and the organization token (from `get_auth_tokens`) so the whole organization gets access.
- There is nothing here for groups. It kinda works because of #1

Proposed actions:
 - [ ] Include only the tokens related to the actually selected permissions. So return only the user token for users, the organization token should only be included if selecting the visualization.
 - [x] Add a token to `groups` and auto generate it on first call.
 - [x] Include the `group` token in the embed for all groups the user belongs to.

cc @juanignaciosl

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #9175

### CODE REVIEW

**Comment by javitonino** [comment]
Heyo, it's CR time, please @gfiorav

File: app/models/carto/visualization.rb [hunk 1]
```diff
@@ -355,8 +355,9 @@ def invalidate_cache
     CartoDB::Varnish.new.purge(varnish_vizjson_key)
   end
 
-  def all_users_with_read_permission
-    permission.users_with_permissions([CartoDB::Visualization::Member::PERMISSION_READONLY]).push(user)
+  def allowed_auth_tokens
+    entities = [user] + permission.entities_with_read_permission
```
Comment (gfiorav) [inline app/models/carto/visualization.rb]: Aren't you getting the owner twice here?

File: lib/carto/named_maps/template.rb [hunk 2]
```diff
@@ -227,12 +227,7 @@ def auth
         method, valid_tokens = if @visualization.password_protected?
                                  [AUTH_TYPE_SIGNED, @visualization.user.get_auth_tokens]
                                elsif @visualization.organization?
-                                 auth_tokens = @visualization.all_users_with_read_permission
-                                                             .map(&:get_auth_tokens)
-                                                             .flatten
-                                                             .uniq
-
-                                 [AUTH_TYPE_SIGNED, auth_tokens]
+                                 [AUTH_TYPE_SIGNED, @visualization.allowed_auth_tokens]
```
Comment (gfiorav) [inline lib/carto/named_maps/template.rb]: This is now redindant right? Password protected and org shared can use `.allowed_auth_tokens`?

What will happen when a user shares a password protected visualization within the org?

File: spec/models/carto/user_spec.rb [hunk 3]
```diff
@@ -11,6 +11,10 @@ def get_twitter_imports_count_by_user_id(user_id)
     def get_user_by_id(user_id)
       Carto::User.where(id: user_id).first
     end
+
+    def create_user
+      FactoryGirl.create(:carto_user)
+    end
```
Comment (gfiorav) [inline spec/models/carto/user_spec.rb]: Why do you need this abstraction?

File: app/models/carto/visualization.rb (hunk 1 above)
Comment (javitonino) [inline app/models/carto/visualization.rb]: No, in fact I had to add this for existing tests to pass (have a :heart: for that). Permissions only includes the permissions granted in the modal, which may not include the owner (and usually doesn't).

File: spec/models/user_spec.rb [hunk 4]
```diff
@@ -25,6 +25,10 @@ def get_twitter_imports_count_by_user_id(user_id)
     def get_user_by_id(user_id)
       ::User.where(id: user_id).first
     end
+
+    def create_user
+      FactoryGirl.create(:valid_user)
+    end
```
Comment (gfiorav) [inline spec/models/user_spec.rb]: Same here

File: app/models/carto/visualization.rb (hunk 1 above)
Comment (gfiorav) [inline app/models/carto/visualization.rb]: Weird! But ok I guess :grin:

File: lib/carto/named_maps/template.rb (hunk 2 above)
Comment (javitonino) [inline lib/carto/named_maps/template.rb]: Yes, it could be made redundant, but right now it isn't. I will approach this when I do the changes to password protected visualizations #9308. This is only for organizations to keep PR's manageable. Also, this allows me to deploy this without waiting for cartodb.js changes.

**Comment by gfiorav** [comment]
Good tests! 

I have some concerns regarding sharing within org with passwords, so I'll let you review de comments before proceeding.

Nice work!

File: spec/models/carto/user_spec.rb (hunk 3 above)
Comment (javitonino) [inline spec/models/carto/user_spec.rb]: It is used in the shared examples so the same test applies to both user models: https://github.com/CartoDB/cartodb/pull/9312/files/0e1dc708201d1ec29e35730100b8a1c55cee2c28#diff-4b796520136c6d36d55f0ba58ab80103R447

**Comment by javitonino** [comment]
Password protected visualizations shouldn't have changed at all. If you feel like I may have changed some behaviour regarding them, let me know. I intend to approach them in #9308, but not for now (baby steps).

**Comment by gfiorav** [comment]
Yup, got confused. All right, 📦  it!
