### PR TITLE
vector parameter forcing vector flag

### LINKED ISSUE #12478: [vector] vector=true is not working on embeds
STR:
- go to an embed with vector=true in the url like this. https://javi.carto.com/builder/74bb971d-5554-459a-b67d-92834dec63a0/embed?vector=true
- open chrome console and print `vizJSON.vector`, it should be true

When adding the flag vector=true the viz.json should contain `vector:true` so carto.js tries to render the map with vector.

Checking the code looks like it's not doing it: https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/builder/public/embeds_controller.rb#L67

I also think when `vector` param is present should take precedence over the feature flag: the reason is that would allow to test user maps. Right now is just setting that to nil

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #12478. For future reference, it's a partial revert from #12182 (although it's not exactly the same).

### CODE REVIEW

File: app/helpers/vector_helper.rb [hunk 1]
```diff
@@ -0,0 +1,5 @@
+module VectorHelper
+  def vector_render?(visualization, params)
+    visualization.user.has_feature_flag?('vector_vs_raster') || params['vector'] == 'true'
+  end
+end
```
Comment (javitonino) [inline app/helpers/vector_helper.rb]: :trollface:

**Comment by javitonino** [comment]
Like a charm. Just waiting for deploys to be unlocked.
