### PR TITLE
Fix error handling if dropbox file is not found

### LINKED ISSUE #12300: Fix error handling if Dropbox file is not found
NoMethodError: undefined method `http_response' for #<DropboxApi::Errors::NotFoundError: path/not_found/> if a Dropbox file doesn't exist:

```
DropboxApi::Errors::NotFoundError: path/not_found/.
+ 5 non-project frames
6
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/services/datasources/lib/datasources/url/dropbox.rb", line 158 in get_resource_metadata
7
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/app/models/synchronization/member.rb", line 321 in get_downloader
8
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/app/models/synchronization/member.rb", line 245 in get_runner
9
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/app/models/synchronization/member.rb", line 187 in run
10
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/lib/resque/synchronization_jobs.rb", line 13 in block in perform
11
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/lib/resque/base_job.rb", line 21 in call
12
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/lib/resque/base_job.rb", line 21 in run_action
13
File "/home/ubuntu/www/production.cartodb.com/releases/20170612072949/lib/resque/synchronization_jobs.rb", line 10 in perform
```

[occurrences](https://rollbar.com/carto/CartoDB/items/23550/?item_page=0&item_count=100&#instances)

### Steps to Reproduce
1. Sync a dataset with a Dropbox file.
2. Delete the file in Dropbox.
3. Sync again

### Current Result

Fails with the previous error.

### Expected result

Fails without logging an error (it's expected, just "debug" trace if any).

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #12300.

Honestly, I haven't done a test because it's a simple error management improvement, and it should rely on mocking, so I think that it doesn't provide enough value.

_Tests are actually green, they were reversed at Jenkins and I cancelled the wrong one. [Frontend](https://ci.cartodb.net/job/CartoDB-PR-testing-frontend/1682/console), [Backend](https://ci.cartodb.net/job/CartoDB-PR-testing-backend/1693/console)._

### CODE REVIEW

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by juanignaciosl** [comment]
Retest this please

File: app/models/synchronization/member.rb [hunk 1]
```diff
@@ -204,7 +204,11 @@ def run
         notify
 
       rescue => exception
-        CartoDB::Logger.error(exception: exception, sync_id: id)
+        if exception.is_a? CartoDB::Datasources::NotFoundDownloadError
```
Comment (mayoral) [inline app/models/synchronization/member.rb]: I think we can improve this section with one rescue section per exception, instead of handling all inside the generic rescue with ifs. What do you think?

Comment (juanignaciosl) [inline app/models/synchronization/member.rb]: Good point!

File: app/models/synchronization/member.rb [hunk 2]
```diff
@@ -203,42 +203,12 @@ def run
...
 
+      rescue CartoDB::Datasources::NotFoundDownloadError => exception
+        CartoDB::Logger.debug(exception: exception, sync_id: id)
+        handle_run_error(log, exception, importer)
       rescue => exception
         CartoDB::Logger.error(exception: exception, sync_id: id)
-        log.append_and_store exception.message, truncate = false
-        log.append exception.backtrace.join("\n"), truncate = false
-
-        if importer.nil?
```
Comment (juanignaciosl) [inline app/models/synchronization/member.rb]: @mayoral after your comment I first refactored my change in order to avoid adding _yet another_ if. Nevertheless, when I tried to refactor this part I realized that it depends on `importer` value. I don't want to change the behaviour and, in order to do it, I should have to add an `importer.nil?` check at every rescue. It becomes unreadable. Although I don't like those `if`s, I think that a bigger refactor is outside the scope of a simple error fix. What do you think?

Comment (mayoral) [inline app/models/synchronization/member.rb]: In the original code, all was enough understandable, so maybe it worths if we revert this last commit.

Comment (juanignaciosl) [inline app/models/synchronization/member.rb]: Ok!

**Comment by javitonino** [comment]
Seems to work pretty well, and we even give the user a nice error: "Sync failed. Error code 1017: File not found, you must import it again.". Only debug traces in Rollbar.
