### PR TITLE
User deletion with geocodings does not work

### LINKED ISSUE #3073: User deletion with geocodings does not work
While deleting an user which has an import with geocodings:

```
ERROR:  update or delete on table "data_imports" violates foreign key constraint "geocodings_data_import_id_fkey" on table "geocodings"
DETAIL:  Key (id)=(....) is still referenced from table "geocodings".
STATEMENT:  DELETE FROM "data_imports" WHERE "id" = '....'
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

It seems that the `data_import` model is dropped before the `geocoding` model, but does not cascade the deletion nor drops the dependencies first. (ask me for an example of this in prod)

### PR DESCRIPTION
**Pull request by Kartones**
Fixes #3073

### CODE REVIEW

**Comment by Kartones** [comment]
@juanignaciosl CR this please

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2889/))

File: app/models/user.rb [hunk 1]
```diff
@@ -225,17 +225,17 @@ def before_destroy
...
-      self.assets.each { |a| a.destroy }
-      CartoDB::Synchronization::Collection.new.fetch(user_id: self.id).destroy
-
+      # There's a FK from geocodings to data_import.id so must be deleted in proper order
       if self.organization.nil? || self.organization.owner.nil? || self.id == self.organization.owner.id
         self.geocodings.each { |g| g.destroy }
       else
         assign_geocodings_to_organization_owner
       end
+      self.data_imports.each { |d| d.destroy }
```
Comment (juanignaciosl) [inline app/models/user.rb]: @Kartones I think this will still fail if you try to delete an organization user with geocodings at data imports (take a look at [my previous comment](https://github.com/CartoDB/cartodb/issues/3073#issuecomment-90880904)). I did not suggest a strategy because I'm not sure what would be better. Assigning data_imports to owner instead of delete? Clear data_import_id from geocodings? Not sure.

If you want to do another test to check this behavior you can copy the test data at [this test](https://github.com/CartoDB/cartodb/blob/master/spec/models/user_spec.rb#L525).

Comment (Kartones) [inline app/models/user.rb]: `Assigning data_imports to owner instead of delete?` +1
This way data keeps consistent until owner gets deleted. If they're tied, let's move them together.

Comment (juanignaciosl) [inline app/models/user.rb]: Ok, although if we want to be strict it should be more difficult than it will actually be: `data_imports` has a `visualization_id` that _should_ be a FK to `visualizations`. If you move the import without also moving the visualization that id will not point to an actual value (since the visualization will be deleted).

Comment (Kartones) [inline app/models/user.rb]: Then I'll kill the `visualization_id`, as is nullable and we're not moving the vis to the owner. Thanks for pointing it out!

Comment (Kartones) [inline app/models/user.rb]: Nice, no need to do anything: https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L2364

Comment (juanignaciosl) [inline app/models/user.rb]: :dancer:

**Comment by juanignaciosl** [comment]
:+1:
