### PR TITLE
Fix for gz importation from URL

### LINKED ISSUE #4254: Error importing from gzipped url
The importer fails when on the editor using a url of a gziped geojson. The trace on the logs are:

```
2015-06-30 17:37:16 UTC: Fetching datasource public_url metadata for item id https://URL_TO_THE_GZIPPED_GEOJSON.gz
2015-06-30 17:37:16 UTC: File will be downloaded from https://URL_TO_THE_GZIPPED_GEOJSON.gz
2015-06-30 17:37:17 UTC: Before importer run
2015-06-30 17:37:17 UTC: Starting import for /tmp/imports/20150630-29162-jhrr71/Campground.geojson.gz.tgz
```

Uploading it from a local file works so it's only affecting a task that come from urls.

### PR DESCRIPTION
**Pull request by ethervoid**
Solved the problem when a user is trying to import a GZ from an URL and gets error because the dowloader adds a `tgz` extension to the end.

**THIS PR FIXES #4254**

// **Reviewer:** @Kartones

### CODE REVIEW

File: services/importer/lib/importer/downloader.rb [hunk 1]
```diff
@@ -292,11 +292,11 @@ def extension_by_content_type(content_type)
       def name_with_extension(name, headers)
         return name if content_type.nil? || content_type.empty?
 
-        extension = File.extname(name)
-        extension_from_content_type = extension_by_content_type(content_type)
+        file_extension = File.extname(name).split('.').last
+        content_type_extensions = extension_by_content_type(content_type)
+        extension_from_content_type = content_type_extensions.select { |ext| ext == file_extension }.first
```
Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: Ruby's awesome "many ways to do the same". You can also do:
```ruby
extension_from_content_type = content_type_extensions.select { |ext| ext == file_extension }.first
if !file_extension.nil? && !file_extension.empty? && content_type_extensions.include?(file_extension)
```

(`.include?` is handy for arrays)

**Comment by Kartones** [comment]
Nice, but I see no test, I know there weren't but so that you learn would be nice to add one :)

**Comment by ethervoid** [comment]
Tests are here #4343 because I needed in the master branch to use some fixtures as url

File: services/importer/lib/importer/downloader.rb (hunk 1 above)
Comment (ethervoid) [inline services/importer/lib/importer/downloader.rb]: Yup you're right. I've done that way to remove complexity in the if because was a bit large :))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4791/))

**Comment by Kartones** [comment]
ok, then good to go!

**Comment by ethervoid** [comment]
Thank you :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4801/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4810/))

**Comment by ethervoid** [comment]
Please recheck @Kartones because there are changes. I've added unit tests to check differents Content-Types and I've refactorized the code to be more clear

File: services/importer/lib/importer/downloader.rb [hunk 2]
```diff
@@ -290,19 +290,29 @@ def extension_by_content_type(content_type)
...
+        name_without_extension = File.basename(name, ".*")
 
-        return name if extension_from_content_type.nil?
+        #Check for a content-type extension that matches the file extension
+        if (file_extension.nil? or file_extension.empty?) and content_type_extensions.length >= 1
+            return "#{name_without_extension}.#{content_type_extensions.first}"
+        end
 
-        "#{name}.#{extension_from_content_type}"
+        extension_from_content_type = content_type_extensions.select { |ext| ext == file_extension }.first
```
Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: You can join this two lines on one, `.first` will return nill if got an empty array but throw no error:
```
unless content_type_extensions.select { |ext| ext == file_extension }.first.nil?
  return name
...
```

File: services/importer/lib/importer/downloader.rb [hunk 3]
```diff
@@ -290,19 +290,29 @@ def extension_by_content_type(content_type)
...
-           (extension_from_content_type.nil? || (extension == extension_from_content_type))
-           return name
-        end
+        file_extension = File.extname(name).split('.').last
+        name_without_extension = File.basename(name, ".*")
 
-        return name if extension_from_content_type.nil?
+        #Check for a content-type extension that matches the file extension
+        if (file_extension.nil? or file_extension.empty?) and content_type_extensions.length >= 1
+            return "#{name_without_extension}.#{content_type_extensions.first}"
```
Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: Why are we stripping the original extension? It's no big deal, but previously we just appended new extension

File: services/importer/lib/importer/downloader.rb [hunk 4]
```diff
@@ -290,19 +290,29 @@ def extension_by_content_type(content_type)
...
+        end
 
-        "#{name}.#{extension_from_content_type}"
+        extension_from_content_type = content_type_extensions.select { |ext| ext == file_extension }.first
+        if !extension_from_content_type.nil?
+            return name
+        else
+            # In case that content-type doesn't match the file extension, we change the file
+            # extension to adaquate to the content-type extension
+            return "#{name_without_extension}.#{content_type_extensions.first}"
```
Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: Uhh, one small thing: "official" formatting is 2 spaces per tab, spaces instead of tabs. @lbosque will bit you if you don't!

File: services/importer/lib/importer/downloader.rb (hunk 3 above)
Comment (ethervoid) [inline services/importer/lib/importer/downloader.rb]: As far as i know this was the bug's reason. When you came to this step `name` was for example `file.gz` but the `Content-type` header is `application/x-gzip` so tgz extension is added to the end of the `name` creating a `file.gz.tgz` file which is wrong.

Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: mm fair enough. In other scenarios we got things like `download.php` so wasn't hurting adding the extension, but true that here might, so then :+1:

File: services/importer/lib/importer/downloader.rb (hunk 4 above)
Comment (ethervoid) [inline services/importer/lib/importer/downloader.rb]: My editor is configured to use 4 spaces instead of tab, I'll change to use 2 spaces instead of 4

File: services/importer/lib/importer/downloader.rb (hunk 2 above)
Comment (ethervoid) [inline services/importer/lib/importer/downloader.rb]: Ok, normally I try to avoid large lines to avoid complexity while i'm reading code but I'll change it

Comment (Kartones) [inline services/importer/lib/importer/downloader.rb]: ok,  that was more personal taste, so as you see fit. if line gets big I just split it... like:
```
unless content_type_extensions.select { |ext| ext == file_extension }
                              .first.nil?
  return name
...
```

but is personal taste

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4826/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4829/))

**Comment by ethervoid** [comment]
I've refactored and simplify this part with the help of @juanignaciosl , it passes the tests and I've test in staging. Please another CR, sorry :(, and I will deploy today :)

// @CartoDB/backend

File: services/importer/lib/importer/downloader.rb [hunk 5]
```diff
@@ -40,51 +40,51 @@ class Downloader
       CONTENT_TYPES_MAPPING = [
         {
           content_types: ['text/plain'],
-          extension: 'txt'
+          extension: ['txt']
```
Comment (juanignaciosl) [inline services/importer/lib/importer/downloader.rb]: Maybe I'm too rigid here, but if this is an array it should be named `extensions`. Weak typing makes naming more important. I'd change it if it's not risky .

File: services/importer/lib/importer/downloader.rb [hunk 6]
```diff
@@ -290,19 +290,22 @@ def extension_by_content_type(content_type)
...
         return name if content_type.nil? || content_type.empty?
 
-        extension = File.extname(name)
-        extension_from_content_type = extension_by_content_type(content_type)
-
-        if !extension.nil? && !extension.empty? && 
-           (extension_from_content_type.nil? || (extension == extension_from_content_type))
-           return name
-        end
+        content_type_extensions = extension_by_content_type(content_type)
```
Comment (juanignaciosl) [inline services/importer/lib/importer/downloader.rb]: Same here: `extensions_by_content_type`

File: services/importer/lib/importer/downloader.rb [hunk 7]
```diff
@@ -290,19 +290,22 @@ def extension_by_content_type(content_type)
...
+        # We don't have extension registered for that content-type
+        return name if content_type_extensions.nil?
```
Comment (juanignaciosl) [inline services/importer/lib/importer/downloader.rb]: Since `extension(s)_by_content_type` it should not return `nil` but empty array. That would make following code simpler indeed.

File: services/importer/lib/importer/downloader.rb [hunk 8]
```diff
@@ -290,19 +290,22 @@ def extension_by_content_type(content_type)
...
 
-        return name if extension_from_content_type.nil?
+        file_extension = File.extname(name).split('.').last
+        name_without_extension = File.basename(name, ".*")
 
-        "#{name}.#{extension_from_content_type}"
+        #Check for a content-type extension that matches the file extension
+        if (file_extension.nil? || file_extension.empty?) || !content_type_extensions.include?(file_extension)
```
Comment (juanignaciosl) [inline services/importer/lib/importer/downloader.rb]: I _think_ this is wrong, or at least not clear. Why using `content_type_extensions.first` if `!content_type_extensions.include?(file_extension)`?

Comment (juanignaciosl) [inline services/importer/lib/importer/downloader.rb]: PD: I'd do a test battery for this method, _really_ easy to do and will give a lot of trust.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4838/))
