### PR TITLE
Choosing actual layer table owner

### LINKED ISSUE #8974: Create map with shared dataset doesn't work
STR

1. Share a dataset with user.
2. Create a map with that user and that dataset.

The map should display the data. Nevertheless there're errors on SQL API requests and map won't show data. It seems to be a problem generating the SQL.

cc @gfiorav @javitonino 

PS: adding layers with shared datasets works.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #8974

### CODE REVIEW

**Comment by juanignaciosl** [comment]
What to test:

- Organization users:
  - Create map with public, own table. Check public view.
  - Add layer with public, own table. Check public view.
  - Create map with private, own table. Check public view.
  - Add layer with private, own table. Check public view.
  - Create map with public, shared table. Check public view.
  - Add layer with public, shared table. Check public view.
  - Create map with private, shared table. Check public view.
  - Add layer with private, shared table. Check public view.
- Normal user
  - Create map with public, own table. Check public view.
  - Add layer with public, own table. Check public view.
  - Create map with private, own table. Check public view.
  - Add layer with private, own table. Check public view.

... for Editor and Builder

😢

**Comment by juanignaciosl** [comment]
@gfiorav  could you do a first CR, please? Disclaimer: I haven't 100% tested it yet (see the test cases comment and feel free to add anything you think), but this is slow and annoying to test and I want to discuss the approach with you before. This change is huge and risky, the more eyes and brains aware of this, the better.

When we get to a final fix I'll do a test suite covering this before merging, because this can't happen again U_U

cc @javitonino , as he will be asked for CR later.

File: lib/carto/named_maps/template.rb [hunk 1]
```diff
@@ -167,6 +167,19 @@ def visibility_wrapped_sql(sql, index)
         "SELECT * FROM (#{sql}) AS wrapped_query WHERE <%= layer#{index} %>=1"
       end
 
+      def generate_sql(layer, user)
+        # Inspired from CartoDB::LayerModule::Presenter#default_query_for
+        layer_options = layer.options
+        user_name = layer_options['user_name']
+        table_name = layer_options['table_name']
```
Comment (gfiorav) [inline lib/carto/named_maps/template.rb]: I'd symbolise fetch these

File: lib/carto/named_maps/template.rb [hunk 2]
```diff
@@ -167,6 +167,19 @@ def visibility_wrapped_sql(sql, index)
...
+
+        if user_name.present? && user.username != user_name && table_name.present?
+          %{ select * from "#{user_name}".#{table_name} }
+        else
+          layer.wrapped_sql(user)
+        end
```
Comment (gfiorav) [inline lib/carto/named_maps/template.rb]: You're not taking into account the possibility that a `:query` and/or a `:query_wrapper` is provided in layer options and has `<= sql >` that needs to be replaced by the sql you calculate here. Look at `wrapped_sql`:

```ruby
def wrapped_sql(user)
  query = options[:query]

  sql = if query.present?
          query
        else
          "SELECT * FROM #{qualified_table_name(user)}"
        end

  query_wrapper = options[:query_wrapper]
  sql = query_wrapper.gsub('<%= sql %>', sql) if query_wrapper.present? && torque?

  sql
end
```

**Comment by gfiorav** [comment]
I've made some comments regarding some concerns I have!

File: lib/carto/named_maps/template.rb (hunk 2 above)
Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: Proposals?

Comment (juanignaciosl) [inline lib/carto/named_maps/template.rb]: PS: your comment is collapsed by Github because of an unrelated commit.

Comment (gfiorav) [inline lib/carto/named_maps/template.rb]: Maybe have `wrapper_sql` receive params so to overwrite the normal `"SELECT * FROM #{qualified_table_name(user)}"` behaviour or overwrite the `:query` with the right params. It's ugly, but `:query` will have bad data (other user schema) that needs to be sanitised in this case.

**Comment by juanignaciosl** [comment]
@gfiorav I've taken into account your two comments and moved a symbolized version of the patch from the named map to layer `wrapped_sql` method, so I think that I fix your relevant catch. Take a look at the commit and the full code while I keep testing this, please. I've also added some code to avoid double _schematization_ of the table name.

PS: create new comment threads for the next insights, as Github won't expand older ones once they've been collapsed.

File: app/controllers/carto/api/layers_controller.rb [hunk 3]
```diff
@@ -15,8 +15,8 @@ def layers_by_map
         raise RecordNotFound if @parent.nil?
 
         layers = @parent.layers(@parent).map { |layer|
-            Carto::Api::LayerPresenter.new(layer, { viewer_user: current_user, user: @parent.user }).to_poro
-          }
+          Carto::Api::LayerPresenter.new(layer, viewer_user: current_user, user: owner_user(layer)).to_poro
+        }
```
Comment (gfiorav) [inline app/controllers/carto/api/layers_controller.rb]: only if you need to make a new commit anyway: `do...end` for multiple lines is nice :)

File: app/models/carto/layer.rb [hunk 4]
```diff
@@ -140,12 +145,20 @@ def user
...
             else
-              "SELECT * FROM #{qualified_table_name(user)}"
+              user_name = options[:user_name]
+              table_name = options[:table_name]
+
+              if table_name.present? && !table_name.include?('.') && user_name.present? && user.username != user_name
+                %{ select * from "#{user_name}".#{table_name} }
+              else
+                "SELECT * FROM #{qualified_table_name(user)}"
+              end
```
Comment (gfiorav) [inline app/models/carto/layer.rb]: Yes, this feels a lot safer now!

File: app/models/carto/layer.rb [hunk 5]
```diff
@@ -140,12 +145,20 @@ def user
...
 
       sql = if query.present?
               query
             else
-              "SELECT * FROM #{qualified_table_name(user)}"
+              user_name = options[:user_name]
+              table_name = options[:table_name]
+
+              if table_name.present? && !table_name.include?('.') && user_name.present? && user.username != user_name
+                %{ select * from "#{user_name}".#{table_name} }
```
Comment (gfiorav) [inline app/models/carto/layer.rb]: Cosmetic, of course, but why not use caps for SQL reserved words and use `%{}`? If there is a good reason for any of them, please update line 160 as well :)

File: app/models/carto/layer.rb [hunk 6]
```diff
@@ -177,7 +190,10 @@ def affected_table_names
 
     def tables_from_table_name_option
       return[] if options.empty?
-      ::Table.get_all_user_tables_by_names([options.symbolize_keys[:table_name]], user)
+      user_name = options.symbolize_keys[:user_name]
+      table_name = options.symbolize_keys[:table_name]
```
Comment (gfiorav) [inline app/models/carto/layer.rb]: If you symbolise here, you should also symbolise 154 and 155.

File: app/models/layer.rb [hunk 7]
```diff
@@ -210,7 +214,10 @@ def tables_from_query_option
   end
 
   def tables_from_table_name_option
-    ::Table.get_all_by_names([options.symbolize_keys[:table_name]], user)
+    user_name = options.symbolize_keys[:user_name]
+    table_name = options.symbolize_keys[:table_name]
```
Comment (gfiorav) [inline app/models/layer.rb]: same here

**Comment by gfiorav** [comment]
It looks safe to me!

You could deploy this now. If you find any improvements to make, maybe take my other comments into account.

📦 !

File: app/controllers/carto/api/layers_controller.rb (hunk 3 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/layers_controller.rb]: 👍

File: app/models/carto/layer.rb (hunk 5 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: We have no style convention about SQL caps. In general I prefer small caps but I don't really care. If @javitonino  and you agree upon any criteria I'll follow it. I'll also use it for new and changed code.

I prefer not adding anything smart for extracting `select *`. It's actual duplication, but any alternative is more complex and doesn't add any value, IMHO.

File: app/models/carto/layer.rb (hunk 6 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: Yep, and only once. On it!

File: app/models/layer.rb (hunk 7 above)
Comment (juanignaciosl) [inline app/models/layer.rb]: 👍

**Comment by juanignaciosl** [comment]
No, I won't 🚢  yet. Best scenario: tomorrow early morning. I still have to run the tests and, if possible, cover the changes.

**Comment by juanignaciosl** [comment]
@javitonino could you do a second CR, please? Editor tests with normal layers have worked. I can't test Torque because of #9017, and I've just seen an error with the builder, probably unrelated.

File: app/controllers/carto/api/layers_controller.rb [hunk 8]
```diff
@@ -66,6 +66,19 @@ def map_from_params
         @parent = Carto::Map.where(id: params[:map_id]).first
       end
 
+      private
+
+      def owner_user(layer)
+        if current_user.nil? || @parent.user.id != current_user.id
+          # This keeps backwards compatibility with map user assignment. See #8974
+          @parent.user
```
Comment (javitonino) [inline app/controllers/carto/api/layers_controller.rb]: Does this work in the following case?
 - New visualization, so `visualization.user == map.user != dataset.user`
 - Visitor is anonymous, so `current_user == nil`

I think in that case, it goes into this code path, and takes the user name from the map, which would be incorrect (it should take the user from the layer/dataset).

**Comment by javitonino** [comment]
I came up with a case where this might be wrong, although I may be totally mistaken. I will take another look first thing tomorrow, with a fresh head.

**Comment by juanignaciosl** [comment]
@javitonino hold on, because this won't work with the builder U_U.

File: app/controllers/carto/api/layers_controller.rb (hunk 8 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/layers_controller.rb]: The user name from the map (now) is correct, it's the same than layer's and visualization's.

**Comment by juanignaciosl** [comment]
@javitonino although I still have to do deep testing, latest commit should fix the builder issue, you can begin the CR whenever you want.

File: app/controllers/carto/api/layers_controller.rb (hunk 8 above)
Comment (javitonino) [inline app/controllers/carto/api/layers_controller.rb]: I think I see how it works now. The passed username would be the owner of the visualization, not of the shared dataset. So, `viewer_user = nil`, `user = vis_user`.  In `Carto::LayerPresenter.qualify_table_name` I think it would go through the qualified table name branch and work.

A mess (not a comment of your PR) but it works. :sparkles:

File: app/controllers/carto/api/vizjson3_presenter.rb [hunk 9]
```diff
@@ -558,14 +558,12 @@ def layer_name
         layer_alias = @layer.options.fetch('table_name_alias', nil)
         table_name  = @layer.options.fetch('table_name')
 
-        return table_name unless layer_alias && !layer_alias.empty?
-        layer_alias
+        layer_alias && !layer_alias.empty? ? layer_alias : table_name
```
Comment (javitonino) [inline app/controllers/carto/api/vizjson3_presenter.rb]: `layer_alias.present?` may be cleaner here

File: app/controllers/carto/api/vizjson3_presenter.rb [hunk 10]
```diff
@@ -558,14 +558,12 @@ def layer_name
...
       end
 
-      def sql_from(options)
-        query = options.fetch('query', '')
-        return default_query_for(options) if query.nil? || query.empty?
-        query
+      def sql_from(layer)
+        query = layer.options.fetch('query', '')
+        query.nil? || query.empty? ? layer.default_query : query
```
Comment (javitonino) [inline app/controllers/carto/api/vizjson3_presenter.rb]: Same here with `layer.blank?`. Mainly, I don't like trusting the order of operations when ternary operators are involved.

File: app/controllers/carto/api/vizjson3_presenter.rb (hunk 9 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/vizjson3_presenter.rb]: Sure. I only refactored the double exit point without seeing beyond that.

File: app/controllers/carto/api/vizjson3_presenter.rb (hunk 10 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/vizjson3_presenter.rb]: `.present?` 👍

File: app/models/carto/layer.rb [hunk 11]
```diff
@@ -177,7 +197,11 @@ def affected_table_names
 
     def tables_from_table_name_option
       return[] if options.empty?
-      ::Table.get_all_user_tables_by_names([options.symbolize_keys[:table_name]], user)
+      sym_options = options.symbolize_keys
+      user_name = sym_options[:user_name]
+      table_name = sym_options[:table_name]
+      schema_prefix = user_name.present? && table_name.present? && !table_name.include?('.') ? %{"#{user_name}".} : ''
```
Comment (javitonino) [inline app/models/carto/layer.rb]: I'm alergic to trusting the order of operations with ternary operators in the mix :stuck_out_tongue:

File: app/controllers/carto/api/layers_controller.rb (hunk 8 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/layers_controller.rb]: Yup, really messy. When the old editor is gone I'll gather coders with torches and burn a lot of code around this >_<

File: app/models/carto/layer.rb [hunk 12]
```diff
@@ -140,18 +146,32 @@ def user
...
+      else
+        sql
+      end
+    end
 
-      query_wrapper = options[:query_wrapper]
-      sql = query_wrapper.gsub('<%= sql %>', sql) if query_wrapper.present? && torque?
+    def default_query(user = nil)
+      sym_options = options.symbolize_keys
+      query = options[:query]
```
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: outch, good catch!

File: app/controllers/carto/api/vizjson3_presenter.rb (hunk 10 above)
Comment (javitonino) [inline app/controllers/carto/api/vizjson3_presenter.rb]: `.blank?` is the antonym of `.present?`. But `present?` and reversing the condition works too.

File: app/models/carto/layer.rb (hunk 11 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: 😆  how come? I don't mind changing it to an if, but ternary operation condition evaluation order is no different than an if ;-)

File: app/controllers/carto/api/vizjson3_presenter.rb (hunk 10 above)
Comment (juanignaciosl) [inline app/controllers/carto/api/vizjson3_presenter.rb]: Yes, I prefer using `present?` and reversing. `blank?` is better if there's only one condition (to avoid `!whatever.present?`), but if there's an `else` being positive first is easier to read.

File: app/models/carto/layer.rb (hunk 11 above)
Comment (javitonino) [inline app/models/carto/layer.rb]: PHP + an aweful codestyle with nested ternaries. Did you know that some languages have right-associative ternaries and others do left-associativity? Not something you wold have to know because you shouldn't use more than one ternary per-expression. Also, `and`/`or` operators usually have lower precedence than ternaries but `&&`/`||` have higher one.

Anyway, this code is fine, easy to read and works as expected. I may have a little bit of PTSD from previous projects.

Comment (juanignaciosl) [inline app/models/carto/layer.rb]: :D I'll keep it as a treatment for your PTSD then :-)

**Comment by javitonino** [comment]
Looks good. Was thinking about other potentially problematic pieces of code but this should cover everything I can think of right now. Good job in tracking all of this, I can only imagine... :+1:

**Comment by juanignaciosl** [comment]
@javitonino , @gfiorav thank you for the CRs. I'll test and cover. I'll ping you again before the final merge. :fingers_crossed:

**Comment by juanignaciosl** [comment]
Ok, @javitonino (back), @alonsogarciapablo (front) , last CR before merging?

**Comment by javitonino** [comment]
:+1:

File: lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js [hunk 13]
```diff
@@ -83,11 +83,10 @@ module.exports = Backbone.Collection.extend({
       var sourceId = nodeIds.next(o.letter);
 
       if (o.table_name && (!o.source || o.source === sourceId)) {
-        o.table_name = o.table_name && o.table_name.replace(/"/g, '');
```
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js]: Not sure why this was introduced in the first place... why are we adding the double quotes back? `SELECT foo FROM user.name` to `SELECT bar FROM "user".name`?

Comment (juanignaciosl) [inline lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js]: In PostgreSQL double quoting schemas or table names is useful to avoid problems with special characters. For example, for `juanignaciosl-ded01` user you need to use double quotes because of the dash. I asked @xavijam about the replacement and he said that "about that, I removed them on purpose, I didn’t know they were necessary".

Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js]: Thanks for the explanation! 👍 👍 👍

**Comment by juanignaciosl** [comment]
Thank you, @alonsogarciapablo 

Master merged (and some redundant parenthesis that I previously forgot pushing, @javitonino ). I'll merge and deploy after 🍏

**Comment by juanignaciosl** [comment]
Had to do an extra merge because of package.json, but last test passed, so I'm deploying.
