### PR TITLE
Failing spec for user deletion with geocodings

### LINKED ISSUE #11011: User deletion fails in org users with multiple geocodings
### Context
https://github.com/CartoDB/cartodb-management/issues/4740 

### Steps to Reproduce
1. Create a user in an org
2. Add two geocodings
3. Delete the user

### Current Result
It fails, the issue is in [`assign_search_tweets_to_organization_owner`](https://github.com/CartoDB/cartodb/blob/0bed788b09d84a4acdd8120cf7361c72d7ef39ea/app/models/user.rb#L1688) which iterates over an array as it's modifying it, so it only reassigns half the geocodings. Simplified example:
```
a=[1,2,3,4]
a.each do |i| a.delete(i) end
a == [2, 4]
```

Also see https://github.com/CartoDB/cartodb/pull/11013 for a PR with a spec that checks this that I did in order to reproduce the issue. Feel free to continue working on top of that (or delete the branch/PR if not).

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #11011

Changes `geocodings` to `geocodings_dataset`. The first one is an array (called association cache in the docs) kept by Sequel which updates as geocodings are associated/disassociated from the user. Due to how the iterator works, this was making it iterate only over half the elements.

The `_dataset` returns a Dataset object (representds a query). Calling `.each` on it,, executes the query (internally, calls `. all`) and returns an array of results, which is static, so iterating over it is safe.

Doc: http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html#label-Dataset+Method

A little cleanup as an extra.

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -1673,26 +1673,26 @@ def http_client
...
     CartoDB::Logger.error(exception: e, message: 'Error assigning search tweets to org owner', user: self)
   end
 
   # INFO: assigning to owner is necessary because of payment reasons
   def assign_geocodings_to_organization_owner
-    return if self.organization.nil? || self.organization.owner.nil? || self.id == self.organization.owner.id
-    self.geocodings.each { |g|
-      g.user = self.organization.owner
+    return if organization.nil? || organization.owner.nil? || organization_owner?
+    geocodings_dataset.each do |g|
```
Comment (juanignaciosl) [inline app/models/user.rb]: Oh, I'm pretty sure that I made that mistake, time ago. Anyway, I can't find explicit documentation on that at Sequel page (I've searched at [this](https://github.com/jeremyevans/sequel/blob/master/doc/association_basics.rdoc), [this](http://sequel.jeremyevans.net/rdoc/files/doc/advanced_associations_rdoc.html), [this](http://sequel.jeremyevans.net/2011/04/14/dynamic-association-modification.html), [this](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html), [this](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/Associations/DatasetMethods.html)...). Although this _currently_ works, maybe adding an explicit `.all` to `geocodings_dataset` might be better. What do you think?

PD: good catch!

File: spec/models/user_spec.rb [hunk 2]
```diff
@@ -725,28 +725,38 @@ def overquota(delta = 0)
...
-      st.state = ::SearchTweet::STATE_COMPLETE
-      st.save
+      SearchTweet.create(tweet_attributes.merge(retrieved_items: 5))
+      SearchTweet.create(tweet_attributes.merge(retrieved_items: 10))
 
       u1.reload
       u2.reload
-      u2.get_geocoding_calls.should == 1
-      u2.get_twitter_imports_count.should == 5
+      u2.get_geocoding_calls.should == 3
```
Comment (juanignaciosl) [inline spec/models/user_spec.rb]: Minor: consider refactor these magic numbers.

File: app/models/user.rb (hunk 1 above)
Comment (javitonino) [inline app/models/user.rb]: Not a bad idea to add the explicit `.all`, specially since the `_dataset` methods is a bit complicated, added.
