### PR TITLE
Better sequel qualified identifiers

### LINKED ISSUE #6138: publish map error on maps that have dataset name that start with an underscore
When you publish a map that has a dataset with a name that starts with an underscore, you get an error message: **Failed to load resource: the server responded with a status of 403 (Forbidden)**.

Steps:

1- Import a dataset with a name that starts with an underscore, for example "_dataset"
2- Create a map from dataset
3- Select "Publish" from map
4- Copy url from "Get the link" option
5- Paste the url in a new tab
Get this error message:
screen shot 2015-11-16 at 16 57 07

**If the dataset is renamed and  the underscore is removed from the beginning of the name  ("dataset") and you repeat the previous steps you get the map correctly published:**
screen shot 2015-11-16 at 16 59 26

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #6138

cc/ oriolbx

### CODE REVIEW

**Comment by rafatower** [comment]
what is the root cause of the problem? I prefer @juanignaciosl to give feedback for this kind of changeset

File: app/models/table.rb [hunk 1]
```diff
@@ -1219,7 +1226,7 @@ def update_name_changes
 
   # @see https://github.com/jeremyevans/sequel#qualifying-identifiers-columntable-names
   def sequel_qualified_table_name
-    "#{owner.database_schema}__#{@user_table.name}".to_sym
+    Sequel.qualify(owner.database_schema, @user_table.name)
   end
```
Comment (gfiorav) [inline app/models/table.rb]: @rafatower this was the root cause. If the table name started with `_`, the previous manual qualification produced `schema___table_name`, from which postgres interprets that the table name is `schema` (not `_table_name`) and produces an error `PG ERROR: relation name 'schema' does not exist`.

It's fixed using the appropriate Sequel method for qualifying table names.

**Comment by gfiorav** [comment]
@juanignaciosl , please CR.

I'm testing thoroughly in staging for orgs and normal users... might be worth to go through smoke tests. Form my testing I seems OK so far.

**Comment by rafatower** [comment]
> what's the root cause of the problem?

Could you please kindly answer my question? better along with the issue description #6138

File: app/models/table.rb [hunk 2]
```diff
@@ -1192,7 +1192,14 @@ def update_name_changes
 
       unless register_table_only
         begin
-          owner.in_database.rename_table(@name_changed_from, name)
+          # Quite infuriating, but no other way for '_' prefixed names
+          if name.start_with?('_')
+            temp_name = "#{10.times.map{ rand(9) }.join}_" + name
+            owner.in_database.rename_table(@name_changed_from, temp_name)
+            owner.in_database.rename_table(temp_name, name)
```
Comment (rafatower) [inline app/models/table.rb]: why do you need to change it twice passing through a temp name?

Comment (gfiorav) [inline app/models/table.rb]: Sequel will use a temp name internally when renaming that is formed like: `_<table name>`. When you rename any to the same name starting with an underscore, sequel will use a temp name that is the same as the destination name, so in the process, postgres will complain `PG ERROR: '_<table name>' already exists`.

File: spec/models/table_spec.rb [hunk 3]
```diff
@@ -86,6 +86,15 @@ def @data_import.data_source=(filepath)
...
     end
 
+    it 'can use underscore prefixed names for tables' do
+      table = Table.new
+      table.user_id = $user_1.id
+      table.name = '_name'
+      table.save
+
+      table.valid?.should == true
+    end
```
Comment (rafatower) [inline spec/models/table_spec.rb]: I'd also check that the final name is indeed not "standardized" to anything else, if that's the expected behavior.

Comment (gfiorav) [inline spec/models/table_spec.rb]: Good catch!

File: spec/models/table_spec.rb [hunk 4]
```diff
@@ -86,6 +86,16 @@ def @data_import.data_source=(filepath)
...
     end
 
+    it 'can use underscore prefixed names for tables' do
+      table = Table.new
+      table.user_id = $user_1.id
+      table.name = '_name'
+      table.name.should eq '_name'
+      table.save
+
+      table.valid?.should == true
```
Comment (rafatower) [inline spec/models/table_spec.rb]: If the expected behavior is to keep the name rather than "normalizing" as in other cases, I'd check the final name as well.

Comment (rafatower) [inline spec/models/table_spec.rb]: after saving :smile:

Comment (gfiorav) [inline spec/models/table_spec.rb]: ... :sweat:

File: app/models/table.rb (hunk 2 above)
Comment (rafatower) [inline app/models/table.rb]: you should probably add that as a comment.

maybe a cleaner option is to write the query in plain SQL

Comment (juanignaciosl) [inline app/models/table.rb]: Wow, this _is_ ugly. I agree @rafatower , please explain this better. Some kind of link about this and the explicit mention of the Sequel limitation would be nice. Keep in mind that when other person (even my future me), out of the context of this PR, won't be able to know/remember about that Sequel limitation.

**Comment by juanignaciosl** [comment]
Noting else to say :+1:
