### PR TITLE
13012 subdomainless org signup

### LINKED ISSUE #13012: Organization signup page not working on subdomainless
### Context
* Testing signup locally

### Steps to Reproduce

1. Set up app_config.yml 
  - `session_domain:  'localhost.lan`
  - `subdomainless_urls:  true`

2. Create an organization (*yourorg*), and add whitelisted emails to enable login and signup. 

3. Go to `http://fuf.me:3000/user/yourorg/signup`

### Current Result

Routing Error: No route matches [GET] "/user/yourorg/signup"

### Expected result
I must be able to see the signup page

### PR DESCRIPTION
**Pull request by alrocar**
Closes #13012

### CODE REVIEW

File: app/controllers/signup_controller.rb [hunk 1]
```diff
@@ -155,8 +155,18 @@ def github_config
...
+      subdomain = request.host.to_s.gsub(".#{CartoDB.session_domain}", '')
+      if subdomain == CartoDB.session_domain
+        subdomain = params[:user_domain]
+      end
+    else
+      subdomain = CartoDB.subdomain_from_request(request)
+    end
+
+    if subdomain && subdomain != CartoDB.session_domain
+      @organization = ::Organization.where(name: subdomain).first
```
Comment (amartinj) [inline app/controllers/signup_controller.rb]: What if the condition is not met? shouldn't we raise an error?

File: spec/requests/signup_controller_spec.rb [hunk 2]
```diff
@@ -15,6 +15,26 @@
       @fake_organization.delete if @fake_organization
     end
 
+    it 'returns 200 when subdomainless and route is signup_subdomainless' do
+      @fake_organization = FactoryGirl.create(:organization_whitelist_carto)
```
Comment (amartinj) [inline spec/requests/signup_controller_spec.rb]: use a local variable instead of an instance variable

File: spec/requests/signup_controller_spec.rb [hunk 3]
```diff
@@ -15,6 +15,26 @@
...
+      CartoDB.stubs(:subdomainless_urls?).returns(true)
+      CartoDB.stubs(:session_domain).returns('localhost.lan')
+      Organization.stubs(:where).returns([@fake_organization])
+      host! "localhost.lan"
+      get signup_subdomainless_url(user_domain: 'organization')
+      response.status.should == 200
+    end
+
+    it 'returns 404 when subdomainless and route is signup' do
+      @fake_organization = FactoryGirl.create(:organization_whitelist_carto)
```
Comment (amartinj) [inline spec/requests/signup_controller_spec.rb]: same here

File: app/controllers/signup_controller.rb (hunk 1 above)
Comment (amartinj) [reply app/controllers/signup_controller.rb]: Also, add a test for this case

File: spec/requests/signup_controller_spec.rb (hunk 2 above)
Comment (alrocar) [reply spec/requests/signup_controller_spec.rb]: mm but the rest of the tests are using an instance variable, I think it's because of the tear down method that destroys the organization.

File: app/controllers/signup_controller.rb (hunk 1 above)
Comment (alrocar) [reply app/controllers/signup_controller.rb]: If condition is not met it means there's no organization in the URL, thus [it renders a 404](https://github.com/CartoDB/cartodb/blob/master/app/controllers/signup_controller.rb#L173)

A test for that case can be found [here](https://github.com/CartoDB/cartodb/blob/13012-subdomainless-org-signup/spec/requests/signup_controller_spec.rb#L28)

File: spec/requests/signup_controller_spec.rb (hunk 2 above)
Comment (amartinj) [reply spec/requests/signup_controller_spec.rb]: If the teardown is the one destroying the org, it should be the setup the one creating it :/. If it's the test itself the one doing it, it should be it the one destroying it

Comment (amartinj) [reply spec/requests/signup_controller_spec.rb]: Since the rest of the tests are creating the org and letting the teardown deal with the destruction, we'll leave this as it is.

**Comment by ethervoid** [comment]
### Acceptance 💚 

- [x] Tested locally and it worked as intended
