### PR TITLE
11243 cors issues public uploads path

### LINKED ISSUE #11243: Serve `public/uploads` files with CORS
### Context

This was discovered by @ivanmalagon when testing locally stored organisation assets.  

### Steps to Reproduce

1. Use a locally stored asset in front

### Current Result

```
settings:1 Access to Image at 'http://localhost.lan:3000/uploads/organization_assets/up…0780-4ccd-83a8-7bf9fee11b34/asset_download_148421623820170112-17158-n63s3l' from origin 'http://globex.localhost.lan:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://globex.localhost.lan:3000' is therefore not allowed access. The response had HTTP status code 404.
```
 

### Expected result

The asset is displayed.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #11243 (CORS issues)

The approach followed is:
- For local assets, store a URL without domain in the database.
- In the presenter, add the domain name corresponding to the organization (taking into account URL generation settings, e.g: subdomainless).

This fixes a number of issues:
 - CORS, fixed by using the same name as the organization
 - Custom paths. Setting `RAILS_PUBLIC_UPLOADS_PATH` in the previous version messed up public url generation
 - Support for https (old version hardcoded http)

It also adds a bunch of tests covering this issues, as well as https://github.com/CartoDB/cartodb/issues/11234 (by testing end-to-end local storage upload).

----
**Acceptance**

This needs to test at least:
 - Subdomainless/Subdomainful
 - Custom uploads paths (`RAILS_PUBLIC_UPLOADS_PATH` env variable)

I'd recommend using a merge of @ivanmalagon branch about organization assets which is what uncovered this issues in the first place. It must be test locally to cover all the cases. Staging is configured to use S3 file upload.

Please check both uploading assets for markers (it should be rendered in the map) and avatars.

### CODE REVIEW

File: app/models/carto/asset.rb [hunk 1]
```diff
@@ -29,6 +29,11 @@ def self.for_organization(organization:, resource:)
           kind: 'organization_asset')
     end
 
+    def absolute_public_url
+      uri = URI.parse(public_url)
+      (uri.absolute? ? uri : URI.join(base_domain, uri)).to_s
```
Comment (juanignaciosl) [inline app/models/carto/asset.rb]: How come `URI.join(base_domain, uri))`  works? I think that you even have a test for that. Nevertheless, I'm checking it in a console and `join` fail unless one of them is absolute, and `base_domain` looks like a domain (more on this later) and `uri` can't be absolute in that expression.

File: app/models/carto/asset.rb [hunk 2]
```diff
@@ -42,5 +47,9 @@ def validate_storage_info
     def remove_asset_from_storage
       Carto::AssetsService.new.remove(storage_info)
     end
+
+    def base_domain
+      CartoDB.base_domain_from_name(user ? user.subdomain : organization.name)
```
Comment (juanignaciosl) [inline app/models/carto/asset.rb]: `base_domain_from_name` does exist? I can't find it in the code or use it at the console, and it's not thefined in this PR.

**Comment by javitonino** [comment]
Tests broken, fixing...

File: lib/carto/storage_options/local.rb [hunk 3]
```diff
@@ -17,9 +17,7 @@ def upload(path, file)
     FileUtils.mv(file.path, target_directory)
 
     identifier = File.join(target_directory, filename)
-    url = File.join('http://',
-                    CartoDB.account_host,
-                    identifier.gsub('public/', ''))
+    url = File.join('/uploads', @location, path, filename)
```
Comment (juanignaciosl) [inline lib/carto/storage_options/local.rb]: This is no longer a URL, right? This looks like a big change in behaviour, but no other related code seems to have changed.

File: app/models/carto/asset.rb (hunk 2 above)
Comment (javitonino) [inline app/models/carto/asset.rb]: Sorry, missing commit (was the same thing that was breaking tests). Fixed now.

File: app/models/carto/asset.rb (hunk 1 above)
Comment (javitonino) [inline app/models/carto/asset.rb]: Base domain looks like `http://localhost.lan:3000`. I did want to avoid `base_url` as that is already defined in `carto_db.rb` to include the `/u/user` part, and base_domain refers to just the protocol + domain + port.

File: lib/carto/storage_options/local.rb (hunk 3 above)
Comment (javitonino) [inline lib/carto/storage_options/local.rb]: Well, kind of. It is not an absolute URL anymore, it is a relative URL. This URL is not used internally, it is only used at the presenter to pass it to the frontend. In the presenter (and model) you can see the corresponding change to keep behaviour, the method `absolute_public_url`, which adds the domain if it is missing (right now, this is for local uploads only).

The relative URL works for frontend, it displays assets correctly with it. But it needs and absolute URL to write to the cartocss (so the tiler can access the asset if used as an icon). I am not sure presenting the absolute URL should be a backend concern, perhaps it's better to move the `absolute_public_url` from backend to frontend (the information they need is already present in frontend models).
