### PR TITLE
Fixed problem related with dataset privacy

### LINKED ISSUE #9465: Change dataset privacy is not working for "standard" users
Checking the problem, we have realized that, for a user that doesn't belong to an organization, the dialog is useless because only the header (for changing the privacy) would appear.

This publish dialog belongs to "standard" user in a map:

screen shot 2016-08-17 at 15 32 50

For a dataset we remove the "central" part, so...

Possibilities:

1. Open a dropdown (not a modal), just for changing the privacy. Bad part is CTA, where to include it?.
2. Open a totally different dialog (with the new design) and only offering the privacy change.

cc @saleiva @urbanphes @piensaenpixel

### PR DESCRIPTION
**Pull request by xavijam**
Dataset view:
screen shot 2016-08-18 at 16 26 55

Share map view:
screen shot 2016-08-18 at 16 28 03

Also, privacy tags have been changed to have the same size (the big ones), looks ok @josecruz?
screen shot 2016-08-18 at 16 28 12
screen shot 2016-08-18 at 16 28 16

cc @josecruz @piensaenpixel 
CR: @javierarce 

Fixes #9465.

### CODE REVIEW

**Comment by josecruz** [comment]
Awesome @xavijam. If we're gonna change privacy tag we'll need to replace it on the Dashboard (basically on every dataset and map list) so we maintain consistency between tags, what do you think @saleiva ?

**Comment by xavijam** [comment]
About the dashboard change, yeah, it will happen eventually.

File: lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js [hunk 1]
```diff
@@ -40,7 +41,7 @@ module.exports = function (visDefinitionModel, userModel) {
       // Set state that depends on vis and user attrs, they should not vary during the lifecycle of this collection
       return _.defaults({
         selected: option.privacy === currentPrivacy,
-        disabled: !(option.alwaysEnable || canSelectPremiumOptions)
+        disabled: !(option.alwaysEnabled || canSelectPremiumOptions)
```
Comment (javierarce) [inline lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js]: If `alwaysEnabled` is going to be always `true` doesn't make sense to remove it?

Comment (javierarce) [inline lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js]: Can `option.alwaysEnabled` be something different than `true`?

**Comment by javierarce** [comment]
👍  (except for a comment)

File: lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js (hunk 1 above)
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js]: Undefined, because it is not defined/expressed in the ALL_OPTIONS object.
The thing is, public privacy can't be disabled, and the only way to do that is check that, in fact it was previously done like that, but there was a bug and it was not working properly.

Comment (javierarce) [inline lib/assets/javascripts/cartodb3/components/modals/publish/create-privacy-options.js]: Ah, ok, then 🚢  or :shipit: or 🚀
