### PR TITLE
Propagate table name changes to source analyses

### LINKED ISSUE #9633: Renaming a dataset doesnt get propagated to maps using it
so all maps get broken.

To reproduce,
- Create a map using a dataset,
- go to the dataset view and rename it
- Go back to the map.

#SMOKE_DT32

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #9633

In the same manner that we rewrite queries on layers on table name change, we should do the same with analyses. This code follows the same philosophy and tries to minimise the hassle for the lack of layer <-> source analysis relation and maximise the "generic" aspect of analyses.

### CODE REVIEW

**Comment by gfiorav** [comment]
Please CR @juanignaciosl

File: app/models/carto/analysis.rb [hunk 1]
```diff
@@ -61,6 +61,12 @@ def self.source_analysis_for_layer(layer, index)
     new(visualization_id: visualization_id, user_id: user_id, analysis_definition: analysis_definition)
   end
 
+  def update_table_name!(old_name, new_name)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: I'd remove the bang character from every method of this PR. As there's no safe version of these methods it's useless.

File: app/models/carto/analysis.rb [hunk 2]
```diff
@@ -82,6 +88,36 @@ def analysis_node
 
   private
 
+  RENAMABLE_TAGS = ['query', 'table_name'].freeze
+
+  def rename_in_definition!(hash, target, substitution)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: `rename_table_in_definition` is a better naming. Without the context of the caller you don't know what you are renaming.

File: app/models/carto/analysis.rb (hunk 1 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: It's trying to symbolise that you are persisting the changes just by calling on it. I can make a no bang method that will just set it in memory

File: app/models/carto/analysis.rb [hunk 3]
```diff
@@ -82,6 +88,36 @@ def analysis_node
 
   private
 
+  RENAMABLE_TAGS = ['query', 'table_name'].freeze
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: They're not _tags_ but _attributes_.

File: app/models/carto/analysis.rb (hunk 2 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: Well it can rename anything in reality. But I do agree to make it table name specific and keep it focused.

File: app/models/layer.rb [hunk 4]
```diff
@@ -187,6 +187,10 @@ def user
     map.user if map
   end
 
+  def carto_layer
```
Comment (juanignaciosl) [inline app/models/layer.rb]: AFAIK there's one only `carto_whatever` method returning an AR model from an old model: `Member#carto_visualization`. It _might_ be explained because it's used a lot within that class, _and it's private_, which is a huge safety measure. I wouldn't add a `carto_layer` here at all, specially being public.

File: app/models/table.rb [hunk 5]
```diff
@@ -1351,6 +1352,21 @@ def update_cdb_tablemetadata
 
   private
 
+  def propagate_name_change_to_analyses
+    affected_visualizations = @user_table.layers
```
Comment (juanignaciosl) [inline app/models/table.rb]: Extract this to a `related_visualizations` method and get rid of this annoying indentation :-)

File: app/models/carto/analysis.rb [hunk 6]
```diff
@@ -82,6 +88,36 @@ def analysis_node
...
+
+  def rename_in_definition!(hash, target, substitution)
+    hash.each do |key, value|
+      if value.is_a?(Hash)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: How come an `analysis_definition` can be anything other than a `Hash`? :-\

File: app/models/carto/analysis.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Yes, you _can_ do it but it's not there or needed. As there are tons of methods in CartoDB that persist changes without bang character I think that using it here doesn't give any actual information. But keep it if you prefer 👍

File: app/models/carto/analysis.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Yes, please, we don't want people to start renaming anything xD. And if we ever come up with a better table renaming strategy we won't be breaking any contract.

File: app/models/carto/analysis.rb (hunk 6 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Wait, _trying to understand this_.

File: app/models/carto/analysis.rb [hunk 7]
```diff
@@ -82,6 +88,36 @@ def analysis_node
...
+        rename_in_definition!(value, target, substitution)
+      elsif value.is_a?(Array)
+        rename_in_array!(value, target, substitution)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Ok, I see. You call recursively to `rename_in_definition` not only to rename "full" definitions but also fragments, which makes totally sense. I think that I was misled by `Array` check, which is not needed by the way. Instead of doing this:

```ruby
elsif value.is_a?(Array)
  rename_in_array!(value, target, substitution)
```

you can do this:

```
elsif value.is_a?(Array)
  value.map { |v| rename_in_definition!(value, target, substitution) }
```

With this you can delete `rename_in_array!` method, and `rename_in_definition` recursion becomes more evident, as there's either recursion or leaf check.

File: app/models/carto/analysis.rb [hunk 8]
```diff
@@ -82,6 +88,36 @@ def analysis_node
...
+  end
+
+  def rename_in_array!(array, target, substitution)
+    array.each do |value|
+      if value.is_a?(Hash)
+        rename_in_definition!(value, target, substitution)
+      elsif value.is_a?(Array)
+        rename_in_array!(value, target, substitution)
+      elsif RENAMABLE_TAGS.include?(key.to_s) && value.include?(target)
+        value.gsub!(target, substitution)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Take a look at `Layer#rename_in` method, which is a little more demanding about renaming. I'd certainly rename it to `rename_table_name`, extract it to a `TableRenamer` mixing and include it both in `Layer` and `Analysis`.

Comment (gfiorav) [inline app/models/carto/analysis.rb]: Yeah, i've seen that method. I basically is the same but looks for full word match. I'm not sold it will work in all situations (i.e: custom query `SELECT * FROM bogus;#whatever`

Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Yes, but as it's been working for a long time, I'd certainly go for it, it's a better start. The opposite (rewriting only a fragment of a word) is more risky.

File: app/models/layer.rb (hunk 4 above)
Comment (gfiorav) [inline app/models/layer.rb]: Why not? What's the issue with it being public? It bridges stuff to the new model which is what we want

File: app/models/table.rb (hunk 5 above)
Comment (gfiorav) [inline app/models/table.rb]: I'm a bit resilient to jam more methods into this class unless they're actually used in multiple places :/

File: app/models/layer.rb (hunk 4 above)
Comment (juanignaciosl) [inline app/models/layer.rb]: About it being there:
- Circular dependencies are wrong, and new models are really likely to depend on old ones for a long time, so adding a dependency from the old to the new one adds a new dependency.
- It's not needed: the caller could just run `Carto::Layer.find(layer.id)`. It's not a lot of extra work and doesn't add a circular dependency.

**Comment by gfiorav** [comment]
have a second look @juanignaciosl :)

File: app/models/carto/analysis.rb [hunk 9]
```diff
@@ -82,6 +88,24 @@ def analysis_node
 
   private
 
+  RENAMABLE_ATTRIBUTES = ['query', 'table_name'].freeze
+
+  def rename_table_in_definition(definition, target, substitution)
+    if definition.is_a?(Hash)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: This if-elsif can be improved:
- In `if-elsif`s (and switches, which are essentially the same) you should always end with an `else`, probably raising an error because "it shouldn't happen", or maybe with a comment explaining why it should do nothing. In brief, making the "alternative" behaviour explicit.
- In this case I'd try moving the actual replacement to that final else, and call `rename_table_in_definition` instead.

File: app/models/carto/analysis.rb [hunk 10]
```diff
@@ -82,6 +88,24 @@ def analysis_node
...
+      definition.each do |key, value|
+        if value.is_a?(String) && RENAMABLE_ATTRIBUTES.include?(key.to_s) && value.include?(target)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Checkoing `value.include?(target)` is redundant.

File: app/models/carto/analysis.rb [hunk 11]
```diff
@@ -82,6 +88,24 @@ def analysis_node
...
+          value.gsub!(/\b#{target}\b/, substitution)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: I don't like having different renaming logic at `Layer` and here. How come you don't extract and reuse in both?

File: app/models/table.rb [hunk 12]
```diff
@@ -1351,6 +1352,22 @@ def update_cdb_tablemetadata
 
   private
 
+  def related_visualizations
+    carto_layers = @user_table.layers.map do |layer|
```
Comment (juanignaciosl) [inline app/models/table.rb]: Use `(self.)layers` instead of `@user_table.layers`.

File: app/models/table.rb [hunk 13]
```diff
@@ -1351,6 +1352,22 @@ def update_cdb_tablemetadata
...
+      Carto::Layer.find(layer.id) if layer.persisted?
```
Comment (juanignaciosl) [inline app/models/table.rb]: Is `layer.persisted?` actually needed?

File: app/models/table.rb [hunk 14]
```diff
@@ -1351,6 +1352,22 @@ def update_cdb_tablemetadata
...
+    end
+
+    carto_layers.flatten.compact.uniq.map(&:visualization).flatten.compact.uniq
```
Comment (juanignaciosl) [inline app/models/table.rb]: Last `flatten.compact` is not needed.

File: spec/models/table_spec.rb [hunk 15]
```diff
@@ -145,6 +145,27 @@ def @data_import.data_source=(filepath)
       table.table_visualization.name  .should == table.name
     end
 
+    it 'propagates name changes to analyses' do
```
Comment (juanignaciosl) [inline spec/models/table_spec.rb]: Nice test <3. I'd add an explicit check about the old name not included at the definition.

File: app/models/carto/analysis.rb (hunk 9 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: I beg to differ:

I only deal with arrays or hashes. If I find an array, I send each element separately to `rename_table_in_definition`. If a Hash has a promising key and it's value is a string I process it. If not, I have it be dealt with `rename_table_in_definition`.

It's been very tricky to get a working solution. This is the most intuitive I've found.

File: app/models/carto/analysis.rb (hunk 11 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: Here's is the thing. If it weren't written over there, I'd use `\b` as here. Since it's written slightly differently over there and it uses matches (over complex IMHO) I don't want to use that. I don't want to refactor what's over there, because I'd like this to be as simple and revertible as posible as it's quite critical.

File: app/models/carto/analysis.rb (hunk 9 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: What happens if the array contains strings?

File: app/models/table.rb (hunk 13 above)
Comment (gfiorav) [inline app/models/table.rb]: I can check for `id` nilness but it's the same. If it's not persisted yet this whole process isn't run (see compact).

File: app/models/table.rb (hunk 14 above)
Comment (gfiorav) [inline app/models/table.rb]: Yup, leftover.

File: app/models/carto/analysis.rb (hunk 11 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Not sure about this one, but up to you 👍

File: spec/models/table_spec.rb (hunk 15 above)
Comment (gfiorav) [inline spec/models/table_spec.rb]: Totally, but i'm explicitly checking the query and the table name which are substituted. This test must change when new substitution rules are added.

File: app/models/table.rb (hunk 13 above)
Comment (juanignaciosl) [inline app/models/table.rb]: So, it's not needed, you can safely remove it. Even if it's `nil` next `compact` will remove it, so you can skip this check.

File: app/models/carto/analysis.rb (hunk 9 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: If a string enters `rename_table_in_definition` it's ignored as it's supposed to. Remember I need a `key: value` so I can know to replace a string or not depending on the key. 

I guess I could add another case where if a hash with an accepted key is submitted and it's value is an array of strings, each should be examined but then think the case were one of the elements is something other than a string...

It gets complicated fast. If you can come up with a better solution I'm all 👂 

There's probably a better one too..

File: app/models/carto/analysis.rb (hunk 11 above)
Comment (gfiorav) [inline app/models/carto/analysis.rb]: Long story short: I don't want to add a critical refactor to this already critical fix.

In the end this whole model will die and we'll have to rethink a lot of stuff. Also, no too big of a duplication.

File: app/models/table.rb (hunk 13 above)
Comment (gfiorav) [inline app/models/table.rb]: No, if I perform a `Carto::Visualisation.find` on nil it will raise an exception.

File: spec/models/table_spec.rb (hunk 15 above)
Comment (juanignaciosl) [inline spec/models/table_spec.rb]: Concatenating the new name instead of replacing would make this test pass :trollface:

File: app/models/carto/analysis.rb (hunk 9 above)
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: Meh. My point was mostly about readability. I dislike if-elsifs without every case explicitly handled. If you don't think that's important, we can keep this 👍

Comment (gfiorav) [inline app/models/carto/analysis.rb]: I'll give this a second thought.

File: app/models/table.rb (hunk 13 above)
Comment (juanignaciosl) [inline app/models/table.rb]: Oh, you're right, I forgot about that 👍  I'd go for `id.nil?` check then, but up to you.

File: app/models/carto/analysis.rb [hunk 16]
```diff
@@ -82,6 +88,25 @@ def analysis_node
...
+
+    definition.each do |key, value|
+      case value
+      when String
+        value.gsub!(/\b#{target}\b/, substitution) if RENAMABLE_ATTRIBUTES.include?(key.to_s)
+      when Hash
+        rename_table_in_definition(value, target, substitution)
+      when Array
+        value.each do |element|
+          rename_table_in_definition({ "#{key}": element }, target, substitution)
```
Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: How come you don't just call  `rename_table_in_definition` for the `element`? Building up a new hash here is neither needed nor convenient. You can't come up with `key: element` here. `key` is the key of the array. Assigning the key to _each_ value has a different meaning.

Comment (juanignaciosl) [inline app/models/carto/analysis.rb]: I don't like a Hash here, but we've already spent too much time on this and code is good enough. If you like this approach and it's tested, :shipit:

Comment (gfiorav) [inline app/models/carto/analysis.rb]: For the record (in case someone actually digs back to this trying to understand at some point):

The (admittedly craft-man) approach is: We want to support JSONy definitions where we arrive at stuff like

```json
{
  "query": [
    "foo",
    "foofoo",
    "pan"
  ],
  "nothing": [
      {
        "table_name": "foo",
        "foo": "foo"
      },
      "bar"
    ]
  }
}
```

We would like to replace all 'foo' instances for 'bar' that are under an allowed key (say `query` and `table_name`). There are some complications:

+ Recursively travel through arrays and hashes alike
+ Don't ignore things like `not_query: { hey: 'a', query: 'i have to change this' }` just because the top key is not valid
+ Deal with array substitutions for things like `query: ['change this', 'and this', 'and this']`

The controversy with this one is in the last case, the crafty decision to forge temporal hashes. The idea is that you take it one element at a time so you can split the problem in:

`query: ['change this', 'and this', 'and this']` -> `query: 'change this'`, `query: 'and this`, and `query: 'and this'`

This is also implicitly saying that `query: ['this query`]` is the same as `query: 'this query'`, which to replace effects it is.

It looks like there will be a better solution (and there might be) but one tends to overlook the fact that you have to carry the `key` with you in recursion some how to know if the value under it (if it happens to be a string) must be replaced or not. It's not so trivial.

I'm keeping this approach despite the controversy because splitting the problem up and always "speaking" in arrays is a 100%, no corner case robust solution. I'm not so sure any other approach proposed would be so predictable or stay compact like this.

**Comment by gfiorav** [comment]
Posting this again here so it's not removed due to updated code:

For the record (in case someone actually digs back to this trying to understand at some point):

The (admittedly craft-man) approach is: We want to support JSON definitions where we arrive at stuff like

```json
{
  "query": [
    "foo",
    "foofoo",
    "pan"
  ],
  "nothing": [
      {
        "table_name": "foo",
        "foo": "foo"
      },
      "bar"
    ]
  }
}
```

We would like to replace all 'foo' instances for 'bar' that are under an allowed key (say `query` and `table_name`). There are some complications:

+ Recursively travel through arrays and hashes alike
+ Don't ignore things like `not_query: { hey: 'a', query: 'i have to change this' }` just because the top key is not valid
+ Deal with array substitutions for things like `query: ['change this', 'and this', 'and this']`

The controversy with this one is in the last case, the crafty decision to forge temporal hashes. The idea is that you take it one element at a time so you can split the problem in:

`query: ['change this', 'and this', 'and this']` -> `query: 'change this'`, `query: 'and this`, and `query: 'and this'`

This is also implicitly saying that `query: ['this query`]` is the same as `query: 'this query'`, which to replace effects it is.

It looks like there will be a better solution (and there might be) but one tends to overlook the fact that you have to carry the `key` with you in recursion some how to know if the value under it (if it happens to be a string) must be replaced or not. It's not so trivial.

I'm keeping this approach despite the controversy because splitting the problem up and always "speaking" in arrays is a 100%, no corner case robust solution. I'm not so sure any other approach proposed would be so predictable or stay compact like this.
