### PR TITLE
10657 better check for mapcaps

### LINKED ISSUE #10657: NoMethodError: undefined method `regenerate_visualization' for nil:NilClass
[Trace](https://rollbar.com/vizzuality/CartoDB/items/21067/?item_page=0&item_count=100&#traceback):

```ruby
NoMethodError: undefined method `regenerate_visualization' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20161108170937/app/models/carto/visualization.rb", line 449 in for_presentation
2
File "/home/ubuntu/www/production.cartodb.com/releases/20161108170937/app/controllers/carto/builder/public/embeds_controller.rb", line 84 in visualization_for_presentation
3
File "/home/ubuntu/www/production.cartodb.com/releases/20161108170937/app/controllers/carto/builder/public/embeds_controller.rb", line 53 in load_vizjson
+ 2 non-project frames
6
File "/home/ubuntu/www/production.cartodb.com/releases/20161108170937/app/controllers/application_controller.rb", line 99 in wrap_in_profiler
+ 73 non-project frames
```

I still haven't dug into the cause. Nevertheless, this is failing by a indirect check:

```ruby
455   def non_mapcapped
456     mapcapped? ? latest_mapcap.visualization : self
457   end
```

After `mapcapped?` `true` we assume that there's a `latest_mapcap`, which is not right (given that line).

cc @CartoDB/builder-backend

### PR DESCRIPTION
**Pull request by gfiorav**
Not sure it fixes #10657, but it makes since anyway.

This check should be safer. Previous `.exists?` depends on how the relation is constructed and I don't trust it since `Carto::Mapcap.exists?` (so a non-scoped relation build) returns `true`. So theres a chance that this defaults to `true` in some weird RAILish situation which is not good. I prefer to fetch `LIMIT 1` (i.e: `.first`) and check presence. For that I just reuse `latest_mapcap`.

See if it makes sense to you @juanignaciosl.

### CODE REVIEW

File: app/models/carto/visualization.rb [hunk 1]
```diff
@@ -388,7 +388,7 @@ def create_mapcap!
   end
 
   def mapcapped?
-    mapcaps.exists?
+    latest_mapcap.present?
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Even though this looks better it still doesn't address my main concern:

```ruby
455   def non_mapcapped
456     mapcapped? ? latest_mapcap.visualization : self
457   end
```

`non_mapcapped` is calling  a method on`latest_mapcap` without an explicit check. If this code is a better, safer definition of `mapcapped?`, great, but replacing the `mapcapped?` check with `latest_mapcap.present?` in `non_mapcapped` as well would be even better. IMHO you shouldn't need to read `mapcapped?` implementation to know whether `non_mapcapped` is safe or not.

Anyway, your call here.

Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: BTW, how come is this method named `non_mapcapped`? 🤔  I don't get it now, as it can return the visualization from a mapcap >_<

Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Oh, you told me about this logic but I couldn't remember it even reading the code :-\ I can't come up with any better alternative. `non_mapcapped_original_visualization`? Not much better. Maybe you could add a comment.

**Comment by juanignaciosl** [comment]
As I see that you ignore my suggestion about the ternary check, 👍  😅  . A comment at `non_mapcapped` might be nice anyway.

**Comment by gfiorav** [comment]
Sorry, didn't mean to ignore it! Since this is already a bit old, I'll review a bit and address all your comments!

**Comment by juanignaciosl** [comment]
@gfiorav no, I understand that it's open to discussion. Feel free to ignore it, it's something that I'd do but I understand that others disagree. _Really_ minor, indeed :-)

**Comment by gfiorav** [comment]
As a general comment: `mapcapped?` now just checks for `latest_mapcap.present?` so it's not worth the refactor IMHO.


Thanks for the comments!
