### PR TITLE
Enterprise user management API redesign 

### LINKED ISSUE #6318: Enterprise User Management API redesign
After reviewing the API and the docs I have some concerns I'd like to _discuss_ (meaning I'm open to suggestions, I might not be right).

1. Original design seemed to have the organization id in the URL: `org.cartodb.com/u/org-owner/api/v1/organization/abcdefgh-1234-4321-abcd-1234567890ab/users`. Nevertheless it got lost during development, since I need to remove it to make calls work: `org.cartodb.com/u/org-owner/api/v1/organization/users`. I think keeping the id is better:
  - It's consistent with [existing URLs](https://github.com/CartoDB/cartodb/blob/master/config/routes.rb#L394).
  - It's _explicit_ and coherent with usual REST API design guidelines.
  - It's flexible and robust: what if a user could own or belong to several organizations and we had subdomainless urls?

2. It's an API. APIs are done with JSON (I don't know if there's any exception for that), so I think the payload should be JSON instead of parameters.

3. For [updates and deletions you select the user with the "username" or "email" parameter in the payload](http://docs.cartodb.com/cartodb-enterprise/enterprise-api/#modify-users-with-the-enterprise-api). This is not too "REST-y". Since a user is a resource you should be able to identify it with the URI: `org.cartodb.com/u/org-owner/api/v1/organization/abcdefgh-1234-4321-abcd-1234567890ab/users/abcdefgh-1234-4321-abcd-1234567890ab`. Payload should not be used to identify.

4. Related to previous one, `new_email` is actually an smell. There's no `new_email` attribute, I guess it's needed to avoid `email` collision.

Additional note: you might rise a concern about those ids (both user and organization) in the URLs: they're cryptic, not user-friendly and sometimes not even available.I think we should support the three "identifier attributes": `id`, `username` (users) / `name` (organizations) and `email`. Example: `myorg.cartodb.com/u/org-owner/api/v1/organization/myorg/users/theuser`.

What do you think, @ethervoid , @gfiorav, @xavijam ?

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #6318

I think I covered all suggestions.

~~Updated quick start to come.~~

UPDATE: New quick start: https://gist.github.com/gfiorav/d65f14b32827ce7c7fec

cc/ @juanignaciosl @xavijam @javisantana

### CODE REVIEW

**Comment by juanignaciosl** [comment]
I think you're missing the tests, which [still send plain text payload instead of JSON](https://github.com/CartoDB/cartodb/blob/master/spec/requests/carto/api/organization_users_controller_spec.rb), isn't it?

File: app/controllers/carto/api/organization_users_controller.rb [hunk 1]
```diff
@@ -7,11 +7,18 @@ module Api
     class OrganizationUsersController < ::Api::ApplicationController
       include OrganizationUsersHelper
 
-      ssl_required :create, :update, :destroy
+      ssl_required :create, :update, :destroy, :show
 
       before_filter :load_organization
 
-      UPDATE_PARAMS_MAP = { new_email: :email }
+      def show
```
Comment (juanignaciosl) [inline app/controllers/carto/api/organization_users_controller.rb]: This method is missing a test.

File: app/controllers/carto/api/organization_users_controller.rb [hunk 2]
```diff
@@ -7,11 +7,18 @@ module Api
     class OrganizationUsersController < ::Api::ApplicationController
       include OrganizationUsersHelper
 
-      ssl_required :create, :update, :destroy
+      ssl_required :create, :update, :destroy, :show
 
       before_filter :load_organization
```
Comment (juanignaciosl) [inline app/controllers/carto/api/organization_users_controller.rb]: You could add a `:load_user` as well to avoid user loading code duplication.

**Comment by gfiorav** [comment]
@juanignaciosl yes, right, on it!

File: app/controllers/carto/api/organization_users_controller.rb (hunk 1 above)
Comment (gfiorav) [inline app/controllers/carto/api/organization_users_controller.rb]: yes, just added it, i'm missing tests!

File: app/controllers/carto/api/organization_users_controller.rb (hunk 2 above)
Comment (gfiorav) [inline app/controllers/carto/api/organization_users_controller.rb]: will do

**Comment by juanignaciosl** [comment]
Ok, let me know when you want next CR.

File: app/helpers/organization_users_helper.rb [hunk 3]
```diff
@@ -2,8 +2,27 @@
...
+    if @organization.nil?
+      render_jsonp({}, 401) # Not giving clues to guessers via 404
+      return
+    end
+  end
+
+  def owners_only
+    unless current_viewer_is_owner?
+      render_jsonp({}, 401)
+      return
```
Comment (juanignaciosl) [inline app/helpers/organization_users_helper.rb]: This is right in Rails 3, but being prepared for Rails 4 is interesting. Since this is a `before_filter` and you want pipeline to stop after `render_jsonp`, better `return false`.

Comment (gfiorav) [inline app/helpers/organization_users_helper.rb]: Good insights! changing that, thanks!

File: app/controllers/carto/api/organization_users_controller.rb [hunk 4]
```diff
@@ -36,27 +38,23 @@ def create
...
-        render_jsonp("No user with #{identify_params}", 404) && return if user.nil?
-
-        # Turn new_email: into email:, etc
-        transformed_update_params = Hash[update_params.map { |k, v| [UPDATE_PARAMS_MAP[k] || k, v] }]
+        params_to_update = update_params
 
         # ::User validation requires confirmation
-        if transformed_update_params[:password].present?
-          transformed_update_params[:password_confirmation] = transformed_update_params[:password]
+        if params_to_update[:password].present?
```
Comment (juanignaciosl) [inline app/controllers/carto/api/organization_users_controller.rb]: This `if` is not really needed. If it's not present `params_to_update[:password]` will return `nil`, thus setting `params_to_update[:password_confirmation]` to nil as well.

Comment (gfiorav) [inline app/controllers/carto/api/organization_users_controller.rb]: True, changing.

File: app/controllers/carto/api/organization_users_controller.rb [hunk 5]
```diff
@@ -64,23 +62,20 @@ def update
       end
 
       def destroy
-        render_jsonp({}, 401) && return unless current_viewer_is_owner?
-        render_jsonp('No delete params provided', 410) && return if delete_params.empty?
-
-        user = ::User.where(delete_params).first
-        render_jsonp({}, 401) && return if @organization.owner.id == user.id
+        render_jsonp({}, 401) && return if @organization.owner_id == @user.id
```
Comment (juanignaciosl) [inline app/controllers/carto/api/organization_users_controller.rb]: I know this was the previous code, but providing an explanation about why it failed (not allowing to delete the owner user) would be nice.

**Comment by juanignaciosl** [comment]
I've done some minor comments. Take into account as many as you can. :+1: afterwards.
