### PR TITLE
7494 analysis form models

### LINKED ISSUE #7468: Render analysis controls view at bottom
Leftover from #7467, since had to prioritize some other work.

### LINKED ISSUE #7494: Change analysis nodes creation/update to work with form models
**Problems**
- Add-analysis workflow requires creation of faulty nodes, since we can't impossibly know what analysis values to put by default, which gives a pretty bad UX
- Logic related to analysis node validation and checks spread out in various places
- Non-trivial to add new analysis types, need to know how things are setup and where and take into account the quirks related to the previous points.

**Proposed solution:**
- Change _layer > analysis_ view to work with form models
- Add-analysis to create a form model instead of actual node, allowing to have missing values (and indicate so in the form view). node will be created once user added all missing values

The primary goal is to make it clear and easy to add new analysis types.

### LINKED ISSUE #7517: [analysis] trade areas not working with time
steps:

1) import a points table
2) add trade areas analysis (by time, 150s)

check call to maps api errors:

```json
{"errors":["Invalid type for param \"time\", expects \"number\" type, got `\"160\"`"]}
```

the payload is

```json
{
   "layers":[
      {
         "type":"cartodb",
         "options":{
            "cartocss":"#points['mapnik::geometry_type'=1] {\n  marker-fill-opacity: 1;\n  marker-line-color: #FFF;\n  marker-line-width: 0.5;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 8;\n  marker-fill: #FABADA;\n  marker-allow-overlap: true;\n}\n#lines['mapnik::geometry_type'=2] {\n  line-color: #000000;\n  line-width: 2;\n  line-opacity: 1;\n}\n#polygons['mapnik::geometry_type'=3] {\n  polygon-fill: #FABADA;\n  polygon-opacity: 1;\n  line-color: #FFF;\n  line-width: 0.5;\n  line-opacity: 1;\n}",
            "cartocss_version":"2.1.1",
            "interactivity":[

            ],
            "source":{
               "id":"a1"
            }
         }
      }
   ],
   "dataviews":{

   },
   "analyses":[
      {
         "id":"a1",
         "type":"trade-area",
         "params":{
            "source":{
               "id":"a0",
               "type":"source",
               "params":{
                  "query":"SELECT * FROM paradas_metro_madrid"
               }
            },
            "kind":"walk",
            "time":"160",
            "isolines":"1",
            "dissolved":false
         }
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by viddo**
Yes, a big PR because the issues above were all related to the problems of current implementation, so solved them in one go.

The main benefit, though, is that it will be easy for others (who don't know how things are wired together), to add new analyses 🎉 they just need to:

1. add a [new option entry](https://github.com/CartoDB/cartodb/blob/7494-analysis-form-models/lib/assets/javascripts/cartodb3/components/modals/add-analysis/default-options.js)
1. Implement a [form model(+view to go with it) representing the new type](https://github.com/CartoDB/cartodb/blob/7494-analysis-form-models/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-forms-collection.js#L6-L10)

More details below:

**Closes #7494 - Change analysis nodes creation/update to work with form models**
The layer-contenta-analyses-view now works with form models instead of directly interacting with the node definitions. This have the benefit of having invalid models w/ trouble, and representing editing state in a simpler way and not polluting the node models.

Also simplifies add-analysis modal, since it now just need to add metadata about an analysis. In theory we should be able to move this to the camshaft reference even, having all the the options generated from the metadata. This also solved the bug of showing the secondary source as an error when creating a new point-in-polygon analysis. 🎉 

Validation is now also done using the params restrictions defined in the [camshaft reference](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.10.0/reference.json)

**Closes #7517 - [analysis] trade areas not working with time**
The form converts the model's values to strings (`123`, `false`, etc.). Solved by doing conversion based on the [type definitions in the camshaft reference](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.10.0/reference.json#L13).

**Closes #7468 - Render analysis controls view at bottom**
Changed the layout structure, and could remove some unnecessary views. The hierarchy now is basically:

```
LayerContentAnalyses
  ScrollView
    ListView
      Workflow
      Form
  AnalysesControls (apply etc.)
```

Also some general boyscouting while at it, e.g. stack layout bugs, node internals, duplicated code (add-analysis modal creation) etc.

---

Some screens:

screen shot 2016-05-31 at 16 41 57
screen shot 2016-05-31 at 16 42 02
screen shot 2016-05-31 at 16 42 06
screen shot 2016-05-31 at 16 42 20

@xavijam sorry for such a large PR again, but can you review? 🙏 🙇 
cc @javierarce @alonsogarciapablo

### CODE REVIEW

**Comment by xavijam** [comment]
Before reviewing it, I checked one thing while you were showing to me. When a new analysis is chosen, until you click over apply, it is not saved, could we change the title of the button in that case?

- Before being saved: 'Create', 'Save',...
- After being saved: 'Apply'

How does it sound?

**Comment by viddo** [comment]
Sounds reasonable, in the case that the node is valid it could also be
saved immediately.

On Tue, May 31, 2016 at 2:50 PM, Javier Álvarez Medina <
notifications@github.com> wrote:

> Before reviewing it, I checked one thing while you were showing to me.
> When a new analysis is chosen, until you click over apply, it is not saved,
> could we change the title of the button in that case?
>
>    - Before being saved: 'Create', 'Save',...
>    - After being saved: 'Apply'
>
> How does it sound?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/7578#issuecomment-222678384>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA7uHQl5idDi2ZbmuMwq49AdsiSifXq0ks5qHC57gaJpZM4Iqa5_>
> .
>



-- 

*Nicklas Gummesson*, software engineer
*CartoDB* — Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by xavijam** [comment]
Yeah, sounds :top:

File: lib/assets/javascripts/cartodb3/components/modals/modals-service-model.js [hunk 1]
```diff
@@ -3,6 +3,8 @@ var cdb = require('cartodb.js');
 var ModalView = require('./modal-view');
 var ModalViewModel = require('./modal-view-model');
 
+const DESTROYED_MODAL_EVENT = 'destroyedModal';
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/modals/modals-service-model.js]: I feel this works from version 11 for IE, and we support IE10:
- https://github.com/CartoDB/cartodb#requirements
- https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const

Comment (viddo) [inline lib/assets/javascripts/cartodb3/components/modals/modals-service-model.js]: Ooups, that's actually a typo! Too used to write ES6 code on my side-projects 😂

Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/modals/modals-service-model.js]: :joy:

File: lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-view.js [hunk 2]
```diff
@@ -1,76 +1,53 @@
...
+   * @override cdb.core.View.prototype.clearSubViews
+   */
+  clearSubViews: function () {
+    if (this._analysisFormView) {
+      this._analysisFormView.remove(); // the Backbone.Form equivalent to "view.clean()"
+    }
 
-  _analysisDefinitionNodeModel: function () {
-    return this._viewModel.get('selectedNode');
+    return cdb.core.View.prototype.clearSubViews.apply(this, arguments);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-view.js]: I feel clearsubviews method doesn't return anything.

**Comment by xavijam** [comment]
Could we deploy this in any staging please?

**Comment by viddo** [comment]
Yes, let me finish the last fix you ask for and I'll deploy it.

On Tue, May 31, 2016 at 4:10 PM, Javier Álvarez Medina <
notifications@github.com> wrote:

> Could we deploy this in any staging please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/pull/7578#issuecomment-222700273>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA7uHbm0Go-f9BBr-Eor6hIKUI8K6hGIks5qHEFSgaJpZM4Iqa5_>
> .
>



-- 

*Nicklas Gummesson*, software engineer
*CartoDB* — Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by xavijam** [comment]
It is difficult to check all changes, but at a first sight, LGTM. After a check in staging, I'll give a final thumbs up.

**Comment by viddo** [comment]
screen shot 2016-05-31 at 16 41 57
screen shot 2016-05-31 at 16 42 02
screen shot 2016-05-31 at 16 42 06
screen shot 2016-05-31 at 16 42 20

**Comment by viddo** [comment]
updated desc with images intead

**Comment by xavijam** [comment]
thanks man!

**Comment by xavijam** [comment]
About last changes :+1:

**Comment by viddo** [comment]
Deployed on ded03 🚀

File: lib/assets/javascripts/cartodb3/data/widget-definition-model.js [hunk 3]
```diff
@@ -58,8 +57,8 @@ module.exports = cdb.core.Model.extend({
    */
   toJSON: function () {
     var o = _.pick(this.attributes, ATTRS_AT_TOP_LEVEL);
-    o.source = {id: this.get('source_id')};
```
Comment (viddo) [inline lib/assets/javascripts/cartodb3/data/widget-definition-model.js]: Good question, but IMHO we should not have fallback/backward compatibility for something that's not even released yet, otherwise we would have to do fallbacks for every breaking change.

**Comment by xavijam** [comment]
SFW -> Sweden for the win.

**Comment by viddo** [comment]
Frontend tests passing, so merging 🚀

File: lib/assets/javascripts/cartodb3/data/widget-definition-model.js (hunk 3 above)
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/data/widget-definition-model.js]: Let's wait for the screaming people then :P
