### PR TITLE
Lower MAX_IDENTIFIER_LENGTH to 61 chars

### LINKED ISSUE #12732: Import error with long and similar filenames
### Context
https://github.com/CartoDB/support/issues/967

### Steps to Reproduce
1. Create a file named `carto_long_filename_that_almost_matches_another_one_63chars_aaa.csv` and import it into CARTO
2. Create a file named `carto_long_filename_that_almost_matches_another_one_63chars_aab.csv` and import it into CARTO

### Current Result
Error 9999, the import log shows
```
2017-09-05 14:21:41 UTC: Exception: PG::Error: ERROR:  type "_carto_long_filename_that_almost_matches_another_one_63chars_aa" already exists in schema "xxxxx"
```

cc @juanignaciosl @rochoa

### PR DESCRIPTION
**Pull request by mayoral**
This PR fixes #12732.

Quoting from https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

> The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

63 is OK for creating tables, but for some reason, during `ALTER TABLE foo RENAME`, Postgres appends an underscore in the autogenerated type name, making the crash when two long names are almost the same:

```
ERROR:  type "_carto_long_filename_that_almost_matches_another_one_63chars_aa" already exists in schema "xxxxx"
```

Lowering our MAX_IDENTIFIER_LENGHT to 61 we can be sure we are not running again in problems when `RENAME`ing tables.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
> 63 is OK for creating tables, but for some reason, during ALTER TABLE foo RENAME, Postgres appends an underscore in the autogenerated type name

Do you have STR for this?

**Comment by juanignaciosl** [comment]
I dug deeper into this because reducing the maximum name lenght is a behaviour change that I don't think that we can afford. For example, we might break maps with sync tables of long filenames.

We have a problem. From [the documentation](https://www.postgresql.org/docs/9.6/static/sql-createtable.html).

```sql
CREATE TABLE also automatically creates a data type that represents the composite type corresponding to one row of the table. Therefore, tables cannot have the same name as any existing data type in the same schema.
```

So, your "for some reason, during ALTER TABLE foo RENAME, Postgres appends an underscore in the autogenerated type name" is actually "on table creation PG creates a type with the same name than the table; as the table name length is equal or bigger than the maximum one, the type name is truncated".

The previous PG documentation excerpt is both the cause and the hint for the solution: "Therefore, tables cannot have the same name as any existing data type in the same schema". [If you search for `propose_valid_table_name` you get 4 usages](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=propose_valid_table_name&type=), and all of them have the same issue: `taken_names` are the user tables names. As PG documentation say, it should also be the type names.

So, in order to fix this, in this order:
1.- Add an acceptance test that imports two files with the same name than the issue suggest. I think that the expected name for the second file should be `carto_long_filename_that_almost_matches_another_one_63chars_a_1`, because although there's no table with a matching name (`carto_long_filename_that_almost_matches_another_one_63chars_aab`), the type that gets generated (`_ carto_long_filename_that_almost_matches_another_one_63chars_aa`) does exist. cc @javitonino  . This test must fail with the known error.
2.- Fix it by adding existing data types to the list of taken names at the 4 usages. Please minimize code duplication.

**Comment by mayoral** [comment]
👍 

Should I close this PR and delete this branch? To start with your proposal in a new one.

**Comment by mayoral** [comment]
So I revert my commits & continue the work in this branch, isn't it?

**Comment by juanignaciosl** [comment]
Yup.

**Comment by mayoral** [comment]
Following your example, we run in the same problem with the `_1` and `_2` versions:

```
carto_db_development=# CREATE TABLE public.carto_long_filename_that_almost_matches_another_one_63chars_a_1 (id serial);
CREATE TABLE
carto_db_development=# CREATE TABLE cdb_importer.carto_long_filename_that_almost_matches_another_one_63chars_a_2 (id serial);
CREATE TABLE
carto_db_development=# ALTER TABLE cdb_importer.carto_long_filename_that_almost_matches_another_one_63chars_a_2 SET SCHEMA public;
ERROR:  type "_carto_long_filename_that_almost_matches_another_one_63chars_a_" already exists in schema "public"
```

PostgreSQL is smart enough to rename conflicting versions when creating new tables, like:

```
carto_db_development=# CREATE TABLE public.carto_long_filename_that_almost_matches_another_one_63chars_a_2 (id serial);
CREATE TABLE
carto_db_development=# CREATE TABLE public.carto_long_filename_that_almost_matches_another_one_63chars_a_3 (id serial);
CREATE TABLE
```

This creates the typnames `__carto_long_filename_that_almost_matches_another_one_63chars_a` and `___carto_long_filename_that_almost_matches_another_one_63chars_` in the `pg_catalog.pg_type` table. 

I've tried renaming first the table, and I got another error with this approach:

```
carto_db_development=# ALTER TABLE cdb_importer.carto_long_filename_that_almost_matches_another_one_63chars_aab rename to foobar;
ALTER TABLE
carto_db_development=# ALTER TABLE cdb_importer.foobar SET SCHEMA public;
ERROR:  relation "carto_long_filename_that_almost_matches_another_one_63ch_id_seq" already exists in schema "public"
```

The table changes it's name, but the sequence maintains the name. If I create another table ending in aac, I'll end with a sequence named `carto_long_filename_that_almost_matches_another_one_63c_id_seq1`.

**Comment by juanignaciosl** [comment]
> Following your example, we run in the same problem with the _1 and _2 versions:

Yep, maybe we need a more complex approach. From your failing example:

```sql
carto_db_development=# CREATE TABLE public.carto_long_filename_that_almost_matches_another_one_63chars_a_1 (id serial);
CREATE TABLE
carto_db_development=# CREATE TABLE cdb_importer.carto_long_filename_that_almost_matches_another_one_63chars_a_2 (id serial);
CREATE TABLE
carto_db_development=# ALTER TABLE cdb_importer.carto_long_filename_that_almost_matches_another_one_63chars_a_2 SET SCHEMA public;
ERROR:  type "_carto_long_filename_that_almost_matches_another_one_63chars_a_" already exists in schema "public"
```

As you see that the straightforward approach would be anticipating the type. We shouldn't propose `carto_long_filename_that_almost_matches_another_one_63chars_a_2` because it leads to `_carto_long_filename_that_almost_matches_another_one_63chars_a_` type, which is taken. Iterating with the current approach should lead to `carto_long_filename_that_almost_matches_another_one_63chars__10`, which leads to `_carto_long_filename_that_almost_matches_another_one_63chars__1` type, which is available.

Did you consider this?

Your attempt of rename + change schema was not bad, but the sequence error is worse, because it's based in our own conventions. I'd prefer to struggle only against posgres', instead of against both of them.

Can you come up with another alternative that doesn't change the current behaviour for working imports?

cc @javitonino

**Comment by javitonino** [comment]
My initial idea when I saw this was that instead of finding tables with matching names to see if we have to rename, we can look at matching only the first 62 characters instead (keeping the truncation at 63). Not 100% sure if this work, but it's what pops to mind.

File: lib/carto/valid_table_name_proposer.rb [hunk 1]
```diff
@@ -8,6 +8,7 @@ class ValidTableNameProposer
     DEFAULT_SEPARATOR = '_'.freeze
     DEFAULT_TABLE_NAME = 'untitled_table'.freeze
     MAX_RENAME_RETRIES = 10000
+    NON_COLLISIONABLE_STRING_LENGHT = 61
```
Comment (javitonino) [inline lib/carto/valid_table_name_proposer.rb]: Typo. It's LENGTH

File: lib/carto/valid_table_name_proposer.rb [hunk 2]
```diff
@@ -26,7 +27,11 @@ def find_unused_name_with_prefix(names, prefix, separator: DEFAULT_SEPARATOR)
       proposal = prefix
 
       (1..MAX_RENAME_RETRIES).each do |appendix|
-        return proposal unless names.include?(proposal)
+        # We exclude the proposal either if the taken names array already have the proposal, or if the taken names
+        # array contains a string with the first 62 chars equal to the proposal. With this we avoid typnames collision
+        # when moving schemas
+        return proposal unless names.include?(proposal) ||
+                               names.any? { |name| name_can_have_typname_collision(name, proposal) }
```
Comment (javitonino) [inline lib/carto/valid_table_name_proposer.rb]: Since you are extracting the text to a method, why not do the include inside the loop as well, to avoid double looping:

```
return proposal unless names.any? { |name| name_can_have_typname_collision(name, proposal) }

def name_can_have_typname_collision(name, proposal)
  name == proposal || name[0..NON_COLLISIONABLE_STRING_LENGHT] == proposal[0..NON_COLLISIONABLE_STRING_LENGHT]
end
```

File: lib/carto/valid_table_name_proposer.rb (hunk 1 above)
Comment (mayoral) [reply lib/carto/valid_table_name_proposer.rb]: 👍

File: lib/carto/valid_table_name_proposer.rb (hunk 2 above)
Comment (mayoral) [reply lib/carto/valid_table_name_proposer.rb]: 👍

**Comment by javitonino** [comment]
Please, fill in NEWS.md and then move to acceptance.
