### PR TITLE
Problems related with context-menu cleaning fixed

### LINKED ISSUE #7457: Uncaught TypeError: Cannot read property 'ownerDocument' of undefined (context-menu-view:55)
Saw this exception in the dev console in production env:

```
jquery:1430 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
b.contains @ jquery:1430
b.exports.f.core.View.extend._onDocumentElementClicked @ context-menu-view.js:55
_.event.dispatch @ jquery:4435q.handle @ jquery:4121
```

[content-menu-view:55](https://github.com/CartoDB/cartodb/blob/350f182802ad10d32cfce4b24a88b52e1fb621dd/lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js#L55)

### PR DESCRIPTION
**Pull request by xavijam**
Fixes #7457.

So, from my point of view, only external views should open the context-menu, not the proper view.
And also, document binds should not be enabled until the view is visible.
What do you think mate?

CR: @alonsogarciapablo

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js [hunk 1]
```diff
@@ -90,6 +78,19 @@ module.exports = cdb.core.View.extend({
...
 
+  _onEscapePressed: function (ev) {
+    if (ev.which === $.ui.keyCode.ESCAPE) {
+      this.hide();
+    }
+  },
+
+  _onDocumentElementClicked: function (ev) {
+    var $el = $(ev.target);
+    if ($el.closest(this.$el).length === 0 && $el.attr('id') !== this._triggerElementID) {
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: Not sure about triggerElementID reference, but it is useful to check if it was clicked over that reference.

File: lib/assets/javascripts/cartodb3/editor/layers/layers-view.js [hunk 2]
```diff
@@ -48,7 +49,8 @@ module.exports = cdb.core.View.extend({
 
   _addLayerView: function (m) {
     var view;
-    if (m.get('order') === 0) {
+
+    if (m.get('type') === 'Tiled') {
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/layers/layers-view.js]: Could it do the trick?

File: lib/assets/javascripts/cartodb3/editor/map/map-view.js [hunk 3]
```diff
@@ -82,6 +82,7 @@ module.exports = cdb.core.View.extend({
     });
 
     this.$el.append(stackLayoutView.render().$el);
+    this.addView(stackLayoutView);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/map/map-view.js]: One of the original problems.

File: lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js [hunk 4]
```diff
@@ -20,55 +20,43 @@ module.exports = cdb.core.View.extend({
...
-
-    this.options = _.extend({}, this.options, opts);
+    this._triggerElementID = opts.triggerElementID;
 
     this.model = new cdb.core.Model({
       visible: false
     });
 
-    this._initBinds();
+    this._onEscapePressed = this._onEscapePressed.bind(this);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: This solves the problem that document bindings were not removed correctly.

Comment (xavijam) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: Already used in the `custom-carousel-view.js` by the way, thanks to @nobuti.

File: lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js [hunk 5]
```diff
@@ -121,7 +126,33 @@ describe('components/context-menu/context-menu-view', function () {
     expect(this.view.$el.css('wadus')).toBeUndefined();
   });
 
+  describe('document binds when item is not visible', function () {
+    beforeEach(function () {
+      spyOn(this.view, 'hide');
+    });
+
+    it('should not check outside click', function () {
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: `should not try to hide the context menu when clicking somewhere else`?

File: lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js [hunk 6]
```diff
@@ -121,7 +126,33 @@ describe('components/context-menu/context-menu-view', function () {
...
+      $('body').click();
+      expect(this.view.hide).not.toHaveBeenCalled();
+      this.$button.click();
+      $('body').click();
+      expect(this.view.hide).toHaveBeenCalled();
+    });
+
+    it('should not check ESC keypress', function () {
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: `should not try to hide the context menu when pressing ESCAPE`?

File: lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js [hunk 7]
```diff
@@ -46,32 +51,32 @@ describe('components/context-menu/context-menu-view', function () {
     expect(this.view.$el.find('button[title="Label 2"]')).toBeDefined();
   });
 
-  it('should be toggled when clicking on the triggerElement', function () {
+  it('should be toggled when clicking on the button', function () {
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: This test and the following are now the same... I think it's important to ensure that both clicking on an element (previously `this.triggerElement`) and in some element inside of if (`this.button`) works as expected.

File: lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js [hunk 8]
```diff
@@ -121,7 +126,33 @@ describe('components/context-menu/context-menu-view', function () {
...
 
+  describe('document binds when item is not visible', function () {
+    beforeEach(function () {
+      spyOn(this.view, 'hide');
+    });
+
+    it('should not check outside click', function () {
+      $('body').click();
+      expect(this.view.hide).not.toHaveBeenCalled();
+      this.$button.click();
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: Perhaps we could use `this.view.show()` here and in the following test instead of `this.button.click()` to make it more obvious that we're showing the view?

File: lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js (hunk 1 above)
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: $el.closest() will only work if the element that triggered the click (`$(ev.target)`) is a descendent of `this.$el`, That's not the case in the context menu that is displayed for layers. That's why I had to use the triggerElementID reference.

File: lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js [hunk 9]
```diff
@@ -20,55 +20,43 @@ module.exports = cdb.core.View.extend({
...
   },
 
-  _onEscapePressed: function (ev) {
-    if (ev.which === $.ui.keyCode.ESCAPE) {
-      this.hide();
-    }
+  _initBinds: function () {
+    this.model.on('change:visible', function (mdl, isVisible) {
+      this.render();
+      if (isVisible) {
```
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: :+1: Like it!

File: lib/assets/javascripts/cartodb3/editor/layers/layer-view.js [hunk 10]
```diff
@@ -121,6 +122,10 @@ module.exports = cdb.core.View.extend({
     this._stackLayoutModel.nextStep(this.model, 'layers', selectedNode);
   },
 
+  _onOpenContextMenu: function () {
+    this._menuView.toggle();
```
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/editor/layers/layer-view.js]: 👍  Like it too! :)

File: lib/assets/javascripts/cartodb3/editor/layers/layers-view.js (hunk 2 above)
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/editor/layers/layers-view.js]: I guess we can live with it for now. I'm not a big fan of having this kind of magic literals for layer types (I'd rather have a global LAYER_TYPES.TILED or something along those lines) but since it's a common pattern, let's go with this.

I'd rename `BasemapLayerView` to `TiledLayer` or something different since the layer with labels is not really a basemap... But, we can do this in the future.

**Comment by alonsogarciapablo** [comment]
I like the approach 👏  👏  👏  (more efficient than what we had before)

File: lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js (hunk 4 above)
Comment (alonsogarciapablo) [inline lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js]: `_.bindAll(...)` should also work, right?

File: lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js [hunk 11]
```diff
@@ -23,13 +25,19 @@ describe('components/context-menu/context-menu-view', function () {
...
     this.triggerElement.append(this.button);
+
     $('body').append(this.triggerElement);
 
     this.view = new ContextMenuView({
       collection: this.collection,
       triggerElementID: this.triggerElement[0].id
     });
 
+    this.triggerElement.on('click', function (ev) {
```
Comment (alonsogarciapablo) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: Do we need this?

Comment (xavijam) [inline lib/assets/test/spec/cartodb3/components/context-menu/context-menu-view.spec.js]: you mean the paco thing? Yeah, it is cool.

**Comment by alonsogarciapablo** [comment]
👍  Thanks @xavijam!

**Comment by xavijam** [comment]
Passing travis frontend tests, merging!

**Comment by matallo** [comment]
🙌
