### PR TITLE
Fix memory leaks when disconnecting from user databases

### LINKED ISSUE #6797: Memory leaks in User database connections
When running for long times, we leak memory. Using the tooling from https://github.com/CartoDB/cartodb/pull/6746 we have identified more than 4k sequel connections (`Sequel::Postgres::Database`) and `User` objects live.

### PR DESCRIPTION
**Pull request by javitonino**
Sequel keeps a list of all databases it has connected to and never cleans it. It is a problem for multi-DB applications such as CartoDB. This PR deletes the connections from that list when they are closed, releasing the resources.

Closes #6797

CR @juanignaciosl

### CODE REVIEW

**Comment by javitonino** [comment]
Retest this, please

**Comment by juanignaciosl** [comment]
Can we somehow do an specific test for this? That code is hard to reach and to try outside production environments.

**Comment by javitonino** [comment]
Added a test to check for memory leaks. It monkey-patches the connection limit to a low number, launches several new connections and checks the number of objects is not growing. All three tests fail when removing the Sequel::DATABASES patch.

Can you CR? @juanignaciosl

**Comment by javitonino** [comment]
This now also fixes a bug where the newest connection in the pool was being dropped. It could significantly improve performance, by increasing the frequency of connection reuse.

File: lib/cartodb/connection_pool.rb [hunk 1]
```diff
@@ -56,12 +56,12 @@ def close_connections!(db=nil)
...
       @pool = newpool
     end
-    
+
     def close_oldest_connection!
       older = nil
       oldest_access = nil
       @pool.each do |connection_id, conn|
-        if oldest_access.nil? || oldest_access < conn[:last_accessed]
+        if oldest_access.nil? || conn[:last_accessed] < oldest_access
```
Comment (javitonino) [inline lib/cartodb/connection_pool.rb]: Please, review this. I am pretty sure we used to evict the newest connection of the pool instead of the oldest.

File: Makefile [hunk 2]
```diff
@@ -81,6 +81,7 @@ WORKING_SPECS_1 = \
 WORKING_SPECS_2 = \
   spec/lib/cartodb/stats/importer_spec.rb \
 	spec/lib/cartodb/stats/platform_spec.rb \
+	spec/lib/cartodb/connection_pool.rb \
```
Comment (juanignaciosl) [inline Makefile]: It should be `connection_pool_spec.rb`

File: lib/cartodb/connection_pool.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: Ô_o You're right! I've just confirmed this by lowering the pool size.

File: spec/lib/cartodb/connection_pool.rb [hunk 3]
```diff
@@ -0,0 +1,52 @@
+require_relative '../../spec_helper'
```
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool.rb]: Try using the new (merged yesterday, you'll have to merge master). `spec_helper_min`. Let me know if it's not a drop in replacement. It's slimmer and faster.

File: lib/cartodb/connection_pool.rb (hunk 1 above)
Comment (ethervoid) [inline lib/cartodb/connection_pool.rb]: I think you're right. We are removing one of the connections, not the last one, while the last_accessed date is oldest than the current one. For example:

```
Last accessed dates:

- 11:10
- 10:10
- 12:10

First iteration 11:10 becomes the oldest_access in both cases

In the second iteration:

a) old code:
    - 11:10 < 10:10 (we don't get the oldest one)
b) changed code:
    - 10:10 < 11:10 (this ensures the oldest connection)
```

I'd try to order the connection array by the oldest_access property (if possible) and delete the last one (less error prone)

File: spec/lib/cartodb/connection_pool.rb (hunk 3 above)
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool.rb]: PS: after doing it, move it to `SPEC_HELPER_MIN_SPECS` section of the Makefile.

File: spec/lib/cartodb/connection_pool.rb [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+    GC.start
+    ObjectSpace.each_object(Sequel::Postgres::Database).count
+  end
+
+  def user_object_count
+    GC.start
+    ObjectSpace.each_object(User).count
+  end
+
+  describe '#user_databases' do
```
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool.rb]: Add a test covering the `close_oldest_connection` issue you found, please.

File: lib/cartodb/connection_pool.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: Although I also use to do it that way, since we're not only accessing an array but the pair (`connection_id` , `conn`) in this case I think there's not a big benefit on the sorting + getting the first/last.

Comment (ethervoid) [inline lib/cartodb/connection_pool.rb]: Basically avoid errors like this, maybe is a bit slower but we don't have to deal with dates

File: lib/cartodb/connection_pool.rb [hunk 5]
```diff
@@ -69,12 +69,16 @@ def close_oldest_connection!
...
     private
-    
+
     def close_connection(connection, id)
       if id.end_with?('sequel')
         connection.disconnect
+        # Sequel keeps a list of all databases it has connected to that is never deleted
+        # We must manually delete the connection or it is never garbage collected, leaking memory
+        # See https://github.com/jeremyevans/sequel/blob/3.42.0/lib/sequel/database.rb#L10
+        Sequel::DATABASES.delete(connection)
```
Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: I've taken a look a Sequel code I think that `Sequel::DATABASES` is only needed for [this](https://github.com/jeremyevans/sequel/blob/1e9137167faade311f2ee255aba775beecd26cd5/lib/sequel/model/base.rb#L227):

```
      def db
        return @db if @db
        @db = self == Model ? Sequel.synchronize{DATABASES.first} : superclass.db
        raise(Error, "No database associated with #{self}: have you called Sequel.connect or #{self}.db= ?") unless @db
        @db
      end
```

So, always deleting on connection close might make this code fail if there was only one connection, which is assumed to be the "default". Do you think deleting it is safe, or maybe we could always keep "the last" database at the array?

Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: PS: the purpose of `DATABASES` is commented in [`core.rb`](https://github.com/jeremyevans/sequel/blob/1e9137167faade311f2ee255aba775beecd26cd5/lib/sequel/core.rb#L98).

File: lib/cartodb/connection_pool.rb (hunk 1 above)
Comment (javitonino) [inline lib/cartodb/connection_pool.rb]: Pool is a hash (connection_id is the key), not an array, so it is not an easy fix to sort this.

File: lib/cartodb/connection_pool.rb (hunk 5 above)
Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: PS2: every `DATABASES` modification in Sequel code is done with `Sequel.synchronize` (example: `Sequel.synchronize{::Sequel::DATABASES.delete(db)}`). [It looks like it's not needed in MRI](http://www.rubydoc.info/github/jeremyevans/sequel/Sequel.synchronize), but it's probably convenient.

**Comment by juanignaciosl** [comment]
I've made some comments that are probably not important, but since this might have a big impact please give them a thought. Ping me when you think it's done. We should probably sync with devops in order to deploy this so they can monitor connection and memory usage.

File: lib/cartodb/connection_pool.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/cartodb/connection_pool.rb]: @ethervoid you can't avoid dealing with dates here. If you want to sort this (maybe turning this hash into a tuple sorted array) you must use a comparator block based on `conn[:last_accessed]`.

File: lib/cartodb/connection_pool.rb (hunk 5 above)
Comment (javitonino) [inline lib/cartodb/connection_pool.rb]: Thanks for locating this! It helps understand why it is there.
I have been looking at the code and we call Model.db from several places, but it is not a problem even with an empty DATABASES array (even though DATABASES will never be empty. It will hold as many elements as our connection pool).

The first time `db` is called, the active database (metadata) will be associated to the models (`Sequel::Model.@db`) and it will be used from there on. No further accesses to Sequel::DATABASES past first global model use.

Even then, I'm thinking of never deleting the metadata connection from the pool, just to minimize risk. I have tested by emptying the DATABASES array on each new connection and everything seems to work, but yoy never know.

About `synchronize`: Good catch! Definitely agree it is the way to go.

**Comment by juanignaciosl** [comment]
@javitonino I've received some notifications on this PR that I can't see anymore, let me know when you want a second CR to keep the discussion and further testing and planning.

I'll ping @santisaez for him to know that we'll probably release soon (tomorrow morning, maybe?) this fix for memory leaks, which involves sequel connection management. This will require devops help for monitoring load and errors.

**Comment by javitonino** [comment]
Added a test to check for the LRU policy.

I have not added a check to avoid deleting `Sequel::DATABASES[0]`. That cannot happen as the first connection to the metadata db is opened by the Rails initialization and does not use out connection pool at all. That also explains why I was getting more elements in `Sequel::DATABASES` than in the pool itself.

CR @juanignaciosl (was finishing writing this message and testing a couple of final details). Will be testing this in staging today. Will probably recruit some help to generate some load to the connection pool.

@santisaez Do we have metrics on number of new connections to the database per second? This change should improve that, by better reuse of existing connections.

File: spec/lib/cartodb/connection_pool_spec.rb [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+
+      conn_1 = $user_1.in_database
+      pool_contains?(conn_1).should be_true
+      pool_contains?(conn_2).should be_false
+      pool_contains?(conn_3).should be_true
+    end
+  end
+
+  describe '#user_databases' do
+    it 'does not leak user databases' do
```
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool_spec.rb]: Could you please explain how come this assertions are not affected by having set `ConnectionPool::MAX_POOL_SIZE = 2`? This test is probably right, but it's not obvious for a first-time reader, who might think that 10 is never raised because of that.

Comment (javitonino) [inline spec/lib/cartodb/connection_pool_spec.rb]: Yup, it was too much of a magic number. It should be better now.

**Comment by javitonino** [comment]
Retest this, please

File: spec/lib/cartodb/connection_pool_spec.rb (hunk 6 above)
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool_spec.rb]: Thanks :-) I've run it in local without the patch and object count indeed raises to 45 :laughing:

File: spec/lib/cartodb/connection_pool_spec.rb [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+      @new_user.destroy
+      @new_user = nil
+
+      (0..4).each do |_|
+        [$user_1, $user_2].each do |user|
+          user.in_database.test_connection.should be_true
+        end
+      end
+      database_object_count.should < MAX_ALLOWABLE_CONNECTIONS
+      user_object_count.should eq initial_user_count
```
Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool_spec.rb]: This line fails if I run the test in local. Does it work for you?

```
  1) CartoDB::ConnectionPool#user_databases does not leak user databases
     Failure/Error: user_object_count.should eq initial_user_count

       expected: 2
            got: 3

       (compared using ==)
     # ./spec/lib/cartodb/connection_pool_spec.rb:82:in `block (3 levels) in <top (required)>'
```

Comment (javitonino) [inline spec/lib/cartodb/connection_pool_spec.rb]: Works for me. How are you running it? Does this happens if you run only this test case? `spec/lib/cartodb/connection_pool_spec.rb:54` I had some problems when running both tests but that should be solved now with the before/after(:each) cleanup.

Comment (juanignaciosl) [inline spec/lib/cartodb/connection_pool_spec.rb]: I run it using `bundle exec rspec spec/lib/cartodb/connection_pool_spec.rb`. Running only that test `...:54` also fails. I'll take a look.

**Comment by javitonino** [comment]
Retest this, please

**Comment by javitonino** [comment]
Tests passing. One last CR please @juanignaciosl 
Only code changes are `extracting close_sequel_connections` to a helper, closing a connection in `db_service`, and adjusting the tests.

**Comment by juanignaciosl** [comment]
:+1: 

Please make sure that devops is aware of this before deploying, and ask for help about monitoring this, since problems (or good news!) will only appear under heavy load.

Great work on this :clap:
