### PR TITLE
Skip on collision strategy

### LINKED ISSUE #11385: Address table duplication on .carto importing
### Context

If we want to take advantage of .carto for migrations, we should address current table duplication on collision. A `strategy` parameter, allowing duplication (current behavior) or skipping would be fine. 

Overwriting might also be useful, but it's an overkill for current needs. Extracted here: #11389.

 

### Steps to Reproduce

1. Create two maps based on the same table.
2. Export them and import it into another account.

### Current Result

Table is duplicated.

 

### Expected result

There should be a way to avoid duplication.

Please note that this only addresses _table_ duplication. Map duplication is not a problem (not right now, at least).

- [x] .carto
- [x] Normal imports.
- [x] Connectors.

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #11385.

**do not merge yet** because of migration file

Minimum acceptance:
- [x] Import a .carto with several tables (dropping the file in the dashboard).
- [x] Delete one of the tables and the map. Then import the .carto with the Import API and "collision_strategy=skip" parameter. It should import the deleted table and the map, without duplicating tables.
- [x] Delete all the datasets and the map. Import the .carto at the dashboard twice. Both the map and the datasets are duplicated.
- [x] Set [`MIN_IMPORT_TIME_TO_NOTIFY`](https://github.com/CartoDB/cartodb/blob/b12571f4181346c52ab0bee2d7c4882515778c9d/services/importer/lib/importer/mail_notifier.rb#L8) to 0 so the email is always sent, restart the queues. Do an import with skip so that all tables would be skipped. Check that you receive a successful import email.

### CODE REVIEW

File: lib/carto/valid_table_name_proposer.rb [hunk 1]
```diff
@@ -8,8 +8,12 @@ class ValidTableNameProposer
     DEFAULT_TABLE_NAME = 'untitled_table'.freeze
     MAX_RENAME_RETRIES = 10000
 
-    def initialize(user_id)
-      @user = ::User.where(id: user_id).first
+    def initialize(user_or_id)
+      @user = user_or_id.respond_to?(:username) ? user_or_id : ::User.where(id: user_or_id).first
+    end
```
Comment (gfiorav) [inline lib/carto/valid_table_name_proposer.rb]: I'd really favor having this logic outside. Id take the time to refactor a bit and either:

1. Have a separate initialiser method:
```ruby
def self.for_user_id(user_id)
  new(::User.where(id: user_id).first)
end

def initialise(user)
  @user = user
end
```

and then you'd call it like:

```ruby
Carto::ValidTableNameProposer.for_user_id(...)
```

2. Take the time to fetch the user outside:

```ruby
Carto::ValidTableNameProposer.new(::User.where(id: user_id))
```

File: lib/carto/valid_table_name_proposer.rb [hunk 2]
```diff
@@ -8,8 +8,12 @@ class ValidTableNameProposer
...
+
+    def taken?(table_name)
+      fetch_taken_names.include?(table_name)
```
Comment (gfiorav) [inline lib/carto/valid_table_name_proposer.rb]: I think we could avoid adding a public method here if `propose_valid_table_name` method in this class is rewritten to return early if name is available. Something like:

```ruby
def propose_valid_table_name(contendent = DEFAULT_TABLE_NAME.dup, taken_names: fetch_taken_names)
  return contendent unless taken_names.include?(contendent)
  ...
end
```

That way you avoid external checks and naively call `propose_valid_table_name` always.

File: services/importer/lib/importer/runner.rb [hunk 3]
```diff
@@ -300,6 +301,16 @@ def single_resource_import
         end
       end
 
+      def should_import?(source_file)
+        !should_skip?(source_file)
+      end
+
+      def should_skip?(source_file)
+        return false unless @user && @collision_strategy == 'skip'
```
Comment (gfiorav) [inline services/importer/lib/importer/runner.rb]: I think you can safely 

```ruby
return unless @user && @collision_strategy == 'skip'
```

Nowhere should we be doing `if whatever != false`, but rather `if whatever`

File: services/importer/lib/importer/runner.rb [hunk 4]
```diff
@@ -300,6 +301,16 @@ def single_resource_import
...
+
+        Carto::ValidTableNameProposer.new(@user).taken?(table_name_from_source_file(source_file))
```
Comment (gfiorav) [inline services/importer/lib/importer/runner.rb]: Ok, now I can see why you added the `.taken?` public method to `Carto::ValidTableNameProposer`.

I think it's very convenient, but not the right place. I'd see that some intermediate class (say `TableNameInspector`) was used both by `ValidTableNameProposer` and this for checking taken names, but as of now, it doesn't make sense that `ValidTableNameProposer` offers a `taken?` public service.

File: services/importer/lib/importer/runner.rb [hunk 5]
```diff
@@ -408,6 +419,10 @@ def result_for(job, source_file, table_names, support_table_names=[], exception_
         )
       end
 
+      def table_name_from_source_file(source_file)
+        source_file.name
+      end
```
Comment (gfiorav) [inline services/importer/lib/importer/runner.rb]: General comment:

You can globally access the source file via `downloader.source_file` instead of passing it around. 

I actually prefer to pass it around, but I don't know we should go against the spirit in this class.

Interesting debate :)

File: app/models/carto/layer.rb [hunk 6]
```diff
@@ -227,7 +227,10 @@ def default_query(user = nil)
 
     def register_table_dependencies
       if data_layer?
-        maps.reload if persisted?
+        if persisted?
+          reload
+          maps.reload
```
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: It was needed. Otherwise it doesn't link the table right. Do you think that it's a problem?

File: app/models/data_import.rb [hunk 7]
```diff
@@ -198,8 +198,13 @@ def run_import!
     log.append 'After dispatch'
 
     if results.empty?
-      self.error_code = 1002
-      self.state      = STATE_FAILURE
+      if collision_strategy == 'skip'
+        self.error_code = 1022
```
Comment (juanignaciosl) [inline app/models/data_import.rb]: Well, I won't change a column name because of this :D I think that it might be nice, for debugging purpose, knowing that nothing was imported because of skip.

File: app/models/data_import.rb [hunk 8]
```diff
@@ -880,7 +886,7 @@ def notify(results)
 
     # Calculate total size out of stats
     total_size = 0
-    ::JSON.parse(self.stats).each {|stat| total_size += stat['size']}
+    ::JSON.parse(stats).each { |stat| total_size += stat ? stat['size'] : 0 }
```
Comment (juanignaciosl) [inline app/models/data_import.rb]: It's a side effect of not importing anything: `stat` is `nil`. Previous code didn't took this into account. There are several approaches for this, but I think that returning 0 on `nil` is not bad.

File: lib/carto/valid_table_name_proposer.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/carto/valid_table_name_proposer.rb]: Yes, I must admit that I cut corners with this. I'll refactor to 1) 👍

File: app/models/carto/layer.rb (hunk 6 above)
Comment (gfiorav) [inline app/models/carto/layer.rb]: Yeah, it's a shortcut. It yields the same result AFAIK.

When I said _"I'm not sure you should"_ I was referring to using the shortcut I proposed, not about using the reload. :)

File: app/models/data_import.rb (hunk 7 above)
Comment (gfiorav) [inline app/models/data_import.rb]: I can understand the inertia of not changing the column, but let's take note that in the future we shouldn't use `error_code` but rather `code` to be open to the future :D

File: app/models/data_import.rb (hunk 8 above)
Comment (gfiorav) [inline app/models/data_import.rb]: Ah! Thanks for the explanation!

File: services/importer/lib/importer/runner.rb (hunk 4 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/runner.rb]: How come `taken?` doesn't make sense in `ValidTableNameProposer`?

Comment (gfiorav) [inline services/importer/lib/importer/runner.rb]: Well, the `ValidTableNameProposer` proposes valid table names. Strictly speaking, it should be telling you anything about what names exist already. That's just how it's implementing.

Of course, you could argue I'm nitpicking and you'd be right, but I just find that having a different piece to do that (with it's own tests) and reuse it in the name proposer is the most righteous thing to too :D

File: app/models/carto/layer.rb (hunk 6 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: Oh, sure! I will :-)

File: lib/carto/valid_table_name_proposer.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/carto/valid_table_name_proposer.rb]: In fact all other instantiations of `ValidTableNameProposer` already had a `User` instance, so the factory method is not even needed!

File: services/importer/lib/importer/runner.rb (hunk 3 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/runner.rb]: Question mark in method names means _boolean_ return type: ["The names of predicate methods (methods that return a boolean value) should end in a question mark. "](https://github.com/Vizzuality/ruby-style-guide). I prefer keeping that convention.

File: services/importer/lib/importer/runner.rb (hunk 4 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/runner.rb]: Ok, I will split `ValidTableNameProposer`. It should only _propose_ valid table names, so I'll extract table names fetching.

File: app/models/carto/data_import.rb [hunk 9]
```diff
@@ -4,6 +4,7 @@
 
 module Carto
   class DataImport < ActiveRecord::Base
+    include Carto::DataImportConstants
```
Comment (javitonino) [inline app/models/carto/data_import.rb]: Maybe it makes sense to add a model validation to check the strategy is one of the allowed ones.

File: app/models/carto/layer.rb [hunk 10]
```diff
@@ -227,7 +227,7 @@ def default_query(user = nil)
 
     def register_table_dependencies
       if data_layer?
-        maps.reload if persisted?
+        reload.maps.reload if persisted?
```
Comment (javitonino) [inline app/models/carto/layer.rb]: This `reload` seems a bit dangerous (could discard changes). Can you tell me why did you need to add it?

File: services/importer/lib/importer/runner.rb [hunk 11]
```diff
@@ -275,7 +272,7 @@ def single_resource_import
             end
 
             table_files.each_with_index do |source_file, index|
-              next if (index >= MAX_TABLES_PER_IMPORT)
+              next if (index >= MAX_TABLES_PER_IMPORT) || !should_import?(table_name_from_source_file(source_file))
```
Comment (javitonino) [inline services/importer/lib/importer/runner.rb]: Minor, probably not worth to change it. Should we count skipped tabled towards the max_tables_per_import limit? I guess it doesn't matter too much.

File: services/importer/lib/importer/runner.rb [hunk 12]
```diff
@@ -408,6 +405,10 @@ def result_for(job, source_file, table_names, support_table_names=[], exception_
         )
       end
 
+      def table_name_from_source_file(source_file)
```
Comment (javitonino) [inline services/importer/lib/importer/runner.rb]: I think this method can go. It's just a simple attribute accessor unless I'm missing something.,

File: app/models/carto/layer.rb (hunk 10 above)
Comment (juanignaciosl) [inline app/models/carto/layer.rb]: Sure. You know that layer has a `user_table` relationship that stores the dependencies. Without doing the reload, the layer added the dependencies twice. The reload fixes this by getting the updated `user_table` content, so AR knows that the relationship already exist.

Comment (javitonino) [inline app/models/carto/layer.rb]: Oh! So that how it happened. I saw the duplicated user tables but I couldn't find a way to reproduce. Nice to see it located and fixed! Thanks for the explanation ✨ 

Paranoid: Is `user_tables.reload` enough? It might be a non-issue to reload the whole model (in fact, I think it is as this is called `after_save`) but it doesn't sit right with me.

Comment (juanignaciosl) [inline app/models/carto/layer.rb]: After some tests, your suggestion seems to work and it's safer (narrower), so let's do it. Nice suggestion 👍

File: services/importer/lib/importer/runner.rb (hunk 11 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/runner.rb]: Although your comment might be right, I think that for the moment we can keep this like it is right now. Limits should be gross. As skipping depends on the context I'm not that sure of considering it for the count.

File: services/importer/lib/importer/runner.rb (hunk 12 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/runner.rb]: I did it in order to hide implementation details, but it's private and simple, so it might be overengineering. Inlining 👍

**Comment by javitonino** [comment]
I relaunched tests since they failed in the classic `shp_spec`, but they should be ✅. Let us know when this is ready for next CR, since this is unassigned in CR column but is mostly waiting for some more tests IIRC.

**Comment by juanignaciosl** [comment]
@javitonino this is ready for CR.

**Comment by juanignaciosl** [comment]
> This does not take into account other user shared tables, right?

No, it doesn't, as importing is still scoped to the user account. I think that you mean the scenario in #11434. Do you?

> Acceptance suggestion: check emails (for 1022 code, mainly)

Could you please add it to Acceptance?

**Comment by javitonino** [comment]
Oh yeah, #11434 is exactly what I meant. Added to acceptance and advanced columns.

**Comment by javitonino** [comment]
For reference, curl call to import `.carto` with `skip`

`curl -v -F create_vis=true -F collision_strategy=skip -F file=@'XXX (on 2017-02-07 at 16.35.19).carto'    "https://username.carto.com/api/v1/imports?api_key=aaaaaaaaaaaaaaaaa"`

**Comment by javitonino** [comment]
This is the email that is being sent.
screenshot_20170207_174828

Not too bad, the message is clear enough and this should never happen anyway (the mail notification timeout will not normally trigger if nothing is imported, ad the import will be fast). I think this is ready to be deployed. Agreed @juanignaciosl?

**Comment by juanignaciosl** [comment]
I think so, let's deploy this tomorrow.

**Comment by juanignaciosl** [comment]
Oh, this hasn't been CR'd by @CartoDB/dataservices yet. Pinging them before deployment. Migration is ready.

**Comment by rafatower** [comment]
hey, taking a look...

I'm also removing the @CartoDB/dataservices thing, ok?

**Comment by juanignaciosl** [comment]
Ok, good to know :-)

**Comment by rafatower** [comment]
:+1: looks nice and good to me

I can provide little value there, as it is much more related to viz/perm management than to import itself. Maybe we shall think on splitting raw data from table/viz management more explicitly. Just food for thought...

vamossss!

**Comment by juanignaciosl** [comment]
@rafatower ok, thanks, we'll deploy this, then, no more refactors in this PR :-) I wanted some of you to be aware of the changes.

Thanks!
