### PR TITLE
Fix image infowindows

### LINKED ISSUE #1970: Image infowindow is buggy
When having an image selected, and changing one of the columns it says that the image URL is not valid, but it is.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
(opened for discussion)

This PR fixes #1970. The way I have been able to reproduce the problem was:

1. Open a visualization where you have some image field.
2. Open the infowindow pane and disable all fields.
3. Reorder some fields and make sure that the field with the image url is at the top.
4. Select all fields using the "All" switch.

The Infowindow will say that the image url is invalid, even if you have a valid url and the field with the image is at the top. The reason is that we're getting the columns from the table and adding them as fields in the wrong order. More specifically, we're just iterating through the names of the columns, without considering the position they are currently in.

I've introduced [this method](https://github.com/CartoDB/cartodb/compare/1970-image-infowindows?expand=1#diff-d643227951c49f2a9a5d811b3fed2f0fR173) that gets the column names from the view, which is the only place where the order is right. But **it doesn't feel right to ask the view for that**.

@xavijam @javisantana @viddo @javierarce Any ideas on how to do it better?

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2567/))

**Comment by javisantana** [comment]
the thing here: in the infowindow we save the order of the fields, we don't we use that?

**Comment by xavijam** [comment]
If I remember, there is an attribute called order or index, isn't there?

**Comment by alonsogarciapablo** [comment]
From my understanding, in `cdb.admin.mod.InfowindowFieldsPane`, the model is a `cdb.geo.ui.InfowindowModel`, which is a "collection" that contains the fields we're displaying in the pane with right position. When we use the "All" switch, we first clear the fields (loosing the order) and then re-add all of them in no particular order. That's the problem.

I guess, instead of relying on the subviews to get the names of the fields in the right order, we could save the state of the model before clearing the fields, so that we can remember it after we select all. I'm not sure I explained myself clearly... what do you guys think? thx!

**Comment by alonsogarciapablo** [comment]
I'm adding a test first to replicate the bug.

**Comment by xavijam** [comment]
I prefer this last idea than use view items order.

**Comment by javisantana** [comment]
I'd do the thing using the model, the way we try to work is:

- all the things you need to change are done through the model
- the views only respond to model changes

Also I think that logic of keeping the order should be in the model, right?

**Comment by alonsogarciapablo** [comment]
Makes total sense @javisantana and @xavijam. Thanks for your feedback.

The order is being kept in the model, the thing is that we are "clearing" that model when we select/unselect all. But I can keep a copy of that in that situation :+1:

**Comment by javisantana** [comment]
for the record:

the infowindow model has a problem, the fields are managed internally as an array instead of using a Backbone.Collection. That makes the logic to control the views is harder because we can't control each view item, we need to deal with fields list as a whole. That makes that a single change in a field redraw the whole list. 

For reference take a look to all the field related methods we added to infowindow (https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/ui/infowindow.js#L38). Those could be replaced with a Backbone.Collection method easily. Nobody had the time or was brave enough to do that :D

**Comment by alonsogarciapablo** [comment]
@javisantana I saw those. There's also another problem with the "[sort](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/ui/infowindow.js#L78-L80)" function. We basically sort the fields based on its position, but in some cases (when user drags&drop) positions can be duplicated.

I can give a try to using Backbone.Collection after I'm done with solving the actual issue.

**Comment by xavijam** [comment]
Go pablo go! :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2586/))

**Comment by alonsogarciapablo** [comment]
I've been able to replicate the bug with [this test](https://github.com/CartoDB/cartodb/pull/2924/files#diff-091d6735c3d12cf502c56444edc28bddR225). I'm now trying to use a Backbone.Collection to internally store the position of each field, even when the model is cleared.

**Comment by xavijam** [comment]
:) :dancer:

**Comment by alonsogarciapablo** [comment]
@xavijam @javisantana please take a look at [this commit](https://github.com/CartoDB/cartodb/commit/7cc4393c07c13dd66f2ef4e688dd5077a94c0f08). I'm now using an internal Backbone.Collection to keep track of how the fields are ordered in the view. When the panel is rendered, we store how things are ordered, and we update the order whenever there's a drag and drop. If this is not "The Backbone Way", I'm happy to change it again... thx

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2603/))

**Comment by alonsogarciapablo** [comment]
InfoWindows (and the panels to manage them) are now using `cdb.geo.ui.InfowindowModel` that holds the fields that are currently enabled. These fields contains the name, position and index. Another solution would be to:

1. Modify `cdb.geo.ui.InfowindowModel` to be a `Backbone.Collection`, as suggested by @javisantana.
2. Instead of adding and removing fields from `cdb.geo.ui.InfowindowModel` when fields are enabled/disabled in the panel, make that model contain all fields and have an extra attribute per field to store wether it's enabled or disabled.

**Comment by alonsogarciapablo** [comment]
@javisantana @xavijam what do you guys think about this? thx

**Comment by xavijam** [comment]
It's likely that another field could give us more headaches. I'd try with the first one, with a pair of *****.

**Comment by alonsogarciapablo** [comment]
We're going to leave the refactor for later (although I'm kind of eager to do it). So let's focus on the current fix for #1970. What do you guys think? thx!

File: lib/assets/javascripts/cartodb/table/menu_modules/infowindow/infowindow_fields_pane.js [hunk 1]
```diff
@@ -50,31 +59,25 @@
...
-          this.$selectAll.addClass("disabled").removeClass("enabled");
-        } else {
-          this.$selectAll.addClass("enabled").removeClass("disabled");
-        }
-      } else {
-        this.$selectAll.addClass("enabled working");
-      }
+      this.$selectAll.toggleClass("working", this.working);
+      this.$selectAll.toggleClass("enabled", this.selectedAll);
+      this.$selectAll.toggleClass("disabled", !this.selectedAll);
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb/table/menu_modules/infowindow/infowindow_fields_pane.js]: :+1:

File: lib/assets/javascripts/cartodb/table/menu_modules/infowindow/infowindow_fields_pane.js [hunk 2]
```diff
@@ -31,6 +38,8 @@
       this.$selectAll = this.$el.find(".selectall");
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb/table/menu_modules/infowindow/infowindow_fields_pane.js]: At this point, could you change ```this.$el.find('...')``` for ```this.$('...')```. So picky, i know :D.

**Comment by xavijam** [comment]
Tested in staging and works good :)

**Comment by alonsogarciapablo** [comment]
@javisantana unless you have something to say, I'm going to merge this.

**Comment by javisantana** [comment]
:es:

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/2689/))
