### PR TITLE
Fix visual stuff for new georeference modal

### LINKED ISSUE #4262: Geocode fixes
So after test geocode I found a few little things:

- [x] `#666` header icons color and change header copy to `Transform your data into coordinates`: _fixed in #4370_
screen shot 2015-07-07 at 7 04 53 pm

- [x] Update points icon from: _fixed in #4372_
screen shot 2015-07-08 at 11 57 28 am
to this:
screen shot 2015-07-08 at 12 05 07 pm

- [x] Delete Learn more and its tooltip: _fixed in #4372_
screen shot 2015-07-08 at 11 16 46 am

- [x] To unify this type of boxes, we decided to make them one-click, just like Merge tables one behaves. So no confirm button needed.
  -  _fixed in #4372_

- [x] Subheader to go back: _fixed in #4380_
screen shot 2015-07-02 at 11 40 20 am

- [x]  Fix header tabs distance: _fixed in #4380_
(they are 20px and should be 30px)
screen shot 2015-07-07 at 5 34 04 pm

- [x] As @xavijam mentioned on #4255 here are some enhancements to the dropdown (the "arrow" should be the same):
screen shot 2015-07-02 at 12 11 32 pm

- [x] Header text to options space should be 40px:
This:
screen shot 2015-07-07 at 6 55 15 pm
instead of this:
artboard

 - [x] Spacings between options should be 28px:
screen shot 2015-07-08 at 12 32 49 pm
screen shot 2015-07-08 at 12 35 51 pm

- [x] Green icon when you select a column:
screen shot 2015-07-02 at 11 40 59 am

- [x] Thanks to @iriberri for spotting this) On small windows, footer's button does not show.
screen shot 2015-07-07 at 6 59 31 pm

### PR DESCRIPTION
**Pull request by viddo**
This fixes #4262 (see the issue for scope)

screen shot 2015-07-14 at 15 26 33

While at it I could consolidate a lot of repeated code among the different models, why there are a lot of things moved around there, basically each use-case has it's own model that provides the context-specific data, while views related to the rows and selecting geometry method are now generic.

@xavijam please code review
cc @josecruz since he reported most the issues

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4960/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4961/))

**Comment by viddo** [comment]
Deployed on ded03 for testing

File: lib/assets/javascripts/cartodb/common/dialogs/georeference/admin_regions_model.js [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+var Backbone = require('backbone');
+var StepsView = require('./steps_view');
+var RowModel = require('./row_model');
+
+/**
+ * Model for the administrative regions georeference option.
+ */
+module.exports = cdb.core.Model.extend({
+
+  TAB_LABEL: 'Admin. Regions',
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/dialogs/georeference/admin_regions_model.js]: We used to create those "static" vars with "_XXXX", have you seen them around the editor?

Comment (viddo) [inline lib/assets/javascripts/cartodb/common/dialogs/georeference/admin_regions_model.js]: I put them as static props since they're not expected to be changed (as you pointed out in a prev code review).
Yes, I've seen them but AFAIK that's used for _private_ variables only, right? In this case the variables are static but accessed by the view.

Comment (xavijam) [inline lib/assets/javascripts/cartodb/common/dialogs/georeference/admin_regions_model.js]: Yeah yeah, they are ok, but we used to add the "_" before the name, but I don't have a strong opinion why we should add it or not.

Comment (viddo) [inline lib/assets/javascripts/cartodb/common/dialogs/georeference/admin_regions_model.js]: IMHO, I think it makes sense to use _prefix to indicate that the var/function is for private usage, since this is not the case I'd prefer to leave them as they are.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4979/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4988/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4989/))

**Comment by xavijam** [comment]
I've spotted one thing

screen shot 2015-07-15 at 15 27 18

**Comment by xavijam** [comment]
In a first view and after reviewing the code, it looks great, but @josecruz is your call now.

**Comment by saleiva** [comment]
Yep, that text is too long @jose

**Comment by viddo** [comment]
The texts were migrated from the prev modal, you probably want to review them [all here](https://github.com/CartoDB/cartodb/blob/92570dd3b362fe912846d454d989ab7bdc743478/lib/assets/javascripts/cartodb/common/dialogs/georeference/street_addresses/estimation.jst.ejs#L18-L26) then

**Comment by saleiva** [comment]
@josecruz go go go!

**Comment by viddo** [comment]
The rest of the changes were OK'd by @josecruz, so I'll go ahead and merge, the text issues can be resolved separately. :kiss:
