### PR TITLE
Checking the_geom presence fixes #5477

### LINKED ISSUE #5477: Error assigning as owner a user with non-cartodbfied tables
While fixing CartoDB/cartodb-platform#1072 we saw that users with tables that are not cartodbfied can't be set as organization owners. When a user is set as owner his tables are moved from `public` to his username schema with this code taken from `User`:

```
1661   def move_tables_to_schema(old_schema, new_schema)
1662     self.real_tables(old_schema).each do |t|
1663       self.in_database(as: :superuser) do |database|
1664         old_name = "#{old_schema}.#{t[:relname]}"
1665         new_name = "#{new_schema}.#{t[:relname]}"
1666         database.run(%Q{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) })
1667         database.run(%Q{ ALTER TABLE #{old_name} SET SCHEMA "#{new_schema}" })
1668         database.run(%Q{ SELECT cartodb._CDB_create_triggers('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) })
1669       end
1670     end
1671   end
```

[`cartodb._CDB_create_triggers` fails](https://github.com/CartoDB/cartodb-postgresql/blob/c12ae7f4a893eebecdcb09fe3f80698cb3adb6e6/scripts-available/CDB_CartodbfyTable.sql#L42) for tables not cartodbfied because of `Sequel::DatabaseError: PG::Error: ERROR:  column "the_geom" of relation "<table name>" does not exist`

Alternative fixes:
a) `move_tables_to_schema` should not run trigger lines (1666 and 1668 at previous code) for non-cartodbfied tables.
b) `_CDB_drop_triggers` and `_CDB_create_triggers` should not fail for non-cartodbfied tables.

cc @CartoDB/backend

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #5477

### CODE REVIEW

**Comment by juanignaciosl** [comment]
@rafatower @javisantana CR this, please. I'm not sure about it because [trigger creation is more than `the_geom`](https://github.com/CartoDB/cartodb-postgresql/blob/c12ae7f4a893eebecdcb09fe3f80698cb3adb6e6/scripts-available/CDB_CartodbfyTable.sql#L202) and maybe this should be handled at extension level, but discussion at #5477 suggested editor level fix.

FYI this error [was introduced (by me)](https://github.com/CartoDB/cartodb/pull/4214/files#diff-4676c008b11a5480d73d4a6de01e45b9R1554) in 91547d895e71f871f6bc82f4db3f489fe3a9ad0f ~3 months ago while fixing #3534 (PR #4214).

File: app/models/user.rb [hunk 1]
```diff
@@ -1655,9 +1655,12 @@ def move_tables_to_schema(old_schema, new_schema)
...
         old_name = "#{old_schema}.#{t[:relname]}"
         new_name = "#{new_schema}.#{t[:relname]}"
-        database.run(%Q{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) })
+
+        has_the_geom = Table.has_column?(in_database, old_schema, t[:relname], 'the_geom')
+
+        database.run(%{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) }) if has_the_geom
         database.run(%Q{ ALTER TABLE #{old_name} SET SCHEMA "#{new_schema}" })
-        database.run(%Q{ SELECT cartodb._CDB_create_triggers('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) })
+        database.run(%{ SELECT cartodb._CDB_create_triggers('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) }) if has_the_geom
```
Comment (rafatower) [inline app/models/user.rb]: Sorry but there are a few things I don't like about the fix:
- the reason of dropping the trigger is that otherwise it cannot move the table to the other schema and keep it working, right?. That can happen for cartodbfy'ed tables (and they can change over time) but also for user triggers. Though user triggers are not that frequent, you might find that problem as well.
- detecting if it is cartodbfy'ed based on the_geom column is not right. From the editor it should simply check for having the table in `user_tables` in metadata DB.
- instead of re-creating cartodb triggers manually, I'd trigger the public-method-with-stable-api CDB_CartodbfyTable()`.

Comment (juanignaciosl) [inline app/models/user.rb]: - You're right about user triggers. Nevertheless is a problem we haven't had yet, so I'd move that to another issue and solve the current problem, since it's blocking organization creations, if you don't mind.
- Uhm. You're right about `the_geom` check being wrong, but checking `user_tables` won't cover all cases. If a user uses sql api to create a table and cartodbfies it without triggering ghost tables it won't be registered. a) Is there a direct cartodbification validatation? or b) we can live with this and I should check cartodbification with user_tables presence?
- Ok, I didn't know it was safe for already cartodbified tables, great! :+1:

Comment (rafatower) [inline app/models/user.rb]: >  If a user uses sql api to create a table and cartodbfies it without triggering ghost tables it won't be registered.

but then you're sure the table in user's DB has no metadata associated, and can let ghost tables link it in the destination schema.

A cartodbfy'ed table by definition should be one with an entry in `user_tables` from editor's perspective, IMHO. There's no other possible validation AFAIK. I vote for (b)


> I didn't know it was safe for already cartodbified tables

`CDB_CartodbfyTable` shall be idempotent. It kind of was and I worked hard on keeping that as a requirement. Maybe you can find some help [here](https://github.com/CartoDB/cartodb-postgresql/pull/151) and/or contribute :smile:

Comment (rafatower) [inline app/models/user.rb]: oh, and I'd make this deal with exceptions in general because otherwise it can break midway not only because there are user triggers but connectivity errors and the such.

Comment (juanignaciosl) [inline app/models/user.rb]: Ok, I buy all your points. Stay tuned for a second CR. Many thanks :-)

**Comment by juanignaciosl** [comment]
@rafatower take a second look, please (currently I can't view our previous conversation thread, don't know why :-\).

File: app/models/user.rb [hunk 2]
```diff
@@ -2261,7 +2267,7 @@ def grant_all_on_schema_queries(schema, db_user = nil)
   end
 
   def drop_users_privileges_in_schema(schema, accounts)
-    in_database(:as => :superuser) do |user_database|
+    in_database(as: :superuser, statement_timeout: 600000) do |user_database|
```
Comment (rafatower) [inline app/models/user.rb]: `statement_timeout` is by default in milliseconds so you're letting 10 minutes for the whole thing. This kind of operation should be fast but maybe you want to be in the safe by allowing a bit more time?

File: app/models/user.rb [hunk 3]
```diff
@@ -1640,24 +1641,29 @@ def setup_schema
...
+      database.transaction do
+        real_tables(old_schema).each do |t|
+          old_name = "#{old_schema}.#{t[:relname]}"
+          new_name = "#{new_schema}.#{t[:relname]}"
+
+          was_cartodbfied = Carto::UserTable.find_by_user_id_and_name(id, t[:relname]).present?
+
+          database.run(%{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) }) if was_cartodbfied
+          database.run(%{ ALTER TABLE #{old_name} SET SCHEMA "#{new_schema}" })
+          database.run(%{ SELECT cartodb.CDB_CartodbfyTable('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) }) if was_cartodbfied
```
Comment (rafatower) [inline app/models/user.rb]: here's the gist of the change, thanks hound for obscuring my review :stuck_out_tongue: 

LGTM

File: app/models/user.rb [hunk 4]
```diff
@@ -1640,24 +1641,29 @@ def setup_schema
...
 
   def move_tables_to_schema(old_schema, new_schema)
-    self.real_tables(old_schema).each do |t|
-      self.in_database(as: :superuser) do |database|
-        old_name = "#{old_schema}.#{t[:relname]}"
-        new_name = "#{new_schema}.#{t[:relname]}"
-        database.run(%Q{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) })
-        database.run(%Q{ ALTER TABLE #{old_name} SET SCHEMA "#{new_schema}" })
-        database.run(%Q{ SELECT cartodb._CDB_create_triggers('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) })
+    in_database(as: :superuser) do |database|
```
Comment (rafatower) [inline app/models/user.rb]: moving schemas shall be fast, but given this is proportional to the number of tables you might one to set an explicit timeout for the whole thing.

**Comment by rafatower** [comment]
:+1: I made a couple of minor comments about timeouts.

File: app/models/user.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/models/user.rb]: 10 minutes is far too much. I could even lower it indeed. I needed more than default at my local environment, but this is not a problematic timeout.
