### PR TITLE
separate privacy sharing saves

### LINKED ISSUE #3441: "Share dialog" won't open from the "Change Privacy dialog" when choosing "Password protected" and password is empty
Steps to reproduce:

1. Login with a user that belongs to an org.
2. Open the Change Privacy dialog.
3. Click "Password protected".
4. Click "Share this dataset with your colleagues" on the banner at the bottom.
5. Nothing happens (Share dialog remains hidden).
6. Type a passord.
7. Click "Share this dataset with your colleagues" again.
9. Share dialog is now visible.

[Here's the reason why it's not working](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/start_view.js#L73). Do you remember why we added that @viddo. I'd say we can remove it.

### PR DESCRIPTION
**Pull request by viddo**
Fixes #3441 

The major change is that change-privacy-view and share-view are separated to two separate modals, because they now have separated flows for privacy vs. permission changes. The share-banner also changed to indicate the different sharing state for the map/dataset:
screen shot 2015-05-06 at 18 53 19
screen shot 2015-05-06 at 18 53 27
screen shot 2015-05-06 at 18 53 44

I'll add inline comments to explain some refactoring details.

### CODE REVIEW

File: lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/view_model.js [hunk 1]
```diff
@@ -1,135 +0,0 @@
-var cdb = require('cartodb.js');
```
Comment (viddo) [inline lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/view_model.js]: With the factoring the view model is no longer needed for the change-privacy part. The remaining parts used for the share view was moved to the share/share_model (seems like git didn't recognize this move, probably because the files differs too much now).

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3522/))

File: lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/share/share_view.js [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+    var $content = this._panes.getActivePane().render().el;
+    if (this._panes.getActivePane() !== this._panes.getPane('sharing')) {
+      return [
+        this._headerEl(),
+        $content
+      ];
+    } else {
+      return $content;
+    }
+  },
```
Comment (viddo) [inline lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/share/share_view.js]: Yes, this method looks hacky. The reason to this is because the CSS styles related to achieve the scrolling and having fixated header/footer requires the DOM to have a certain structure to work, I didn't manage to resolve that even with a few hours of troubleshooting. 

To fix this properly I'm afraid that it would require more time and probably a revamp of the current solution. For future reference: [`.Dialog-content--expaned`](https://github.com/CartoDB/cartodb/blob/master/app/assets/stylesheets/new_common/dialog.css.scss#L54-L62) and [expanded header/footer-subcontent](https://github.com/CartoDB/cartodb/blob/master/app/assets/stylesheets/new_common/dialog.css.scss#L162-L191) in new_common/dialog.css.scss

File: lib/assets/javascripts/cartodb/new_common/views/base_dialog/view.js [hunk 3]
```diff
@@ -25,6 +25,7 @@ var BaseDialog = cdb.ui.common.Dialog;
  *   dialog.appendToBody();
  */
 module.exports = BaseDialog.extend({
+
```
Comment (viddo) [inline lib/assets/javascripts/cartodb/new_common/views/base_dialog/view.js]: While working on the new modals I noticed some inconsistencies and race conditions related to switch between modals which I fixed here (and simplify the code a bit).

**Comment by viddo** [comment]
Please review @xavijam, since you probably want this merged before you start to deprecate the old dashboard stuff. cc @alonsogarciapablo since you changed the sharing view recently and there are some (minor) changes done to the view model, among other things, can probably use another set of :eyeglasses: for review just in case

cc @saleiva and @javierarce for :sparkles: 

Deployed on staging ded02 (ETA 10 min from when you read this :))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3526/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3527/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3528/))

**Comment by alonsogarciapablo** [comment]
Looks really good!

I found something weird here:

wadus

You can see how "blablabla" was enabled, then I toggled "whole organization" twice, enable "blablabla" again, but then it doesn't seem to save changes...

**Comment by viddo** [comment]
@alonsogarciapablo should be fixed with https://github.com/CartoDB/cartodb/commit/0f6748a4e6899b1afe5a8fee7bbee7d2b4d1f367

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3536/))

**Comment by xavijam** [comment]
If we agree with the last change made by @viddo, ready to go! :)

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/3537/))
