### PR TITLE
10768 namedmap with sources

### LINKED ISSUE #10768: Adding default source analysis can break editor maps
### Context
From support: https://github.com/CartoDB/cartodb-management/issues/4704. Summarizing, when a user opens a map in the builder (even if he cancels the migration modal), the layer SQL visibility wrapping breaks.

### Steps to Reproduce
1. Create a map in editor with multiple layers
2. Add something that prevents automatic migration to builder (e.g: overlays)
3. Upgrade the user to builder
4. Try to open the map, a warning is displayed.
5. Cancel the warning

### Current Result
The embed from the map opens the old embed, but you cannot hide layers. This is because when the source analysis where added (during step 4), the new named map does not contain visibility wrapping in the queries.
 
### Expected result
The old map works fine.

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10768 

Named maps for editor maps should never contain `layer.options[:source]`.

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @juanignaciosl

File: app/models/carto/visualization.rb [hunk 1]
```diff
@@ -414,6 +418,10 @@ def add_source_analyses
         CartoDB::Logger.warning(message: 'Couldn\'t add source analysis for layer', user: user, layer: layer)
       end
     end
+
+    # This is needed because Carto::Layer does not yet triggers invalidations on save
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Nice comment 👌
