### PR TITLE
Fixes at import notifications #11269

### LINKED ISSUE #11269: Import error email visuals don't fit the message
From CartoDB/design/issues/491

The visual language is a bit confusing:

image

Looks like everything went fine, instead of raising an error

It looks like current import mail code doesn't support error messages.

cc @AbelVM @saleiva @xavijam @MariaCheca

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #11269 . Many small details here. Please read the issue thoroughly before CRing.

### CODE REVIEW

File: app/mailers/import_mailer.rb [hunk 1]
```diff
@@ -11,8 +11,13 @@ def data_import_finished(user, imported_tables, total_tables, first_imported_tab
     @subject = set_subject
     @first_table = first_imported_table.nil? ? first_table : first_imported_table
     @username = user.username
-    @files = filenames
-    @link = first_imported_table.nil? ? "#{user.public_url}#{CartoDB.path(self, 'tables_index')}" : "#{user.public_url}#{CartoDB.path(self, 'public_tables_show', { id: @first_table['name'] })}"
+    @files = filenames || []
+    @dataset_name = @first_table && @first_table['name'].present? ? @first_table['name'] : @files.first
```
Comment (gfiorav) [inline app/mailers/import_mailer.rb]: Just out of paranoia:

`(@first_table && @first_table['name'].present?) ? @first_table['name'] : @files.first`

seems more parser safe and more readable

File: app/models/data_import.rb [hunk 2]
```diff
@@ -401,6 +401,10 @@ def validate
     errors.add(:user, "Viewer users can't create data imports") if user && user.viewer
   end
 
+  def final_state?
+    [STATE_COMPLETE, STATE_FAILURE, STATE_STUCK].include? state
```
Comment (gfiorav) [inline app/models/data_import.rb]: I think this parameter needs a parenthesis around it! I've read in some style guides the following regarding parenthesis: "If a method returns nothing, it's ok to not use parenthesis. They should be present otherwise". For example the `render` stuff in controllers.

Regardless, I prefer to use them always since the parser can get a bit lost if you put stuff afterwards. Example:

```ruby
def final_state?
  [STATE_COMPLETE, STATE_FAILURE, STATE_STUCK].include? state || other_condition
end
```

What is it here? Is the param of the `include?` method `state || other_condition` or is it meant to be like:

```ruby
[STATE_COMPLETE, STATE_FAILURE, STATE_STUCK].include?(state) || other_condition
```

In any case, `include?` returns a value, so I'd go with parenthesis :)

File: services/importer/lib/importer/mail_notifier.rb [hunk 3]
```diff
@@ -19,7 +19,7 @@ def notify_if_needed
       end
 
       def should_notify?
-        import_time >= MIN_IMPORT_TIME_TO_NOTIFY && @data_import.synchronization_id.nil?
+        import_time >= MIN_IMPORT_TIME_TO_NOTIFY && @data_import.synchronization_id.nil? && @data_import.final_state?
```
Comment (gfiorav) [inline services/importer/lib/importer/mail_notifier.rb]: As a general comment:

This method exists because `MailNotifier` is called before time. This seems wrong to me. Have you explored the `notify_results` method of `DataImport` to see if there's a way to prevent premature calls there?

I've worked with that code and have discovered, sadly, that `notify_results` is called upon initialisation just to "initialise the logger" which of course is totally wrong, so there might be some monsters there that you don't want to face now.

Just curious to hear on that approach.

File: app/models/data_import.rb (hunk 2 above)
Comment (juanignaciosl) [inline app/models/data_import.rb]: Sure, I must admit that I don't pay too much attention when I move old code around :_)

File: services/importer/lib/importer/mail_notifier.rb (hunk 3 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/mail_notifier.rb]: Good point, let's talk about this.

It's not exactly true that "This method exists because MailNotifier is called before time". I'd better say that "this method encapsulates the logic of deciding to notify, which belongs to the notifier". `notify(results)` has plenty of room for enhancement in its naming. If you check it you'll see that it doesn't only notify (by mail) if needed. It takes care of logging and stats aggregation. To be honest, I haven't thought about moving the notification outside, but it might make sense. Take a look at this line:

```ruby
CartoDB::Importer2::MailNotifier.new(self, results, ::Resque).notify_if_needed
```

It doesn't say that it notifies a finished import. According to that code, it could also send an email saying "ey, you're importing 2GB, so it will take some time, but we're on it". _But_ currently it doesn't do that, so this might be a case of premature (naming) optimization. I think that it could be [moved to `run_import!`, after `success ? handle_success : handle_failure`](https://github.com/CartoDB/cartodb/blob/1281308a3720b699c070b05ab727c0cf82c93985/app/models/data_import.rb#L208), but changing `notify_if_needed` to `notify_finished_if_needed`.

How does it sound?

File: app/mailers/import_mailer.rb [hunk 4]
```diff
@@ -11,8 +11,13 @@ def data_import_finished(user, imported_tables, total_tables, first_imported_tab
     @subject = set_subject
     @first_table = first_imported_table.nil? ? first_table : first_imported_table
     @username = user.username
-    @files = filenames
-    @link = first_imported_table.nil? ? "#{user.public_url}#{CartoDB.path(self, 'tables_index')}" : "#{user.public_url}#{CartoDB.path(self, 'public_tables_show', { id: @first_table['name'] })}"
+    @files = filenames || []
+    @dataset_name = (@first_table && @first_table['name'].present?) ? @first_table['name'] : @files.first
```
Comment (juanignaciosl) [inline app/mailers/import_mailer.rb]: ^ :D cc @gfiorav what do you think? :D

File: services/importer/lib/importer/mail_notifier.rb (hunk 3 above)
Comment (gfiorav) [inline services/importer/lib/importer/mail_notifier.rb]: Fair point. After the discussion I wouldn't change anything at all. I don't feel we gain either way :)

File: app/mailers/import_mailer.rb (hunk 4 above)
Comment (gfiorav) [inline app/mailers/import_mailer.rb]: haha oh no!

Honestly, I don't know. It's really ugly to do 

```ruby
@dataset_name = @first_table.try(:[], 'name').present? ? @first_table['name'] : @files.first
```

It's the first time I strongly disagree with Hound. Up to you!

File: services/importer/lib/importer/mail_notifier.rb (hunk 3 above)
Comment (juanignaciosl) [inline services/importer/lib/importer/mail_notifier.rb]: Ok, up to you, but you made a good point. Maybe next time :-) 👍

File: app/mailers/import_mailer.rb (hunk 4 above)
Comment (juanignaciosl) [inline app/mailers/import_mailer.rb]: As I've already triggered the tests and it's not a big deal, let's pretend we didn't hear the barking this time 🙄
