### PR TITLE
Handle states without center

### LINKED ISSUE #12453: undefined method `empty?' for nil:NilClass on import
[trace](https://rollbar.com/carto/CartoDB/items/23887/occurrences/26936460288/):

```
NoMethodError: undefined method `empty?' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/carto/named_maps/template.rb", line 240 in view
2
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/carto/named_maps/template.rb", line 44 in block in to_hash
3
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/cartodb/stats/aggregator.rb", line 97 in method_missing
4
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/carto/named_maps/template.rb", line 31 in to_hash
5
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/carto/named_maps/template.rb", line 50 in to_json
6
File "/home/ubuntu/www/production.cartodb.com/releases/20170711105029/lib/carto/named_maps/api.rb", line 37 in block in create
```

This was addressed by @rafatower in a previous hotfix (50dbbcaef43f08f2c7982e816c2e0b7d3926d209), but it's not working yet.

I guess that it lacks one more check:

if state.nil? || state.empty? || state[:map].empty? || state[:map][:center].empty?

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #12453.

### CODE REVIEW

File: lib/carto/named_maps/template.rb [hunk 1]
```diff
@@ -237,7 +237,7 @@ def auth
 
       def view
         state = @visualization.state.json
-        if state.empty? || state[:map].empty? || state[:map][:center].empty?
+        if state.blank? || state[:map].blank? || state[:map][:center].blank?
```
Comment (mayoral) [inline lib/carto/named_maps/template.rb]: Note for our future selfs: In Ruby >= 2.3 we can do this much shorter:

``` ruby
if state.blank? || state.dig(:map, :center).blank?
```
