### PR TITLE
Make sure org_admin is set in creation controller

### LINKED ISSUE #12159: When creating an organizational admin user, admin rights are not correctly set
### Context
As an owner, when creating a new organizational admin user, admin rights are not correctly set

### Steps to Reproduce

1. Create a new user
2. Assign admin rights

### Current Result
User is created, but not with admin right, requiring an edit to the user settings.

### Expected result
An admin user is created

cc @kevin-reilly

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #12159 

**Acceptance**

Verify that the correct value is set after every step.

- [x] Enable `organization-admins` FF for the organization owner
- [x] As the owner, create a new user, set the administrator flag to true. After creation, ensure that this is correctly saved.
- [x] Repeat the previous with the flag set to false.
- [x] Then, edit the previous user. First, enable it. Then disable it.

### CODE REVIEW

**Comment by juanignaciosl** [comment]
With the feature flag disabled, it fails:

```
Sequel::DatabaseError: PG::Error: ERROR:  null value in column "org_admin" violates not-null constraint
DETAIL:  Failing row contains (juanignaciosl+ded-07-3@carto.com, bd80a965e7d6352723139559c11205e2743e645a, 15a958194de2a4ef552b5c60ee8bf80c2f201c7e, nu
```

[trace](https://rollbar.com/vizzuality/CartoDB/items/23060/?item_page=0&#instances).

File: app/controllers/admin/organization_users_controller.rb [hunk 1]
```diff
@@ -69,8 +69,8 @@ def create
         :soft_obs_snapshot_limit, :soft_obs_general_limit, :soft_mapzen_routing_limit
       ]
     )
-    @user.org_admin = params[:user][:org_admin] == 'true'
     @user.viewer = params[:user][:viewer] == 'true'
+    @user.org_admin = params[:user][:org_admin] if @organization.owner.has_feature_flag?('organization-admins')
```
Comment (juanignaciosl) [inline app/controllers/admin/organization_users_controller.rb]: Uhm. Making the read of a parameter depending of a feature flag is coupling too much with the frontend. My proposal:

`@user.org_admin = params[:user][:org_admin] || false`

That works in every situation. It will be redundant when feature flag is gone, but having safe default values for mandatory parameters is not a bad thing. What do you think?

PS: that would also avoid needing the feature flag in the test, confirming that we're testing the ff itself.

Comment (juanignaciosl) [inline app/controllers/admin/organization_users_controller.rb]: PS: I wanted to "comment", not "approve" changes.

Comment (javitonino) [inline app/controllers/admin/organization_users_controller.rb]: Well, I wanted to avoid API users to create org_admins without the FF, that's why I took the extra step. Indeed, my first approach was `@user.org_admin = params[:user][:org_admin] unless params[:user][:org_admin].nil?`, which uses the default from the model (which is false) rather than setting that in the controller.

Although, given that we are not checking anything in `update` or EUMAPI either, I'll revert to that approach.

Comment (juanignaciosl) [inline app/controllers/admin/organization_users_controller.rb]: That's better, indeed ✨

**Comment by javitonino** [comment]
Ready for round 2
