### PR TITLE
7369 importing error wrong number of arguments

### LINKED ISSUE #7369: Some visualization imports fail with wrong number of arguments
https://rollbar.com/vizzuality/CartoDB/items/18396/?item_page=0&#instances

```
ArgumentError: wrong number of arguments (1 for 2)
1
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/services/minimal-validation/validator.rb", line 32 in store
2
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/services/minimal-validation/validator.rb", line 32 in validate_presence_of_with_custom_message
3
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/models/visualization/member.rb", line 197 in valid?
4
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/models/visualization/member.rb", line 168 in store
5
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/services/carto/visualizations_export_persistence_service.rb", line 61 in save_import
6
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/connectors/importer.rb", line 108 in block in create_visualization
7
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/connectors/importer.rb", line 107 in each
8
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/connectors/importer.rb", line 107 in create_visualization
9
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/connectors/importer.rb", line 60 in run
10
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/models/data_import.rb", line 669 in new_importer
11
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/models/data_import.rb", line 398 in dispatch
12
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/app/models/data_import.rb", line 176 in run_import!
13
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/lib/resque/importer_jobs.rb", line 9 in block in perform
14
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/lib/resque/base_job.rb", line 21 in call
15
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/lib/resque/base_job.rb", line 21 in run_action
16
File "/home/ubuntu/www/production.cartodb.com/releases/20160511143153/lib/resque/importer_jobs.rb", line 9 in perform
```

### PR DESCRIPTION
**Pull request by juanignaciosl**
This fixes #7369. @gfiorav CR this, please.

### CODE REVIEW

File: services/minimal-validation/validator.rb [hunk 1]
```diff
@@ -24,12 +24,14 @@ def validate_presence_of(attributes)
...
       has_errors = false
+      error_attribute = nil
       attributes.each do |attribute, value|
         if (value.nil? || value.empty?)
+          error_attribute = attribute
           has_errors = true
         end
       end
-      errors.store(custom_message) if has_errors
+      errors.store(error_attribute.to_sym, custom_message) if has_errors
```
Comment (gfiorav) [inline services/minimal-validation/validator.rb]: seems a bit odd, you're searching for the attribute of the last occurrence of a non nil non empty error? Only the last one?

Comment (juanignaciosl) [inline services/minimal-validation/validator.rb]: Yep, it looks odd. This is failing code that seemed mostly unused, because it's just wrong. Check the trace, `store` always has 2 arguments. Keep in mind that the method is meant to always trigger the same message,  and only once, no matter related to what it is. So I picked the first one. If you check `errors` usage at that class I think that it makes sense, but I'm open to better alternatives.

Comment (gfiorav) [inline services/minimal-validation/validator.rb]: I'm all for rewriting this, but depending on the workload it supposes I can
totally understand keeping it. Still seems very error prone to only check the
last value found.

On May 11 2016, at 6:41 pm, Juan Ignacio Sánchez Lara
&lt;notifications@github.com&gt; wrote:  

> In [services/minimal-validation/validator.rb](https://github.com/CartoDB/car
todb/pull/7370#discussion_r62882594):

>  
>  
>     >            has_errors = true

>     >          end

>     >        end

>     > -      errors.store(custom_message) if has_errors

>     > +      errors.store(error_attribute.to_sym, custom_message) if
has_errors

>  
>

> Yep, it looks odd. This is failing code that seemed mostly unused, because
it's just wrong. Check the trace, `store` always has 2 arguments. Keep in mind
that the method is meant to always trigger the same message, and only once, no
matter related to what it is. So I picked the first one. If you check `errors`
usage at that class I think that it makes sense, but I'm open to better
alternatives.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/CartoDB
/cartodb/pull/7370/files/44bf4a68e2b3d2daf7fd088fa5a648918ac2a664#r62882594)

Comment (juanignaciosl) [inline services/minimal-validation/validator.rb]: It's almost dead code. That line hadn't been run for months and we have more urgent stuff ongoing :D. This validator will eventually die, don't invest time on it.

Comment (gfiorav) [inline services/minimal-validation/validator.rb]: 🌴

**Comment by gfiorav** [comment]
📦 it!
