### PR TITLE
Avoid deletion of import log after user migration failure

### LINKED ISSUE #13542: User migrator deletes import log after importing failure
When migrating a user with both meta and data (between clouds), if the import fails at the data phase, the UserMigration entry will get deleted, and central cannot get the results. This is caused because the import links to the user/organization model: https://github.com/CartoDB/cartodb/blob/master/app/models/carto/user_migration_import.rb#L103 and there is a CASCADE FK form users to migrations.

We want to avoid deleting in this case so we can look at the log. This most likely implies setting the user/org field to `nil` in case of rollback.

### PR DESCRIPTION
**Pull request by alrocar**
Closes #13542

### CODE REVIEW

**Comment by alrocar** [comment]
retest this please

File: spec/models/carto/user_migration_import_spec.rb [hunk 1]
```diff
@@ -99,9 +126,18 @@ def setup_mocks
...
+    end
+
+    def setup_mocks
+      setup_common_mocks
       @import.expects(:save!).once.returns @import
     end
 
+    def setup_failure_mocks
+      setup_common_mocks
+      @import.expects(:save!).twice
```
Comment (javitonino) [inline spec/models/carto/user_migration_import_spec.rb]: You can use `stubs` instead of `expect` and remove `twice` if you don't care about the specific number of calls. Or `at_least_once` should also work.

File: spec/models/carto/user_migration_import_spec.rb [hunk 2]
```diff
@@ -71,6 +72,32 @@
...
+    it 'avoids cascade deletion of a failed user migration' do
+      setup_failure_mocks
+      should_import_metadata_for_failed_user(@user)
+      should_import_data_with_exception
+      @import.org_import = false
+      @import.organization_id = nil
+      should_update_database_host_for_users([@user])
+
+      @import.run_import
+      @import.user.should eq nil
```
Comment (javitonino) [inline spec/models/carto/user_migration_import_spec.rb]: Uhm, not sure if these tests are enough... These are very heavily stubbed, so they don't really run all the code. I don't think the rollback code is really running.

For example, if you check here if `@user` exists, what does it happen? If the rollback was successful, it should not exist, but I get the feeling that it will. If the user didn't get deleted, of course the migration won't. For this test to be valid, the user should not exist at this point.

Also, instead of checking if the `@import.user` is `nil` (that is, the implementation), you should check the behaviour that was reported in the bug, in this case, that the `@import` itself is note deleted.

Aside from reviewing these tests (or removing them if they are hard to fix, which they may be with so many stubs), I can suggest adding a test in `user_migration_spec.rb` which tests the process from an outside point of view. In that case, you would stuff `import_data` to fail (raise an error) and then check that after the import fails, it does exists (and the imported user doesn't).

File: spec/models/carto/user_migration_spec.rb [hunk 3]
```diff
@@ -159,6 +159,19 @@
       import.run_import.should eq false
       Carto::User.exists?(@user.id).should eq true
     end
+
+    it 'import record should exist if import_data fails and rollbacks' do
+      Carto::UserMigrationImport.any_instance.stubs(:do_import_data).raises('Some exception')
```
Comment (javitonino) [inline spec/models/carto/user_migration_spec.rb]: You can just stub the instance you care about (`imp`) doing something like: `imp.stubs(:do_import_data).raises('Some exception')`. This also gets rid of the need to unstub.

File: spec/models/carto/user_migration_spec.rb [hunk 4]
```diff
@@ -159,6 +159,19 @@
...
+
+      imp = import
+      imp.run_import.should eq false
+      imp.state.should eq 'failure'
+
+      Carto::UserMigrationImport.where(id: imp.id).should_not be_empty
```
Comment (javitonino) [inline spec/models/carto/user_migration_spec.rb]: Instead of the double negative, you can simply use `.should be`. Alternatively, you can do this more obvious with
`Carto::UserMigrationImport.exists?(imp.id).should be_true`

**Comment by javitonino** [comment]
Working like a charm in staging!
