### PR TITLE
exporting maps with username table in the sql keeps the schema

### LINKED ISSUE #11400: Exporting and importing maps with `username.table` in the SQL keeps the schema
This is a regression from #7380.

### Steps to Reproduce

1. Create a map within an organization using an SQL with a `select * from myuser.table`.
2. Export it.
3. Import it in a non-org account

### Current Result

The SQL keep the username.

 

### Expected result

SQL username gets removed.

### .carto file

[Untitled Map 1 (on 2017-01-31 at 09.34.58).zip](https://github.com/CartoDB/cartodb/files/741562/Untitled.Map.1.on.2017-01-31.at.09.34.58.zip)

### PR DESCRIPTION
**Pull request by juanignaciosl**
This closes #11400 

About the CR, you might want to read independent commits instead of the full PR:
- I first had to refactor the tests to be able to use an intermediate user, helper methods relied too much in state.
- The second commit is the actual change.

Minimum acceptance:
- [ ] Create a map within an organization, including a query that contains the username in the table schema (`select * from username.table_name`). Export the map and delete that user. Create a user outside any organization, but with the same username. Import the map. It should work.
- [ ] Import within an organization account (with a different username).

### CODE REVIEW

File: lib/carto/query_rewriter.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@ module Carto
   module QueryRewriter
     def rewrite_query(query, old_username, new_user, renamed_tables)
       new_query = query
-      new_query = rewrite_query_for_new_user(query, old_username, new_user) if old_username != new_user.username
+      new_query = rewrite_query_for_new_user(query, old_username, new_user) if old_username != new_user.database_schema
```
Comment (javitonino) [inline lib/carto/query_rewriter.rb]: Hilando fino 😄

This makes me wonder, maybe we should be exporting the user schema rather than its username. I tested and exporting from a non-org user a valid query like `SELECT * FROM public.something` results in an incorrect import. I don't think we should prioritize this at all (as this should be a rare exception) but though I would mention it.

File: spec/services/carto/visualizations_export_service_2_spec.rb [hunk 2]
```diff
@@ -916,34 +917,72 @@ def check_username_replacement(source_user, target_user)
...
         source_user.username.should include('-')
-        check_username_replacement(source_user, target_user).should eq query(target_user)
+        check_username_change(@visualization, @table, source_user, target_user).should eq query(@table, target_user)
       end
 
       it 'replaces owner name (without dash) with new user name (with dash) on import for user_name and query' do
         source_user = @carto_org_user_1
         target_user = @carto_org_user_with_dash_2
-        setup_visualization_with_layer_query(source_user, target_user)
+        @map, @table, @table_visualization, @visualization = shared_table_viz_with_layer_query(source_user, target_user)
```
Comment (javitonino) [inline spec/services/carto/visualizations_export_service_2_spec.rb]: Maybe you could have kept `setup_visualization_with_layer_query` and make it call `shared_table_viz_with_layer_query` and do the instance variable assignment, as it is a common pattern.

File: lib/carto/query_rewriter.rb (hunk 1 above)
Comment (juanignaciosl) [inline lib/carto/query_rewriter.rb]: Certainly, we usually mix usernames and database schemas. I think that you're right: we should export the original schema, as we need it for rewrites. But it doesn't belong to this PR. As it's not urgent, what do you think about scheduling that change for .carto v2?

Comment (javitonino) [inline lib/carto/query_rewriter.rb]: Sound like a plan. We should at least take a look to see if it's worth it. :+1:

File: spec/services/carto/visualizations_export_service_2_spec.rb (hunk 2 above)
Comment (juanignaciosl) [inline spec/services/carto/visualizations_export_service_2_spec.rb]: 👍  best of both!

File: spec/services/carto/visualizations_export_service_2_spec.rb [hunk 3]
```diff
@@ -849,57 +849,62 @@ def verify_overlay_vs_export(overlay, overlay_export)
...
+        map, table, table_visualization, visualization = create_full_visualization(owner_user,
                                                                                        map: map,
                                                                                        table: user_table,
                                                                                        data_layer: layer)
 
-        FactoryGirl.create(:source_analysis, visualization: @visualization, user: owner_user,
-                                             source_table: @table.name, query: query_1)
+        FactoryGirl.create(:source_analysis, visualization: visualization, user: owner_user,
+                                             source_table: table.name, query: query1)
+        return map, table, table_visualization, visualization
```
Comment (gfiorav) [inline spec/services/carto/visualizations_export_service_2_spec.rb]: Agreed

**Comment by gfiorav** [comment]
Acceptance seems 🍏 with one concern:

@juanignaciosl The schema is removed as expected, but the `sql` label still appears. Moreover, the analysis says it's pointing to the old user schema ( 😱 ).

See screenshot:

screen shot 2017-02-02 at 10 28 53


Is this expected?

**Comment by javitonino** [comment]
About the analysis, this should have been caught by `fix_analysis_node_queries`. It's probably what's causing the SQL thing. Anyway, seems unrelated with this PR.

**Comment by gfiorav** [comment]
Yup, looking at the changes, it seems unrelated. Going to prod then. Will open an issue for the analysis thing

**Comment by juanignaciosl** [comment]
@gfiorav good catch, thanks!

**Comment by gfiorav** [comment]
I was preparing an issue but I can't reproduce it anymore which is rather weird...

It's a pity since the issue is practically done, I was just creating a .carto for it.

Oh well, let's see if it pops up again!
