### PR TITLE
3501 notify when reach max retries

### LINKED ISSUE #3501: Suggestion: Send an email to user when sync has reached max_retries
Feedback from @d4weed

When a sync table fails to be synced and it gets to "max retries", it's never synced again. We could warn the users through an email that this is happening so that they're aware that their data will be no longer updated.

cc @saleiva

### PR DESCRIPTION
**Pull request by ethervoid**
Now we send an email to the owner of the dataset when reaches the max number of retries while trying to synchronize.
 
Closes #3501

### CODE REVIEW

**Comment by ethervoid** [comment]
Please @rafatower check this PR :)

File: app/models/synchronization/member.rb [hunk 1]
```diff
@@ -368,9 +368,12 @@ def set_failure_state_from(importer)
           default_message = CartoDB::IMPORTER_ERROR_CODES.fetch(self.error_code, {})
           self.error_message = default_message.fetch(:title, '')
         end
-        self.retried_times  = self.retried_times + 1
+        self.retried_times  += 1 unless self.retried_times >= MAX_RETRIES
```
Comment (rafatower) [inline app/models/synchronization/member.rb]: instead of the `unless`, shouldn't be the increment right before `::Resque.enqueue`?

File: app/models/synchronization/member.rb [hunk 2]
```diff
@@ -380,12 +383,21 @@ def set_general_failure_state_from(exception, error_code = 99999, error_message
         self.state          = STATE_FAILURE
         self.error_code     = error_code
         self.error_message  = error_message
-        self.retried_times  = self.retried_times + 1
+        self.retried_times  += 1 unless self.retried_times >= MAX_RETRIES
```
Comment (rafatower) [inline app/models/synchronization/member.rb]: same as above here

**Comment by rafatower** [comment]
aside from that minor comment, ok

File: app/models/synchronization/member.rb (hunk 1 above)
Comment (ethervoid) [inline app/models/synchronization/member.rb]: Inside the if not the else i assume. If left this way because is how its done and I don't know if there is some implication. If its ok I'll put inside the `if self.retried_times < MAX_RETRIES`

Comment (rafatower) [inline app/models/synchronization/member.rb]: yes, in the `if` part.
