### PR TITLE
8440 8445 redirect public views from builder

### LINKED ISSUE #8440: Public dataset view is not working with the new URLs
It has to be exactly like the actual one, but with the new URLs
cc/ @xavijam 

https://team.cartodb.com/u/saleiva/dataset/scge_migration_2

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #8440 and #8445

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @juanignaciosl

File: app/controllers/carto/builder/datasets_controller.rb [hunk 1]
```diff
@@ -38,7 +38,7 @@ def load_canonical_visualization
       end
 
       def authors_only
-        render_403 unless !current_user.nil? && @canonical_visualization.is_writable_by_user(current_user)
+        unauthorized unless current_user && @canonical_visualization.is_writable_by_user(current_user)
```
Comment (juanignaciosl) [inline app/controllers/carto/builder/datasets_controller.rb]: This looks like overwriting `unauthorized`, but it's not actually an "unauthorized response" but a "public table map redirection", I'd rename it in this class to `redirect_to_public_table_map`.

File: app/controllers/carto/builder/visualizations_controller.rb [hunk 2]
```diff
@@ -41,12 +41,16 @@ def load_derived_visualization
...
       def authors_only
-        render_403 unless !current_user.nil? && @visualization.is_writable_by_user(current_user)
+        unauthorized unless !current_user.nil? && @visualization.is_writable_by_user(current_user)
       end
 
       def editable_visualizations_only
         render_404 unless @visualization.editable?
       end
+
+      def unauthorized
```
Comment (juanignaciosl) [inline app/controllers/carto/builder/visualizations_controller.rb]: Same.

**Comment by juanignaciosl** [comment]
I've made a minor naming comment, but LGTM.

File: app/controllers/carto/builder/datasets_controller.rb (hunk 1 above)
Comment (javitonino) [inline app/controllers/carto/builder/datasets_controller.rb]: Yep, I'm actually overwriting it because I want unauthorized users to be redirected to the public page. If I am renaming this, I would have to change the method called from BuilderUsersModule, as that should also execute a redirection.

Comment (juanignaciosl) [inline app/controllers/carto/builder/datasets_controller.rb]: :zipped_mouth: then.
