### PR TITLE
[QA ded05] 3859 org permission based on roles

### LINKED ISSUE #3859: Massive user creation issues
User 1091 creation failed because "GRANT SELECT ON ALL TABLES IN SCHEMA \"public\" TO \"development_cartodb_user_7d7d7501-6ac4-4f1f-9c72-89fd72c8159d\"" query ([line](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L2055)) triggered this error: PG::Error: ERROR: row is too big: size 8168, maximum size 8160. Relevant backtrace:

 "/vagrant/app/models/user.rb:2016:in `run_queries_in_transaction'",
 "/vagrant/app/models/user.rb:1611:in `set_user_privileges_in_public_schema'",
 "/vagrant/app/models/user.rb:1674:in `set_user_privileges'",
 "/vagrant/app/models/user.rb:1539:in `setup_schema'",
 "/vagrant/app/models/user.rb:1506:in `setup_organization_user'",
 "/vagrant/app/models/user.rb:1691:in `setup_user'",
 "/vagrant/app/models/user.rb:142:in `after_create'"

[Problem explaination & workaround found](http://www.commandprompt.com/blogs/alvaro_herrera/2011/03/grant_schema_usage_to_2500_users_no_can_do/).

Permission granting is a bigger issue than expected, this issue groups all:
- [X] 1091 limit because of "GRANT SELECT ON ALL TABLES IN SCHEMA \"public\" TO \"development_cartodb_user_7d7d7501-6ac4-4f1f-9c72-89fd72c8159d\"".
- [X] [2043 limit on connection granting](https://github.com/CartoDB/cartodb/issues/3859#issuecomment-106860109).
- [X] [2265 limit](https://github.com/CartoDB/cartodb/issues/3859#issuecomment-107865676).
- [X] [2267 limit](https://github.com/CartoDB/cartodb/issues/3859#issuecomment-107915305).
- [X] [2443 limit](https://github.com/CartoDB/cartodb/issues/3859#issuecomment-107950737).
- [X] [SLOW org deletion because exponential permission revoking](https://github.com/CartoDB/cartodb/issues/3859#issuecomment-107839454). Now it's linear.
- [X] Working organization deletion.
- SQL-API
  - [X] Access to shared tables.
  - [X] Inserting in shared tables. See CartoDB/CartoDB-SQL-API#230 about sequence permissions.
- [X] Deletion of org if there's a shared table.
- [X] Avoid `CASCADE` at `database.run(%Q{ DROP SCHEMA IF EXISTS "#{self.database_schema}" CASCADE })` (`drop_organization_user` method, see [PR comments](https://github.com/CartoDB/cartodb/pull/3881/files#r31926173)).

### PR DESCRIPTION
**Pull request by juanignaciosl**
@Kartones , @javisantana CR this, please. Marked as NOMERGE until agreement, after talking about implications on other projects. This fixes #3859.

@iriberri could you pass QA to this, please? It's deployed on ded02.

### Permission changes

This changes the global permission granting model of organizations, from user-centric to role-centric: previously users where granted/revoked themselves, now permission is granted to the role all organization users share. The key for understanding the changes is comparing the [new `setup_schema` method](https://github.com/CartoDB/cartodb/pull/3881/files#diff-4676c008b11a5480d73d4a6de01e45b9R1564) and [`set_user_privileges`](https://github.com/CartoDB/cartodb/pull/3881/files#diff-4676c008b11a5480d73d4a6de01e45b9R1712). For organization users now many "set privileges" methods are not called. That "granting to users" has changed to ["granting to organization role"](https://github.com/CartoDB/cartodb/pull/3881/files#diff-4676c008b11a5480d73d4a6de01e45b9R1573). [That role, `CDB_Organization_Member_Group_Role_Member_Name()` is assigned to users on user creation](https://github.com/CartoDB/cartodb-postgresql/blob/9114d4e463c8664c1fb31e3bc538ce96c0dd0771/scripts-available/CDB_Organizations.sql#L24), it's not "new", so this is functionally equivalent.

Since new users on old organization are not assigned permissions as before, we must assign those to org role (that's done on owner assignment on new organizations). To do it you must run this task: `bundle exec rake cartodb:db:assign_org_permissions_to_org_role`.

### What to test

Anything related to creation/deletion/sharing of organizations, users and datasets/maps. For example, there's no need at all to test every editor option, but you need to test whether organization and user management works fine, and if a user can/cannot view/edit something he should. Similarly, no need to test importing formats, only one importer is enough. SQL and Maps API should also be tested. Normal user management logic shouldn't have changed, but you should also test that this is true.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4033/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4052/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4074/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4093/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4102/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4112/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4130/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4132/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4142/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4144/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4175/))

File: app/models/user.rb [hunk 1]
```diff
@@ -297,54 +299,80 @@ def drop_organization_user(org_id, is_owner=false)
...
-        end
-
-        # Drop user quota function
-        database.run(%Q{ DROP FUNCTION IF EXISTS "#{self.database_schema}"._CDB_UserQuotaInBytes()})
         # If user is in an organization should never have public schema, so to be safe check
-        drop_all_functions_from_schema(self.database_schema)
         unless self.database_schema == 'public'
           # Must drop all functions before or it will fail
-          database.run(%Q{ DROP SCHEMA IF EXISTS "#{self.database_schema}" })
+          database.run(%Q{ DROP SCHEMA IF EXISTS "#{self.database_schema}" CASCADE })
```
Comment (Kartones) [inline app/models/user.rb]: uhhh, no no. No cascade as we can screw up many things.

Many of the additional logic of user deletion comes from having to manually simulate a cascade by dropping things, trying again, etc. If we need to check PG logs to see "new objects to destroy" after this permission changes lets do it, but I'm against a DROP CASCADE as we can wipe out critical stuff, shared functions, etc.

Either that or @javisantana or @lbosque agree to this decision and we assume we can remove unexpected things, but in the past the restriction was there of never doing a CASCADE.

File: app/models/user.rb [hunk 2]
```diff
@@ -297,54 +299,80 @@ def drop_organization_user(org_id, is_owner=false)
...
         end
       end
 
       conn = self.in_database(as: :cluster_admin)
       User.terminate_database_connections(database_name, database_host)
-      conn.run("REVOKE ALL ON DATABASE \"#{database_name}\" FROM \"#{database_username}\"")
-      conn.run("REVOKE ALL ON DATABASE \"#{database_name}\" FROM \"#{database_public_username}\"")
-      conn.run("DROP USER \"#{database_public_username}\"")
+      conn.run("DROP USER IF EXISTS \"#{database_public_username}\"")
```
Comment (Kartones) [inline app/models/user.rb]: DROP USER performs itself the rekoves on the DB? 
and no need to at least revoke the role from the user too?

File: app/models/user.rb [hunk 3]
```diff
@@ -297,54 +299,80 @@ def drop_organization_user(org_id, is_owner=false)
...
+
+  def revoke_all_memberships_on_database_to_role(conn, database, role)
+    q = "select rolname from pg_user join pg_auth_members on (pg_user.usesysid=pg_auth_members.member) join pg_roles on (pg_roles.oid=pg_auth_members.roleid) where pg_user.usename='#{role}'"
+    conn.fetch(q).each { |rolname|
+      conn.run("REVOKE \"#{rolname[:rolname]}\" FROM \"#{role}\"")
+    }
+  end
+
+  def drop_owned_by_user(conn, role)
+    conn.run("DROP OWNED BY \"#{role}\" CASCADE")
```
Comment (Kartones) [inline app/models/user.rb]: Same here, I'm really afraid of how this can work without tests proving that does not break hell, something like doing a function of USER A that selects from tables USERA.table1 and USERB.table2, a function calling functions from other users and things like that that could bge affected by a CASCADE.

I'm worried because this is quite open to interpretation: `CASCADE: Automatically drop objects that depend on the affected objects.` ([+](http://www.postgresql.org/docs/8.2/static/sql-drop-owned.html)). Previous examples could enter in that bag.

File: app/models/user.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/user.rb]: I also doubt on that, but manually simulating a cascade is no safer, you're deleting everything you need anyway. I looked at the code and nothing was moved, saved or cancelled in any case, everything's dropped. I'll wait for their opinion anyway.

Comment (Kartones) [inline app/models/user.rb]: Yes but there's one difference, when it currently tries to drop stuff "from you", [it never goes outside your schema](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L2152), so it's safe as you cannot drop a function from other user.

Based on PG's description, nothing guarantees me that the CASCADE won't follow the DROPping to other schemas, is what I meant.

Comment (juanignaciosl) [inline app/models/user.rb]: I can buy that argument for `DROP OWNED`, since you can own things outside your schema and that 'depending' might be ambiguous, but [according to the docs DROPS SCHEMA ... CASCADE only deletes objects _contained_ in _that_ schema)[http://www.postgresql.org/docs/9.3/static/sql-dropschema.html].

Comment (Kartones) [inline app/models/user.rb]: I'd add tests with multiple schemas to confirm and be sure, but yes, in that description DROP SCHEMA CASCADE looks "safe".

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4204/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4205/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4209/))

File: app/models/user.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/user.rb]: Ok, Kartones, take a look at the "keeps a table shared with an user when that user is deleted" test I've just pushed, to see if current logic matches your expectations. Ask for more fine grained checks if you think it should have more.

**Comment by juanignaciosl** [comment]
@iriberri will QA this tomorrow. @Kartones , @rochoa , @javisantana could you CR this, please? @Kartones , I know you already did, but I've changed some code but maybe you still miss some tests.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4228/))

**Comment by juanignaciosl** [comment]
Retest this, please.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4232/))

File: app/models/user.rb [hunk 4]
```diff
@@ -299,54 +301,85 @@ def drop_organization_user(org_id, is_owner=false)
...
+  def drop_user(conn = self.in_database(as: :cluster_admin), username = database_username)
+    database_with_conflicts = nil
+    retried = false
+    begin
+      conn.run("DROP USER IF EXISTS \"#{username}\"")
+    rescue => e
+      if !retried && e.message =~ /cannot be dropped because some objects depend on it/
+        retried = true
+        e.message =~ /object[s]? in database (.*)$/
+        if database_with_conflicts == $1
```
Comment (rochoa) [inline app/models/user.rb]: I didn't know about that syntax :imp:

File: app/models/user.rb (hunk 1 above)
Comment (rochoa) [inline app/models/user.rb]: I'm just wondering what happens when I share with other role a function and all my functions are deleted on cascade.

File: app/models/user.rb [hunk 5]
```diff
@@ -2136,6 +2187,17 @@ def reset_database_permissions
     end
   end
 
+  def revoke_all_on_database_from(conn, database, role)
+    conn.run("REVOKE ALL ON DATABASE \"#{database}\" FROM \"#{role}\"") if role_exists?(conn, role)
+  end
+
+  def revoke_privileges(db, schema, u)
+    db.run("REVOKE ALL ON SCHEMA \"#{schema}\" FROM #{u}")
```
Comment (rochoa) [inline app/models/user.rb]: Why not use here `cascade` also?

**Comment by Kartones** [comment]
A nice test (I can code it tomorrow if you want) would be to create a vis of org_user_1 that uses in a layer a table shared from org_user_2. Because `share_table` plays with permissions but deleting a vis triggers a cascade of callbacks and "related tables" and the like.
But as I said tomorrow rested I could code that test easily.

I don't know if also adding something like a [PG function](http://www.postgresql.org/docs/9.3/static/sql-createfunction.html) to org_user_1, another that inside calls the first one to org_user_2 and  and testing at the 'users destruction logic' that the org_user_1 function is kept upon destruction. This is actually a 2x1 as we are testing that user functions don't impede/stop the deletion.

Is not the most common scenario but some users (like @andrewxhill) have lots of custom functions.

File: app/models/user.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/user.rb]: Well... they should be deleted if they're in your schema and you're deleting them, isn't it? I could argue about what might happen to a function you own but resides in other user schema, but if it's yours and is in your schema I think deletion is expected on user deletion...

File: app/models/user.rb (hunk 5 above)
Comment (juanignaciosl) [inline app/models/user.rb]: Uhm, I think you're right, [revoke fails if there's dependent privileges](http://www.postgresql.org/docs/9.3/static/sql-revoke.html), I'm adding it, thanks!

**Comment by juanignaciosl** [comment]
@zenitraM take a look

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4300/))

File: app/models/user.rb (hunk 1 above)
Comment (lbosque) [inline app/models/user.rb]: In the past I've seen that a drop cascade could end in dropping almost the entire internet starting with a simple user drop or permission in postgres. I agree with @Kartones that it's better to limit in code which things must be dropped or modified. A human error may end in lost data.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4368/))

File: app/models/user.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/user.rb]: Ok, I'll remove this cascade.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4371/))

**Comment by juanignaciosl** [comment]
Ok, since there wasn't quorum on using `CASCADE`s I've replaced them recovering previous explicit drops. I've checked this destroys both "new" and "old" organizations with shared tables.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4376/))

**Comment by juanignaciosl** [comment]
@Kartones , @zenitraM you might want to take a look at [last commit](https://github.com/CartoDB/cartodb/commit/a069c7c997007a3d90ddd8c26d3da26419907668). @zenitraM found #4092. Instead of just adding the `nil` check I've avoided updating named maps on delete operations.

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4396/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4672/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4674/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4676/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4714/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4778/))
