### PR TITLE
fixed blending

### LINKED ISSUE #7790: Blending mode selector doesn't seems to work
Create a map with point data, and change the blending mode. It doesn't do anything.

### PR DESCRIPTION
**Pull request by javisantana**
fixes #7790

cc @xavijam

### CODE REVIEW

File: lib/assets/javascripts/cartodb3/editor/style/style-converter.js [hunk 1]
```diff
@@ -70,6 +70,12 @@ function pointSize (props) {
   return css;
 }
 
+function blending (b, type) {
+  var css = {};
+  css[type + '-comp-op'] = b
```
Comment (xavijam) [inline lib/assets/javascripts/cartodb3/editor/style/style-converter.js]: ; 💃
