### PR TITLE
Correctly log rollbar errors logging exceptions

### LINKED ISSUE #10553: Rollbar exception reporting
`e` is not defined here 
```
    rescue
      # Last chance to report error
      begin
        Rollbar.error(e)
      rescue
      end
    end
```

### PR DESCRIPTION
**Pull request by javitonino**
Fixes #10553

### CODE REVIEW

**Comment by javitonino** [comment]
Please CR @gfiorav

File: lib/cartodb/logger.rb [hunk 1]
```diff
@@ -14,10 +14,10 @@ def self.log(level, exception: nil, message: nil, user: nil, **additional_data)
         # Error reporting to Rollbar, usually caused by unserializable data in payload
         Rollbar.log('warning', nil, 'Could not report to Rollbar', stack: caller)
       end
-    rescue
+    rescue => rollbar_exception
       # Last chance to report error
       begin
-        Rollbar.error(e)
+        Rollbar.error(rollbar_exception)
```
Comment (gfiorav) [inline lib/cartodb/logger.rb]: `rollbar_exception_2_definitivo_final_para_imprimir`

:trollface:
