### PR TITLE
Notify error if common data is not loaded fixes #3831

### LINKED ISSUE #3831: Monitor common data loading
If `CommonData#datasets_url` returns an error common data loading fails silently, it should be, at least, monitored (probably through a test as well).

cc @zenitraM @iriberri

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rafatower CR this, please. This fixes #3831.

### CODE REVIEW

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4177/))

**Comment by Cartofante** [comment]
Frontend tests were OK :+1: ([details](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/4179/))

File: app/models/common_data.rb [hunk 1]
```diff
@@ -31,9 +31,11 @@ def is_enabled?
   def get_datasets(json)
     begin
       rows = JSON.parse(json).fetch('rows', [])
-    rescue
+    rescue => e
+      CartoDB.notify_exception(e)
       rows = []
     end
+    CartoDB.notify_error('common-data empty', { rows: rows }) if rows.nil? || rows.empty?
```
Comment (rafatower) [inline app/models/common_data.rb]: this will log 2 errors for the same problem, right? I'm ok with it if you're ok

**Comment by rafatower** [comment]
:+1:

File: app/models/common_data.rb (hunk 1 above)
Comment (juanignaciosl) [inline app/models/common_data.rb]: It will log twice when `JSON.parse` crashes, but it will log once when rows is just empty (this scenario has happened in the past). Not the most elegant log info but this is not noisy at all and I think this is the simplest code I could come up with.
