### PR TITLE
11234 add public uploads path

### LINKED ISSUE #11234: Bug in Local organisation assets
### Context

@ivanmalagon is implementing organization assets front and while S3 is working, local has a bug where a variable `public_uploads_path` is missing. This variable should be `public/uploads` and must have been removed by accident in a refactor. The fix is a one-liner.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Upload an asset without configuring s3.

### Current Result

500 error complains about the missing variable.

 

### Expected result

The asset is stored in local.

### PR DESCRIPTION
**Pull request by gfiorav**
Fixes #11234

## Context

This is fixes a bug related exclusively with organization assets when they're stored in local.

## Acceptance

Acceptance should make sure that the `s3` part of their configuration is commented (to force local storage) and check uploading an asset. The url produced should yield the asset. Only upload needs be tested.

### CODE REVIEW

File: lib/carto/storage_options/local.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ def initialize(location)
 
   def upload(path, file)
     filename = Pathname.new(file.path).basename
-    target_directory = File.join(public_uploads_path,
+    target_directory = File.join('public/uploads',
```
Comment (javitonino) [inline lib/carto/storage_options/local.rb]: Why not just call `public_uploads_path` which is defined in `Carto::Configuration` and takes into account the configuration file.

**Comment by javitonino** [comment]
As a note, if this is breaking, shouldn't have it triggered a test.

**Comment by gfiorav** [comment]
Hey @javitonino, yes, indeed. It's a bit shameful, but were stubbing the upload method. 

I feel we might as well let it slip for now as very basic testing would make it obvious (as has happened when it's been used). The method is quite simple
