### PR TITLE
Fix pagination in visualization API

### LINKED ISSUE #14476: Wrong pagination in Visualizations API when ordered by size
### Context
Visualizations index does not return the expected number of results when there are more than 2 pages and you request one from the middle and order by size.

### Steps to Reproduce
Having at least 3 pages of datasets:
1. Order by size
2. Go to the second page
3. Check the API response (the view is showing the right results)

### Current Result
If you have 45 datasets (and the page size is 20), it's returning:
- Page 1: 20 items
- Page 2: 25 items (seems like page 2 + 3)
- Page 3: 5 items

### Expected result
- Page 1: 20 items
- Page 2: 20 items
- Page 3: 5 items

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Closes #14476 

The problem was that the square brackets operator for an array does not receive the last index as the second parameter, but the length: https://ruby-doc.org/core-2.2.0/Array.html#method-i-5B-5D

Also, the way to get the row_count (estimated and actual) from Visualization has been changed to use memoization in order to improve performance in visualizations controller.

### CODE REVIEW

File: app/models/carto/visualization.rb [hunk 1]
```diff
@@ -390,11 +390,11 @@ def has_read_permission?(user)
   alias :can_view_private_info? :has_read_permission?
 
   def estimated_row_count
-    table_service.nil? ? nil : table_service.estimated_row_count
+    user_table.try(:row_count)
```
Comment (juanignaciosl) [inline app/models/carto/visualization.rb]: Wow, I had to go through several misleading named methods to actually grasp that both are estimations but one of them is memoized and other isn't (as you said in your comment). Good catch!

File: app/queries/carto/offdatabase_query_adapter.rb [hunk 2]
```diff
@@ -64,11 +64,11 @@ def get_results
           asc_or_desc == :asc ? x_attribute <=> y_attribute : y_attribute <=> x_attribute
         end
       end
-      all[@offset, last_index(all)]
+      all[@offset, size(all)]
     end
 
-    def last_index(array)
-      @limit.nil? ? array.count : (@offset + @limit)
+    def size(array)
```
Comment (juanignaciosl) [inline app/queries/carto/offdatabase_query_adapter.rb]: I'd consider inlining this method or renaming it. `size(array)` should always return the size of the array. Taking `@limit` into account doesn't feel appropriate for the naming.

Comment (gonzaloriestra) [reply app/queries/carto/offdatabase_query_adapter.rb]: Your are right, `size` is misleading... I'm removing the method, as it's quite small.

**Comment by juanignaciosl** [comment]
Acceptance :+1:
